---
permalink: faq/faq-general-insight-questions.html 
sidebar: sidebar 
keywords: redhat,Linux 
summary: 이 FAQ는 OnCommand Insight에 대한 일반적인 질문과 답변을 제공합니다. 
---
= 일반적인 질문
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 FAQ는 OnCommand Insight에 대한 일반적인 질문과 답변을 제공합니다.



== OCI(OnCommand Insight)가 언제 출시되었습니까?

OCI는 10년 이상 능동적 개발을 통해 업계에서 가장 완성도가 높은 인프라 모니터링 제품 중 하나입니다. 이전에는 Onaro 또는 SANscreen로 알려진 SANscreen 이름은 OnCommand 포트폴리오 제품군에 참여할 때 변경되었으며 현재 OnCommand Insight 또는 보다 일반적인 Insight 또는 OCI로 불립니다.



== 현재 환경에 OCI를 배포하는 데 시간이 얼마나 걸립니까?

OCI는 단순히 소프트웨어를 다운로드하는 것입니다. 소프트웨어는 2개의 전용 가상 서버 또는 물리적 서버에 설치됩니다. 일반적인 설치는 2시간 이내에 수행할 수 있으며 인벤토리, 용량 및 성능 데이터는 거의 즉시 제공됩니다. 추가적인 성능 및 모범 사례 정책, 사용자 주석 및 비용 인식 설정은 추가적인 계획 논의를 필요로 합니다.



== OCI에 에이전트, 수집기 또는 프로브가 필요합니까?

OCI는 100% 에이전트가 없기 때문에 에이전트, 탭 또는 프로브를 사용할 필요가 없습니다. 모든 장치 검색은 읽기 전용이며 대역외 및 IP를 통해 수행됩니다.



== OCI는 어떻게 장치를 검색하고 연결합니까?

OCI는 에이전트나 프로브 없이 데이터 센터 환경에 이미 존재하는 기본 API 및 프로토콜을 활용합니다. SSH, HTTP, SMIS 및 CLI는 몇 가지 예에 불과합니다. 디바이스 요소 관리자가 이미 존재하는 경우(예: EMC의 Unisphere), OCI는 요소 관리자와 통신하여 기존 환경 데이터를 캡처합니다. 대부분의 장치 검색 시 IP 주소와 읽기 전용 사용자 이름 및 암호만 필요합니다. 이러한 디바이스 발견은 OCI의 VMware 데이터 소스와 같이 "일대다"일 수 있습니다. VMware vCenter를 검색하면 하나의 IP 주소 및 자격 증명을 통해 모든 ESXi 호스트와 관련 VM을 검색할 수 있습니다.



== OCI에 프로페셔널 서비스가 필요합니까? 그러한 서비스를 이용할 수 있습니까? 그리고 어떤 서비스를 제공합니까?

중간 규모의 환경에서는 배포, 구성 및 통합뿐만 아니라 다양한 사용자 지정 보고 및 데이터 유효성 검사 기능을 위한 프로페셔널 서비스를 권장합니다. OCI 팀 및 어카운트 계약 관리자와의 짧은 논의를 통해 귀사에 가장 큰 도움이 될 서비스를 파악할 수 있습니다.



== 새로운 기능 및 개선을 위해 OCI 릴리스를 얼마나 자주 업데이트합니까?

여러 버전의 OCI에 대한 제품 업데이트 및 서비스 팩을 사용할 수 있습니다. 주요 릴리스 또는 부 릴리스는 일반적으로 몇 개월마다 제공되며, 새 장치 지원 및 펌웨어를 더 자주 릴리스하는 서비스 팩을 포함합니다. 두 가지 모두 support.netapp.com 다운로드 사이트에서 다운로드할 수 있습니다. 제조업체로부터 더 자주 나오는 새로운 디스크 모델과 같은 특정 업데이트는 자동으로 OCI 소프트웨어로 푸시됩니다. 또한 개발 수정 또는 업데이트 직후 사이트에서 OCI 데이터 소스 장치 수집에 패치를 적용할 수 있습니다.



== OCI 관리 팀에서 새 데이터 소스 요청에 대해 우선순위를 어떻게 지정합니까?

OCI의 제품 관리 팀은 모든 고객 개선 사항 및 상호 운용성 기능 요청(IFR)을 적극적으로 추적합니다. 각 요청은 실현 가능성에 대해 자세히 평가되고 고객 수요 및 전반적인 전략적 비즈니스 영향에 따라 우선 순위가 지정됩니다. 요청이 수락되면 노력 수준 및 향후 개발 일정을 기준으로 요청 크기가 조정됩니다. OCI 개발 프로세스의 민첩한 특성을 통해 정기적으로 예정된 릴리스 주기 외에 새로운 데이터 소스를 사용할 수 있습니다. NetApp 어카운트 담당자는 고객 문의 및 귀사를 대신하여 새로운 요청을 제출할 수 있도록 지원할 수 있습니다. OCI를 업그레이드할 필요 없이 데이터 소스에 패치를 적용할 수 있습니다.



== 우리 회사는 리눅스에서 완벽하게 운영된다. OCI는 Linux에서 작동합니까?

예. OCI는 Linux와 Windows의 다양한 기능을 지원합니다. COGNOS(데이터 웨어하우스와 함께 OCI에 사용되는 IBM의 보고 도구)는 Windows에서만 지원되므로 보고에 OCI를 사용하는 경우 Windows 서버에서 보고 도구를 실행해야 합니다. OCI 설치 가이드에는 각 OCI 구성 요소에 대한 서버 요구 사항과 지원되는 운영 체제가 나와 있습니다.



== OCI는 인터넷에 연결되지 않은 보안 환경에 적합합니까?

예, OCI는 상위 10개 Fortune 500대 기업에서 사용되고 있으며 오늘날 전 세계 최고의 은행, 의료, 연구 및 정부 기관을 통해 사용되고 있습니다. OCI는 미국 군사용 CAC(Common Access Card)를 지원하며 지리적으로 분산되어 있거나 방화벽으로 둘러싸인 환경을 위한 솔루션을 제공합니다.



== OCUM(OnCommand Unified Manager)이 cDOT용 관리 솔루션이라는 말을 계속 듣게 됩니다. 제가 OCI를 사용해야 하는 이유를 이해하는 데 도움을 줄 수 있습니까?

OnCommand Unified Manager는 스토리지 어레이 "장치 관리" 계층에서 운영되며 cDOT(clustered Data ONTAP) 어레이 및 클러스터 인터커넥트에 대한 심층 인시던트 및 이벤트 기반 분석을 제공합니다. OCI 7-Mode, clustered Data ONTAP 및 기타 타사 어레이로 구성된 사내 및 전 세계에 분산된 환경에 대한 종합적인 뷰를 제공합니다. VM에서 스핀들에 이르는 엔드 투 엔드 가시성을 통해 용량, 성능 및 비용 모델링에 대한 기간별 추세 파악과 예측을 수행할 수 있으므로 데이터 센터 관리에 대한 사전 예방적 서비스 품질 접근 방식을 적용할 수 있습니다.



== Automation Storefront에 언급된 OnCommand Insight 보조 ETL은 무엇입니까?

일부 OnCommand Insight 자동화 Storefront 보고서 다운로드에서 참조되는 "보조 ETL" 요구 사항은 캡처된 데이터의 추가 ETL(Extract, Transform, Load)을 호출하는 데 사용되는 개발된 전문 서비스 구현을 나타냅니다. 이 구현은 OnCommand Insight 데이터 웨어하우스로 모을 수 있습니다.

보조 ETL 프로세스의 주요 목적은 "배치" 데이터를 프리페치하여 복잡한 보고서를 더 빠르게 생성하거나 매일 실행되도록 예약하는 것입니다.

이 보조 ETL은 OnCommand Insight 데이터 웨어하우스 관리 가이드에 자세히 설명되어 있는 권장 "하루에 한 번" ETL에 추가됩니다.

NetApp 프로페셔널 서비스는 기존 OnCommand Insight 보고서 스케줄, 자동화된 백업, 확장성 또는 기타 시스템 성능 활동에 영향을 미치지 않도록 보조 ETL 스크립팅을 구성할 수 있습니다. ETL 스크립팅 또는 데이터 검증 요구사항에 대한 자세한 내용은 NetApp 영업 담당자에게 연락하여 NetApp의 전문 서비스가 어떤 도움을 줄 수 있는지 논의하십시오.
