---
permalink: faq/faq-performance-troubleshooting.html 
sidebar: sidebar 
keywords:  
summary: 이 FAQ는 OnCommand Insight 성능 문제 해결과 관련된 일반적인 질문에 답합니다. 
---
= 성능 문제 해결
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 FAQ는 OnCommand Insight 성능 문제 해결과 관련된 일반적인 질문에 답합니다.



== 내 환경에서 모든 greedy 리소스 목록을 생성하려면 어떻게 해야 합니까?

OCI의 상관관계 분석을 사용하면 지정된 서비스 경로에 대해 과다 사용 및 성능 저하 리소스를 식별할 수 있습니다. 상관 관계 피처의 생성된 분석은 각 개체를 보는 동안 실시간으로 수행됩니다. 제공된 분석을 통해 성능 문제를 해결하고 근본 원인을 파악하는 데 필요한 시간을 크게 줄일 수 있습니다. 정의된 성능 정책에 대해 생성된 위반 사항을 탐색하는 것은 과다 사용 또는 성능 저하 리소스를 검색하는 한 가지 진입 지점입니다. OCI의 이상 탐지 기능은 서비스 중단이 발생하기 전에 애플리케이션 인프라에서 과다 사용 또는 성능 저하된 리소스를 식별하기 위한 사전 예방적 접근 방식으로도 사용될 수 있습니다. 위젯과 대시보드 모두 최신 쿼리 기능을 사용하여 예상 IOPS(과다 사용), 활용률 또는 지연 시간이 높은 리소스를 필터링, 정렬 및 시각화할 수 있습니다.



== OCI는 성능 문제를 진단할 수 있는 장소를 제공할 수 있습니까?

예. OCI의 성능 문제 해결은 여러 가지 방법으로 접근할 수 있습니다. OCI에는 다양한 경고 방법이 있습니다. SNMP, Syslog 및 e-메일 알림이 일반적으로 사용됩니다. e-메일 알림을 통해 사용자는 OCI 내에서 영향을 받는 리소스를 빠르게 클릭하여 시작할 수 있습니다. 전역 검색 창을 사용하면 관리자가 자원 이름을 입력하기만 하면 상황 분석을 시작할 수 있습니다.

OCI의 위반 대시보드를 사용하면 이벤트 수, 기간 및 시간을 기준으로 작업의 우선순위를 지정할 수 있습니다. 다양한 알림 유형의 예로는 지연 시간, IOPS, 활용률, 심각도, 사업부 또는 관련 애플리케이션 등이 있습니다.

관리자는 OCI의 상관관계 분석을 통해 영향을 받는 리소스와 연결된 객체를 비교하고 IOPS, 지연 시간, 활용률, CPU 및 BB 크레딧에 대한 영향을 파악할 수 있습니다.

OCI의 최신 이상 탐지 및 이더넷 모니터링 개선은 서비스 중단 또는 운영 중단이 발생하기 전에 리소스 행동 이탈을 감지하는 보다 공격적이고 능동적인 접근 방식을 제공합니다.

OCI의 쿼리 기술 및 위젯 대시보드를 사용하면 데이터 센터 내의 문제 영역을 대상으로 하는 체계화된 보기에서 구체적인 내용을 파악할 수 있습니다.



== OCI가 7-Mode에서 cDOT로의 마이그레이션을 지원할 수 있습니까?

예, OCI는 기존 워크로드 수요 및 마이그레이션 후 검증에 대한 중요한 이해를 제공합니다. 오늘날 데이터 센터를 현대화하는 OCI의 역할은 변경 관리 시뮬레이션, 마이그레이션 전 최적화 계획 및 적합한 서비스 계층을 정의하는 데 있습니다. OCI는 단 몇 번의 클릭으로 멀티 벤더 환경에서 수천 개의 NFS 공유와 파이버 채널 경로에 걸쳐 비즈니스 영향을 손쉽게 수집 및 상호 연관시킵니다. OCI에서 마이그레이션에서 기술 업데이트까지, 안정적이고 적절한 규모의 마이그레이션을 지원하고 계획되지 않은 서비스 중단을 완화할 수 있는 경로를 제공합니다.



== OCI 성능 모니터링은 "실시간"에 어떤 영향을 줍니까?

OCI는 사내 및 하이브리드 클라우드 데이터 센터 관리 모두에서 * 거의 실시간 * 으로 간주됩니다. 데이터 소스 폴링은 더 자주 발생하도록 구성할 수 있지만 대부분의 사용자는 5분 미만의 대부분의 디바이스에 대해 성능 수집 간격을 설정하여 분석 기능을 크게 활용할 수 없습니다. 더 자주 수집하면 관리 중인 개체와 수행된 분석에 불필요한 부담이 될 수 있습니다. 물론 보다 세분화된 수집이 필요한 상황이 있을 수 있으며, 다행히도 OCI는 구성 가능한 장치 인벤토리 및 특정 데이터 센터 환경 요구 사항에 맞는 성능 폴링 간격을 비롯한 완벽한 유연성을 제공합니다.



== "합계"가 "읽기" 및 "쓰기"와 다른 이유는 무엇입니까?

경우에 따라 카운터의 _Total_이 해당 카운터의 _reads_plus_Writes_의 합계와 같지 않을 수 있습니다. 이 문제가 발생할 수 있는 경우는 몇 가지가 있습니다.

* IOPS *: 스토리지 어레이 또는 기타 자산은 읽기 및 쓰기 외에도 워크로드 데이터 흐름과 관련이 없는 내부 작업을 처리합니다. 이러한 작업을 "시스템", "메타데이터" 또는 "기타" 작업이라고도 하며 스냅샷, 중복 제거 또는 공간 재할당 등의 내부 프로세스에 기인합니다. 이 경우 지정된 자산에 대한 시스템 작업의 양을 찾으려면 _Total_IOPS에서 _Read_and_Write_IOPS의 합계를 빼십시오. 읽기 및 쓰기 IOPS의 합계는 데이터 흐름과 직접 관련된 총 IOPS입니다.

* 지연 시간 *: 총 응답 시간이 시간 가중 평균이므로 작업에 대한 총 응답 시간(지연 시간)은 쓰기 응답 시간 _ 미만으로 보고될 수 있습니다. I/O 워크로드는 종종 쓰기 작업보다 더 많은 읽기 작업으로 구성되며 쓰기 작업은 일반적으로 더 큰 지연 시간을 관찰합니다. 예를 들어, 평균 지연 시간이 5ms인 10개의 읽기 작업과 평균 지연 시간이 10ms인 5개의 쓰기 작업을 수행한 경우 총 가중치 평균 지연 시간은 읽기 지연 시간의 읽기 횟수를 기준으로 계산되며 또한 쓰기 횟수에는 평균 쓰기 지연 시간이 곱되고 총 I/O 작업 수로 나누어집니다(예: 10 * 5 + 5 * 10)/(10 + 5) = 6.33ms.



== OCIOCI와 OCUM에서 초과된 공간에 대해 서로 다른 값을 표시하는 이유는 무엇입니까?

OCUM(OnCommand Unified Manager) 개념을 통해 "프로비저닝된" 공간에 FlexVol(OnCommand Insight 내부 볼륨)이 증가할 수 있는 자동 확장 제한이 있을 수 있습니다. OCI "용량"에 자동 확장 제한이 반영되지 않습니다. 따라서 자동 확장 FlexVol이 있는 환경에서 OCUM 프로비저닝 용량은 OCI 스토리지 레벨 "오버 커밋 용량"을 초과할 수 있습니다. 델타는 FlexVol 용량과 자동 용량 간의 차이가 됩니다.
