---
permalink: faq/faq-insight-licensing.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight 라이센스에 대한 일반적인 질문에 대한 답변입니다. 
---
= OnCommand Insight 라이센스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight 라이센스에 대한 일반적인 질문에 대한 답변입니다.



== OCI 라이센싱 개요

OCI는 용량별로 라이센스가 부여됩니다. 고객은 사용하려는 각 모듈에 대해 라이센스를 구입해야 합니다.

* Discover * 는 보증, 수행 및 계획을 위한 필수 조건이며 단독으로 제공되지 않습니다. 검색 라이센스가 TB의 관리 용량으로 제공됩니다.

* Assure * 는 관리형 용량을 TB 단위로 라이센싱합니다(FC, NAS, iSCSI, FCoE 등의 모든 스토리지 인프라에 대한 단일 비용 청구 단위).

* Perform * 은 TB의 관리 용량으로 라이센스가 부여됩니다.

* 계획 * 은 TB의 관리 용량으로 라이센스가 부여됩니다.

"매노화된 용량"은 포맷하기 전에 물리 디스크, 가상 디스크 및 테이프의 원시 용량으로 정의됩니다. 이는 Insight가 사내 및 클라우드에서 모두 검색한 모든 스토리지에 적용할 수 있습니다.

대부분의 데이터 소스는 디스크 물리적 용량 2를 기준으로 합니다. 스페어 디스크, 할당되지 않은 디스크 또는 RAID 디스크와 같은 디스크 역할은 고려하지 않습니다.

두 가지 유형의 Insight 라이센스를 사용할 수 있습니다. * 영구 * 및 * 가입 *.

* 영구 라이센스 * 를 사용하면 해당 라이센스 약관에 따라 얻은 소프트웨어의 특정 버전/릴리스를 무기한 사용할 수 있습니다. SSP(소프트웨어 지원 계획)를 구입한 경우 NetApp은 지원 서비스 약관에 따라 업데이트가 제공되는 경우 NetApp Support 사이트를 통해 상용 소프트웨어 업데이트에 대한 액세스를 제공합니다. NetApp 기술 지원 센터에서 제공하는 특별 패치에 액세스할 수도 있습니다.

* 가입 * 은 다음과 같은 권한을 부여하는 소프트웨어의 고정 기간 라이선스입니다.

* 해당 라이센스 약관에 따라 제한된 기간(가장 일반적으로 12개월) 동안만 소프트웨어를 사내에 사용합니다
* 해당 기간 동안 소프트웨어 지원(이전 SSP)을 받습니다
* 유효한 동안 정식 사용자는 최신 상용 버전, 릴리스 또는 업데이트를 사용할 수 있으며 소프트웨어에 대한 지원을 받을 수 있습니다


각 고정 기간(가장 일반적으로 12개월)이 끝나면 추가 고정 기간(가장 일반적으로 12개월)에 대해 라이센스를 갱신할 수 있습니다. 라이선스를 갱신하지 않을 경우 라이선스를 부여받은 회사는 더 이상 소프트웨어를 사용할 권리를 보유하지 않으며 SSP의 혜택을 받을 수 없으며 정식 사용자는 소프트웨어의 모든 사본을 파기해야 합니다.



== OCI 라이센스 모듈에 대해 자세히 알아보십시오

OCI는 현재의 데이터 센터 환경 요구사항을 충족하는 4개의 핵심 라이센스 모듈을 가지고 있습니다. 이러한 모듈은 * 검색, 수행, 보증 및 계획 * 입니다. Discover는 기본 모듈이며 다른 모든 모듈 구매에 필요합니다.

Discover * 모듈을 사용하면 OCI가 데이터 센터에서 자산을 찾고 장치 서비스 경로를 동적으로 매핑할 수 있습니다. 용량, 공급업체 정보, 모델, 펌웨어 및 일련 번호와 같은 정보가 제공됩니다.

* Perform * 은 OCI의 성능 수집 모듈입니다. IOPS, 처리량, 지연 시간, CPU 및 메모리 정보를 캡처하고 다른 분석을 제공합니다.

* 보증 * 은 파이버 채널 환경 및 효율성 기술을 지향합니다. 이 솔루션은 파이버 채널 및 iSCSI 환경의 위험을 식별하고 관리하는 데 도움이 됩니다. 또한 마스킹, 매핑 및 조닝 서비스 경로 항목에 대한 식별, 매핑 및 경고, Fabric 이중화, 스위치 홉, 팬아웃 비율 및 씬 프로비저닝과 같은 효율성 Best Practice 정책에 대한 정보를 제공합니다.

* Plan * 은 하이브리드 사내 및 전 세계에 분산된 데이터 센터 환경에서 컴퓨팅, 패브릭 및 다양한 유형의 스토리지(cDOT, 7-Mode, 타사) 전반의 추세를 식별하고 예측하는 기능을 제공합니다. 보존 시간이 길어집니다. 데이터 웨어하우스는 보고서를 작성할 수 있는 기본 제공 인텔리전스로 구성되어 있으며 엔터프라이즈 공유 스토리지 환경에서 메트릭의 이중 카운트를 방지합니다. 제품화된 보고서의 보완을 만들고 예약할 수 있으며 통합 보고서 작성 도구를 사용하여 자신만의 보고서를 만들 수도 있습니다.
