---
permalink: faq/faq-integrating-insight-and-third-party-tools.html 
sidebar: sidebar 
keywords:  
summary: 이 FAQ에서는 OnCommand Insight와 다른 툴의 통합에 대한 일반적인 질문에 답합니다. 
---
= Insight를 다른 툴과 통합
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 FAQ에서는 OnCommand Insight와 다른 툴의 통합에 대한 일반적인 질문에 답합니다.



== OCI를 다른 툴과 통합할 수 있습니까? 사용 가능한 통합 포인트는 무엇입니까?

예. OCI는 타사 오케스트레이션, 비즈니스 관리, 변경 제어 및 티켓 시스템과 사용자 정의 CMDB 통합을 지원하는 확장 가능한 개방형 솔루션입니다. OCI에서 완전히 게시된 RESTful API와 개방형 MySQL 데이터베이스 기본 통합 지점을 사용하면 데이터를 간단하고 효과적으로 이동할 수 있으며 사용자가 데이터에 원활하게 액세스할 수 있습니다.

Insight의 Swagger 기반 API 설명서는 * (?) 아래 제품에 있습니다. 도움말 > REST API 설명서 *.



== Insight BMC Connector란 무엇입니까?

BMC용 OnCommand Insight 커넥터는 DWH(OnCommand Insight 데이터 웨어하우스)와 CMDB(BMC Atrium 구성 관리 데이터베이스)를 통합합니다. Insight Connector for BMC는 네트워크 스토리지 시스템(예: 스토리지 장치, 호스트 스토리지 서비스, VS 스토리지 서비스 및 VM 스토리지 서비스)과 장치(호스트, 스토리지 스위치, 및 테이프)를 BMC CMDB에 구성 항목 및 관계로 가져옵니다. BMC용 OnCommand Insight 커넥터에 대한 자세한 내용은 NetApp Support 사이트에서 확인할 수 있습니다.



== OCI가 SCOM 또는 VROL과 작동합니까?

예. OCI는 많은 비즈니스 관리 솔루션을 보완하며 데이터 센터의 스토리지, 컴퓨팅, 하이퍼바이저 및 패브릭 정보에 대한 신뢰할 수 있는 소스로 간주됩니다. OCI 고객은 OCI의 RESTful API 및 확장형 MySQL 데이터베이스를 활용하여 BMC의 Remedy, ServiceNow, SCOM, Vrops, Splunk와 같은 수많은 애플리케이션을 개선하고 몇 가지 이름을 말하십시오. OCI는 거의 모든 기록 소스에서 정보를 가져오거나 캡처된 환경 메트릭을 인기 있는 타사 모니터링, 발권, CMDB 청구 및 오케스트레이션 시스템에 전송하여 통합을 확장합니다.



== OCI를 이미 사용하고 있거나 사용을 고려 중인 클라우드 서비스와 함께 사용할 수 있습니까?

예. 기존 사내 환경과 민첩한 하이브리드 클라우드 환경을 모두 관리하는 OCI는 비즈니스 서비스 요구사항에 가장 적합한 비용 효율적인 플랫폼을 결정할 때 가시성을 제공합니다. OCI는 마이그레이션 전/후 분석에 활용될 수 있으며, 클라우드에 적합한 워크로드를 식별하는 데 도움이 됩니다. 적절한 클라우드 서비스를 선택하려면 기간별 용량 추세, 성능 및 비용이 모두 필요합니다. OCI의 I/O 밀도와 기타 메트릭을 활용하는 서비스 설계 워크샵은 환경을 최적화했는지와 클라우드가 적합했는지와 같은 질문에 답변하는 데에도 도움이 됩니다. OCI는 NetApp 프라이빗 스토리지, Cloud ONTAP, Amazon S3, OpenStack KVM을 지원하여 범위를 지속적으로 확장하고 있습니다. OCI는 NetApp 클라우드 관리 캠페인에서 중요한 역할을 계속 수행하며, 특히 용량 계획, 성능, 서비스 품질 및 지불 거절에 대한 가시성이 중요한 영역에서 더욱 그러합니다.



== OCI 인시던트 관리 솔루션에서 인시던트를 열 수 있습니까?

예. OCI 위반 이벤트는 SNMP를 통해 트랩 또는 Syslog를 통해 서버로, 그리고 일부는 RESTful API를 통해 트리거되어 전송될 수 있습니다. 제공된 이벤트에 포함된 세부 정보는 여러 타사 사고 관리 및 발권 솔루션에서 해석할 수 있습니다.



== 부서 또는 부서에 리소스를 할당할 수 있습니까?

예. OCI는 주석이라는 메타데이터 태그 지정 방법을 통합합니다. 사업부, 사업부, 사업 부문, 테넌트 및 프로젝트를 데이터 센터 리소스에 할당하여 자산, 용량 계획, 문제 해결 및 보고에 관한 보다 풍부한 비즈니스 컨텍스트를 제공할 수 있습니다.



== OCI는 WFA(Work Flow Automator)와 작동합니까?

OCI와 타사 CMDB, 청구 및 오케스트레이션 기술의 통합 기능은 성공을 위한 핵심 가치이며 WFA도 예외는 아닙니다. NetApp의 프로페셔널 서비스는 현재 WFA 워크플로우 및 OCI와 수많은 성공적인 통합을 수행했습니다.



== 성능 데이터에 대한 OCI 보존 시간은 얼마입니까?

OCI 서버는 실시간에 가까운 90일 동안의 성능과 현재(시점) 인벤토리(논리적 및 물리적 구조)를 보유합니다.

OCI 성능 폴링 간격은 사용자가 구성할 수 있습니다. 일반적으로 대부분의 공급업체는 스토리지 성능을 5분마다 구성합니다. 성능/인벤토리 데이터는 장기 기록 및 예측 보고를 위해 DWH(OCI 데이터 웨어하우스)로 매일 전송됩니다. DWH는 이 데이터를 요약된 데이터(시간별, 일별, 월별 롤업 데이터)로 변환합니다. 스토리지/컴퓨팅/패브릭 구성/매핑에 대해 모니터링되는 환경 기록과 같이 ""변경""을 추적하는 우리의 능력은 오늘 정의된 제한이 없습니다.

데이터 웨어하우스는 데이터 마트 및 데이터 세분화를 기반으로 기간별 데이터를 보유합니다.



== 성과 계획 보고서가 있습니까?

예, OCI와 함께 제공된 여러 보고서가 있으며 사용 사례를 기반으로 당사의 프로페셔널 서비스 카탈로그에 여러 보고서가 있습니다. 또한 데이터 웨어하우스 모듈에는 사용자가 자신의 보고서를 만들 수 있는 Cognos 보고서 작성 도구 제품군이 함께 제공됩니다.
