---
permalink: faq/faq-scale-and-ease-of-use.html 
sidebar: sidebar 
keywords:  
summary: 이 FAQ는 OnCommand Insight 확장과 사용 편의성에 대한 일반적인 질문에 답합니다. 
---
= 확장성 및 사용 편의성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 FAQ는 OnCommand Insight 확장과 사용 편의성에 대한 일반적인 질문에 답합니다.



== OCI는 어떻게 확장됩니까?

OCI는 상호 운용성과 최소한의 설치 공간으로 얻을 수 있는 자산 수를 기준으로 한 리더입니다. 핵심 요소로서 OCI는 2개의 가상 또는 물리적 서버가 필요합니다. 하나는 모든 데이터 센터 자산을 검색하는 운영 서버용이고, 다른 하나는 장기 내역 보고를 위해 통합된 데이터 웨어하우스에 적합합니다. OCI의 기업 범위 에서는 단일 서버 인스턴스에서 수백 개의 어레이, 수만 개의 가상 머신, 100,000개의 파이버 채널 경로 및 10,000개 이상의 파이버 채널 포트를 모두 지원합니다.



== OCI 애플리케이션을 관리하는 데 필요한 사람은 몇 명입니까?

OCI는 한 명의 담당자가 관리할 수 있습니다. 하지만 OCI에는 보고, 문제 해결 또는 분석 요구 사항이 각각 다른 역할을 가진 비즈니스 환경 내의 여러 사용자가 사용할 수 있는 기능이 있습니다. 구성 문제를 표시하는 상태 및 알림 메뉴에서 Fabric에 연결된 물리적 호스트의 자동 검색에 이르기까지 툴 유지 보수를 최소화하기 위해 모든 노력을 기울였습니다. 유연한 주석을 통해 모든 유형의 사용자에 대한 에코시스템 데이터에 비즈니스 컨텍스트를 제공할 수 있습니다. 스토리지, 패브릭 및 가상화 관리자부터 용량 플래너, 비즈니스 분석가 및 경영진에 이르기까지, OCI는 비즈니스 사일로와 기술 전반에 걸쳐 단일 창에서 정보를 공유할 수 있도록 합니다.



== OCI는 맞춤형 보고를 지원합니까?

예. OCI는 IBM Cognos 비즈니스 인텔리전스 툴을 통해 보고 기능을 제공하므로, OCI의 데이터 웨어하우스에 수집된 데이터로부터 완전한 맞춤형 보고서를 생성할 수 있습니다.



== 사용자 지정 보고서를 얼마나 쉽게 만들 수 있습니까?

OCI 보고 기능은 초보자 및 고급 사용자 모두에게 제공됩니다. OCI는 "Dag and Drop" 보고서 작성 및 고급 사용자 또는 전문 서비스 계약을 위한 SQL 쿼리 기반 보고 등 다양한 보고서 작성 기능을 제공합니다. OCI에 내장된 비즈니스 인텔리전스 솔루션(IBM Cognos)은 용량 두 배 증가 같은 일반적인 실수를 방지합니다. 즉시 사용 가능한 보고서, 위젯, 쿼리 및 대시보드를 보완하여 모든 보고 요구 사항에 맞는 서비스를 제공합니다.

또한 고객은 OCI 커뮤니티 스토어에서 제공되는 다운로드 가능한 보고 템플릿을 찾을 수 있습니다.



== OCI는 "신호등" 단순성으로 성능 및 가용성을 보여줄 수 있습니까?

예. OCI 데이터 웨어하우스 및 보고 기능을 사용하면 색상 개선 사항(예: 빨강/노랑/녹색 ""조건부 스타일"" 값)이 있는 보고서를 작성할 수 있습니다. 최종 사용자와 전문 서비스 모두 보고서에 컬러 글꼴 또는 배경 생성 기능을 구현할 수 있습니다. OCIS 위젯 라이브러리를 사용하면 비즈니스 관련 성능 메트릭을 대시보드에 표시할 수 있습니다.
