---
permalink: faq/faq-anomaly-detection.html 
sidebar: sidebar 
keywords:  
summary: 이 FAQ는 OnCommand Insight 이상 징후 탐지에 대한 일반적인 질문에 답합니다. 
---
= 이상 징후 탐지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 FAQ는 OnCommand Insight 이상 징후 탐지에 대한 일반적인 질문에 답합니다.



== 이상이란 무엇입니까?

이상 현상에는 이전에 관찰된 패턴과 예상된 패턴을 준수하지 않는 IOPS, 지연 시간, 활용률, 버퍼 대 버퍼 크레딧 및 CPU의 성능 변경 이벤트가 있습니다. OCI 이상 탐지 기능은 애플리케이션을 지원하는 애플리케이션 인프라를 대상으로 하며 처리 패턴 및 동작의 변화를 모색합니다. 이러한 주기적 처리 패턴에는 업무 시간 및 주말 동안의 워크로드 성능 측면에서 과거 ""ebb 및 흐름""이 포함됩니다. OCI의 이상 탐지 엔진은 머신 러닝 인텔리전스를 사용하여 "정상적인" 기준 패턴을 설정하고 정의된 애플리케이션이 예상된 동작에서 벗어날 때를 감지합니다.



== OCI에서 이상 탐지 기능은 무엇입니까?

OCI의 이상 탐지는 내역 정보를 기반으로 머신 러닝 인텔리전스를 활용하여 사전 예방 모니터링 접근 방식입니다. 기존 임계치보다 훨씬 빠르게 새로운 성능 이상을 감지할 수 있으므로 관리자가 애플리케이션 SLO 또는 데이터 센터 서비스에 영향을 미치기 전에 문제를 논의, 계획 및 완화할 수 있는 추가 시간을 확보할 수 있습니다.

Insight는 컴퓨팅 리소스, 스위치 패브릭 및 스토리지 리소스 등을 통해 애플리케이션을 지원하는 전체 인프라 스택을 검색하고 자동으로 매핑합니다. OCI는 IOPS, 지연 시간, 노드 정보, 스토리지 풀 활용률, 하이퍼바이저 CPU, 그리고 각 리소스에 대한 BB Credit Zero는 애플리케이션 이상 현상 분석에 사용할 이상 징후 탐지 엔진에 해당 데이터를 제공합니다. 이상 징후 결과는 시간당 두 번 업데이트되며 애플리케이션 대시보드, 애플리케이션 랜딩 페이지 및 쿼리 테이블 위젯을 사용하여 확인할 수 있습니다. 이상 징후 점수는 리소스별로 카운터 단위로 수행되며 전체 애플리케이션 인프라에 대해 전반적인 중요도 점수가 제공됩니다.



== OCI에서 이상 감지를 지원하는 버전은 무엇입니까?

이상 징후 감지는 OCI 7.2 이상에서 지원됩니다.



== OCI에서 이상 감지를 지원할 수 있는 애플리케이션은 몇 개입니까?

OCI는 최대 48개의 비즈니스 크리티컬 애플리케이션에 대한 모니터링을 지원합니다.



== ADES(이상 탐지 엔진)를 몇 개 구축할 수 있습니까?

OCI 운영 서버당 하나의 이상 탐지 엔진



== 48개 이상의 애플리케이션이 있는 경우 추가 이상 탐지 엔진을 구축할 수 있습니까?

예. 현재 OCI는 OCI 서버당 하나의 이상 탐지 엔진을 페어링할 수 있습니다. 다중 OCI 서버 환경에서는 이상 탐지 엔진과 OCI 운영 서버를 ""쌍을 이룬" 방식으로 추가로 구축할 수 있습니다. 각 서버는 이상 탐지 기능이 활성화된 응용 프로그램에만 가시성을 가집니다.



== 애플리케이션 클러스터/그룹의 크기에 대한 확장 제한이 있습니까?

Insight anomaly 감지 기능을 사용하여 최적의 운영 및 확장성을 위한 OCI 엔지니어링 일반 지침은 다음과 같습니다. Insight 서버당 하나의 이상 징후 탐지 엔진이 지원됩니다. OCI에서 최대 48개의 애플리케이션을 모니터링할 수 있습니다. 애플리케이션 인프라는 최대 4000개의 오브젝트로 구성될 수 있습니다. 리소스가 부족하면 전체적인 규모가 줄어듭니다.



== 이상 징후 탐지에 필요한 OCI 라이센스는 무엇입니까?

이상 징후 탐지 분석에는 라이센스 검색 및 수행 모두 필요합니다.



== 이상 징후 탐지를 시작하고 결과를 보는 데 시간이 얼마나 걸립니까?

이상 징후 점수 결과는 애플리케이션 모니터링이 활성화된 후 2-3시간 이내에 나타납니다.



== 결과 운영을 사용하기 전에 얼마나 기다려야 합니까?

이상 징후 탐지 엔진의 품질과 정확도는 시간(주, 월, 분기 등)에 따라 향상됩니다. 주기적 평가(주기성)는 일반적으로 3주 경에 시작됩니다. 시간이 긴 패턴(예: 매월)의 경우, 이상 점수를 조정하기 전에 반복 이벤트를 관찰해야 합니다.



== 이상 현상 감지 엔진이 학습을 유지하는 시간은 얼마입니까?

이상 현상 감지 엔진은 학습 정보를 저장하는 방식에 매우 효율적입니다. 통계적 학습은 개체의 비정상적인 동작에 대해 수 개월 단위로 측정할 수 있습니다. Insight에서는 일반 데이터 집합을 사용할 때 흔히 생각하는 "보존"은 없습니다. 이상 징후 탐지 엔진은 시간이 지남에 따라 "의미 있는" 것으로 결정된 데이터를 학습하고 저장하며, 필요한 경우 중요하지 않은 데이터를 오랜 시간 동안 보관합니다. 이 메커니즘은 학습 기간을 크게 증가시키고 데이터를 저장하는 데 필요한 리소스와 분석을 수행하는 데 필요한 시간을 모두 줄여줍니다



== 오늘 이상 징후 탐지를 활성화하면 지난 주에 발생한 이상 징후를 알 수 있습니까?

아니요. 이상 현상 감지를 초기화할 때 Insight 서버는 Insight 서버에서 기존 성능 데이터를 로드하여 모니터링된 애플리케이션과 인프라에 대한 이상 징후 탐지 엔진을 지원합니다. 수집된 ""기존" 성능 데이터에는 이상이 제공되지 않습니다. 기존 데이터에 대해 분석할 때 새로 들어오는 데이터에만 이상이 보고됩니다. 새로 감지된 이상은 몇 시간 안에 표시됩니다.



== 이상 징후 점수는 어떻게 계산됩니까?

각 응용 프로그램 이상 점수는 다양한 개별 자산 점수의 롤업에서 계산됩니다. 이상 징후 탐지 엔진은 30개 이상의 복잡한 알고리즘과 공식을 이용하여 이상 징후 확인 및 점수를 제공합니다. 사용자는 다양한 변수와 측정(체중, 연령, 신장, 밀도 등)으로 구성된 체질량지수(BMI) 점수와 같은 유사한 의료 점수 기술과 이러한 유형의 분석 점수 기법을 비교할 수 있습니다.



== 각 파란색 막대는 무엇을 나타냅니까?

막대 3개의 각 블록은 리소스 및 이상 중요도 범위를 나타냅니다. 파란색 막대가 많을수록 관찰된 행동의 변화가 커집니다. 블록을 클릭하면 개별 리소스 및 카운터의 중요도(이상)가 표시됩니다.



== 개별 리소스 점수가 총 응용 프로그램 점수에 합산되지 않는 이유는 무엇입니까?

각 리소스는 관찰된 행동의 편차에 따라 개별적으로 점수가 매겨집니다. 개별 리소스 점수 부여 중요성은 전체 응용 프로그램 점수에 영향을 주지만 다른 분석 및 수학 요소도 포함될 수 있습니다.



== 주석이 할당된 비즈니스 엔터티 또는 개체를 모니터링하도록 이상 탐지를 구성할 수 있습니까?

현재는 정의된 애플리케이션에서만 이상 탐지를 활성화할 수 있습니다. 애플리케이션에 할당할 수 있는 모든 개체(VM, 하이퍼바이저, 서버, 볼륨 및 내부 볼륨)를 그룹화 및 모니터링할 수 있습니다.



== OCI는 높은 이상 점수를 통지할 수 있습니까?

예. 애플리케이션의 이상 징후 점수를 기반으로 애플리케이션 성능 정책을 생성할 수 있습니다. 정책에 정의된 임계값을 건너면 응용 프로그램의 리소스와 관련된 문제를 사용자에게 알리는 알림이 트리거됩니다.



== 애플리케이션에서 이상 현상 감지를 끄면 어떻게 됩니까?

애플리케이션 인프라스트럭처에 대해 학습된(기간별 이상) 정보는 이상 탐지 엔진에서 모두 삭제됩니다. 모든 이상 징후 감지 결과가 Insight 운영 데이터베이스에서 삭제됩니다.



== 정적 임계값은 언제 사용해야 합니까?

정적 임계값은 인프라 리소스 제한에 대한 Best Practice 알림과 이벤트 기간을 식별하는 데 적합합니다. 또한 서비스 수준 관리를 지원하고 링크 재설정, 클래스 3 폐기 및 동기화 손실 등의 다양한 오류 카운터 메트릭을 경고합니다.



== 이상 징후 탐지에 다른 메트릭을 포함하기 위한 계획은 무엇입니까?

새로운 통계 데이터, 사용자 피드백 및 제품 개선을 이용할 수 있게 됨에 따라 이상 머신 러닝 모델 및 알고리즘이 계속 개선되거나 조정됩니다.



== 데이터 웨어하우스(DWH)에서 이상 결과 를 사용할 수 있습니까?

현재 비정상 결과가 OCI 데이터 웨어하우스로 전송(ETL 제공)되지 않습니다. 사용자는 OCI 애플리케이션 랜딩 페이지 또는 사용자 정의 쿼리 테이블 위젯에서 결과를 찾을 수 있습니다.
