---
permalink: config-admin/3par-inserv-firmware-ssh-data-source.html 
sidebar: sidebar 
keywords:  
summary: 'OnCommand Insight는 3PAR InServ\(펌웨어 2.2.2+, SSH\) 데이터 소스를 사용하여 HP 3PAR StoreServ 스토리지 어레이의 인벤토리를 검색합니다.' 
---
= 3PAR InServ 데이터 소스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight는 3PAR InServ(펌웨어 2.2.2+, SSH) 데이터 소스를 사용하여 HP 3PAR StoreServ 스토리지 어레이의 인벤토리를 검색합니다.



== 용어

OnCommand Insight는 3PAR InServ 데이터 소스에서 다음과 같은 인벤토리 정보를 가져옵니다. Insight에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 소스를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

|===


| 공급업체/모델 기간 | Insight 용어입니다 


 a| 
물리 디스크
 a| 
디스크



 a| 
스토리지 시스템
 a| 
스토리지



 a| 
컨트롤러 노드
 a| 
스토리지 노드



 a| 
공통 프로비저닝 그룹
 a| 
스토리지 풀



 a| 
가상 볼륨
 a| 
볼륨

|===
[NOTE]
====
이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 소스의 모든 경우를 나타내는 것은 아닙니다.

====


== 요구 사항

* InServ 클러스터의 IP 주소 또는 FQDN입니다
* 인벤토리의 경우 InServ 서버에 대한 읽기 전용 사용자 이름 및 암호입니다.
* 성능을 위해 InServ 서버에 대한 읽기-쓰기 사용자 이름 및 암호.
* 포트 요구 사항: 22(인벤토리 수집), 5988 또는 5989(성능 수집) [참고: 3PAR 성능은 InServ OS 3.x+에서 지원됩니다.]
* 성능 수집을 위해 SSH를 통해 3PAR 스토리지에 로그인하여 SMI-S가 활성화되었는지 확인합니다.




== 구성

|===


| 필드에 입력합니다 | 설명 


 a| 
클러스터 IP
 a| 
InServ 클러스터의 IP 주소 또는 정규화된 도메인 이름입니다



 a| 
사용자 이름
 a| 
InServ 서버의 사용자 이름입니다



 a| 
암호
 a| 
InServ 서버에 사용되는 암호입니다



 a| 
SMI-S 호스트 IP입니다
 a| 
SMI-S Provider 호스트의 IP 주소입니다



 a| 
SMI-S 사용자 이름
 a| 
SMI-S Provider 호스트의 사용자 이름입니다



 a| 
SMI-S 암호
 a| 
SMI-S Provider 호스트에 사용되는 암호입니다

|===


== 고급 구성

|===


| 필드에 입력합니다 | 설명 


 a| 
재고 폴링 간격(분)
 a| 
재고 조사 간격(기본값 40분)



 a| 
장치 제외
 a| 
제외할 장치 IP의 쉼표로 구분된 목록입니다



 a| 
SSH 프로세스 대기 시간 초과(초)
 a| 
SSH 프로세스 시간 초과(기본값 60초)



 a| 
SSH 재시도 횟수
 a| 
SSH 재시도 횟수입니다



 a| 
SSH 배너 대기 시간 제한(초)
 a| 
SSH 배너 대기 시간 초과(기본값 20초)



 a| 
SMI-S 포트
 a| 
SMI-S Provider 호스트에서 사용하는 포트입니다



 a| 
프로토콜
 a| 
SMI-S 공급자에 연결하는 데 사용되는 프로토콜입니다



 a| 
SMI-S 네임스페이스
 a| 
SMI-S 네임스페이스



 a| 
성능 폴링 간격(초)
 a| 
성능 폴링 간격(기본값 300초)



 a| 
SMI-S 연결 재시도 횟수
 a| 
SMI-S 연결 재시도 횟수입니다

|===