---
permalink: config-admin/about-oncommand-insight-anomaly-detection.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight에는 애플리케이션의 인프라에 대한 가시성을 제공하고 서비스 중단이 발생하기 전에 성능 이상을 식별하는 머신 러닝 이상 탐지 분석이 포함되어 있습니다. 
---
= OnCommand Insight 이상 징후 탐지 작동 방식
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight에는 애플리케이션의 인프라에 대한 가시성을 제공하고 서비스 중단이 발생하기 전에 성능 이상을 식별하는 머신 러닝 이상 탐지 분석이 포함되어 있습니다.

이상 현상 분석을 통해 애플리케이션의 정상적인 운영 워크로드 범위를 식별하고 성능 변화가 예상 수준을 벗어날 때 이를 알려줍니다. 애플리케이션 이상 징후 탐지 엔진은 Insight에서 수집한 성능 메트릭을 수집하고 애플리케이션 인프라의 이상 징후를 식별합니다.

이상 현상 감지를 사용하여 다음 작업을 수행할 수 있습니다.

* 애플리케이션 인프라 동작의 중요한 변경 사항 파악
* 전체 스택 및 여러 카운터에서 응용 프로그램을 추적합니다
* 애플리케이션 워크로드에서 주기적으로 반복되는 이벤트의 원인을 진단합니다
* 정적 임계값을 사용하는 성능 카운터의 데이터와 비교하여 보다 포괄적인 정보 집합을 제공합니다
* 토폴로지를 완벽하게 파악하고 가장 이례적인 동작에 집중할 수 있는 기능을 통해 개선된 대응 모드로 모니터링합니다.


이상 현상 감지 엔진은 애플리케이션 분석을 위해 Insight 데이터를 사용합니다. 모니터링을 처음 시작할 때 분석 엔진을 통해 최대 14일간의 기간별 성능 데이터를 수집해 볼 수 있습니다. 데이터는 몇 주 또는 몇 개월 동안 수집되어 특정 리소스에 대한 보다 정확한 데이터를 제공합니다. 데이터에는 다음 카운터의 총계가 포함됩니다.

|===


| 오브젝트 | 카운터 


 a| 
VM
 a| 
지연 시간, IOPS



 a| 
하이퍼바이저
 a| 
CPU 활용률, IOPS



 a| 
에지 포트
 a| 
BB 크레딧 없음



 a| 
스토리지 노드
 a| 
지연 시간, 활용률, IOPS



 a| 
볼륨
 a| 
지연 시간, IOPS



 a| 
내부 볼륨
 a| 
지연 시간, IOPS



 a| 
스토리지 풀
 a| 
IOPS, 활용률

|===
이상 징후 탐지 엔진이 수집한 데이터는 Insight 서버에서 성능 데이터 아카이빙을 활성화할 때 보관됩니다. 시스템 상태 페이지를 참조하여 아카이빙이 활성화되었는지 확인합니다.

이상 현상 감지 엔진은 Insight 서버가 아닌 별도의 서버에서 실행됩니다. 물리적 시스템 또는 VM에 구성할 수 있습니다. 자세한 내용은 Windows 또는 Linux용 OnCommand Insight 설치 안내서 를 참조하십시오.
