---
permalink: config-admin/adding-a-missing-disk-model.html 
sidebar: sidebar 
keywords:  
summary: 알 수 없는 디스크 모델로 인해 획득에 실패한 경우 누락된 디스크 모델을 new_disk_models.txt 파일에 추가하고 획득을 다시 실행할 수 있습니다. 
---
= 누락된 디스크 모델을 추가하는 중입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
알 수 없는 디스크 모델로 인해 획득에 실패한 경우 누락된 디스크 모델을 에 추가할 수 있습니다 `new_disk_models.txt` 촬영 후 다시 실행합니다.



== 이 작업에 대해

OnCommand Insight 획득을 통해 스토리지 디바이스를 폴링하는 과정에서 스토리지 디바이스의 디스크 모델이 읽힙니다. 공급업체가 Insight에서 알지 못하는 새로운 디스크 모델을 어레이에 추가하거나, Insight가 찾는 모델 번호와 스토리지 장치에서 반환된 모델 번호가 일치하지 않으면 해당 데이터 소스를 획득하지 못하고 오류가 발생합니다. 이러한 오류를 방지하려면 Insight에 알려진 디스크 모델 정보를 업데이트해야 합니다. 업데이트, 패치 및 유지 관리 릴리즈를 통해 새로운 디스크 모델이 Insight에 추가됩니다. 그러나 패치나 업데이트를 기다리는 대신 이 정보를 수동으로 업데이트할 수 있습니다.

OnCommand Insight는 5분마다 디스크 모델 파일을 읽기 때문에 입력한 새 데이터 모델 정보가 자동으로 업데이트됩니다. 변경 사항을 적용하기 위해 서버를 다시 시작할 필요는 없지만 서버 및 원격 획득 장치(RA)를 다시 시작하여 다음 업데이트 전에 변경 사항을 적용할 수 있습니다.

디스크 모델 업데이트가 에 추가됩니다 `new_disk_models.txt` 에 있는 파일``<SANScreenInstallDir>\wildfly\standalone\deployments\datasources.war`` 디렉토리. 를 업데이트하기 전에 새 디스크 모델을 설명하는 데 필요한 정보를 파악합니다 `new_disk_models.txt` 파일. 파일의 정보가 부정확하면 잘못된 시스템 데이터가 생성되고 획득 실패를 초래할 수 있습니다.

Insight 디스크 모델을 수동으로 업데이트하려면 다음 지침을 따르십시오.



== 단계

. 디스크 모델에 대한 적절한 정보를 찾습니다.
. 텍스트 편집기를 사용하여 를 엽니다 `new_disk_models.txt` 파일.
. 새 데이터 원본에 필요한 정보를 추가합니다.
. 에 파일을 저장합니다 `<SANScreenInstallDir>\wildfly\standalone\deployments\datasources.war` 서버의 디렉터리입니다.
. 를 백업합니다 `new_disk_models.txt` 파일을 안전한 위치에 보관합니다. 이후의 OnCommand Insight 업그레이드 중에 이 파일을 덮어씁니다. 디스크 모델 정보가 업그레이드된 파일에 없는 경우 다시 입력해야 합니다.

