---
permalink: config-admin/adding-data-sources.html 
sidebar: sidebar 
keywords:  
summary: 데이터 원본 추가 대화 상자를 사용하여 데이터 원본을 빠르게 추가할 수 있습니다. 
---
= 데이터 소스 추가
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 원본 추가 대화 상자를 사용하여 데이터 원본을 빠르게 추가할 수 있습니다.



== 단계

. 브라우저에서 OnCommand Insight를 열고 관리자 권한이 있는 사용자로 로그인합니다.
. Admin * 을 선택하고 * Data Sources * 를 선택합니다.
. 추가 * 버튼을 클릭합니다.
+
데이터 소스 추가 마법사가 열립니다.

. 설정 * 섹션에서 다음 정보를 입력합니다.
+
|===


| 필드에 입력합니다 | 설명 


 a| 
이름
 a| 
이 데이터 원본의 고유한 네트워크 이름을 입력합니다. 참고: 데이터 소스 이름에는 문자, 숫자 및 밑줄(_) 문자만 사용할 수 있습니다.



 a| 
공급업체
 a| 
드롭다운에서 데이터 소스의 공급업체를 선택합니다.



 a| 
모델
 a| 
드롭다운에서 데이터 원본의 모델을 선택합니다.



 a| 
실행 위치
 a| 
로컬 을 선택하거나 환경에 RAU가 구성되어 있는 경우 원격 획득 장치를 선택할 수 있습니다.



 a| 
수집 대상
 a| 
대부분의 데이터 원본의 경우 이러한 옵션은 인벤토리 및 성능 입니다. 재고는 항상 기본적으로 선택되며 선택 취소할 수 없습니다. 일부 데이터 원본의 경우 옵션이 다를 수 있습니다. 선택한 컬렉션 옵션은 구성 및 고급 구성 섹션에서 사용 가능한 필드를 변경합니다.

|===
. Configuration* 링크를 클릭하고 선택한 데이터 수집 유형을 사용하여 데이터 원본에 필요한 기본 설정 정보를 입력합니다.
. 이러한 유형의 데이터 소스를 네트워크에 설정하기 위해 일반적으로 더 자세한 정보가 필요한 경우 * 고급 구성 * 링크를 클릭하여 추가 정보를 입력합니다.
. 특정 데이터 원본에 필요하거나 사용 가능한 구성 또는 고급 구성 정보에 대한 자세한 내용은 를 참조하십시오link:vendor-specific-data-source-reference.html["공급업체별 데이터 소스 참조"].
. 데이터 소스가 올바르게 구성되었는지 확인하려면 * Test *(테스트 *) 링크를 클릭합니다.
. 저장 * 을 클릭합니다.

