---
permalink: config-admin/advanced-asset-search-techniques-new.html 
sidebar: sidebar 
keywords:  
summary: 모니터링되는 환경에서 데이터 또는 개체를 검색하는 데 여러 검색 기술을 사용할 수 있습니다. 
---
= 고급 검색 기술
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
모니터링되는 환경에서 데이터 또는 개체를 검색하는 데 여러 검색 기술을 사용할 수 있습니다.



== 와일드카드 검색

문자를 사용하여 여러 문자 와일드카드 검색을 수행할 수 있습니다. 예를 들어, _applic*n_은(는) 응용 프로그램을 반환합니다.



== 검색에 사용되는 구

구문은 큰따옴표로 둘러싸인 단어 그룹입니다(예: "Paw VNX LUN 5"). 큰따옴표를 사용하여 이름이나 속성에 공백이 포함된 문서를 검색할 수 있습니다.



== 부울 연산자

부울 연산자를 사용하면 여러 용어를 결합하여 보다 복잡한 쿼리를 만들 수 있습니다.

* * 또는 *
+
** 또는 연산자는 기본 결합 연산자입니다.
+
두 용어 사이에 부울 연산자가 없으면 OR 연산자가 사용됩니다.

** OR 연산자는 두 용어를 연결하고 문서에 일치하는 용어가 있는 경우 일치하는 문서를 찾습니다.
+
예를 들어, "스토리지 또는 NetApp"은 "스토리지" 또는 "NetApp"이 포함된 문서를 검색합니다.

** 대부분의 조건과 일치하는 문서에 높은 점수가 부여됩니다.


* 및 *
+
AND 연산자를 사용하여 두 검색어가 모두 하나의 문서에 있는 문서를 찾을 수 있습니다. 예를 들어, ""오로라"와 "NetApp""이 모두 포함된 문서를 검색합니다.

+
단어 및 대신 && 기호를 사용할 수 있습니다.

* * NOT *
+
NOT 연산자를 사용하면 NOT가 포함된 모든 문서가 검색 결과에서 제외됩니다. 예를 들어, "NetApp이 아닌 스토리지"는 "NetApp"이 아닌 "스토리지"만 포함된 문서를 검색합니다.

+
기호를 사용할 수 있습니다! 대신 'NOT'이라는 단어를 사용하십시오.





== 접두사 및 접미사 검색

* 검색 문자열을 입력하기 시작하면 검색 엔진은 가장 일치하는 항목을 찾기 위해 접두사 및 접미사 검색을 수행합니다.
* 정확히 일치하는 항목이 접두사 또는 접미사 일치보다 높은 점수를 받습니다. 점수는 실제 검색 결과와 검색 용어의 거리를 기준으로 계산됩니다. 예를 들어, ""오로라", ""오로라 1", ""오로라 11""의 세 가지 창고를 사용할 수 있습니다. 아우르(Aur)를 검색하면 3곳의 모든 업소를 찾을 수 있습니다. 그러나 검색결과 검색어와 검색문자열 사이의 거리가 가장 가깝기 때문에 검색 결과가 가장 높은 점수를 받게 됩니다.
* 또한 검색 엔진은 검색어를 역순으로 검색하여 접미사 검색을 수행할 수 있습니다. 예를 들어 검색 상자에 ""345""를 입력하면 검색 엔진이 ""345""를 검색합니다.
* 검색은 대/소문자를 구분하지 않습니다.




== 인덱싱된 용어를 사용하여 검색합니다

인덱싱된 용어 중 더 많은 조건과 일치하는 검색을 수행하면 더 높은 점수를 얻을 수 있습니다.

검색 문자열은 스페이스를 기준으로 별도의 검색어로 분할됩니다. 예를 들어 검색 문자열 "Storage aurora NetApp"은 "Storage", "aurora", "NetApp" 등의 세 가지 키워드로 구분됩니다. 검색은 세 가지 용어를 모두 사용하여 수행됩니다. 이 용어 중 대부분과 일치하는 문서의 점수가 가장 높습니다. 더 많은 정보를 제공할수록 검색 결과가 더 좋습니다. 예를 들어 이름 및 모드로 스토리지를 검색할 수 있습니다.

UI는 범주 별로 검색 결과를 표시하며 범주 당 상위 3개 결과를 표시합니다. 원하는 문서를 찾지 못한 경우 검색 문자열에 더 많은 용어를 포함해서 검색 결과를 개선할 수 있습니다.

다음 표에서는 검색 문자열에 추가할 수 있는 인덱싱된 용어 목록을 제공합니다.

|===


| 범주 | 인덱싱된 용어 


 a| 
스토리지
 a| 
* "스토리지"
* 이름
* 공급업체
* 모델




 a| 
스토리지 풀
 a| 
* "초라풀"
* 이름
* 스토리지의 이름입니다
* 스토리지의 IP 주소입니다
* 스토리지의 일련 번호입니다
* 스토리지 공급업체
* 스토리지 모델
* 연결된 모든 내부 볼륨의 이름입니다
* 연결된 모든 디스크의 이름입니다




 a| 
내부 볼륨
 a| 
* "'인턴 볼륨'"
* 이름
* 스토리지의 이름입니다
* 스토리지의 IP 주소입니다
* 스토리지의 일련 번호입니다
* 스토리지 공급업체
* 스토리지 모델
* 스토리지 풀의 이름입니다
* 연결된 모든 공유의 이름입니다
* 모든 관련 애플리케이션 및 업무 엔티티의 이름




 a| 
볼륨
 a| 
* "'볼륨'"
* 이름
* 라벨
* 모든 내부 볼륨의 이름입니다
* 스토리지 풀의 이름입니다
* 스토리지의 이름입니다
* 스토리지의 IP 주소입니다
* 스토리지의 일련 번호입니다
* 스토리지 공급업체
* 스토리지 모델




 a| 
스토리지 노드
 a| 
* "거어코드"
* 이름
* 스토리지의 이름입니다
* 스토리지의 IP 주소입니다
* 스토리지의 일련 번호입니다
* 스토리지 공급업체
* 스토리지 모델




 a| 
호스트
 a| 
* "'호스트'"
* 이름
* IP 주소
* 모든 관련 애플리케이션 및 업무 엔티티의 이름




 a| 
데이터 저장소
 a| 
* "다타스토어"
* 이름
* 가상 센터 IP
* 모든 볼륨의 이름입니다
* 모든 내부 볼륨의 이름입니다




 a| 
가상 머신
 a| 
* "'가상시스템'"
* 이름
* DNS 이름입니다
* IP 주소
* 호스트의 이름입니다
* 호스트의 IP 주소입니다
* 모든 데이터 저장소의 이름입니다
* 모든 관련 애플리케이션 및 업무 엔티티의 이름




 a| 
스위치(일반 및 NPV)
 a| 
* 마녀
* IP 주소입니다
* WWN입니다
* 이름
* 일련 번호입니다
* 모델
* 도메인 ID입니다
* 패브릭의 이름입니다
* 패브릭의 WWN입니다




 a| 
응용 프로그램
 a| 
* "'응용 프로그램'"
* 이름
* 테넌트
* LOB가 포함됩니다
* 부서
* 프로젝트




 a| 
테이프
 a| 
* "'테이프'"
* IP 주소입니다
* 이름
* 일련 번호입니다
* 공급업체




 a| 
포트
 a| 
* "'포트'"
* WWN입니다
* 이름




 a| 
패브릭
 a| 
* "'fabric'"
* WWN입니다
* 이름


|===