---
permalink: config-admin/amazon-aws-ec2-data-source.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight은 이 데이터 소스를 사용하여 Amazon AWS EC2의 인벤토리 및 성능을 검색합니다. 
---
= Amazon AWS EC2 데이터 소스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight은 이 데이터 소스를 사용하여 Amazon AWS EC2의 인벤토리 및 성능을 검색합니다.



== 전제 조건:

Amazon EC2 장치에서 데이터를 수집하려면 다음 정보가 있어야 합니다.

* IAM 액세스 키 ID가 있어야 합니다
* Amazon EC2 클라우드 계정에 대한 비밀 액세스 키가 있어야 합니다
* "조직 목록" 권한이 있어야 합니다
* 포트 433 HTTPS
* EC2 인스턴스는 가상 머신 또는 (비교적 자연스럽게) 호스트로 보고할 수 있습니다. EBS 볼륨은 VM에서 사용하는 가상 디스크와 가상 디스크의 용량을 제공하는 데이터 저장소로 보고될 수 있습니다.


액세스 키는 액세스 키 ID(예: AKIAIOSFODN7EXAMPLE)와 비밀 액세스 키(예: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY)로 구성됩니다. 액세스 키를 사용하여 Amandzon EC2 SDK, REST 또는 쿼리 API 작업을 사용하는 경우 EC@에 만드는 프로그래밍 방식 요청에 서명할 수 있습니다. 이러한 키는 아마존에서 귀하의 계약과 함께 제공됩니다.



== 이 데이터 소스를 구성하는 방법

Amazon AWS EC2 데이터 소스를 구성하려면 AWS 계정에 대한 AWS IAM 액세스 키 ID와 비밀 액세스 키가 필요합니다.

아래 표에 따라 데이터 원본 필드를 채웁니다.



== 구성:

|===


| 필드에 입력합니다 | 설명 


 a| 
AWS 지역
 a| 
AWS 지역을 선택하십시오



 a| 
IAM 역할
 a| 
AWS의 AU에서 획득한 경우에만 사용합니다. IAM 역할에 대한 자세한 내용은 아래를 참조하십시오.



 a| 
AWS IAM 액세스 키 ID
 a| 
AWS IAM 액세스 키 ID를 입력합니다. IAM Role을 사용하지 않는 경우 필수입니다.



 a| 
AWS IAM 비밀 액세스 키
 a| 
AWS IAM 비밀 액세스 키를 입력합니다. IAM Role을 사용하지 않는 경우 필수입니다.



 a| 
저는 AWS가 API 요청에 대해 청구하는 것을 알고 있습니다
 a| 
이 확인란을 선택하여 AWS에서 Insight 폴링으로 인한 API 요청 비용을 청구하는지 확인하십시오

|===


== 고급 구성:

|===


| 필드에 입력합니다 | 설명 


 a| 
추가 지역 포함
 a| 
폴링에 포함할 추가 영역을 지정합니다.



 a| 
교차 계정 역할
 a| 
서로 다른 AWS 계정의 리소스에 액세스하는 역할입니다.



 a| 
재고 폴링 간격(분)
 a| 
재고 조사 간격(기본값: 60분)



 a| 
HTTP 연결 및 소켓 시간 제한(초)
 a| 
HTTP 연결 시간 초과(기본값 300초)



 a| 
AWS 태그 포함
 a| 
Insight 주석에서 AWS 태그에 대한 지원을 활성화하려면 이 확인란을 선택합니다



 a| 
성능 폴링 간격(초)
 a| 
성능 폴링 간격(기본값: 1800초)

|===


== AWS 태그를 Insight 주석에 매핑

AWS EC2 데이터 원본에는 AWS에 구성된 태그로 Insight 주석을 채울 수 있는 옵션이 포함되어 있습니다. 주석 이름은 AWS 태그와 정확히 일치해야 합니다. Insight는 항상 같은 이름의 텍스트 유형 주석을 채우고 다른 유형의 주석(숫자, 부울 등)을 채우기 위한 "최선의 시도"를 만듭니다. 주석이 다른 유형이고 데이터 소스가 주석을 채우지 못할 경우 주석을 제거하고 텍스트 유형으로 다시 생성해야 할 수 있습니다.

AWS는 대/소문자를 구분하며 Insight는 대/소문자를 구분합니다. 따라서 Insight에서 "소유자"라는 주석을 만들고 AWS에서 "소유자", "소유자", "소유자", "소유자"라는 태그를 만들면 "소유자"의 모든 AWS 변형이 Insight의 "소유자" 주석에 매핑됩니다.

관련 정보:

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_access-keys.html["IAM 사용자를 위한 액세스 키 관리"]



== 추가 지역 포함

AWS Data Collector * 고급 구성 * 섹션에서 추가 영역을 포함하도록 * 추가 영역 포함 * 필드를 쉼표 또는 세미콜론으로 구분하여 설정할 수 있습니다. 기본적으로 이 필드는 모든 미국 AWS 지역에서 수집하는 *_us-. * _ * 로 설정됩니다. on_all_regions를 수집하려면 이 필드를 * _. * _ * 로 설정합니다.

추가 영역 포함 * 필드가 비어 있으면 * 구성 * 섹션에 지정된 * AWS 지역 * 필드에 지정된 자산에 대한 데이터 수집기가 수집됩니다.



== * AWS 하위 계정에서 수집 *

Insight는 단일 AWS 데이터 수집기 내에서 AWS의 하위 계정 수집을 지원합니다. 이 컬렉션에 대한 구성은 AWS 환경에서 수행됩니다.

* 운영 계정 ID가 하위 계정에서 EC2 세부 정보에 액세스할 수 있도록 각 하위 계정에 AWS 역할을 구성해야 합니다.
* 각 하위 계정에는 동일한 문자열로 구성된 역할 이름이 있어야 합니다
* 이 역할 이름 문자열을 * 교차 계정 역할 * 필드의 Insight AWS Data Collector * 고급 구성 * 섹션에 입력합니다.


모범 사례: AWS 사전 정의된 AmazonEC2ReadOnlyAccess 정책을 ECS 기본 계정에 할당하는 것이 좋습니다. 또한 데이터 소스에서 구성된 사용자는 AWS를 쿼리하기 위해 미리 정의된 __AWSOrganizationReadOnlyAccess__ 정책이 할당되어 있어야 합니다.

Insight를 AWS 하위 계정에서 수집할 수 있도록 환경을 구성하는 방법은 다음을 참조하십시오.

https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html["자습서: IAM 역할을 사용하여 AWS 계정 전체에서 대리인 액세스"]

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_common-scenarios_aws-accounts.html["AWS 설정: 사용자가 소유한 다른 AWS 계정에서 IAM 사용자에 대한 액세스 제공"]

https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user.html["IAM 사용자에 대한 권한을 위임하기 위한 역할 생성"]



== IAM 역할

IAM Role_security를 사용할 때는 생성하거나 지정하는 역할에 리소스에 액세스하는 데 필요한 적절한 권한이 있는지 확인해야 합니다.

예를 들어, 이름이 _InstanceE2ReadOnly_인 IAM 역할을 생성하는 경우 이 IAM 역할에 대한 모든 EC2 리소스에 EC2 읽기 전용 목록 액세스 권한을 부여하도록 정책을 설정해야 합니다. 또한 이 역할이 계정 간에 역할을 수행할 수 있도록 STS(보안 토큰 서비스) 액세스를 부여해야 합니다.

IAM 역할을 생성한 후 새 EC2 인스턴스 또는 기존 EC2 인스턴스를 생성할 때 연결할 수 있습니다.

IAM role_InstanceE2ReadOnly_를 EC2 인스턴스에 연결하면 IAM 역할 이름으로 인스턴스 메타데이터를 통해 임시 자격 증명을 검색하고 이 EC2 인스턴스에서 실행되는 모든 애플리케이션에서 이 자격 증명을 사용하여 AWS 리소스에 액세스할 수 있습니다.


NOTE: IAM 역할은 획득 장치가 AWS 인스턴스에서 실행 중인 경우에만 사용할 수 있습니다.
