---
permalink: config-admin/assigning-annotations-using-a-query.html 
sidebar: sidebar 
keywords: bulk edit 
summary: 자산 그룹에 주석을 할당하면 쿼리 또는 대시보드에서 관련 자산을 보다 쉽게 식별하거나 사용할 수 있습니다. 
---
= 쿼리를 사용하여 여러 자산에 주석 할당
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
자산 그룹에 주석을 할당하면 쿼리 또는 대시보드에서 관련 자산을 보다 쉽게 식별하거나 사용할 수 있습니다.



== 시작하기 전에

자산에 지정하려는 주석이 이미 생성되어 있어야 합니다.



== 이 작업에 대해

쿼리를 사용하여 여러 자산에 주석을 할당하는 작업을 단순화할 수 있습니다. 예를 들어 특정 데이터 센터 위치의 모든 어레이에 사용자 지정 주소 주석을 할당하려는 경우



== 단계

. 새 쿼리를 만들어 주석을 할당할 자산을 식별합니다. 쿼리 * > * + 새 쿼리 * 를 클릭합니다.
. Search for... * 드롭다운에서 * Storage * 를 선택합니다. 표시된 저장소 목록을 더 좁히도록 필터를 설정할 수 있습니다.
. 표시된 저장소 목록에서 저장소 이름 옆의 확인란을 클릭하여 하나 이상의 저장소 를 선택합니다. 목록 상단의 기본 확인란을 클릭하여 표시된 모든 저장소를 선택할 수도 있습니다.
. 원하는 저장소를 모두 선택한 경우 * Actions * > * Edit Annotation * 을 클릭합니다.
+
주석 추가 대화 상자가 표시됩니다.

. 저장소에 할당할 * 주석 * 및 * 값 * 을 선택하고 * 저장 * 을 클릭합니다.
+
해당 주석의 열을 표시하는 경우 선택한 모든 저장소에 표시됩니다.

. 이제 주석을 사용하여 위젯 또는 쿼리의 저장소를 필터링할 수 있습니다. 위젯에서 다음을 수행할 수 있습니다.
+
.. 대시보드를 만들거나 기존 대시보드를 엽니다. 변수 * 를 추가하고 위의 저장소에 설정한 주석을 선택합니다. 변수가 대시보드에 추가됩니다.
.. 방금 추가한 변수 필드에서 * any * 를 클릭하고 필터링할 적절한 값을 입력합니다. 체크 표시를 클릭하여 변수 값을 저장합니다.
.. 위젯을 추가합니다. 위젯의 쿼리에서 ** 필터 기준 ****+** 단추를 클릭하고 목록에서 적절한 주석을 선택합니다.
.. 아무 * 나 * 를 클릭하고 위에서 추가한 주석 변수를 선택합니다. 작성한 변수는 ""$"로 시작하고 드롭다운에 표시됩니다.
.. 원하는 다른 필터 또는 필드를 설정한 다음 위젯이 원하는 대로 사용자 지정되면 * 저장 * 을 클릭합니다.


+
대시보드의 위젯에는 주석을 할당한 저장소에 대한 데이터만 표시됩니다.


