---
permalink: config-admin/auditing-system-and-user-activities.html 
sidebar: sidebar 
keywords:  
summary: 예기치 않은 변경 내용을 찾으려면 OnCommand Insight 시스템 및 해당 사용자 작업의 감사 추적을 볼 수 있습니다. 감사 로그 메시지는 감사 페이지에 표시될 뿐만 아니라 syslog에 선택적으로 보낼 수 있습니다. 
---
= 시스템 및 사용자 작업 감사
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
예기치 않은 변경 내용을 찾으려면 OnCommand Insight 시스템 및 해당 사용자 작업의 감사 추적을 볼 수 있습니다. 감사 로그 메시지는 감사 페이지에 표시될 뿐만 아니라 syslog에 선택적으로 보낼 수 있습니다.



== 이 작업에 대해

Insight는 다음을 비롯하여 스토리지 네트워크 또는 스토리지 관리에 영향을 미치는 모든 사용자 활동에 대한 감사 항목을 생성합니다.

* 로그인 중입니다
* 경로를 승인 또는 승인 해제하는 중입니다
* 승인된 경로 업데이트 중
* 글로벌 정책 또는 임계값 설정
* 데이터 소스 추가 또는 제거
* 데이터 소스 시작 또는 중지
* 데이터 소스 속성을 업데이트하는 중입니다
* 작업 추가, 편집 또는 삭제
* 응용 프로그램 그룹을 제거하는 중입니다
* 장치 ID 식별 또는 변경
* 사용자를 생성합니다
* 사용자를 삭제합니다
* 사용자 역할 변경
* 사용자 수정(Guest à Admin)
* 사용자 로그아웃(강제 로그아웃 또는 수동 로그아웃)
* 획득 장치 삭제
* 라이센스 업데이트
* 백업 설정 중
* 백업을 사용하지 않도록 설정합니다
* ASUP 활성화(동일한 페이지에서 프록시 활성화 가 감사 로그에 보고됨)
* ASUP 비활성화(동일한 페이지에서 프록시 비활성화가 감사 로그에 보고됨)
* 보안 - 키를 다시 누르고 시스템 암호를 변경합니다.
* 자산의 주석 제거/추가
* CAC 사용자 로그온/로그오프
* CAC 사용자 세션 시간 초과




== 단계

. 브라우저에서 Insight를 엽니다.
. Admin * 을 클릭하고 * Audit * 을 선택합니다.
+
감사 페이지에는 표에 감사 항목이 표시됩니다.

. 테이블에서 다음 세부 정보를 볼 수 있습니다.
+
** 시간 *
+
변경 날짜 및 시간입니다

** * 사용자 *
+
감사 항목과 연결된 사용자의 이름입니다

** * 역할 *
+
게스트, 사용자 또는 관리자인 사용자 계정의 역할

** * IP *
+
감사 항목과 연결된 IP 주소입니다

** * 작업 *
+
감사 항목의 작업 유형입니다

** * 세부 정보 *
+
감사 항목의 세부 정보입니다

+
데이터 소스 또는 애플리케이션과 같이 리소스에 영향을 미치는 사용자 활동이 있는 경우 세부 정보에는 리소스의 랜딩 페이지에 대한 링크가 포함됩니다.

+
[NOTE]
====
데이터 소스가 삭제되면 데이터 소스와 관련된 사용자 활동 세부 정보에 더 이상 데이터 소스의 랜딩 페이지에 대한 링크가 포함되지 않습니다.

====


. 특정 기간(1시간, 3시간, 24시간, 3일, 7일)을 선택하여 감사 항목을 표시할 수 있습니다. Insight에서 선택한 기간 동안 최대 1000건의 위반 사례를 보여줍니다.
+
한 페이지에 맞는 것보다 많은 데이터가 있는 경우 표 아래의 페이지 번호를 클릭하여 페이지별로 데이터를 탐색할 수 있습니다.

. 테이블의 열 정렬 순서를 열 머리글의 화살표를 클릭하여 오름차순(위쪽 화살표) 또는 내림차순(아래쪽 화살표)으로 변경하고 기본 정렬 순서로 돌아가려면 다른 열 머리글을 클릭합니다.
+
기본적으로 테이블에는 항목이 내림차순으로 표시됩니다.

. 필터 * 상자를 사용하여 표에 원하는 항목만 표시할 수 있습니다.
+
사용자가 감사 항목만 표시합니다 `izzyk`를 입력합니다 `izzyk` 필터 * 상자에 입력합니다.


