---
permalink: config-admin/brocade-sphereon-intrepid-switch-snmp-data-source.html 
sidebar: sidebar 
keywords:  
summary: 'OnCommand Insight는 Brocade Sphereon/Intrepid Switch\(SNMP\) 데이터 소스를 사용하여 Brocade Sphereon 또는 Intrepid 스위치의 인벤토리를 검색합니다.' 
---
= Brocade Sphereon/Intrepid 스위치 데이터 소스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight는 Brocade Sphereon/Intrepid 스위치(SNMP) 데이터 소스를 사용하여 Brocade Sphereon 또는 Intrepid 스위치의 인벤토리를 검색합니다.



== 요구 사항

[NOTE]
====
이 데이터 수집기는 OnCommand Insight 7.3.11부터 사용할 수 없습니다.

====
* Fabric의 모든 스위치에 대한 IP 연결이 있어야 합니다. Fabric에서 모든 스위치 검색 확인란을 선택하면 OCI가 Fabric의 모든 스위치를 식별하지만, 추가 스위치를 검색하려면 해당 스위치에 대한 IP 연결이 필요합니다.
* SNMP V1 또는 SNMP V2를 사용하는 경우 읽기 전용 커뮤니티 문자열입니다.
* 조닝 정보를 얻기 위해 스위치에 대한 HTTP 액세스.
* 를 실행하여 액세스 검증을 수행합니다 `snmpwalk` 스위치에 대한 유틸리티( 참조 `<install_path\>\bin\)`.




== 구성

|===


| * 필드 * | * 설명 * 


 a| 
Sphereon 스위치
 a| 
스위치의 IP 주소 또는 정규화된 도메인 이름입니다



 a| 
SNMP 버전
 a| 
SNMP 버전입니다



 a| 
SNMP 커뮤니티
 a| 
스위치에 액세스하는 데 사용되는 SNMP 읽기 전용 커뮤니티 문자열입니다



 a| 
사용자 이름
 a| 
스위치에 대한 SMI-S 사용자 이름(SNMP v3만 해당)



 a| 
암호
 a| 
스위치에 대한 SMI-S 암호(SNMP v3만 해당)

|===


== 고급 구성

|===


| * 필드 * | * 설명 * 


 a| 
재고 폴링 간격(분)
 a| 
재고 조사 간격(기본값 15분)



 a| 
SNMP 인증 프로토콜
 a| 
SNMP 인증 프로토콜(SNMPv3만 해당)



 a| 
SNMP 개인 정보 보호 프로토콜
 a| 
SNMP 개인 정보 보호 프로토콜(SNMPv3만 해당)



 a| 
SNMP 개인 정보 보호 암호
 a| 
SNMP 개인 정보 보호 암호입니다



 a| 
SNMP 재시도 횟수
 a| 
SNMP 재시도 횟수입니다



 a| 
SNMP 시간 초과(ms)
 a| 
SNMP 시간 초과(기본값 5,000ms)



 a| 
패브릭 이름
 a| 
데이터 소스에서 보고할 Fabric 이름입니다. 패브릭 이름을 WWN으로 보고하려면 공백으로 두십시오.



 a| 
트래핑을 활성화합니다
 a| 
장치에서 SNMP 트랩을 수신할 때 획득을 활성화하려면 선택합니다. 트래핑 활성화를 선택한 경우 SNMP도 활성화해야 합니다.



 a| 
Ttrap(Ttrap) 사이의 최소 시간(초)
 a| 
트랩에 의해 트리거된 획득 시도 사이의 최소 시간(기본값 10초)



 a| 
성능 폴링 간격(초)
 a| 
성능 폴링 간격(기본값 300초)

|===