---
permalink: config-admin/brocade-fc-switch-firmware-ssh-data-source.html 
sidebar: sidebar 
keywords:  
summary: 'OnCommand Insight는 Brocade FC 스위치\(SSH\) 데이터 소스를 사용하여 계수 운영 체제\(FOS\) 펌웨어 4.2 이상을 실행하는 Brocade 또는 재브랜드 스위치 디바이스의 인벤토리를 검색합니다. FC 스위치와 액세스 게이트웨이 모드의 디바이스가 모두 지원됩니다.' 
---
= Brocade FC 스위치 데이터 소스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight는 Brocade FC 스위치(SSH) 데이터 소스를 사용하여 계수 운영 체제(FOS) 펌웨어 4.2 이상을 실행하는 Brocade 또는 재브랜딩 스위치 디바이스의 인벤토리를 검색합니다. FC 스위치와 액세스 게이트웨이 모드의 디바이스가 모두 지원됩니다.



== 용어

OnCommand Insight는 Brocade FC 스위치 데이터 소스에서 다음 인벤토리 정보를 가져옵니다. Insight에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 소스를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

|===


| 공급업체/모델 기간 | Insight 용어입니다 


 a| 
스위치
 a| 
스위치



 a| 
포트
 a| 
포트



 a| 
가상 패브릭, 물리적 패브릭
 a| 
패브릭



 a| 
Zone(영역)
 a| 
Zone(영역)



 a| 
논리 스위치
 a| 
논리 스위치



 a| 
LSAN 구역
 a| 
IVR 영역

|===
[NOTE]
====
이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 소스의 모든 경우를 나타내는 것은 아닙니다.

====


== 요구 사항

* 획득 장치(로컬 또는 원격)는 Brocade 스위치의 TCP 포트 22에 대한 연결을 시작하여 인벤토리 데이터를 수집합니다. 또한 AU는 성능 데이터 수집을 위해 UDP 포트 161에 대한 연결을 시작합니다.
* Fabric의 모든 스위치에 대한 IP 연결이 있어야 합니다. Fabric에서 모든 스위치 검색 확인란을 선택하면 OCI가 Fabric의 모든 스위치를 식별하지만, 추가 스위치를 검색하려면 해당 스위치에 대한 IP 연결이 필요합니다.
* Fabric의 모든 스위치에서 동일한 계정이 전 세계적으로 필요합니다. PuTTY(오픈 소스 터미널 에뮬레이터)를 사용하여 액세스를 확인할 수 있습니다.
* Perform 라이센스가 설치된 경우 SNMP 성능 폴링을 위해 Fabric의 모든 스위치에 대해 포트 161과 162가 열려 있어야 합니다.
* SNMP 읽기 전용 커뮤니티 문자열




== 구성

|===


| 필드에 입력합니다 | 설명 


 a| 
스위치 IP
 a| 
스위치의 IP 주소 또는 정규화된 도메인 이름입니다



 a| 
사용자 이름
 a| 
스위치의 사용자 이름입니다



 a| 
암호
 a| 
스위치에 사용되는 암호입니다



 a| 
SNMP 버전
 a| 
SNMP 버전입니다



 a| 
SNMP 커뮤니티 문자열
 a| 
스위치에 액세스하는 데 사용되는 SNMP 읽기 전용 커뮤니티 문자열입니다



 a| 
SNMP 사용자 이름입니다
 a| 
SNMP 버전 프로토콜 사용자 이름(SNMP v3에만 적용)



 a| 
SNMP 암호
 a| 
SNMP 버전 프로토콜 암호(SNMP v3에만 적용)

|===


== 고급 구성

|===


| 필드에 입력합니다 | 설명 


 a| 
패브릭 이름
 a| 
데이터 소스에서 보고할 Fabric 이름입니다. 패브릭 이름을 WWN으로 보고하려면 공백으로 두십시오.



 a| 
장치 제외
 a| 
폴링에서 제외할 장치 ID의 쉼표로 구분된 목록입니다



 a| 
재고 폴링 간격(분)
 a| 
재고 조사 간격(기본값 15분)



 a| 
시간 초과(초)
 a| 
연결 시간 초과(기본값 30초)



 a| 
배너 대기 제한 시간(초)
 a| 
SSH 배너 대기 시간 초과(기본값 5초)



 a| 
관리자 도메인이 활성화되었습니다
 a| 
관리자 도메인을 사용하는 경우 선택합니다



 a| 
MPR 데이터 검색
 a| 
다중 프로토콜 라우터(MPR)에서 라우팅 데이터를 가져오려면 선택합니다.



 a| 
트래핑을 활성화합니다
 a| 
장치에서 SNMP 트랩을 수신할 때 획득을 활성화하려면 선택합니다. 트래핑 활성화를 선택한 경우 SNMP도 활성화해야 합니다.



 a| 
트랩 사이의 최소 시간(초)
 a| 
트랩에 의해 트리거된 획득 시도 사이의 최소 시간(기본값 10초)



 a| 
패브릭의 모든 스위치를 살펴보십시오
 a| 
Fabric의 모든 스위치를 검색하려면 선택합니다



 a| 
HBA와 을 선택합니다 영역 별칭
 a| 
HBA 또는 영역 별칭을 사용할지 여부를 선택합니다



 a| 
성능 폴링 간격(초)
 a| 
성능 폴링 간격(기본값 300초)



 a| 
SNMP 인증 프로토콜
 a| 
SNMP 인증 프로토콜(SNMP v3만 해당)



 a| 
SNMP 개인 정보 보호 프로토콜
 a| 
SNMP 개인 정보 보호 프로토콜(SNMP v3만 해당)



 a| 
SNMP 개인 정보 보호 암호
 a| 
SNMP 개인 정보 보호 암호(SNMP v3만 해당)



 a| 
SNMP 재시도
 a| 
SNMP 재시도 횟수입니다



 a| 
SNMP 시간 초과(ms)
 a| 
SNMP 시간 초과(기본값 5,000ms)

|===