---
permalink: config-admin/brocade-efcm-9-5-to-9-7-data-sources.html 
sidebar: sidebar 
keywords:  
summary: 'OnCommand Insight는 Brocade Enterprise Fabric Connectivity Manager\(EFCM\) 데이터 소스를 사용하여 Brocade EFCM 스위치의 인벤토리를 검색합니다. Insight는 EFCM 버전 9.5, 9.6 및 9.7을 지원합니다.' 
---
= Brocade Enterprise Fabric Connectivity Manager 데이터 소스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight는 Brocade EFCM(Enterprise Fabric Connectivity Manager) 데이터 소스를 사용하여 Brocade EFCM 스위치의 인벤토리를 검색합니다. Insight는 EFCM 버전 9.5, 9.6 및 9.7을 지원합니다.



== 요구 사항

[NOTE]
====
이 데이터 수집기는 OnCommand Insight 7.3.11부터 사용할 수 없습니다.

====
* EFCM 서버의 네트워크 주소 또는 정규화된 도메인 이름입니다
* EFCM 버전은 9.5, 9.6 또는 9.7이어야 합니다
* EFCM 서버의 IP 주소입니다
* EFCM 서버에 대한 읽기 전용 사용자 이름 및 암호입니다
* 포트 51512를 통해 읽기 전용 사용자 이름과 암호를 사용하여 Insight 서버에서 텔넷을 통해 Connectrix 스위치에 대한 액세스를 검증했습니다




== 구성

|===


| * 필드 * | * 설명 * 


 a| 
EFC 서버
 a| 
EFC 서버의 IP 주소 또는 정규화된 도메인 이름입니다



 a| 
사용자 이름
 a| 
스위치의 사용자 이름입니다



 a| 
암호
 a| 
스위치에 사용되는 암호입니다

|===


== 고급 구성

|===


| * 필드 * | * 설명 * 


 a| 
재고 폴링 간격(분)
 a| 
재고 조사 간격(기본값 15분)



 a| 
패브릭 이름
 a| 
EFCM 데이터 소스에서 보고할 Fabric 이름입니다. 패브릭 이름을 WWN으로 보고하려면 공백으로 두십시오.



 a| 
통신 포트
 a| 
스위치와 통신하는 데 사용되는 포트입니다



 a| 
트래핑을 활성화합니다
 a| 
장치에서 SNMP 트랩을 수신할 때 획득을 활성화하려면 선택합니다. 트래핑 활성화를 선택한 경우 SNMP도 활성화해야 합니다.



 a| 
트랩 사이의 최소 시간(초)
 a| 
트랩에 의해 트리거된 획득 시도 사이의 최소 시간(기본값 15초)



 a| 
비활성 Zoneset
 a| 
활성 영역 세트에서 획득을 수행할 뿐만 아니라 획득을 수행할 비활성 Zoneset의 쉼표로 구분된 목록입니다



 a| 
사용할 NIC입니다
 a| 
SAN 디바이스에서 보고할 때 RAU에서 사용해야 하는 네트워크 인터페이스를 지정합니다



 a| 
장치 제외
 a| 
폴링에서 포함하거나 제외할 단위 이름의 쉼표로 구분된 목록입니다



 a| 
EFCM 스위치 별칭을 Insight 스위치 이름으로 사용합니다
 a| 
EFCM 스위치 별칭을 Insight 스위치 이름으로 사용하려면 선택합니다



 a| 
성능 폴링 간격(초)
 a| 
성능 폴링 간격(기본값 300초)

|===