---
permalink: config-admin/cdot-landing-page-terminology-storage.html 
sidebar: sidebar 
keywords:  
summary: NetApp clustered Data ONTAP 스토리지 자산 랜딩 페이지에서 오브젝트 또는 레퍼런스에 적용되는 용어입니다. 
---
= Clustered Data ONTAP 스토리지
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp clustered Data ONTAP 스토리지 자산 랜딩 페이지에서 오브젝트 또는 레퍼런스에 적용되는 용어입니다.



== Clustered Data ONTAP 스토리지 용어

다음 용어는 NetApp clustered Data ONTAP 스토리지 자산 랜딩 페이지에서 찾을 수 있는 오브젝트 또는 참조에 적용됩니다. 이러한 용어 중 다수는 다른 데이터 수집기에도 적용됩니다.

* 모델 -- 이 클러스터 내에서 고유한 개별 노드 모델 이름을 쉼표로 구분한 목록입니다. 클러스터의 모든 노드가 동일한 모델 유형인 경우 하나의 모델 이름만 표시됩니다.
* 공급업체 -- 새 데이터 원본을 구성하는 경우 동일한 공급업체 이름입니다.
* 일련 번호 -- 스토리지 일련 번호입니다. NetApp clustered Data ONTAP과 같은 클러스터 아키텍처 스토리지 시스템에서는 이 일련 번호가 개별 "스토리지 노드" 일련 번호보다 덜 유용할 수 있습니다.
* IP -- 일반적으로 데이터 소스에 구성된 IP 또는 호스트 이름이 됩니다.
* 마이크로코드 버전 -- 펌웨어.
* Raw Capacity - - 역할에 관계없이 시스템의 모든 물리적 디스크에 대한 기본 2개의 합계입니다.
* 지연 시간 -- 읽기 및 쓰기 모두에서 호스트에서 발생하는 워크로드를 나타냅니다. 이상적으로는 OCI가 이 가치를 직접 소싱하지만 이 아닌 경우가 많습니다. 이러한 업적을 제공하는 스토리지 대신, OCI는 일반적으로 개별 내부 볼륨 "" 통계에서 파생된 IOP 가중 계산을 수행합니다.
* Throughput - 내부 볼륨에서 집계된 것입니다.
* 관리 -- 장치의 관리 인터페이스에 대한 하이퍼링크가 포함될 수 있습니다. 인벤토리 보고의 일부로 Insight 데이터 소스에 의해 프로그래밍 방식으로 만들어집니다.

