---
permalink: config-admin/changing-oncommand-insight-internal-user-passwords.html 
sidebar: sidebar 
keywords:  
summary: '보안 정책에 따라 OnCommand Insight 환경의 암호를 변경해야 할 수 있습니다. 한 서버의 암호 중 일부는 환경의 다른 서버에 있으므로 두 서버의 암호를 변경해야 합니다. 예를 들어 Insight Server에서 "인벤토리" 사용자 암호를 변경하는 경우 해당 Insight Server에 대해 구성된 데이터 웨어하우스 서버 Connector의 "인벤토리" 사용자 암호와 일치해야 합니다.' 
---
= OnCommand Insight 내부 사용자 암호 변경
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
보안 정책에 따라 OnCommand Insight 환경의 암호를 변경해야 할 수 있습니다. 한 서버의 암호 중 일부는 환경의 다른 서버에 있으므로 두 서버의 암호를 변경해야 합니다. 예를 들어, Insight Server에서 ""인벤토리"" 사용자 암호를 변경할 경우 해당 Insight Server에 대해 구성된 데이터 웨어하우스 서버 Connector의 ""인벤토리"" 사용자 암호와 일치해야 합니다.



== 시작하기 전에

[NOTE]
====
암호를 변경하기 전에 사용자 계정의 종속성을 이해해야 합니다. 필요한 모든 서버에서 암호를 업데이트하지 못하면 Insight 구성 요소 간의 통신 장애가 발생합니다.

====


== 이 작업에 대해

다음 표에는 Insight Server의 내부 사용자 암호가 나열되어 있으며 새 암호와 일치해야 하는 종속 암호가 있는 Insight 구성 요소가 나열되어 있습니다.

|===


| Insight Server 암호 | 필수 변경 사항 


 a| 
_내부
 a| 



 a| 
획득
 a| 
Lau, RAU



 a| 
DWh _ 내부
 a| 
데이터 웨어하우스



 a| 
호스트
 a| 



 a| 
인벤토리
 a| 
데이터 웨어하우스



 a| 
루트
 a| 

|===
다음 표에는 데이터 웨어하우스에 대한 내부 사용자 암호가 나열되어 있으며 새 암호와 일치해야 하는 종속 암호가 있는 Insight 구성 요소가 나열되어 있습니다.

|===


| 데이터 웨어하우스 암호 | 필수 변경 사항 


 a| 
Cognos_admin
 a| 



 a| 
드Wh
 a| 



 a| 
dWh_INTERNAL(서버 커넥터 구성 UI를 사용하여 변경)
 a| 
Insight 서버



 a| 
Dwhuser(사용자)
 a| 



 a| 
호스트
 a| 



 a| 
인벤토리(서버 커넥터 구성 UI를 사용하여 변경됨)
 a| 
Insight 서버



 a| 
루트
 a| 

|===
* DWH 서버 연결 구성 UI * 에서 암호 변경

다음 표에는 Lau의 사용자 암호와 새 암호와 일치해야 하는 종속 암호가 있는 Insight 구성 요소가 나열되어 있습니다.

|===


| Lau 암호 | 필수 변경 사항 


 a| 
획득
 a| 
Insight 서버, RAU

|===