---
permalink: config-admin/cisco-fc-switch-firmware-snmp-data-source.html 
sidebar: sidebar 
keywords:  
summary: 'OnCommand Insight는 Cisco FC 스위치 펌웨어 2.0+\(SNMP\) 데이터 소스를 사용하여 Cisco MDS 파이버 채널 스위치에 대한 인벤토리 및 FC 서비스가 사용되는 다양한 Cisco Nexus FCoE 스위치를 검색합니다. 또한 이 데이터 소스를 통해 NPV 모드에서 실행되는 여러 Cisco 장치 모델을 발견할 수 있습니다.' 
---
= Cisco FC 스위치 펌웨어(SNMP) 데이터 소스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight는 Cisco FC 스위치 펌웨어 2.0+(SNMP) 데이터 소스를 사용하여 Cisco MDS 파이버 채널 스위치에 대한 인벤토리 및 FC 서비스가 사용되는 다양한 Cisco Nexus FCoE 스위치를 검색합니다. 또한 이 데이터 소스를 통해 NPV 모드에서 실행되는 여러 Cisco 장치 모델을 발견할 수 있습니다.



== 용어

OnCommand Insight는 Cisco FC 스위치 데이터 소스에서 다음 인벤토리 정보를 가져옵니다. Insight에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 소스를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

|===


| 공급업체/모델 기간 | Insight 용어입니다 


 a| 
스위치
 a| 
스위치



 a| 
포트
 a| 
포트



 a| 
vSAN을 선택합니다
 a| 
패브릭



 a| 
Zone(영역)
 a| 
Zone(영역)



 a| 
논리 스위치
 a| 
논리 스위치



 a| 
이름 서버 항목
 a| 
이름 서버 항목



 a| 
IVR(Inter-VSAN Routing) 존
 a| 
IVR 영역

|===
[NOTE]
====
이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 소스의 모든 경우를 나타내는 것은 아닙니다.

====


== 요구 사항

* 패브릭 또는 개별 스위치에 있는 스위치 중 하나의 IP 주소입니다
* 섀시 검색, 패브릭 검색 지원
* SNMP V2를 사용하는 경우 읽기 전용 커뮤니티 문자열입니다
* 포트 161은 장치에 액세스하는 데 사용됩니다
* 를 사용하여 유효성 검사에 액세스합니다 `snmpwalk` 스위치에 대한 유틸리티( 참조 `<install_path\>\bin\`)




== 구성

|===


| 필드에 입력합니다 | 설명 


 a| 
Cisco 스위치 IP
 a| 
스위치의 IP 주소 또는 정규화된 도메인 이름입니다



 a| 
SNMP 버전
 a| 
성능 획득을 위해서는 SNMP 버전 v2 이상이 필요합니다



 a| 
SNMP 커뮤니티 문자열
 a| 
스위치에 액세스하는 데 사용되는 SNMP 읽기 전용 커뮤니티 문자열(SNMP v3에는 적용되지 않음)



 a| 
사용자 이름
 a| 
스위치의 사용자 이름(SNMP v3만 해당)



 a| 
암호
 a| 
스위치에 사용된 암호(SNMPv3만 해당)

|===


== 고급 구성

|===


| 필드에 입력합니다 | 설명 


 a| 
재고 폴링 간격(분)
 a| 
재고 조사 간격(기본값 40분)



 a| 
SNMP 인증 프로토콜
 a| 
SNMP 인증 프로토콜(SNMPv3만 해당)



 a| 
SNMP 개인 정보 보호 프로토콜
 a| 
SNMP 개인 정보 보호 프로토콜(SNMPv3만 해당)



 a| 
SNMP 개인 정보 보호 암호
 a| 
SNMP 개인 정보 보호 암호입니다



 a| 
SNMP 재시도
 a| 
SNMP 재시도 횟수입니다



 a| 
SNMP 시간 초과(ms)
 a| 
SNMP 시간 초과(기본값 5,000ms)



 a| 
트래핑을 활성화합니다
 a| 
트래핑을 활성화하려면 선택합니다. 트래핑을 사용하는 경우 SNMP 알림도 활성화해야 합니다.



 a| 
트랩 사이의 최소 시간(초)
 a| 
트랩에 의해 트리거된 획득 시도 사이의 최소 시간(기본값 10초)



 a| 
모든 패브릭 스위치를 살펴보십시오
 a| 
Fabric의 모든 스위치를 검색하려면 선택합니다



 a| 
장치 제외
 a| 
폴링에서 제외할 장치 IP의 쉼표로 구분된 목록입니다



 a| 
장치 포함
 a| 
폴링에 포함할 장치 IP의 쉼표로 구분된 목록입니다



 a| 
장치 유형을 확인하십시오
 a| 
자신을 Cisco 장치로 명시적으로 광고하는 장치만 수락하려면 선택합니다



 a| 
기본 별칭 유형
 a| 
별칭 해상도에 대한 첫 번째 기본 설정을 제공합니다. 다음 중에서 선택합니다.

* * 장치 별칭 *
+
이 이름은 필요에 따라 모든 구성 명령에 사용할 수 있는 포트 WWN(pwwn)에 대한 사용자 친화적인 이름입니다. Cisco MDS 9000 제품군의 모든 스위치는 분산 장치 별칭(장치 별칭)을 지원합니다.

* * 없음 *
+
별칭을 보고하지 않습니다

* * 포트 설명 *
+
포트 목록에서 포트를 식별하는 데 도움이 되는 설명입니다

* * 영역 별칭(모두) *
+
조닝 구성에만 사용할 수 있는 포트에 대한 알기 쉬운 이름입니다

* * 영역 별칭(활성 전용) *
+
활성 구성에만 사용할 수 있는 포트에 대한 사용자 친화적인 이름입니다. 이것이 기본값입니다.





 a| 
보조 별칭 유형
 a| 
별칭 해상도에 대한 두 번째 기본 설정을 제공합니다



 a| 
제3 별칭 유형
 a| 
별칭 해상도에 대한 세 번째 기본 설정을 제공합니다



 a| 
SANTap 프록시 모드 지원을 설정합니다
 a| 
Cisco 스위치가 프록시 모드에서 SANTap을 사용하고 있는지 여부를 선택합니다. EMC RecoverPoint를 사용하는 경우 SANTap을 사용할 수 있습니다.



 a| 
성능 폴링 간격(초)
 a| 
성능 폴링 간격(기본값 300초)

|===