---
sidebar: sidebar 
permalink: collector_hds_ops_center.html 
keywords: data collector, Hitachi Ops Center 
summary: HDS Ops Center 데이터 수집기 구성 
---
= Hitachi Ops Center 데이터 수집기
:allow-uri-read: 


[role="lead"]
이 데이터 수집기는 Hitachi Ops Center의 통합 애플리케이션 제품군을 사용하여 여러 스토리지 디바이스의 인벤토리 및 성능 데이터에 액세스합니다. 인벤토리 및 용량 검색을 위해 Ops Center 설치에는 "공통 서비스" 및 "관리자" 구성 요소가 모두 포함되어야 합니다. 성능 수집을 위해 "Analyzer"를 추가로 구축해야 합니다.



== 용어

OnCommand Insight는 이 데이터 수집기에서 다음 인벤토리 정보를 가져옵니다. 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 수집기를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

[cols="2*"]
|===
| 공급업체/모델 기간 | OnCommand Insight 용어입니다 


| 스토리지 시스템 | 스토리지 


| 볼륨 | 볼륨 


| 패리티 그룹 | 스토리지 풀(RAID), 디스크 그룹 


| 디스크 | 디스크 


| 스토리지 풀 | 스토리지 풀(씬, 스냅) 


| 외부 패리티 그룹 | 스토리지 풀(백엔드), 디스크 그룹 


| 포트 | 스토리지 노드 → 컨트롤러 노드 → 포트 


| 호스트 그룹 | 볼륨 매핑 및 마스킹 


| 볼륨 쌍 | 저장소 동기화 
|===
참고: 이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 수집기의 모든 경우를 나타내는 것은 아닙니다.



== 재고 요건

재고 데이터를 수집하려면 다음이 있어야 합니다.

* "공통 서비스" 구성 요소를 호스팅하는 Ops Center 서버의 IP 주소 또는 호스트 이름입니다
* Ops Center 구성 요소를 호스팅하는 모든 서버에 있는 루트/sysadmin 사용자 계정 및 암호입니다. HDS는 Ops Center 10.8 이상이 될 때까지 LDAP/SSO 사용자의 REST API 지원을 구현하지 않았습니다




== 성능 요구사항

성능 데이터를 수집하려면 다음 요구사항을 충족해야 합니다.

* HDS Ops Center "Analyzer" 모듈을 설치해야 합니다
* 스토리지 어레이가 운영 센터 "Analyzer" 모듈에 제공되어야 합니다




== 구성

[cols="2*"]
|===
| 필드에 입력합니다 | 설명 


| Hitachi Ops Center IP 주소입니다 | "공통 서비스" 구성 요소를 호스팅하는 Ops Center 서버의 IP 주소 또는 정규화된 도메인 이름입니다 


| 사용자 이름 | Ops Center 서버의 사용자 이름입니다. 


| 암호 | Ops Center 서버에 사용되는 암호입니다. 
|===


== 고급 구성

|===


| 필드에 입력합니다 | 설명 


| 연결 유형 | 기본값은 HTTPS(포트 443)입니다 


| TCP 포트를 재정의합니다 | 기본값이 아닌 경우 사용할 포트를 지정합니다 


| 재고 폴링 간격(분) | 재고 조사 사이의 간격입니다. 기본값은 40입니다. 


| 목록을 지정하려면 '제외' 또는 '포함'을 선택하십시오 | 데이터를 수집할 때 아래 어레이 목록을 포함할지 제외할지 여부를 지정합니다. 


| 장치 목록을 필터링합니다 | 포함하거나 제외할 장치 일련 번호의 쉼표로 구분된 목록입니다 


| 성능 폴링 간격(초) | 성능 폴링 간격입니다. 기본값은 300입니다. 
|===
추가 정보는 에서 찾을 수 있습니다 link:concept_requesting_support.html["지원"] 페이지 또는 에 있습니다 link:https://docs.netapp.com/us-en/cloudinsights/CloudInsightsDataCollectorSupportMatrix.pdf["Data Collector 지원 매트릭스"].
