---
permalink: config-admin/configuring-sso.html 
sidebar: sidebar 
keywords:  
summary: 'SSO(Single Sign-On)를 사용하면 조직의 사용자가 특수 계정 없이도 OnCommand Insight를 사용할 수 있습니다.' 
---
= SSO(Single Sign-On) 구성
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SSO(Single Sign-On)를 사용하면 조직의 사용자가 특수 계정 없이도 OnCommand Insight를 사용할 수 있습니다.

관리자는 회사 도메인의 사용자에 대한 * SSO(Single Sign-On) * 액세스용으로 OnCommand Insight 서버를 구성할 수 있습니다. SSO를 구성하면 도메인 이메일 주소를 가진 모든 사용자가 회사 자격 증명을 사용하여 Insight에 로그인할 수 있습니다. OnCommand Insight는 SSO에 대한 OIDC(OpenID Connect) 프로토콜을 지원합니다.

[NOTE]
====
SSO는 Insight Server 웹 기반 UI에서만 사용할 수 있습니다. SSO는 데이터 웨어하우스, 보고 또는 Java 클라이언트 UI 구성 요소에 사용할 수 없습니다.

OnCommand Insights는 * Azure Active Directory * 에서만 SSO를 지원합니다.

====


== SSO 구성 단계

* 메뉴로 이동: Admin [Settings > Users]
* SSO 구성 URL을 입력하여 구성 필드를 자동으로 채웁니다("OpenID-configuration"이라고도 함). ID 공급자의 구성을 설명하는 JSON을 제공하는 URI입니다.
* 또는 다음 ID 공급자 리소스에 대해 SSO 구성 URL을 수동으로 입력합니다. 이러한 리소스에 대한 자세한 내용은 이 페이지 하단의 관련 정보 섹션에서 확인할 수 있습니다.
+
** * 인증 끝점 *: 사용자에게 자격 증명을 묻는 ID 공급자 리소스입니다. ID가 성공적으로 완료되면 OnCommand Insight에 사용자 대신 작업을 수행할 수 있는 권한 부여 권한이 발급됩니다.
** * JWK Set URI *: JWT 토큰에 서명하는 데 사용되는 공개 키를 제공합니다. 이를 통해 클라이언트는 JWT 토큰이 실제로 제삼자가 아닌 ID 공급자에 의해 발급되었는지 확인할 수 있습니다.
** * 토큰 엔드포인트 *: 클라이언트가 JWT 토큰에 대한 승인 부여를 처리하는 ID 공급자 리소스입니다. 클라이언트는 클라이언트 ID와 클라이언트 암호도 제공해야 합니다(아래 참조). Insight에서 사용하는 JWT 토큰은 사용자의 사용자 이름과 역할을 나타내는 "ID 토큰"입니다.
** * End Session Endpoint * : ID 공급자가 제공하는 클라이언트(OCI)로 인해 브라우저가 리디렉션되고 ID 공급자가 ID 공급자와의 사용자 세션을 무효화합니다. 즉, 다음 번 로그인 시 사용자가 자격 증명을 입력해야 합니다.


* * 클라이언트 ID *: 클라이언트(OCI)를 고유하게 식별하고 ID 공급자가 알고 있는 다른 클라이언트와 구분합니다. ID 공급자는 응용 프로그램을 만들 때 클라이언트 ID를 생성하고 클라이언트는 토큰 요청의 일부로 클라이언트 ID를 제공해야 합니다.
* * Client Secret *: ID 공급자에 클라이언트를 인증하는 ID 공급자와 클라이언트에만 알려진 임의의 문자열로, 클라이언트가 이 클라이언트가 주장하는 응용 프로그램이며 악의적인 타사가 아닌 것으로 증명합니다. 클라이언트 ID와 함께 클라이언트 암호는 토큰 요청의 일부로 ID 공급자에 전달됩니다. 클라이언트 암호는 ID 공급자에 의해 생성됩니다. Azure Active Directory를 사용하면 여러 클라이언트 암호를 사용할 수 있습니다.
* * 사용자 이름 * 에 대한 JWT 클레임: 사용자의 사용자 이름을 식별하는 ID JWT 토큰의 클레임입니다. 청구는 JWT 토큰의 JSON 페이로드에서 키 값 쌍입니다. 구성된 "사용자 이름에 대한 JTW 클레임"은 키의 이름이며, 각 ID 토큰에 대한 값은 인증 중인 사용자의 사용자 이름입니다. 키 이름은 ID 공급자마다 다를 수 있습니다. Azure Active Directory의 경우 일반적으로 클레임 이름은 "preferred_username"입니다.
* * JWT는 역할에 대한 요구 *: 위와 같이 이 클레임의 값이 OCI 역할 목록(예: "guest", "user", "admin")임을 제외하고 위와 같습니다. Azure Active Directory의 경우 이 키의 이름은 "역할"입니다.




== SSL 인증서를 관리합니다

ID 공급자의 SSL 인증서 체인의 루트 인증서를 가져와야 합니다. 이렇게 하려면 토큰 끝점의 호스트 이름과 연결된 루트 인증서를 다운로드합니다. (Azure Active Directory의 경우 login.microsoftonline.com) 파일에 저장합니다. 그런 다음 "인증서" 버튼을 클릭하고 "수동" 탭을 사용하여 파일을 선택하고 "so-root"와 같은 별칭을 사용하여 파일을 가져옵니다.

SSO가 이미 활성화되어 있고 새 인증서를 가져온 경우 SANscreen 서비스를 다시 시작해야 합니다.



== 운영 체제에서 SSO 활성화

현재 시스템에서 SSO를 활성화하고 업그레이드를 통해 ssoAuth 시스템 속성을 보존하려면 다음을 수행해야 합니다.

Windows에서 SSO를 활성화하려면 레지스트리에서 _HKEY_LOCAL_MACHINE\SOFTWARE\NetApp\SANscreen_으로 이동합니다. ssoAuth 값을 false 에서 true 로 변경합니다. 이 값은 업그레이드 중에 읽으며 업그레이드된 시스템에 대한 ssoAuth 시스템 속성을 설정하는 데 사용됩니다. 현재 인스턴스에는 영향을 미치지 않습니다. ssoAuth도 _HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Apache Software Foundation\Procrun 2.0\SANscreen Server\Parameters\Java Options_에서 업데이트해야 합니다.

Linux에서 SSO를 활성화하려면 _/opt/netapp/OCI/conf/_로 이동하여 _wildfly.properties_ 파일을 엽니다. sso_AUTH_ENABLED_의 값을 false 에서 true 로 변경합니다.

SSO를 활성화한 후 SANscreen 서비스를 다시 시작합니다.



== SSO 문제 해결

"승인되지 않음" 오류가 발생하면 server.log 에서 자세한 내용을 확인하십시오. Insight에서 인증에 실패했지만 ID 공급자가 사용자를 올바르게 인증한 경우 이 오류가 발생할 수 있습니다.

사용자가 SSO로 로그인할 수 없는 경우 관리자 권한으로 비 SSO 사용자로 로그인하고 SSO 구성을 수정하십시오. 브라우저 창에 __<Your Insight URL>**/uiserver/login.html#**__을 입력하여 이 작업을 수행할 수 있습니다.

* 관련 정보 *

https://ldapwiki.com/wiki/Openid-configuration[]

https://ldapwiki.com/wiki/Authorization_endpoint[]

https://ldapwiki.com/wiki/JWK%20Set[]

https://ldapwiki.com/wiki/Token_endpoint[]

https://ldapwiki.com/wiki/End_session_endpoint[]

https://ldapwiki.com/wiki/Client_id[]

https://ldapwiki.com/wiki/Client%20Secret[]

https://ldapwiki.com/wiki/Identity%20Token[]
