---
permalink: config-admin/configuring-the-number-of-hours-to-ignore-dynamic-data.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight에서 사용된 용량과 같은 동적 데이터 업데이트를 무시하는 시간을 구성할 수 있습니다. 기본 6시간이 사용되고 구성이 변경되지 않으면 기본 시간 이후까지 보고서가 동적 데이터로 업데이트되지 않습니다. 이 옵션은 동적 데이터만 변경될 때 업데이트를 지연하므로 성능이 향상됩니다. 
---
= 동적 데이터를 무시할 시간 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight에서 사용된 용량과 같은 동적 데이터 업데이트를 무시하는 시간을 구성할 수 있습니다. 기본 6시간이 사용되고 구성이 변경되지 않으면 기본 시간 이후까지 보고서가 동적 데이터로 업데이트되지 않습니다. 이 옵션은 동적 데이터만 변경될 때 업데이트를 지연하므로 성능이 향상됩니다.



== 이 작업에 대해

이 옵션에 값이 설정되어 있으면 OnCommand Insight는 다음 규칙에 따라 동적 데이터를 업데이트합니다.

* 구성을 변경하지 않고 용량 데이터가 변경되면 데이터가 업데이트되지 않습니다.
* 구성 변경 이외의 동적 데이터는 이 옵션에 지정된 시간 제한 이후에만 업데이트됩니다.
* 구성이 변경되면 구성 및 동적 데이터가 업데이트됩니다.


이 옵션의 영향을 받는 동적 데이터에는 다음이 포함됩니다.

* 용량 위반 데이터
* 파일 시스템에 할당된 용량 및 사용된 용량
* 하이퍼바이저
+
** 가상 디스크 사용된 용량
** 가상 머신 사용 용량


* 내부 볼륨
+
** 데이터 할당 용량
** 사용된 데이터 용량
** 중복제거 절약
** 마지막으로 알려진 액세스 시간입니다
** 마지막 스냅샷 시간입니다
** 기타 사용된 용량
** 스냅샷 수
** 사용된 스냅샷 용량
** 사용된 총 용량입니다


* iSCSI 세션 초기자 IP, 대상 세션 ID 및 초기자 세션 ID
* 사용된 용량 qtree 할당량
* 사용된 할당량 파일 및 사용된 용량
* 스토리지 효율성 기술, 이득/손실 및 잠재적 이득/손실
* 스토리지 풀
+
** 사용된 데이터 용량
** 중복제거 절약
** 기타 사용된 용량
** 사용된 스냅샷 용량
** 사용된 총 용량입니다


* 볼륨
+
** 중복제거 절약
** 마지막으로 알려진 액세스 시간입니다
** 사용된 용량






== 단계

. Insight 도구 모음에서 * Admin * 을 클릭하고 * Troubleshooting * 을 선택합니다.
. 다른 작업 영역의 페이지 하단에서 * 고급 문제 해결 * 링크를 클릭합니다.
. 고급 설정 * 탭을 클릭하고 획득 동적 속성 섹션에서 OnCommand Insight가 획득 동적 속성의 동적 데이터를 무시해야 하는 시간을 입력합니다.
. 저장 * 을 클릭합니다.
. (선택 사항) 획득 장치를 다시 시작하려면 * Restart Acquisition Unit(획득 장치 재시작) * 링크를 클릭합니다.
+
로컬 획득 장치를 다시 명시하면 모든 OnCommand Insight 데이터 소스 뷰가 다시 로드됩니다. 이 변경 사항은 다음 폴링 중에 적용되므로 획득 장치를 다시 시작할 필요가 없습니다.


