---
permalink: config-admin/creating-an-application-performance-policy.html 
sidebar: sidebar 
keywords: anomaly score 
summary: 응용 프로그램의 이상 점수를 기반으로 응용 프로그램 성능 정책을 만들 수 있습니다. 임계값을 넘어지면 응용 프로그램의 리소스와 관련된 문제를 알리는 알림이 트리거됩니다. 
---
= 애플리케이션 성능 정책 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
응용 프로그램의 이상 점수를 기반으로 응용 프로그램 성능 정책을 만들 수 있습니다. 임계값을 넘어지면 응용 프로그램의 리소스와 관련된 문제를 알리는 알림이 트리거됩니다.



== 시작하기 전에

애플리케이션 성능 정책에 설정된 임계값을 모니터링하려면 이상 현상 감지 엔진이 Insight 서버에서 실행 중이어야 합니다.



== 이 작업에 대해

모니터링할 다양한 유형의 이상 징후 점수에 대한 알림을 제공하는 정책을 만들 수 있습니다.

* 이상 급증 현상을 식별하려면 임계값을 높은 이상 징후 점수(>90)로 설정하여 첫 번째 발생에 대한 알림을 제공하는 정책을 생성합니다.
* 시간에 따른 동작 변화를 식별하려면 중간 이상 징후 점수에 대해 1시간 후 알림을 보내는 정책을 만듭니다. 이 정책은 3개의 연속 이상 징후 탐지 점수를 기반으로 알림을 제공합니다.




== 단계

. 브라우저에서 OnCommand Insight를 엽니다.
. 관리 * > * 성능 정책 * 을 클릭합니다
+
성능 정책 페이지가 표시됩니다.

. 추가 * 를 클릭합니다.
+
정책 추가 대화 상자가 표시됩니다.

. 정책 이름 * 필드에 고유한 정책 이름을 입력합니다.
+
개체의 다른 모든 정책 이름과 다른 이름을 사용해야 합니다.

. [유형의 개체에 적용] 목록에서 [응용 프로그램]을 선택합니다.
. 응용 프로그램 우선 순위 * 목록에서 응용 프로그램 우선 순위를 선택합니다.
. [다음 창 뒤에 적용]목록에서 임계값 위반을 나타내기 위해 경고를 표시할 시기를 선택합니다.
+
첫 번째 발생 옵션은 첫 번째 점수에서 임계값이 초과될 때 알림을 트리거합니다. 다른 모든 옵션은 임계값을 한 번 넘어섰을 때 경고를 발생시키고 지정된 시간 이상 연속적으로 교차하는 경우에 발생합니다.

+
이상 징후 점수는 30분 간격(시 5분, 시 35분)으로 제공되므로 30으로 나누어지는 기간만 선택해야 합니다.

+
|===


| 창 뒤에 적용합니다 | 위반을 throw하는 데 필요한 버킷 수입니다 


 a| 
첫 번째 발생
 a| 
1



 a| 
5분
 a| 
2



 a| 
10분
 a| 
2



 a| 
15분
 a| 
2



 a| 
30분
 a| 
2



 a| 
45분
 a| 
3



 a| 
1시간
 a| 
3



 a| 
2시간
 a| 
4

|===
. Warning * 목록에서 Critical 또는 Warning을 선택합니다
. 기본 이메일 알림 방법을 변경하려면 이메일을 구성합니다.
. Create alert if * 섹션에서 연산자를 선택한 다음 임계값을 생성할 값을 입력합니다. 이상 징후 점수는 애플리케이션 성능 정책에 사용되는 유일한 성능 카운터입니다.
+
다음과 유사한 범위를 사용하여 알림 집합을 만들 수 있습니다.

+
** 0-20 경고
** 21-50경고 경보
** 51-80 경고 알림
** > 80 긴급 경보


. 경고 발생 시 정책 처리를 중지하려면 * 알림이 생성되면 추가 정책 처리 중지 * 확인란을 선택합니다.




== 결과

알림은 위반을 볼 수 있는 유일한 수단이 아닙니다. 위반은 응용 프로그램 랜딩 페이지 및 위반 대시보드에 표시되며 여기에서 필터링할 수 있습니다. 또한 대시보드를 생성하고 위반 테이블 위젯을 추가하고 성능 정책 이름을 필터링하여 애플리케이션 위반을 확인할 수도 있습니다.
