---
permalink: config-admin/defining-applications.html 
sidebar: sidebar 
keywords:  
summary: 사용자 환경에서 실행 중인 특정 애플리케이션과 관련된 데이터를 추적하려면 해당 애플리케이션을 정의해야 합니다. 
---
= 응용 프로그램 정의
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
사용자 환경에서 실행 중인 특정 애플리케이션과 관련된 데이터를 추적하려면 해당 애플리케이션을 정의해야 합니다.



== 시작하기 전에

애플리케이션을 업무 엔티티에 연결하려면 이미 업무 엔티티를 생성해야 합니다.



== 이 작업에 대해

호스트, 가상 머신, 볼륨, 내부 볼륨, qtree, 공유 및 하이퍼바이저.



== 단계

. OnCommand Insight 웹 UI에 로그인합니다.
. 관리 * 를 클릭하고 * 응용 프로그램 * 을 선택합니다.
+
응용 프로그램을 정의한 후 응용 프로그램 페이지에는 응용 프로그램의 이름, 우선 순위 및 응용 프로그램과 연결된 업무 엔티티가 표시됩니다(해당하는 경우).

+
[NOTE]
====
이상 탐지 엔진이 설치된 경우 응용 프로그램 대시보드 페이지에 해당 응용 프로그램의 이상 점수 도 표시됩니다. 이상 현상 감지 엔진 설치 및 구성에 대한 자세한 내용은 _OnCommand Insight 구성 및 관리 가이드_를 참조하십시오.

====
. 추가 * 를 클릭합니다.
+
응용 프로그램 추가 대화 상자가 표시됩니다.

. 이름 * 상자에 응용 프로그램의 고유한 이름을 입력합니다.
. Priority * 를 클릭하고 해당 환경의 애플리케이션에 대한 우선 순위(중요, 높음, 중간 또는 낮음)를 선택합니다.
. 이 응용 프로그램을 업무 엔티티와 함께 사용하려면 * 업무 엔티티 * 를 클릭하고 목록에서 엔티티를 선택합니다.
. * 선택 사항 *: 볼륨 공유를 사용하지 않는 경우 * 볼륨 공유 확인 * 상자를 클릭하여 지웁니다.
+
이 작업을 수행하려면 보증 라이센스가 필요합니다. 각 호스트가 클러스터의 동일한 볼륨에 액세스할 수 있도록 하려면 이 옵션을 설정합니다. 예를 들어, high-availability 클러스터의 호스트는 장애 조치를 위해 동일한 볼륨에 마스킹되어야 하는 경우가 많지만, 관련 없는 애플리케이션의 호스트는 일반적으로 동일한 물리적 볼륨에 액세스할 필요가 없습니다. 또한 규정 정책에 따라 보안상의 이유로 관련 없는 응용 프로그램이 동일한 물리적 볼륨에 액세스하는 것을 명시적으로 허용하지 않을 수 있습니다.

. 저장 * 을 클릭합니다.
+
응용 프로그램이 응용 프로그램 페이지에 나타납니다. 애플리케이션 이름을 클릭하면 Insight에서 애플리케이션의 자산 페이지를 표시합니다.





== 작업을 마친 후

애플리케이션을 정의한 후 호스트, 가상 머신, 볼륨, 내부 볼륨 또는 하이퍼바이저의 자산 페이지로 이동하여 애플리케이션을 자산에 할당할 수 있습니다.
