---
permalink: config-admin/dell-emc-ecs-data-source.html 
sidebar: sidebar 
keywords:  
summary: 이 데이터 수집기는 EMC ECS 스토리지 시스템에서 인벤토리 및 성능 데이터를 가져옵니다. 구성을 위해 데이터 수집기는 ECS 서버의 IP 주소와 관리 수준 도메인 계정이 필요합니다. 
---
= Dell EMC ECS 데이터 소스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 데이터 수집기는 EMC ECS 스토리지 시스템에서 인벤토리 및 성능 데이터를 가져옵니다. 구성을 위해 데이터 수집기는 ECS 서버의 IP 주소와 관리 수준 도메인 계정이 필요합니다.



== 용어

OnCommand Insight는 EMC ECS 데이터 소스에서 다음과 같은 인벤토리 정보를 가져옵니다. Insight에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 소스를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

|===


| 공급업체/모델 기간 | Insight 용어입니다 


 a| 
Cluser(사용자)
 a| 
스토리지



 a| 
테넌트
 a| 
스토리지 풀



 a| 
버킷
 a| 
내부 볼륨



 a| 
디스크
 a| 
디스크

|===
[NOTE]
====
이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 소스의 모든 경우를 나타내는 것은 아닙니다.

====


== 요구 사항

* ECS Management Console의 IP 주소입니다
* ECS 시스템의 관리 수준 도메인 계정입니다
* 포트 443(HTTPS). ECS 시스템에서 TCP 포트 443에 대한 아웃바운드 연결이 필요합니다.
* 성능을 위해 ssh/scp 액세스를 위한 읽기 전용 사용자 이름과 암호를 사용합니다.
* 성능을 위해서는 포트 22가 필요합니다.




== 구성

|===


| 필드에 입력합니다 | 설명 


 a| 
ECS 호스트
 a| 
ECS 시스템의 IP 주소 또는 정규화된 도메인 이름입니다



 a| 
ECS 호스트 포트
 a| 
ECS 호스트와 통신하는 데 사용되는 포트입니다



 a| 
ECS 공급업체 ID입니다
 a| 
ECS의 공급업체 ID입니다



 a| 
암호
 a| 
ECS에 사용되는 암호입니다

|===


== 고급 구성

|===


| 필드에 입력합니다 | 설명 


 a| 
재고 폴링 간격(분)
 a| 
재고 조사 사이의 간격입니다. 기본값은 360분입니다.

|===