---
permalink: config-admin/dell-emc-powerstore-data-source.html 
sidebar: sidebar 
keywords:  
summary: Dell EMC PowerStore 데이터 수집기는 Dell EMC PowerStore 스토리지에서 인벤토리 정보를 수집합니다. 구성을 위해 데이터 수집기는 스토리지 프로세서의 IP 주소와 읽기 전용 사용자 이름 및 암호를 필요로 합니다. 
---
= Dell EMC PowerStore 데이터 소스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Dell EMC PowerStore 데이터 수집기는 Dell EMC PowerStore 스토리지에서 인벤토리 정보를 수집합니다. 구성을 위해 데이터 수집기는 스토리지 프로세서의 IP 주소와 읽기 전용 사용자 이름 및 암호를 필요로 합니다.



== 용어

OnCommand Insight는 EMC Data Domain 데이터 소스에서 다음 인벤토리 정보를 가져옵니다. Insight에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 소스를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

|===


| 공급업체/모델 기간 | Insight 용어입니다 


 a| 
호스트
 a| 
호스트



 a| 
host_volume_mapping을 선택합니다
 a| 
host_volume_mapping을 선택합니다



 a| 
하드웨어("extra_details" 객체 아래에 드라이브가 있음): 드라이브
 a| 
디스크



 a| 
어플라이언스
 a| 
스토리지 풀



 a| 
클러스터
 a| 
스토리지



 a| 
노드
 a| 
스토리지노드



 a| 
fc_port 를 선택합니다
 a| 
포트



 a| 
볼륨
 a| 
볼륨



 a| 
내부 볼륨
 a| 
파일 시스템



 a| 
파일 시스템
 a| 
내부 볼륨



 a| 
MTree입니다
 a| 
qtree를 입력합니다



 a| 
할당량
 a| 
할당량



 a| 
NFS 및 CIFS 공유
 a| 
파일 공유

|===
[NOTE]
====
이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 소스의 모든 경우를 나타내는 것은 아닙니다.

====


== 요구 사항

* 스토리지 프로세서의 IP 주소 또는 정규화된 도메인 이름입니다
* 읽기 전용 사용자 이름 및 암호




== 상위 일련 번호가 설명되었습니다

일반적으로 Insight는 스토리지 어레이의 일련 번호 또는 개별 스토리지 노드의 일련 번호를 보고할 수 있습니다. 그러나 일부 스토리지 어레이 아키텍처는 이 문제에 완전히 부합되지 않습니다. PowerStore 클러스터는 1-4개의 어플라이언스로 구성될 수 있으며 각 어플라이언스에는 2개의 노드가 있습니다. 어플라이언스 자체에 일련 번호가 있는 경우 해당 일련 번호는 클러스터나 노드의 일련 번호가 아닙니다.

개별 노드가 대형 클러스터의 일부인 중간 어플라이언스/엔클로저 내에 있는 경우 스토리지 노드 개체의 "상위 일련 번호" 속성은 Dell/EMC PowerStore 어레이에 맞게 적절하게 채워집니다.



== 구성

|===


| 필드에 입력합니다 | 설명 


 a| 
PowerStore 게이트웨이
 a| 
PowerStore 스토리지의 IP 주소 또는 정규화된 도메인 이름입니다



 a| 
사용자 이름
 a| 
PowerStore의 사용자 이름입니다



 a| 
암호
 a| 
PowerStore에 사용되는 암호입니다

|===


== 고급 구성

|===


| 필드에 입력합니다 | 설명 


 a| 
HTTPS 포트
 a| 
기본값은 443입니다



 a| 
재고 폴링 간격(분)
 a| 
재고 조사 사이의 간격입니다. 기본값은 60분입니다.

|===
OnCommand Insight의 PowerStore 성능 수집을 통해 PowerStore의 5분 단위 소스 데이터를 사용할 수 있습니다. 따라서 Insight는 5분마다 해당 데이터를 폴링하여 구성할 수 없습니다.
