---
permalink: config-admin/device-resolution.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight를 사용하여 모니터링하려는 모든 장치를 검색해야 합니다. 환경의 성능과 인벤토리를 정확하게 추적하려면 검색이 필요합니다. 일반적으로 사용자 환경의 대부분의 장치는 자동 장치 해상도를 통해 검색됩니다. 
---
= 장치 해상도
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight를 사용하여 모니터링하려는 모든 장치를 검색해야 합니다. 환경의 성능과 인벤토리를 정확하게 추적하려면 검색이 필요합니다. 일반적으로 사용자 환경의 대부분의 장치는 자동 장치 해상도를 통해 검색됩니다.

[NOTE]
====
업그레이드를 수행하는 중에 업그레이드 중인 시스템에 비활성 자동 해결 규칙이 있는 경우 업그레이드 중에 이러한 규칙이 삭제됩니다. 비활성 자동 해결 규칙을 유지하려면 업그레이드를 수행하기 전에 규칙을 활성화(확인란 선택)합니다.

====
데이터 소스를 설치 및 구성한 후에는 스위치, 스토리지 어레이 및 하이퍼바이저와 VM의 가상 인프라를 비롯한 환경의 장치가 식별됩니다. 그러나 이 경우 일반적으로 사용자 환경의 디바이스 중 100%는 식별되지 않습니다.

데이터 소스 유형 디바이스를 구성한 후에는 디바이스 해결 규칙을 활용하여 사용자 환경에서 나머지 알 수 없는 디바이스를 식별하는 것이 가장 좋습니다. 장치 해상도를 통해 알 수 없는 장치를 다음 장치 유형으로 해결할 수 있습니다.

* 물리적 호스트
* 지원합니다
* 테이프
* 스위치


디바이스 확인 후 ""알 수 없음""으로 남아 있는 디바이스는 쿼리와 대시보드에도 표시할 수 있는 일반 디바이스로 간주됩니다.

차례로 생성된 규칙은 사용자 환경에 추가되는 것과 유사한 특성을 가진 새 디바이스를 자동으로 식별합니다. 경우에 따라 장치 해상도를 통해 Insight 내에서 검색되지 않은 장치에 대한 장치 해결 규칙을 우회하여 수동으로 식별할 수도 있습니다.

기기 식별이 완료되지 않으면 다음과 같은 문제가 발생할 수 있습니다.

* 불완전한 경로
* 알 수 없는 다중 경로 연결
* 애플리케이션을 그룹화할 수 없습니다
* 토폴로지 뷰가 부정확합니다
* 데이터 웨어하우스 및 보고의 부정확한 데이터


장치 해상도 기능(* 관리*>* 장치 해상도*)에는 다음 탭이 포함되어 있으며 각 탭은 장치 해상도 계획 및 결과 보기에 역할을 합니다.

* "FC Identify"(FC 식별)에는 자동 디바이스 확인을 통해 해결되지 않은 Fibre Channel 디바이스의 WWN 및 포트 정보가 포함됩니다. 이 탭은 식별된 디바이스의 비율도 식별합니다.
* "IP Identify"(IP 식별)에는 자동 디바이스 확인을 통해 식별되지 않은 CIFS 공유 및 NFS 공유에 액세스하는 디바이스 목록이 포함되어 있습니다. 이 탭은 식별된 디바이스의 비율도 식별합니다.
* "자동 해상도 규칙"에는 Fibre Channel 디바이스 해상도를 수행할 때 실행되는 규칙 목록이 포함되어 있습니다. 식별되지 않은 Fibre Channel 디바이스를 확인하기 위해 생성하는 규칙입니다.
* ""기본 설정""은 환경에 맞게 장치 해상도를 사용자 정의하는 데 사용하는 구성 옵션을 제공합니다.

