---
permalink: config-admin/e-series-landing-page-terminology-storage-pool.html 
sidebar: sidebar 
keywords:  
summary: NetApp E-Series 스토리지 풀 자산 랜딩 페이지에서 확인할 수 있는 오브젝트 또는 참조에 적용되는 용어입니다. 
---
= E-Series 스토리지 풀
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp E-Series 스토리지 풀 자산 랜딩 페이지에서 확인할 수 있는 오브젝트 또는 참조에 적용되는 용어입니다.



== E-Series 스토리지 풀 용어

다음 용어는 NetApp E-Series 스토리지 풀 자산 랜딩 페이지에서 볼 수 있는 오브젝트 또는 참조 자료에 적용됩니다. 이러한 용어 중 다수는 다른 데이터 수집기에도 적용됩니다.

* 스토리지 -- 이 풀이 상주하는 스토리지 배열입니다. 필수입니다.
* 형식 -- 가능성 목록 목록의 설명 값입니다. 가장 일반적인 것은 "씬 프로비저닝" 또는 "RAID 그룹"입니다.
* 노드 -- 이 스토리지 시스템의 아키텍처가 특정 스토리지 노드에 속해 있는 경우 이 스토리지 시스템의 이름은 해당 랜딩 페이지의 하이퍼링크로 표시됩니다.
* Flash Pool 사용 -- 예/아니요 값
* 중복 -- RAID 레벨 또는 보호 체계입니다. DDP 풀에 대한 E-Series의 보고서 "'RAID 7''.
* 용량 -- 이 값은 사용된 논리적 용량, 가용 용량 및 총 논리적 용량 및 이 용량 전체에서 사용된 비율입니다. 이러한 값에는 E-Series의 "보존" 용량이 모두 포함되어 있어 E-Series의 사용자 인터페이스에서 표시할 수 있는 용량보다 숫자 및 백분율이 높습니다.
* 과도하게 커밋된 용량 -- 효율성 기술을 사용하여 스토리지 풀의 논리적 용량보다 큰 총 볼륨 용량을 할당한 경우 여기에 있는 백분율 값은 0%보다 큽니다.
* 스냅샷 -- 사용 중인 스냅샷 용량 및 총 용량. 스토리지 풀 아키텍처가 용량의 일부를 스냅샷용 영역으로 세그먼트하는 경우
* Utilization -- 이 스토리지 풀에 용량을 제공하는 디스크 사용량이 가장 높은 비율을 나타내는 백분율입니다. 디스크 사용률이 반드시 스토리지 성능과 강력한 상관관계가 있는 것은 아닙니다. 호스트 기반 워크로드가 없을 경우 디스크 리빌드, 중복 제거 작업 등으로 인해 사용률이 높을 수 있습니다. 또한 많은 스토리지 "" 복제 구현으로 인해 볼륨 작업 부하로 표시되지 않는 동안 디스크 사용률이 발생할 수 있습니다.
* IOPS -- 이 스토리지 풀에 용량을 제공하는 모든 디스크의 IOPS 합계입니다.
* Throughput - - 이 스토리지 풀에 용량을 제공하는 모든 디스크의 총 처리량입니다.

