---
permalink: config-admin/emc-isilon-ssh-data-source.html 
sidebar: sidebar 
keywords:  
summary: Isilon SSH 데이터 소스는 EMC Isilon 스케일 아웃 NAS 스토리지에서 인벤토리 및 성능을 수집합니다. 
---
= EMC Isilon 데이터 소스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Isilon SSH 데이터 소스는 EMC Isilon 스케일 아웃 NAS 스토리지에서 인벤토리 및 성능을 수집합니다.



== 용어

OnCommand Insight는 EMC Isilon 데이터 소스에서 다음과 같은 인벤토리 정보를 가져옵니다. Insight에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 소스를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

|===


| 공급업체/모델 기간 | Insight 용어입니다 


 a| 
드라이브
 a| 
디스크



 a| 
클러스터
 a| 
스토리지



 a| 
노드
 a| 
스토리지 노드



 a| 
파일 시스템
 a| 
내부 볼륨

|===
[NOTE]
====
이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 소스의 모든 경우를 나타내는 것은 아닙니다.

====


== 요구 사항

* Isilon 스토리지에 대한 관리자 권한
* 을 사용하여 액세스를 검증했습니다 `telnet` 포트 22로 이동합니다




== 구성

|===


| 필드에 입력합니다 | 설명 


 a| 
IP 주소입니다
 a| 
Isilon 클러스터의 IP 주소 또는 정규화된 도메인 이름입니다



 a| 
사용자 이름입니다
 a| 
Isilon 클러스터의 사용자 이름입니다



 a| 
암호
 a| 
Isilon 클러스터의 암호입니다

|===


== 고급 구성

|===


| 필드에 입력합니다 | 설명 


 a| 
재고 폴링 간격(분)
 a| 
재고 조사 간격(기본값 20분)



 a| 
성능 폴링 간격(초)
 a| 
성능 폴링 간격(기본값 300초)



 a| 
SSH 프로세스 대기 시간이 초과되었습니다
 a| 
SSH 프로세스 시간 초과(기본값 60초)



 a| 
SSH 포트
 a| 
SSH 서비스 포트입니다

|===


== CLI 명령 실행 중

OnCommand Insight 버전 7.3.11 및 서비스 팩 9부터는 EMC Isilon 데이터 소스에 향상된 기능이 포함되어 Insight에서 더 많은 CLI 명령을 실행할 수 있습니다. 데이터 소스 내에서 루트 이외의 사용자를 사용하는 경우 해당 사용자 계정에 SSH를 통해 특정 CLI 명령을 실행할 수 있는 기능을 부여하기 위해 "sudoers" 파일을 구성했을 수 있습니다.

Insight에서 EMC의 "Access Zones" 기능을 이해하기 위해 이제 Insight에서 다음과 같은 새로운 CLI 명령을 추가로 실행합니다.

* `sudo isi zone zones list --format json –verbose`
* `sudo isi zone zones list`


Insight는 이러한 명령의 출력을 구문 분석하고 더 많은 기존 명령 인스턴스를 실행하여 기본 액세스 존이 아닌 영역에 있는 qtree, 할당량 및 NAS 공유/내보내기와 같은 개체의 논리적 구성을 가져옵니다. Insight Now는 이 기능 향상의 결과로 기본값이 아닌 액세스 존에 대한 개체를 보고합니다. Insight가 기존 명령(다른 옵션 사용)을 실행하여 해당 데이터를 가져올 때 해당 명령이 작동하려면 sudoers 파일을 변경할 필요가 없습니다. 이는 변경 사항이 필요하다는 위의 새 명령이 도입된 경우에만 해당됩니다.

Insight 서비스 계정이 이 Insight 릴리즈로 업그레이드하기 전에 해당 명령을 실행할 수 있도록 sudoers 파일을 업데이트하십시오. 그렇지 않으면 Isilon 데이터 소스가 실패합니다.



== "파일 시스템" 통계

OnCommand Insight 7.3.12부터 EMC Isilon 데이터 수집기는 EMC Isilon의 노드 객체에 대한 "파일 시스템" 통계를 도입했습니다. OnCommand Insight에서 보고하는 기존 노드 통계는 "디스크" 기반 i.e, 스토리지 노드의 IOPS 및 처리량에 대해 이 노드의 디스크는 Aggregate에서 어떤 작업을 합니까? 그러나 읽기 작업이 메모리에 캐시되거나 압축이 사용 중인 워크로드의 경우 파일 시스템 워크로드가 실제로 디스크에 적중하는 것보다 훨씬 높을 수 있습니다. 5:1을 압축하는 데이터 세트에서는 "파일 시스템 읽기 처리량" 값이 스토리지 노드의 읽기 처리량보다 5배 높을 수 있습니다. 후자는 디스크에서 읽기를 측정하므로 노드가 데이터를 압축 해제하고 클라이언트의 읽기 요청을 처리할 때 5배 확장됩니다.
