---
permalink: config-admin/emc-datadomain-data-source.html 
sidebar: sidebar 
keywords:  
summary: 이 데이터 소스는 EMC Data Domain 데이터 중복 제거 스토리지 시스템에서 스토리지 및 구성 정보를 수집합니다. 데이터 소스를 추가하려면 특정 구성 지침 및 명령을 사용하고 데이터 소스 요구 사항 및 사용 권장 사항을 알고 있어야 합니다. 
---
= EMC Data Domain 데이터 소스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 데이터 소스는 EMC Data Domain 데이터 중복 제거 스토리지 시스템에서 스토리지 및 구성 정보를 수집합니다. 데이터 소스를 추가하려면 특정 구성 지침 및 명령을 사용하고 데이터 소스 요구 사항 및 사용 권장 사항을 알고 있어야 합니다.



== 용어

OnCommand Insight는 EMC Data Domain 데이터 소스에서 다음 인벤토리 정보를 가져옵니다. Insight에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 소스를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

|===


| 공급업체/모델 기간 | Insight 용어입니다 


 a| 
디스크
 a| 
디스크



 a| 
스토리지
 a| 
스토리지



 a| 
포트
 a| 
포트



 a| 
파일 시스템
 a| 
내부 볼륨



 a| 
MTree입니다
 a| 
qtree를 입력합니다



 a| 
할당량
 a| 
할당량



 a| 
NFS 및 CIFS 공유
 a| 
파일 공유

|===
[NOTE]
====
이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 소스의 모든 경우를 나타내는 것은 아닙니다.

====


== 요구 사항

* Data Domain 디바이스의 IP 주소입니다
* Data Domain 스토리지에 대한 읽기 전용 사용자 이름 및 암호
* SSH 포트 22




== 구성

|===


| 필드에 입력합니다 | 설명 


 a| 
IP 주소입니다
 a| 
Data Domain 스토리지 시스템의 IP 주소 또는 정규화된 도메인 이름입니다



 a| 
사용자 이름입니다
 a| 
Data Domain 스토리지 시스템의 사용자 이름입니다



 a| 
암호
 a| 
Data Domain 스토리지 시스템의 암호입니다

|===


== 고급 구성

|===


| 필드에 입력합니다 | 설명 


 a| 
재고 폴링 간격(분)
 a| 
재고 조사 간격(기본값 20분)



 a| 
SSH 프로세스 대기 시간 초과(초)
 a| 
SSH 프로세스 시간 초과(기본값 180초)



 a| 
SSH 포트
 a| 
SSH 서비스 포트입니다

|===