---
permalink: config-admin/emc-vplex-cli-data-source.html 
sidebar: sidebar 
keywords:  
summary: 구성의 경우 이 데이터 소스에 VPLEX 서버의 IP 주소와 관리 레벨 도메인 계정이 필요합니다. 
---
= EMC VPLEX 데이터 소스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
구성의 경우 이 데이터 소스에 VPLEX 서버의 IP 주소와 관리 레벨 도메인 계정이 필요합니다.



== 용어

OnCommand Insight는 EMC VPLEX 데이터 소스에서 다음 인벤토리 정보를 가져옵니다. Insight에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 소스를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

|===


| 공급업체/모델 기간 | Insight 용어입니다 


 a| 
클러스터
 a| 
스토리지



 a| 
엔진
 a| 
스토리지 노드



 a| 
장치, 시스템 확장
 a| 
백엔드 스토리지 풀입니다



 a| 
가상 볼륨
 a| 
볼륨



 a| 
프런트엔드 포트, 백엔드 포트
 a| 
포트



 a| 
분산 장치
 a| 
저장소 동기화



 a| 
스토리지 보기
 a| 
볼륨 맵, 볼륨 마스크



 a| 
스토리지 볼륨
 a| 
백엔드 LUN



 a| 
ITL
 a| 
백엔드 경로

|===
[NOTE]
====
이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 소스의 모든 경우를 나타내는 것은 아닙니다.

====


== 요구 사항

* VPLEX 서버의 IP 주소입니다
* VPLEX 서버의 관리 레벨 도메인 계정입니다
* 포트 443(HTTPS). VPLEX 관리 스테이션의 TCP 포트 443에 대한 아웃바운드 연결이 필요합니다.
* 성능을 위해 ssh/scp 액세스를 위한 읽기 전용 사용자 이름과 암호를 사용합니다.
* 성능을 위해서는 포트 22가 필요합니다.
* 액세스 확인: 을 사용하여 확인합니다 `telnet` 포트 443으로 이동합니다. 기본 포트 이외의 포트에 대해 브라우저를 사용할 수 있습니다




== 구성

|===


| 필드에 입력합니다 | 설명 


 a| 
VPLEX Management Console의 IP 주소입니다
 a| 
VPLEX Management Console의 IP 주소 또는 정규화된 도메인 이름입니다



 a| 
사용자 이름
 a| 
VPLEX CLI의 사용자 이름입니다



 a| 
암호
 a| 
VPLEX CLI에 사용되는 암호입니다



 a| 
VPLEX Management Console의 성능 원격 IP 주소입니다
 a| 
VPLEX Management Console의 성능 원격 IP 주소입니다



 a| 
성능 원격 사용자 이름입니다
 a| 
VPLEX Management Console의 Performance Remote 사용자 이름입니다



 a| 
성능 원격 암호
 a| 
VPLEX Management Console의 성능 원격 암호

|===


== 고급 구성

|===


| 필드에 입력합니다 | 설명 


 a| 
통신 포트
 a| 
VPLEX CLI에 사용되는 포트입니다



 a| 
재고 폴링 간격(분)
 a| 
재고 조사 간격(기본값 20분)



 a| 
연결 시간 초과(초)
 a| 
연결 시간 초과(기본값 60초)



 a| 
재시도 횟수
 a| 
인벤토리 재시도 횟수입니다



 a| 
성능 폴링 간격(초)
 a| 
성능 폴링 간격(기본값 600초)



 a| 
성능 SSH 프로세스 대기 시간 초과(초)
 a| 
SSH 프로세스 시간 초과(기본값 600초)



 a| 
SSH 배너 대기 시간 제한(초)
 a| 
SSH 배너 대기 시간 초과(기본값 20초)



 a| 
재시도 횟수
 a| 
성능 재시도 횟수입니다

|===