---
permalink: config-admin/emc-clariion-navicli-data-source.html 
sidebar: sidebar 
keywords:  
summary: 이 데이터 소스를 구성하기 전에 EMC Navisphere CLI가 타겟 디바이스 및 Insight 서버에 설치되어 있는지 확인합니다. Navisphere CLI 버전은 컨트롤러의 펌웨어 버전과 일치해야 합니다. 성능 데이터 수집을 위해 통계 로깅을 설정해야 합니다. 
---
= EMC CLARiX(NaviCLI) 데이터 소스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 데이터 소스를 구성하기 전에 EMC Navisphere CLI가 타겟 디바이스 및 Insight 서버에 설치되어 있는지 확인합니다. Navisphere CLI 버전은 컨트롤러의 펌웨어 버전과 일치해야 합니다. 성능 데이터 수집을 위해 통계 로깅을 설정해야 합니다.



== Navisphere 명령줄 인터페이스 구문입니다

[listing]
----
naviseccli.exe -h <IP address> -user <user> -password <password> -scope
<scope,use 0 for global scope> -port <use 443 by default> command
----


== 용어

OnCommand Insight는 EMC CLARiX 데이터 소스에서 다음 인벤토리 정보를 가져옵니다. Insight에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 소스를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

|===


| 공급업체/모델 기간 | Insight 용어입니다 


 a| 
디스크
 a| 
디스크



 a| 
스토리지
 a| 
스토리지



 a| 
스토리지 프로세서
 a| 
스토리지 노드



 a| 
씬 풀, RAID 그룹
 a| 
스토리지 풀



 a| 
LUN을 클릭합니다
 a| 
볼륨

|===
[NOTE]
====
이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 소스의 모든 경우를 나타내는 것은 아닙니다.

====


== 요구 사항

* 각 CLARiX 스토리지 프로세서의 IP 주소입니다
* CLARiX 스토리지에 대한 읽기 전용 Navisphere 사용자 이름 및 암호입니다
* Navicli는 Insight 서버/RAU에 설치해야 합니다
* 액세스 검증: 위의 사용자 이름과 암호를 사용하여 Insight 서버에서 각 어레이로 NaviCLI를 실행합니다.
* Navicli 버전은 스토리지의 최신 FLARE 코드와 일치해야 합니다
* 성능을 위해서는 통계 로깅을 설정해야 합니다.
* 포트 요구 사항: 80, 443




== 구성

|===


| 필드에 입력합니다 | 설명 


 a| 
CLARiX 스토리지
 a| 
CLARiX 스토리지의 IP 주소 또는 정규화된 도메인 이름입니다



 a| 
사용자 이름
 a| 
CLARiX 스토리지 디바이스에 로그인하는 데 사용되는 이름입니다.



 a| 
암호
 a| 
CLARiX 스토리지 디바이스에 로그인하는 데 사용되는 암호입니다.



 a| 
NaviCLI.exe 경로 또는 naviseccli.exe 경로에 대한 CLI 경로
 a| 
에 대한 전체 경로입니다 `navicli.exe` 또는 `naviseccli.exe` 실행 파일

|===


== 고급 구성

|===


| 필드에 입력합니다 | 설명 


 a| 
재고 폴링 간격(분)
 a| 
재고 조사 간격(기본값 40분)



 a| 
보안 클라이언트 사용(naviseccli)
 a| 
보안 클라이언트(navseccli)를 사용하려면 선택합니다.



 a| 
범위
 a| 
보안 클라이언트 범위 기본값은 Global 입니다.



 a| 
CLARiX CLI 포트입니다
 a| 
CLARiX CLI에 사용되는 포트입니다



 a| 
재고 외부 프로세스 시간 초과(초)
 a| 
외부 프로세스 시간 초과(기본값 1800초)



 a| 
성능 폴링 간격(초)
 a| 
성능 폴링 간격(기본값 300초)



 a| 
성능 외부 프로세스 시간 초과(초)
 a| 
외부 프로세스 시간 초과(기본값 1800초)

|===