---
permalink: config-admin/emc-solutions-enabler-cli-with-smi-s-performance.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight는 Solutions Enabler symcli 명령을 사용자 환경의 기존 Solutions Enabler 서버와 함께 사용하여 Symmetrix 스토리지 시스템을 검색합니다. 기존 Solutions Enabler 서버는 게이트키퍼 볼륨에 대한 액세스를 통해 Symmetrix 스토리지에 접속할 수 있습니다. 이 장치에 액세스하려면 관리자 권한이 필요합니다. 
---
= SMI-S 성능 데이터 소스를 지원하는 EMC Solutions Enabler
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight는 Solutions Enabler를 사용하여 Symmetrix 스토리지 시스템을 검색합니다 `symcli` 사용자 환경에서 기존 Solutions Enabler 서버와 함께 사용되는 명령입니다. 기존 Solutions Enabler 서버는 게이트키퍼 볼륨에 대한 액세스를 통해 Symmetrix 스토리지에 접속할 수 있습니다. 이 장치에 액세스하려면 관리자 권한이 필요합니다.



== 용어

OnCommand Insight는 EMC Solutions Enabler 데이터 소스에서 다음 인벤토리 정보를 가져옵니다. Insight에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 소스를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

|===


| 공급업체/모델 기간 | Insight 용어입니다 


 a| 
디스크
 a| 
디스크



 a| 
디스크 그룹
 a| 
디스크 그룹



 a| 
스토리지
 a| 
스토리지



 a| 
책임자
 a| 
스토리지 노드



 a| 
디바이스 풀, SRP(Storage Resource Pool)
 a| 
스토리지 풀



 a| 
디바이스, TDEV
 a| 
볼륨

|===
[NOTE]
====
이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 소스의 모든 경우를 나타내는 것은 아닙니다.

====


== 요구 사항

이 데이터 소스를 구성하기 전에 OnCommand Insight 서버가 기존 Solutions Enabler 서버의 포트 2707에 대한 TCP 연결을 가지고 있는지 확인해야 합니다. OnCommand Insight는 해당 서버의 "sycfg list" 출력에 표시된 것처럼 이 서버에 대한 "Local" Symmetrix 스토리지를 모두 검색합니다.

* SMI-S Provider 애플리케이션이 포함된 EMC Solutions Enabler(CLI)가 설치되어 있어야 하며 버전이 Solutions Enabler Server에서 실행 중인 버전과 동일하거나 그 이전이어야 합니다.
* 올바르게 구성되었습니다 `+{installdir}\EMC\SYMAPI\config\netcnfg+` 파일이 필요합니다. 이 파일은 Solutions Enabler 서버의 서비스 이름 및 액세스 방법(Secure/NOSECURE/Any)을 정의합니다.
* 스토리지 노드 레벨에서 읽기/쓰기 지연 시간이 필요한 경우 SMI-S Provider는 Unisphere for VMAX 애플리케이션의 실행 중인 인스턴스와 통신해야 합니다.
* SE(Solutions Enabler) 서버에 대한 관리자 권한
* SE 소프트웨어의 읽기 전용 사용자 이름 및 암호
* Solutions Enabler Server 6.5X 요구 사항:
+
** SMIS-S v1.2용 SMI-S Provider 3.3.1 설치
** 설치 후 를 실행합니다 `\Program Files\EMC\SYMCLI\bin>stordaemon start storsrvd`


* Unisphere for VMAX 애플리케이션은 SMI-S Provider 설치를 통해 관리되는 Symmetrix VMAX 스토리지 시스템에 대한 통계를 실행 및 수집해야 합니다
* 액세스 검증: SMI-S Provider가 실행 중인지 확인합니다. `telnet <se_server\> 5988`




== 구성

[NOTE]
====
SMI-S 사용자 인증을 사용하지 않으면 OnCommand Insight 데이터 소스의 기본값이 무시됩니다.

====
Symmetrix 스토리지에 symauth를 설정하면 OnCommand Insight에서 해당 스토리지를 검색하는 기능이 억제될 수 있습니다. OnCommand Insight 취득은 Solutions Enabler 서버와 통신하는 OnCommand Insight/원격 획득 장치 서버에서 시스템 사용자로 실행됩니다. hostname\system에 symauth 권한이 없으면 OnCommand Insight에서 스토리지를 검색하지 못합니다.

EMC Solutions Enabler Symmetrix CLI 데이터 소스에는 씬 프로비저닝 및 SRDF(Symmetrix Remote Data Facility)에 대한 디바이스 구성이 지원됩니다.

Fibre Channel 및 스위치 성능 패키지에 대한 정의가 제공됩니다.

|===


| 필드에 입력합니다 | 설명 


 a| 
서비스 이름
 a| 
netcnfg 파일에 지정된 서비스 이름입니다



 a| 
CLI의 전체 경로입니다
 a| 
Symmetrix CLI의 전체 경로입니다

|===


== 고급 구성

|===


| 필드에 입력합니다 | 설명 


 a| 
재고 폴링 간격(분)
 a| 
재고 조사 간격(기본값 40분)



 a| 
목록을 지정하려면 '제외' 또는 '포함'을 선택하십시오
 a| 
데이터를 수집할 때 아래 어레이 목록을 포함할지 제외할지 여부를 지정합니다



 a| 
재고 제외 장치
 a| 
포함하거나 제외할 장치 ID의 쉼표로 구분된 목록입니다



 a| 
연결 캐싱
 a| 
연결 캐싱 방법 선택:

* 로컬은 검색하려는 Symmetrix 스토리지에 Fibre Channel 접속이 가능하고 게이트키퍼 볼륨에 액세스할 수 있는 Solutions Enabler 서버에서 OnCommand Insight 획득 서비스가 실행되고 있음을 의미합니다. 이 문제는 일부 RAU(Remote Acquisition Unit) 구성에서 확인할 수 있습니다.
* remote_cached가 기본값입니다. 대부분의 경우 이 기능을 사용해야 합니다. 이 경우 NETCNFG 파일 설정을 사용하여 IP를 사용하여 Solutions Enabler 서버에 접속합니다. 이 서버는 검색할 Symmetrix 스토리지에 Fibre Channel 접속이 있어야 하며 게이트키퍼 볼륨에 액세스할 수 있어야 합니다.
* remote_cached 옵션으로 인해 CLI 명령이 실패하는 경우 원격 옵션을 사용합니다. 구입 프로세스가 느려집니다(극단적인 경우 몇 시간 또는 며칠이 걸릴 수 있음). NETCNFG 파일 설정은 검색 중인 Symmetrix 스토리지에 Fibre Channel 접속이 설정된 Solutions Enabler 서버에 대한 IP 접속에 계속 사용됩니다.


[NOTE]
====
이 설정은 "symcfg list" 출력에 의해 원격 스토리지로 나열된 스토리지에 대한 OnCommand Insight 동작을 변경하지 않습니다. OnCommand Insight는 이 명령으로 로컬로 표시된 장치에서만 데이터를 수집합니다.

====


 a| 
CLI 시간 제한(초)
 a| 
CLI 프로세스 시간 초과(기본값: 7200초)



 a| 
SMI-S 호스트 IP입니다
 a| 
SMI-S Provider 호스트의 IP 주소입니다



 a| 
SMI-S 포트
 a| 
SMI-S Provider 호스트에서 사용하는 포트입니다



 a| 
프로토콜
 a| 
SMI-S 공급자에 연결하는 데 사용되는 프로토콜입니다



 a| 
SMI-S 네임스페이스
 a| 
SMI-S 공급자가 사용하도록 구성된 상호 운용성 네임스페이스입니다



 a| 
SMI-S 사용자 이름
 a| 
SMI-S Provider 호스트의 사용자 이름입니다



 a| 
SMI-S 암호
 a| 
SMI-S Provider 호스트의 사용자 이름입니다



 a| 
성능 폴링 간격(초)
 a| 
성능 폴링 간격(기본값 1000초)



 a| 
성능 필터 유형
 a| 
성능 데이터를 수집할 때 아래 스토리지 목록을 포함할지 제외할지 여부를 지정합니다



 a| 
성능 필터 장치 목록
 a| 
포함하거나 제외할 장치 ID의 쉼표로 구분된 목록입니다



 a| 
RPO 폴링 간격(초)
 a| 
RPO 폴링 간격(기본값 300초)

|===