---
permalink: config-admin/emc-celerra-ssh-data-source.html 
sidebar: sidebar 
keywords:  
summary: 'Celerra \(SSH\) 데이터 소스는 Celerra 스토리지에서 인벤토리 정보를 수집합니다. 구성의 경우 이 데이터 원본에는 스토리지 프로세서의 IP 주소와 읽기 전용 사용자 이름 및 암호가 필요합니다.' 
---
= EMC Celerra 데이터 소스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Celerra(SSH) 데이터 소스는 Celerra 스토리지에서 인벤토리 정보를 수집합니다. 구성의 경우 이 데이터 원본에는 스토리지 프로세서의 IP 주소와 _read-only_user 이름 및 암호가 필요합니다.



== 용어

OnCommand Insight는 EMC Celerra 데이터 소스에서 다음 인벤토리 정보를 가져옵니다. Insight에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 소스를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

|===


| 공급업체/모델 기간 | Insight 용어입니다 


 a| 
Celerra Network Server입니다
 a| 
스토리지



 a| 
Celerra 메타 볼륨/Celerra 스토리지 풀
 a| 
스토리지 풀



 a| 
파일 시스템
 a| 
내부 볼륨



 a| 
Data Mover입니다
 a| 
컨트롤러



 a| 
Data Mover에 마운트된 파일 시스템입니다
 a| 
파일 공유



 a| 
CIFS 및 NFS 엑스포트
 a| 
공유



 a| 
디스크 볼륨
 a| 
백엔드 LUN

|===
[NOTE]
====
이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 소스의 모든 경우를 나타내는 것은 아닙니다.

====


== 요구 사항

* 스토리지 프로세서의 IP 주소입니다
* 읽기 전용 사용자 이름 및 암호
* SSH 포트 22




== 구성

|===


| 필드에 입력합니다 | 설명 


 a| 
Celerra의 주소입니다
 a| 
Celerra 디바이스의 IP 주소 또는 정규화된 도메인 이름입니다



 a| 
사용자 이름
 a| 
Celerra 디바이스에 로그인하는 데 사용되는 이름입니다



 a| 
암호
 a| 
Celerra 디바이스에 로그인하는 데 사용되는 암호입니다

|===


== 고급 구성

|===


| 필드에 입력합니다 | 설명 


 a| 
재고 폴링 간격(분)
 a| 
재고 조사 간격(기본값 20분)



 a| 
SSH 프로세스 대기 시간 초과(초)
 a| 
SSH 프로세스 시간 초과(기본값 600초)



 a| 
재시도 횟수
 a| 
인벤토리 재시도 횟수입니다



 a| 
SSH 배너 대기 시간 제한(초)
 a| 
SSH 배너 대기 시간 초과(기본값 20초)

|===