---
permalink: config-admin/examining-network-performance.html 
sidebar: sidebar 
keywords:  
summary: 스토리지 환경의 성능을 검사하고 활용률이 저조하거나 활용도가 높은 리소스를 식별하고 문제가 발생하기 전에 위험을 식별할 수 있습니다. 
---
= 네트워크 성능 검사
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 환경의 성능을 검사하고 활용률이 저조하거나 활용도가 높은 리소스를 식별하고 문제가 발생하기 전에 위험을 식별할 수 있습니다.

Insight는 수집된 스토리지 데이터를 통해 밝혀진 성능 및 가용성 문제를 해결합니다.

Insight를 사용하여 다음과 같은 성능 관리 작업을 수행할 수 있습니다.

* 환경 전체의 성능 모니터링
* 다른 장치의 성능에 영향을 미치는 리소스를 파악합니다




== 포트의 중요성

DWH(Insight Server and Data Warehouse) 서버는 안정적으로 작동하려면 많은 TCP 포트를 사용할 수 있어야 합니다. 이러한 포트 중 일부는 localhost 어댑터(127.0.0.1)에 바인딩된 프로세스에만 활용되지만 핵심 서비스가 안정적으로 작동하려면 여전히 필요합니다. 필요한 포트 수는 네트워크에서 사용되는 포트의 상위 집합입니다.



== Insight 서버 포트

Insight Server에는 소프트웨어 방화벽이 설치되어 있을 수 있습니다. 열어야 할 "구멍"은 아래와 같습니다.

* 인바운드 HTTPS 443 * - TCP 443에서 Insight WebUI를 실행 중인 경우 다음 소비자 중 일부 및 모두를 허용하도록 해당 를 노출해야 합니다.

* WebUI의 Insight 사용자
* Insight 서버에 연결하려는 원격 획득 장치
* 이 Insight 서버에 대한 커넥터가 있는 OCI DWH 서버
* Insight REST API와의 프로그래밍 상호 작용
* 이상 현상 감지 이상 정보를 렌더링하기 위해 Insight 성능 데이터를 소스를 찾는 엔진


Insight 서버 호스트 레벨 방화벽 구축을 원하는 모든 사람에게 NetApp은 모든 기업 네트워크 IP 블록에 HTTPS 액세스를 허용하도록 권장합니다.

* 인바운드 MySQL(TCP 3306) *. 이 포트는 커넥터가 있는 Insight DWH 서버에만 노출되어야 합니다

Insight에는 수십 개의 데이터 수집기가 있지만 모두 폴링 기반 Insight로 인해 획득 장치(AUS)가 다양한 장치에 대한 아웃바운드 통신을 시작합니다. 호스트 기반 방화벽이 방화벽을 통해 반환 트래픽을 허용할 수 있도록 "상태 저장"되어 있는 한 Insight Server의 호스트 기반 방화벽은 데이터 획득에 영향을 주지 않습니다.



== 데이터 웨어하우스 포트

Insight DWH 서버의 경우:

* 인바운드 HTTPS 443 * - TCP 443에서 Insight WebUI를 실행 중인 경우 다음 소비자를 허용하도록 해당 를 노출해야 합니다.

* DWH 관리 포털의 Insight 관리 사용자


* 인바운드 HTTPS(TCP 9300) * - Cognos 보고 인터페이스입니다. 사용자가 Cognos 보고 인터페이스와 상호 작용할 경우 이 정보는 원격으로 노출되어야 합니다.

DWH를 노출할 필요가 없는 환경을 상상할 수 있습니다. 보고서 작성자는 DWH 서버에 RDP 연결을 만들고 보고서를 작성 및 예약하는 동시에 모든 보고서가 SMTP를 통해 전송되거나 원격 파일 시스템에 기록되도록 예약할 수 있습니다.

* 인바운드 MySQL(TCP 3306) *. 이 포트는 조직이 DWH 데이터와 MySQL 기반 통합을 수행하는 경우에만 노출되어야 합니다. - CMDB, 차지백 시스템 등과 같은 다른 애플리케이션에 대한 인제스트하기 위해 다양한 DWH 데이터 마트에서 데이터를 추출하는 경우
