---
permalink: config-admin/examining-one-data-source-in-detail.html 
sidebar: sidebar 
keywords:  
summary: 데이터 원본에 오류가 있거나 속도가 느려지면 해당 데이터 원본에 대한 자세한 정보 요약을 검토하여 문제의 원인을 확인할 수 있습니다. 주의를 기울여야 하는 조건이 있는 데이터 소스는 빨간색 원으로 표시됩니다. 
---
= 하나의 데이터 소스를 자세히 조사 중입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 원본에 오류가 있거나 속도가 느려지면 해당 데이터 원본에 대한 자세한 정보 요약을 검토하여 문제의 원인을 확인할 수 있습니다. 주의를 기울여야 하는 조건이 있는 데이터 소스는 빨간색 원으로 표시됩니다.



== 단계

. Insight 도구 모음에서 * Admin * 을 클릭합니다.
+
데이터 소스 * 목록이 열립니다. 잠재적인 문제가 있는 나열된 모든 데이터 원본은 빨간색 원으로 표시됩니다. 가장 심각한 문제는 목록의 맨 위에 있습니다.

. 문제를 일으키는 데이터 소스를 선택합니다.
. 데이터 원본 이름 링크를 클릭합니다.
. 데이터 원본 요약 페이지에서 다음 섹션의 정보를 확인합니다.
+
** * 이벤트 일정 *
+
데이터 소스 목록에 표시된 현재 상태와 연결된 이벤트를 나열합니다. 이 요약의 이벤트는 장치별로 표시됩니다. 오류는 빨간색으로 표시됩니다. 타임라인 항목 위에 마우스 포인터를 놓으면 추가 정보를 표시할 수 있습니다.

** * 이 데이터 소스에서 보고한 장치 *
+
디바이스 유형, 해당 IP 주소 및 각 디바이스에 대한 자세한 정보에 대한 링크를 표시합니다.

** * 이 데이터 소스에서 보고된 변경 사항(지난 3주) *
+
추가 또는 제거되었거나 구성이 변경된 모든 장치를 나열합니다.



. 데이터 원본 정보를 검토한 후 페이지 맨 위에 있는 단추를 사용하여 다음 작업 중 하나를 수행할 수 있습니다.
+
** * 편집 * 문제를 해결하기 위한 데이터 원본에 대한 설명입니다.
** * 다시 폴링 * 문제가 지속적이었거나 간헐적으로 발생하는지 여부를 폴링하도록 강제합니다.
** * 3, 7 또는 30일 동안 데이터 소스 폴링을 연기하여 문제를 조사하고 경고 메시지를 중지할 시간을 제공합니다.
** * 데이터 원본에 패치 * 를 설치하여 문제를 해결합니다.
** 기술 지원을 위해 * 오류 보고서 * 를 준비합니다.
** * Insight 모니터링 환경에서 데이터 소스를 * 삭제 * 합니다.



