---
permalink: config-admin/hds-hnas-data-source.html 
sidebar: sidebar 
keywords:  
summary: 'HDS NAS\(HNAS\) 데이터 소스는 HDS NAS 클러스터의 검색을 지원하는 인벤토리 및 구성 데이터 소스입니다. Insight는 NFS 및 CIFS 공유, 파일 시스템\(Insight 내부 볼륨\) 및 스팬\(Insight Storage Pools\)을 검색할 수 있도록 지원합니다.' 
---
= HDS NAS(HNAS) 데이터 소스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
HDS NAS(HNAS) 데이터 소스는 HDS NAS 클러스터의 검색을 지원하는 인벤토리 및 구성 데이터 소스입니다. Insight는 NFS 및 CIFS 공유, 파일 시스템(Insight 내부 볼륨) 및 확장(Insight 스토리지 풀)을 검색할 수 있도록 지원합니다.

이 데이터 소스는 SSH 기반이므로 HNAS 자체의 TCP 22 또는 클러스터가 연결된 시스템 관리 장치(SMU)에 대해 SSH 세션을 시작할 수 있어야 합니다.



== 용어

OnCommand Insight는 HNAS 데이터 소스에서 다음 인벤토리 정보를 가져옵니다. Insight에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 소스를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

|===


| 공급업체/모델 기간 | Insight 용어입니다 


 a| 
계층
 a| 
디스크 그룹



 a| 
클러스터
 a| 
스토리지



 a| 
노드
 a| 
스토리지 노드



 a| 
스팬
 a| 
스토리지 풀



 a| 
파일 시스템
 a| 
내부 볼륨

|===
[NOTE]
====
이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 소스의 모든 경우를 나타내는 것은 아닙니다.

====


== 요구 사항

다음은 이 데이터 소스를 구성하고 사용하기 위한 요구 사항입니다.

* 장치 IP 주소입니다
* 포트 22, SSH 프로토콜
* 사용자 이름 및 암호 권한 수준: 감독자
* 참고: 이 데이터 수집기는 SSH 기반이므로 HNAS 자체의 TCP 22 또는 클러스터가 연결된 시스템 관리 장치(SMU)에 대해 SSH 세션을 시작할 수 있어야 합니다.


[NOTE]
====
이 데이터 수집기는 SSH 기반이므로 HNAS 자체의 TCP 22 또는 클러스터가 연결된 시스템 관리 장치(SMU)에 대해 SSH 세션을 시작할 수 있어야 합니다.

====


== 구성

|===


| 필드에 입력합니다 | 설명 


 a| 
HNAS 호스트
 a| 
HNAS 관리 호스트의 IP 주소 또는 정규화된 도메인 이름입니다



 a| 
사용자 이름
 a| 
HNAS CLI의 사용자 이름입니다



 a| 
암호
 a| 
HNAS CLI에 사용되는 암호입니다

|===


== 고급 구성

|===


| 필드에 입력합니다 | 설명 


 a| 
재고 폴링 간격(분)
 a| 
재고 조사 간격(기본값 30분)



 a| 
SSH 배너 대기 시간 제한(초)
 a| 
SSH 배너 대기 시간 초과(기본값 15초)



 a| 
SSH 명령 시간 초과(초)
 a| 
SSH 명령 시간 초과(기본값 30초)

|===