---
permalink: config-admin/hds-landing-page-terminology-storage-pool.html 
sidebar: sidebar 
keywords:  
summary: HDS 스토리지 풀 자산 랜딩 페이지에서 찾을 수 있는 오브젝트나 참조에 적용되는 용어입니다. 
---
= HDS 스토리지 풀
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
HDS 스토리지 풀 자산 랜딩 페이지에서 찾을 수 있는 오브젝트나 참조에 적용되는 용어입니다.



== HDS 스토리지 풀 용어

다음 용어는 HDS 스토리지 풀 자산 랜딩 페이지에서 찾을 수 있는 오브젝트 또는 참조에 적용됩니다. 이러한 용어 중 다수는 다른 데이터 수집기에도 적용됩니다.

* 유형: 여기에 있는 값은 다음 중 하나입니다.
+
** 예약됨 -- 이 풀이 데이터 볼륨(예: 저널링, 스냅샷)이 아닌 다른 용도로 사용되는 경우
** 씬 프로비저닝 -- HDP 풀인 경우
** RAID 그룹 -- 다음과 같은 몇 가지 이유로 이러한 항목이 표시되지 않을 수 있습니다.
+
OCI는 용량을 모든 비용에 두 배로 늘리는 것을 피하기 위해 강력한 입지를 가지고 있습니다. HDS에서는 일반적으로 디스크에서 RAID 그룹을 구축하고, 해당 RAID 그룹에 풀 볼륨을 생성하고, 해당 풀 볼륨에서 풀(대개 HDP이지만 특수한 용도로 사용될 수 있음)을 구성해야 합니다. OCI가 기본 RAID 그룹과 풀을 모두 보고한 경우 원시 용량의 합이 디스크 합보다 엄청나게 큽니다.

+
대신, OCI의 HDS HiCommand 데이터 수집기는 풀 볼륨의 용량에 따라 RAID 그룹의 크기를 임의로 축소합니다. 결과적으로 OCI가 RAID 그룹을 보고하지 않을 수 있습니다. 또한 결과 RAID 그룹은 OCI WebUI에서 표시되지 않지만 DWH(OCI 데이터 웨어하우스)로 흐르게 되는 방식으로 플래그가 지정됩니다. 이러한 의사 결정의 목적은 대부분의 사용자가 신경 쓰지 않는 것들에 대한 UI 혼란을 피하는 것입니다. HDS 어레이에 50MB의 여유 공간이 있는 RAID 그룹이 있는 경우, 의미 있는 결과를 얻기 위해 이 여유 공간을 사용할 수 없을 것입니다.



* HDS 풀은 특정 노드에 연결되지 않으므로 노드 N/A입니다
* 이중화 - 풀의 RAID 레벨입니다. 여러 RAID 유형으로 구성된 HDP 풀의 값이 여러 개일 수 있습니다
* 용량 % - 풀의 사용된 GB 및 총 논리적 GB 크기와 함께 데이터 사용에 사용된 풀의 비율
* 과도하게 커밋된 용량 - 이 풀의 논리적 용량이 풀의 논리적 용량을 이 비율로 초과하는 논리적 볼륨의 합계로 이 비율에 의해 초과 할당되고 있습니다.
* 스냅샷 - 이 풀의 스냅샷 사용을 위해 예약된 용량을 표시합니다

