---
permalink: config-admin/host-configuration-for-smart-card-and-certificate-login.html 
sidebar: sidebar 
keywords:  
summary: '스마트 카드\(CAC\) 및 인증서 로그인을 지원하려면 OnCommand Insight 호스트 구성을 수정해야 합니다.' 
---
= 스마트 카드 및 인증서 로그인을 위한 호스트 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스마트 카드(CAC) 및 인증서 로그인을 지원하려면 OnCommand Insight 호스트 구성을 수정해야 합니다.



== 시작하기 전에

* 시스템에서 LDAP를 활성화해야 합니다.
* LDAP입니다 `User principal account name` 속성은 사용자 ID가 포함된 LDAP 필드와 일치해야 합니다.



NOTE: 를 사용하여 _server.keystore_and/or_server.trutstore_passwordslink:../config-admin/security-management.html["SecurityAdmin 을 클릭합니다"]를 변경한 경우 LDAP 인증서를 가져오기 전에 _SANscreen_service를 다시 시작하십시오.

[NOTE]
====
최신 CAC 및 인증서 지침은 다음 기술 자료 문서를 참조하십시오(Support login required).

* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_configure_Common_Access_Card_(CAC)_authentication_for_NetApp_OnCommand_Insight["OnCommand Insight에 대한 CAC(Common Access Card) 인증을 구성하는 방법"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_configure_Common_Access_Card_(CAC)_authentication_for_NetApp_OnCommand_Insight_DataWarehouse["OnCommand Insight 데이터 웨어하우스에 대한 CAC(Common Access Card) 인증을 구성하는 방법"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_create_and_import_a_Certificate_Authority_(CA)_signed_certificate_into_OCI_and_DWH_7.3.X["CA(인증 기관) 서명 인증서를 만들어 OnComand Insight 및 OnCommand Insight 데이터 웨어하우스 7.3.x로 가져오는 방법"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_create_a_Self_Signed_Certificate_within_OnCommand_Insight_7.3.X_installed_on_a_Windows_Host["Windows 호스트에 설치된 OnCommand Insight 7.3.X 내에서 자체 서명된 인증서를 만드는 방법"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_import_a_Cognos_Certificate_Authority_(CA)_signed_certificate_into_DWH_7.3.3_and_later["Cognos CA(인증 기관) 서명 인증서를 OnCommand Datawarehouse 7.3.3 이상으로 가져오는 방법"]


====


== 단계

. 를 사용합니다 `regedit` 에서 레지스트리 값을 수정하는 유틸리티입니다 `HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Apache Software Foundation\Procrun2.0\SANscreen Server\Parameters\Java`:
+
.. jvm_option을 변경합니다 `DclientAuth=false` 를 선택합니다 `DclientAuth=true.`


. 키 저장소 파일을 백업합니다. `C:\Program Files\SANscreen\wildfly\standalone\configuration\server.keystore`
. 를 지정하는 명령 프롬프트를 엽니다 `Run as administrator`
. 자체 생성된 인증서 삭제: `C:\Program Files\SANscreen\java64\bin\keytool.exe -delete -alias "ssl certificate" -keystore C:\Program Files\SANscreen\wildfly\standalone\configuration\server.keystore`
. 새 인증서 생성: `C:\Program Files\SANscreen\java64\bin\keytool.exe -genkey -alias "alias_name" -keyalg RSA -sigalg SHA1withRSA -keysize 2048 -validity 365 -keystore "C:\Program Files\SANscreen\wildfly\standalone\configuration\server.keystore" -dname "CN=commonName,OU=orgUnit,O=orgName,L=localityNameI,S=stateName,C=countryName"`
. 인증서 서명 요청(CSR) 생성: `C:\Program Files\SANscreen\java64\bin\keytool.exe -certreq -sigalg SHA1withRSA -alias "alias_name" -keystore "C:\Program Files\SANscreen\wildfly\standalone\configuration\server.keystore" -file C:\temp\server.csr"`
. 6단계에서 CSR이 반환된 후 인증서를 가져온 다음 Base-64 형식으로 인증서를 내보내고 에 넣습니다 `"C:\temp" named servername.cer`.
. 키 저장소에서 인증서를 추출합니다.``C:\Program Files\SANscreen\java64\bin\keytool.exe -v -importkeystore -srckeystore "C:\Program Files\SANscreen\wildfly\standalone\configuration\server.keystore" -srcalias "alias_name" -destkeystore "C:\temp\file.p12" -deststoretype PKCS12``
. P12 파일에서 개인 키를 추출합니다. `openssl pkcs12 -in "C:\temp\file.p12" -out "C:\temp\servername.private.pem"`
. 7단계에서 내보낸 Base-64 인증서를 개인 키와 병합합니다. `openssl pkcs12 -export -in "<folder>\<certificate>.cer" -inkey "C:\temp\servername.private.pem" -out "C:\temp\servername.new.p12" -name "servername.abc.123.yyy.zzz"`
. 병합된 인증서를 키 저장소로 가져옵니다. `C:\Program Files\SANscreen\java64\bin\keytool.exe -importcert -destkeystore "C:\Program Files\SANscreen\wildfly\standalone\configuration\server.keystore" -srckeystore "C:\temp\servername.new.p12" -srcstoretype PKCS12 -alias "alias_name"`
. 루트 인증서 가져오기: `C:\Program Files\SANscreen\java64\bin\keytool.exe -importcert -keystore "C:\Program Files\SANscreen\wildfly\standalone\configuration\server.keystore" -file "C:\<root_certificate>.cer" -trustcacerts -alias "alias_name"`
. 루트 인증서를 서버로 가져옵니다. trustore: `C:\Program Files\SANscreen\java64\bin\keytool.exe -importcert -keystore "C:\Program Files\SANscreen\wildfly\standalone\configuration\server.trustore" -file "C:\<email_certificate>.cer" -trustcacerts -alias "alias_name"`
. 중간 인증서 가져오기: `C:\Program Files\SANscreen\java64\bin\keytool.exe -importcert -keystore "C:\Program Files\SANscreen\wildfly\standalone\configuration\server.trustore" -file "C:\<intermediate_certificate>.cer" -trustcacerts -alias "alias_name"`
+
모든 중간 인증서에 대해 이 단계를 반복합니다.

. 이 예제와 일치하도록 LDAP에 도메인을 지정합니다.


. 서버를 다시 시작합니다.

