---
permalink: config-admin/host-configuration-for-smart-card-and-certificate-login-dwh.html 
sidebar: sidebar 
keywords:  
summary: '스마트 카드\(CAC\) 및 인증서 로그인을 지원하도록 OnCommand Insight 데이터 웨어하우스 구성을 수정해야 합니다.' 
---
= 스마트 카드 및 인증서 로그인을 위한 데이터 웨어하우스 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스마트 카드(CAC) 및 인증서 로그인을 지원하도록 OnCommand Insight 데이터 웨어하우스 구성을 수정해야 합니다.



== 시작하기 전에

* 시스템에서 LDAP를 활성화해야 합니다.
* LDAP입니다 `User principal account name` 속성은 사용자의 정부 ID 번호가 포함된 LDAP 필드와 일치해야 합니다.
+
정부에서 발급한 CAC에 저장된 일반 이름(CN)은 일반적으로 다음과 같은 형식입니다. `first.last.ID`. 와 같은 일부 LDAP 필드의 경우 `sAMAccountName`, 이 형식은 너무 깁니다. 이러한 필드의 경우 OnCommand Insight는 cns에서 ID 번호만 추출합니다.



[NOTE]
====
최신 CAC 및 인증서 지침은 다음 기술 자료 문서를 참조하십시오(Support login required).

* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_configure_Common_Access_Card_(CAC)_authentication_for_NetApp_OnCommand_Insight["OnCommand Insight에 대한 CAC(Common Access Card) 인증을 구성하는 방법"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_configure_Common_Access_Card_(CAC)_authentication_for_NetApp_OnCommand_Insight_DataWarehouse["OnCommand Insight 데이터 웨어하우스에 대한 CAC(Common Access Card) 인증을 구성하는 방법"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_create_and_import_a_Certificate_Authority_(CA)_signed_certificate_into_OCI_and_DWH_7.3.X["CA(인증 기관) 서명 인증서를 만들어 OnComand Insight 및 OnCommand Insight 데이터 웨어하우스 7.3.x로 가져오는 방법"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_create_a_Self_Signed_Certificate_within_OnCommand_Insight_7.3.X_installed_on_a_Windows_Host["Windows 호스트에 설치된 OnCommand Insight 7.3.X 내에서 자체 서명된 인증서를 만드는 방법"]
* https://kb.netapp.com/Advice_and_Troubleshooting/Data_Infrastructure_Management/OnCommand_Suite/How_to_import_a_Cognos_Certificate_Authority_(CA)_signed_certificate_into_DWH_7.3.3_and_later["Cognos CA(인증 기관) 서명 인증서를 OnCommand Datawarehouse 7.3.3 이상으로 가져오는 방법"]


====


== 단계

. regedit를 사용하여 의 레지스트리 값을 수정합니다 `HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Apache Software Foundation\Procrun2.0\SANscreen Server\Parameters\Java`
+
.. jvm_option을 변경합니다 `-DclientAuth=false` 를 선택합니다 `-DclientAuth=true`.


+
Linux의 경우 를 수정합니다 `clientAuth` 매개 변수 in `/opt/netapp/oci/scripts/wildfly.server`

. CA(인증 기관)를 데이터 웨어하우스 trustore에 추가합니다.
+
.. 명령 창에서 로 이동합니다 `..\SANscreen\wildfly\standalone\configuration`.
.. 를 사용합니다 `keytool` 신뢰할 수 있는 CA를 나열하는 유틸리티: `C:\Program Files\SANscreen\java64\bin\keytool.exe -list -keystore server.trustore -storepass changeit`
+
각 줄의 첫 번째 단어는 CA 별칭을 나타냅니다.

.. 필요한 경우 CA 인증서 파일(일반적으로 A)을 제공합니다 `.pem` 파일. 데이터 웨어하우스 신뢰할 수 있는 CA와 함께 고객의 CA를 포함하려면 을 참조하십시오 `..\SANscreen\wildfly\standalone\configuration` 를 사용합니다 `keytool` 가져오기 명령: `C:\Program Files\SANscreen\java64\bin\keytool.exe -importcert -keystore server.trustore -alias my_alias -file 'path/to/my.pem' -v -trustcacerts`
+
my_alias는 일반적으로 에서 CA를 쉽게 식별하는 별칭입니다``keytool -list`` 작동.



. OnCommand Insight 서버에서 를 클릭합니다 `wildfly/standalone/configuration/standalone-full.xml` 에서 verify-client를 "requested"로 업데이트하여 파일을 수정해야 합니다 ``/subsystem=undertow/server=default-server/https-listener=default-https``CAC 활성화 Insight 서버에 로그인하고 적절한 명령을 실행합니다.
+
|===


| OS | 스크립트 


 a| 
Windows
 a| 
<install dir>\SANscreen\Wildlfly\bin\enableCACforRemoteEJB.bat 을 참조하십시오



 a| 
리눅스
 a| 
/opt/netapp/OCI/Wildlfly/bin/enableCACforRemoteEJB.sh 을 참조하십시오

|===
+
스크립트를 실행한 후 다음 단계로 진행하기 전에 Wildlfly 서버의 재로드가 완료될 때까지 기다립니다.

. OnCommand Insight 서버를 다시 시작합니다.

