---
permalink: config-admin/how-annotations-are-assigned.html 
sidebar: sidebar 
keywords:  
summary: 주석 규칙을 사용하여 수동으로 또는 자동으로 주석을 지정할 수 있습니다. 또한 OnCommand Insight는 자산 취득 및 상속에 대한 일부 주석을 자동으로 할당합니다. 자산에 할당한 주석은 자산 페이지의 사용자 데이터 섹션에 표시됩니다. 
---
= 주석 지정 방법
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
주석 규칙을 사용하여 수동으로 또는 자동으로 주석을 지정할 수 있습니다. 또한 OnCommand Insight는 자산 취득 및 상속에 대한 일부 주석을 자동으로 할당합니다. 자산에 할당한 주석은 자산 페이지의 사용자 데이터 섹션에 표시됩니다.

주석은 다음과 같은 방법으로 지정됩니다.

* 주석을 자산에 수동으로 지정할 수 있습니다.
+
주석을 자산에 직접 지정하면 주석이 자산 페이지에 일반 텍스트로 표시됩니다. 수동으로 할당된 주석은 항상 주석 규칙에 의해 상속되거나 할당된 주석보다 우선합니다.

* 동일한 유형의 자산에 주석을 자동으로 할당하는 주석 규칙을 생성할 수 있습니다.
+
주석이 규칙별로 할당된 경우 Insight는 자산 페이지의 주석 이름 옆에 규칙 이름을 표시합니다.

* Insight는 계층 레벨을 스토리지 계층 모델과 자동으로 연결하여 자산 구입 시 리소스에 스토리지 주석을 신속하게 할당할 수 있습니다.
+
특정 스토리지 리소스는 사전 정의된 계층(계층 1 및 계층 2)과 자동으로 연결됩니다. 예를 들어 Symmetrix 스토리지 계층은 Symmetrix 및 VMAX 제품군을 기반으로 하며 계층 1과 연결됩니다. 계층 요구 사항에 맞게 기본값을 변경할 수 있습니다. 주석을 Insight(예: 계층)에 할당하면 자산 페이지의 주석 이름 위에 커서를 놓으면 "시스템 정의"가 표시됩니다.

* 일부 리소스(자산의 하위 항목)는 자산(상위)에서 사전 정의된 계층 주석을 파생시킬 수 있습니다.
+
예를 들어, 주석을 스토리지에 할당할 경우 계층 주석은 모든 스토리지 풀, 내부 볼륨, 볼륨, Qtree 및 스토리지에 속한 공유에 의해 파생됩니다. 스토리지의 내부 볼륨에 다른 주석이 적용되는 경우 주석은 이후에 모든 볼륨, qtree 및 공유에 의해 파생됩니다. 자산 페이지의 주석 이름 옆에 "Deribed"가 나타납니다.


