---
permalink: config-admin/hpe-nimble-data-source.html 
sidebar: sidebar 
keywords:  
summary: HPE Nimble 데이터 수집기는 HPE Nimble 스토리지 어레이에 대한 인벤토리 및 성능 데이터를 지원합니다. 
---
= HPE Nimble 데이터 소스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
HPE Nimble 데이터 수집기는 HPE Nimble 스토리지 어레이에 대한 인벤토리 및 성능 데이터를 지원합니다.



== 용어

OnCommand Insight는 HPE Nimble 데이터 소스에서 다음 인벤토리 정보를 수집합니다. Insight에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 소스를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

|===


| 공급업체/모델 기간 | Insight 용어입니다 


 a| 
스토리지
 a| 
스토리지



 a| 
디스크
 a| 
디스크



 a| 
수영장
 a| 
스토리지 풀



 a| 
볼륨
 a| 
볼륨



 a| 
이니시에이터
 a| 
스토리지 호스트 별칭입니다



 a| 
컨트롤러
 a| 
스토리지 노드



 a| 
Fibre Channel 인터페이스
 a| 
컨트롤러

|===
[NOTE]
====
이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 소스의 모든 경우를 나타내는 것은 아닙니다.

====


== 요구 사항

* 스토리지를 설치하고 구성해야 하며 FQDN(정규화된 도메인 이름) 또는 스토리지 관리 IP 주소를 통해 클라이언트에서 연결할 수 있어야 합니다.
* 스토리지에서 NimbleOS 2.3.x 이상을 실행해야 합니다.
* 어레이에 대한 유효한 사용자 이름과 암호가 있어야 합니다.
* 포트 5392가 어레이에서 열려 있어야 합니다.




== 구성

|===


| * 필드 * | * 설명 * 


 a| 
스토리지 관리 IP 주소입니다
 a| 
FQDN(정규화된 도메인 이름) 또는 스토리지 관리 IP 주소입니다.



 a| 
사용자 이름
 a| 
Nimble 스토리지의 사용자 이름입니다



 a| 
암호
 a| 
Nimble 스토리지의 암호입니다

|===


== 고급 구성

|===


| * 필드 * | * 설명 * 


 a| 
포트
 a| 
Nimble REST API에서 사용하는 포트입니다. 기본값은 5392입니다.



 a| 
재고 폴링 간격(분)
 a| 
재고 조사 간격(기본값: 60분)

|===
참고: 기본 성능 폴링 간격은 300초이며 변경할 수 없습니다. Nimble에서 지원하는 유일한 간격입니다.
