---
permalink: config-admin/ibm-svc-ssh-data-source.html 
sidebar: sidebar 
keywords:  
summary: IBM SVC 데이터 소스는 SSH를 사용하여 인벤토리 및 성능 데이터를 수집하여 SVC 운영 체제를 실행하는 다양한 디바이스를 지원합니다. 지원되는 디바이스 목록에는 SVC, V7000, V5000 및 V3700과 같은 모델이 포함됩니다. 지원되는 모델 및 펌웨어 버전은 Insight 데이터 소스 지원 매트릭스를 참조하십시오. 
---
= IBM SVC 데이터 소스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
IBM SVC 데이터 소스는 SSH를 사용하여 인벤토리 및 성능 데이터를 수집하여 SVC 운영 체제를 실행하는 다양한 디바이스를 지원합니다. 지원되는 디바이스 목록에는 SVC, V7000, V5000 및 V3700과 같은 모델이 포함됩니다. 지원되는 모델 및 펌웨어 버전은 Insight 데이터 소스 지원 매트릭스를 참조하십시오.



== 용어

OnCommand Insight는 IBM SVC 데이터 소스에서 다음 인벤토리 정보를 가져옵니다. Insight에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 소스를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

|===


| 공급업체/모델 기간 | Insight 용어입니다 


 a| 
드라이브
 a| 
디스크



 a| 
클러스터
 a| 
스토리지



 a| 
노드
 a| 
스토리지 노드



 a| 
Mdisk 그룹
 a| 
스토리지 풀



 a| 
vDisk를 선택합니다
 a| 
볼륨



 a| 
Mdisk
 a| 
백엔드 LUN

|===
[NOTE]
====
이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 소스의 모든 경우를 나타내는 것은 아닙니다.

====


== 재고 요건

* 각 SVC 클러스터의 IP 주소입니다
* 포트 22를 사용할 수 있습니다
* Insight에서 생성하거나 이미 SVC에서 사용 중인 키 쌍을 재사용하는 공개 키 및 개인 키 쌍
+
기존 키 쌍을 재사용하는 경우 Putty 형식에서 OpenSSH 형식으로 변환해야 합니다.

* SVC 클러스터에 설치된 공개 키
* 개인 키는 데이터 소스에서 식별되어야 합니다
* 액세스 검증: 열기 `ssh` 개인 키를 사용하여 SVC 클러스터에 대한 세션입니다


[NOTE]
====
타사 소프트웨어를 설치할 필요가 없습니다.

====


== 성능 요구사항

* SVC 콘솔은 모든 SVC 클러스터에 필수이며 SVC 검색 기반 패키지에 필요합니다.
* 관리 액세스 수준은 클러스터 노드에서 구성 노드로 성능 데이터 파일을 복사하는 경우에만 필요합니다.
+
[NOTE]
====
SVC Foundation Discovery Package에 이 액세스 수준이 필요하지 않으므로 SVC Foundation 사용자가 정상적으로 작동하지 않을 수 있습니다.

====
* 포트 22가 필요합니다
* 이 사용자에 대해 개인 및 공용 SSH 키를 생성하고 개인 키를 저장하여 획득 장치에서 액세스할 수 있도록 해야 합니다. SVC Foundation 사용자에게 적절한 권한이 있는 경우 동일한 사용자 및 키가 작동합니다. 인벤토리 및 성능 데이터에 동일한 SSH 키를 사용할 수 있습니다.
* SSH를 통해 SVC 클러스터에 접속하고 다음을 실행하여 데이터 수집을 활성화합니다. `svctask startstats -interval 1`
+
[NOTE]
====
또는 SVC 관리 사용자 인터페이스를 사용하여 데이터 수집을 사용하도록 설정합니다.

====




== 상위 일련 번호가 설명되었습니다

일반적으로 Insight는 스토리지 어레이의 일련 번호 또는 개별 스토리지 노드의 일련 번호를 보고할 수 있습니다. 그러나 일부 스토리지 어레이 아키텍처는 이 문제에 완전히 부합되지 않습니다. SVC 클러스터는 1-4개의 어플라이언스로 구성될 수 있으며, 각 어플라이언스에는 2개의 노드가 있습니다. 어플라이언스 자체에 일련 번호가 있는 경우 해당 일련 번호는 클러스터나 노드의 일련 번호가 아닙니다.

개별 노드가 대규모 클러스터의 일부인 중간 어플라이언스/엔클로저 내에 있는 경우 스토리지 노드 객체의 "상위 일련 번호" 속성이 IBM SVC 스토리지에 맞게 채워집니다.



== 구성

|===


| * 필드 * | * 설명 * 


 a| 
클러스터 IP입니다
 a| 
SVC 스토리지에 대한 정규화된 도메인 이름의 IP 주소입니다



 a| 
자격 증명 유형을 지정하려면 '암호' 또는 'OpenSSH 키 파일'을 선택하십시오
 a| 
SSH를 통해 장치에 연결하는 데 사용되는 자격 증명 유형입니다



 a| 
재고 사용자 이름입니다
 a| 
SVC CLI의 사용자 이름입니다



 a| 
재고 암호
 a| 
SVC CLI의 암호입니다



 a| 
재고 개인 키에 대한 전체 경로
 a| 
인벤토리 개인 키 파일의 전체 경로입니다



 a| 
성능 사용자 이름입니다
 a| 
성능 수집을 위한 SVC CLI의 사용자 이름입니다



 a| 
성능 암호
 a| 
성능 수집을 위한 SVC CLI의 암호입니다



 a| 
성능 개인 키로 가는 전체 경로
 a| 
성능 개인 키 파일의 전체 경로입니다

|===


== 고급 구성

|===


| * 필드 * | * 설명 * 


 a| 
재고 폴링 간격(분)
 a| 
재고 조사 간격(기본값 40분)



 a| 
장치 제외
 a| 
인벤토리 수집에서 제외할 장치 ID의 쉼표로 구분된 목록입니다



 a| 
SSH 프로세스 대기 시간 초과(초)
 a| 
SSH 프로세스 시간 초과(기본값 200초)



 a| 
성능 폴링 간격(초)
 a| 
성능 폴링 간격(기본값 300초)



 a| 
성능 제외 장치
 a| 
성능 컬렉션에서 제외할 장치 ID의 쉼표로 구분된 목록입니다



 a| 
성능 SSH 프로세스 대기 시간 초과(초)
 a| 
SSH 프로세스 시간 초과(기본값 200초)



 a| 
덤프된 통계 파일 정리
 a| 
덤프된 통계 파일을 정리하려면 선택합니다

|===