---
permalink: config-admin/ibm-powervm-ssh-data-source.html 
sidebar: sidebar 
keywords:  
summary: 'IBM PowerVM\(SSH\) 데이터 소스는 하드웨어 관리 콘솔 \(HMC\)에서 관리하는 IBM POWER 하드웨어 인스턴스에서 실행되는 가상 파티션에 대한 정보를 수집합니다. 구성의 경우 이 데이터 원본에서는 SSH를 통해 HMC에 로그인하기 위한 사용자 이름과 HMC 구성에 대한 보기 수준 권한이 필요합니다.' 
---
= IBM PowerVM 데이터 소스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
IBM PowerVM(SSH) 데이터 소스는 HMC(하드웨어 관리 콘솔)에서 관리하는 IBM POWER 하드웨어 인스턴스에서 실행되는 가상 파티션에 대한 정보를 수집합니다. 구성의 경우 이 데이터 원본에서는 SSH를 통해 HMC에 로그인하기 위한 사용자 이름과 HMC 구성에 대한 보기 수준 권한이 필요합니다.



== 용어

OnCommand Insight는 IBM PowerVM 데이터 소스에서 다음 인벤토리 정보를 가져옵니다. Insight에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 소스를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

|===


| 공급업체/모델 기간 | Insight 용어입니다 


 a| 
hdisk
 a| 
가상 디스크



 a| 
관리 대상 시스템
 a| 
호스트



 a| 
LPAR, VIO 서버
 a| 
가상 머신



 a| 
볼륨 그룹
 a| 
데이터 저장소



 a| 
물리적 볼륨
 a| 
LUN을 클릭합니다

|===
[NOTE]
====
이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 소스의 모든 경우를 나타내는 것은 아닙니다.

====


== 요구 사항

* HMC(Hardware Management Console)의 IP 주소
* SSH를 통해 HMC에 대한 액세스를 제공하는 사용자 이름 및 암호
* 포트 요구 사항 SSH-22
* 모든 관리 시스템 및 논리 파티션 보안 도메인에 대한 권한을 봅니다
+
또한 HMC 구성에 대한 보기 권한과 HMC 콘솔 보안 그룹화를 위한 VPD 정보를 수집할 수 있는 기능도 있어야 합니다. 또한 사용자는 논리 파티션 보안 그룹화를 통해 가상 IO 서버 명령 액세스를 허용해야 합니다. 작업자의 역할에서 시작하여 모든 역할을 제거하는 것이 가장 좋습니다. HMC의 읽기 전용 사용자는 AIX 호스트에서 프록시 명령을 실행할 권한이 없습니다.

* IBM 모범 사례는 두 개 이상의 HMCS를 통해 디바이스를 모니터링하는 것입니다. 이렇게 하면 OnCommand Insight에서 중복된 디바이스를 보고할 수 있으므로 이 데이터 수집기의 고급 구성에 있는 "장치 제외" 목록에 중복 디바이스를 추가하는 것이 좋습니다.




== 구성

|===


| * 필드 * | * 설명 * 


 a| 
HMC(Hardware Management Console) 주소입니다
 a| 
PowerVM 하드웨어 관리 콘솔의 IP 주소 또는 정규화된 도메인 이름입니다



 a| 
HMC 사용자
 a| 
하드웨어 관리 콘솔의 사용자 이름입니다



 a| 
암호
 a| 
하드웨어 관리 콘솔에 사용되는 암호입니다

|===


== 고급 구성

|===


| * 필드 * | * 설명 * 


 a| 
재고 폴링 간격(분)
 a| 
재고 조사 간격(기본값 20분)



 a| 
SSH 포트
 a| 
SSH에서 PowerVM에 사용되는 포트입니다



 a| 
SSH 프로세스 대기 시간 초과(초)
 a| 
SSH 프로세스 시간 초과(기본값 600초)



 a| 
재시도 횟수
 a| 
인벤토리 재시도 횟수입니다



 a| 
장치 제외
 a| 
제외할 장치 ID 또는 표시 이름의 쉼표로 구분된 목록입니다

|===