---
permalink: config-admin/ibm-ds-cli-data-source.html 
sidebar: sidebar 
keywords:  
summary: 'IBM DS\(CLI\) 데이터 소스는 DS6xxx 및 DS8xxx 디바이스만 지원합니다. DS3xxx, DS4xxx 및 DS5xxx 장치는 NetApp E-Series 데이터 소스에서 지원됩니다. 지원되는 모델 및 펌웨어 버전은 Insight 데이터 소스 지원 매트릭스를 참조하십시오.' 
---
= IBM DS 데이터 소스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
IBM DS(CLI) 데이터 소스는 DS6xxx 및 DS8xxx 디바이스만 지원합니다. DS3xxx, DS4xxx 및 DS5xxx 장치는 NetApp E-Series 데이터 소스에서 지원됩니다. 지원되는 모델 및 펌웨어 버전은 Insight 데이터 소스 지원 매트릭스를 참조하십시오.



== 용어

OnCommand Insight는 IBM DS 데이터 소스에서 다음 인벤토리 정보를 가져옵니다. Insight에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 소스를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

|===


| 공급업체/모델 기간 | Insight 용어입니다 


 a| 
디스크 드라이브 모듈
 a| 
디스크



 a| 
스토리지 이미지
 a| 
스토리지



 a| 
익스텐트 풀
 a| 
스토리지 풀



 a| 
고정 블록 볼륨
 a| 
볼륨

|===
[NOTE]
====
이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 소스의 모든 경우를 나타내는 것은 아닙니다.

====


== 요구 사항

* 각 DS 배열의 IP 주소입니다
* 스토리지 표시 이름은 선택 사항이며 외관만 가능합니다
* 각 DS 어레이에 대한 읽기 전용 사용자 이름 및 암호
* Insight 서버에 설치된 타사 소프트웨어: IBM dscli
* 액세스 검증: 실행 `dscli` 사용자 이름 및 암호를 사용하는 명령입니다
* 포트 요구 사항: 80, 443 및 1750




== 구성

|===


| 필드에 입력합니다 | 설명 


 a| 
DS 스토리지
 a| 
DS Storage Host의 IP 주소 또는 정규화된 도메인 이름입니다



 a| 
사용자 이름
 a| 
DS CLI에 사용되는 이름입니다



 a| 
암호
 a| 
DS CLI에 사용되는 암호입니다



 a| 
실행 파일 dscli.exe 경로
 a| 
에 대한 전체 경로입니다 ``dscli.exe``유틸리티.

|===


== 고급 구성

|===


| 필드에 입력합니다 | 설명 


 a| 
재고 폴링 간격(분)
 a| 
재고 조사 간격(기본값 40분)



 a| 
스토리지 표시 이름
 a| 
IBM DS 스토리지 어레이의 이름입니다



 a| 
재고 제외 장치
 a| 
인벤토리 수집에서 제외할 장치 일련 번호의 쉼표로 구분된 목록입니다



 a| 
성능 폴링 간격(초)
 a| 
성능 폴링 간격(기본값 300초)



 a| 
성능 필터 유형
 a| 
Include(포함): 목록의 장치에서만 수집된 데이터입니다. 제외: 이러한 장치에서 데이터가 수집되지 않습니다



 a| 
성능 필터 장치 목록
 a| 
성능 컬렉션에서 포함하거나 제외할 장치 ID의 쉼표로 구분된 목록입니다

|===