---
permalink: config-admin/ibm-xiv-cli-data-source.html 
sidebar: sidebar 
keywords:  
summary: 'IBM XIV\(CLI\) 데이터 소스 인벤토리는 XIV 명령줄 인터페이스를 사용하여 수행됩니다. XIV 성능은 포트 5989에서 SMI-S 공급자를 실행하는 XIV 스토리지에 대한 SMI-S 호출을 통해 구현됩니다.' 
---
= IBM XIV 데이터 소스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
IBM XIV(CLI) 데이터 소스 인벤토리는 XIV 명령줄 인터페이스를 사용하여 수행됩니다. XIV 성능은 포트 5989에서 SMI-S 공급자를 실행하는 XIV 스토리지에 대한 SMI-S 호출을 통해 구현됩니다.



== 용어

OnCommand Insight는 IBM XIV 데이터 소스에서 다음 인벤토리 정보를 가져옵니다. Insight에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 소스를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

|===


| 공급업체/모델 기간 | Insight 용어입니다 


 a| 
디스크
 a| 
디스크



 a| 
스토리지 시스템
 a| 
스토리지



 a| 
스토리지 풀
 a| 
스토리지 풀



 a| 
볼륨
 a| 
볼륨

|===
[NOTE]
====
이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 소스의 모든 경우를 나타내는 것은 아닙니다.

====


== 요구 사항

* 포트 요구 사항: TCP 포트 7778
* XIV 관리 인터페이스의 IP 주소입니다
* 읽기 전용 사용자 이름 및 암호
* XIV CLI는 Insight 서버 또는 RAU에 설치해야 합니다
* 액세스 검증: 사용자 이름과 암호를 사용하여 Insight 서버에서 XIV 사용자 인터페이스에 로그인합니다.




== 구성

|===


| * 필드 * | * 설명 * 


 a| 
IP 주소
 a| 
XIV 스토리지의 IP 주소 또는 정규화된 도메인 이름입니다



 a| 
사용자 이름
 a| 
XIV 스토리지의 사용자 이름입니다



 a| 
암호
 a| 
XIV 스토리지의 암호입니다



 a| 
XIV CLI 디렉토리의 전체 경로입니다
 a| 
XIV CLI 디렉토리의 전체 경로입니다

|===


== 고급 구성

|===


| * 필드 * | * 설명 * 


 a| 
재고 폴링 간격(분)
 a| 
재고 조사 간격(기본값 40분)



 a| 
CLI 프로세스 대기 시간 초과(ms)
 a| 
CLI 프로세스 시간 초과(기본 7200000ms)



 a| 
SMI-S 호스트 IP입니다
 a| 
SMI-S Provider 호스트의 IP 주소입니다



 a| 
SMI-S 포트
 a| 
SMI-S Provider 호스트에서 사용하는 포트입니다



 a| 
SMI-S 프로토콜
 a| 
SMI-S 공급자에 연결하는 데 사용되는 프로토콜입니다



 a| 
SMI-S 네임스페이스
 a| 
SMI-S 네임스페이스



 a| 
사용자 이름
 a| 
SMI-S Provider 호스트의 사용자 이름입니다



 a| 
암호
 a| 
SMI-S Provider 호스트의 암호입니다



 a| 
성능 폴링 간격(초)
 a| 
성능 폴링 간격(기본값 300초)



 a| 
SMI-S 연결 재시도 횟수
 a| 
SMI-S 연결 재시도 횟수입니다

|===