---
permalink: config-admin/importing-data-sources-from-a-spreadsheet.html 
sidebar: sidebar 
keywords:  
summary: 스프레드시트에서 여러 데이터 원본을 OnCommand Insight로 가져올 수 있습니다. 이 기능은 검색 장치를 스프레드시트에 이미 유지 관리하는 경우에 유용할 수 있습니다. 이 프로세스는 새 데이터 원본을 추가하지만 기존 데이터 원본을 업데이트하는 데 사용할 수는 없습니다. 
---
= 스프레드시트에서 데이터 원본을 가져옵니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스프레드시트에서 여러 데이터 원본을 OnCommand Insight로 가져올 수 있습니다. 이 기능은 검색 장치를 스프레드시트에 이미 유지 관리하는 경우에 유용할 수 있습니다. 이 프로세스는 새 데이터 원본을 추가하지만 기존 데이터 원본을 업데이트하는 데 사용할 수는 없습니다.



== 이 작업에 대해

OnCommand Insight에는 데이터 원본을 만드는 데 도움이 되는 스프레드시트가 포함되어 있습니다. 이 스프레드시트에는 다음과 같은 속성이 있습니다.

* 스프레드시트는 Microsoft Excel 2003 이상에서 사용할 수 있습니다.
* 각 탭에는 데이터 소스 유형(예: Brocade SSH/CLI)이 하나씩 있습니다.
* 각 행은 만들 새 데이터 소스의 인스턴스를 나타냅니다.


스프레드시트에는 OnCommand Insight에서 새 데이터 원본을 만드는 매크로가 포함되어 있습니다.



== 단계

. 에서 스프레드시트를 찾습니다 `<install_directory>/SANscreen/acq/bin/acqcli/SiteSurvey_DataSourceImporter_w_Macro.zip`.
. 스프레드시트에서 색이 있는 셀에 데이터 원본 정보를 입력합니다.
. 빈 행을 삭제합니다.
. 스프레드시트에서 을 실행합니다 `CreateDataSources` 데이터 원본을 만드는 매크로
. 자격 증명을 묻는 메시지가 나타나면 OnCommand Insight 서버 관리 사용자 이름과 암호를 입력합니다.
+
결과는 획득 로그에 기록됩니다.

. 현재 매크로를 실행 중인 컴퓨터에 OnCommand Insight가 설치되어 있는지 묻는 메시지가 나타납니다.
+
다음 중 하나를 선택합니다.

+
** 아니요: OnCommand Insight 시스템에서 실행해야 하는 배치 파일을 만들 경우 "아니요"를 선택합니다. 설치 디렉토리에서 이 배치 파일을 실행합니다.
** 예: OnCommand Insight가 이미 설치되어 있고 데이터 소스 정보를 생성하는 데 추가 단계가 필요하지 않은 경우 "예"를 선택합니다.


. 데이터 소스가 추가되었는지 확인하려면 브라우저에서 Insight를 엽니다.
. Insight 도구 모음에서 * Admin * 을 클릭합니다.
. 가져온 데이터 원본에 대한 데이터 원본 목록을 확인합니다.

