---
permalink: config-admin/importing-and-exporting-user-data.html 
sidebar: sidebar 
keywords:  
summary: 가져오기 및 내보내기 기능을 사용하여 주석, 주석 규칙, 쿼리, 성능 정책 및 사용자 지정 대시보드를 하나의 파일로 내보낼 수 있습니다. 그런 다음 이 파일을 다른 OnCommand Insight 서버로 가져올 수 있습니다. 
---
= 사용자 데이터 가져오기 및 내보내기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
가져오기 및 내보내기 기능을 사용하여 주석, 주석 규칙, 쿼리, 성능 정책 및 사용자 지정 대시보드를 하나의 파일로 내보낼 수 있습니다. 그런 다음 이 파일을 다른 OnCommand Insight 서버로 가져올 수 있습니다.

내보내기 및 가져오기 기능은 동일한 버전의 OnCommand Insight를 실행하는 서버 간에만 지원됩니다.

사용자 데이터를 내보내거나 가져오려면 * Admin * 을 클릭하고 * Setup * 을 선택한 다음 * Import/Export user data * 탭을 선택합니다.

가져오는 개체와 개체 형식에 따라 가져오기 작업 중에 데이터가 추가, 병합 또는 교체됩니다.

* 주석 유형
+
** 대상 시스템에 동일한 이름의 주석이 없는 경우 주석을 추가합니다.
** 주석 유형이 목록이고 이름이 같은 주석이 대상 시스템에 있는 경우 주석을 병합합니다.
** 주석 유형이 목록 이외의 주석 유형이고 대상 시스템에 동일한 이름의 주석이 있는 경우 주석을 대체합니다.


+
[NOTE]
====
이름이 같지만 유형이 다른 주석이 대상 시스템에 있는 경우 가져오기에 실패합니다. 개체가 실패한 주석에 따라 달라지는 경우 이러한 개체는 부정확하거나 원치 않는 정보를 표시할 수 있습니다. 가져오기 작업이 완료된 후에는 모든 주석 종속성을 확인해야 합니다.

====
* 주석 규칙
+
** 대상 시스템에 같은 이름의 주석 규칙이 없으면 주석 규칙을 추가합니다.
** 주석 규칙이 대상 시스템에 동일한 이름의 규칙이 있는 경우 주석 규칙을 바꿉니다.


+
[NOTE]
====
주석 규칙은 쿼리와 주석 모두에 따라 달라집니다. 가져오기 작업이 완료된 후 모든 주석 규칙이 정확한지 확인해야 합니다.

====
* 정책
+
** 대상 시스템에 동일한 이름의 정책이 없는 경우 정책을 추가합니다.
** 대상 시스템에 동일한 이름의 정책이 있는 경우 정책을 교체합니다.


+
[NOTE]
====
가져오기 작업이 완료된 후 정책이 순서를 벗어났을 수 있습니다. 가져온 후에는 정책 순서를 확인해야 합니다. 주석이 잘못된 경우 주석에 종속된 정책이 실패할 수 있습니다. 가져온 후에는 모든 주석 종속성을 확인해야 합니다.

를 누릅니다

====
* 쿼리
+
** 대상 시스템에 동일한 이름의 쿼리가 없는 경우 쿼리를 추가합니다.
** 쿼리의 리소스 유형이 다른 경우에도 대상 시스템에 동일한 이름의 쿼리가 있는 경우 쿼리를 바꿉니다.


+
[NOTE]
====
쿼리의 리소스 유형이 다른 경우 가져오기 후 해당 쿼리를 사용하는 대시보드 위젯에 원치 않는 결과 또는 잘못된 결과가 표시될 수 있습니다. 가져오기 후 모든 쿼리 기반 위젯의 정확성을 확인해야 합니다. 주석이 잘못된 경우 주석에 종속된 쿼리가 실패할 수 있습니다. 가져온 후에는 모든 주석 종속성을 확인해야 합니다.

를 누릅니다

====
* 대시보드
+
** 타겟 시스템에 동일한 이름의 대시보드가 없는 경우 대시보드를 추가합니다.
** 쿼리의 리소스 유형이 다른 경우에도 대상 시스템에 동일한 이름의 대시보드가 있는 경우 대시보드를 대체합니다.


+
[NOTE]
====
가져오기 후 대시보드의 모든 쿼리 기반 위젯이 정확한지 확인해야 합니다. 소스 서버에 동일한 이름의 대시보드가 여러 개 있는 경우 모두 내보내집니다. 그러나 첫 번째 서버만 대상 서버로 가져옵니다. 가져오는 동안 오류를 방지하려면 대시보드를 내보내기 전에 고유한 이름을 지정해야 합니다.

를 누릅니다

====

