---
permalink: config-admin/locating-required-information-for-new-disk-model.html 
sidebar: sidebar 
keywords:  
summary: 디스크 모델 정보를 찾으려면 공급업체 및 모델 번호를 확인하고 인터넷 검색을 실행합니다. 
---
= 새 디스크 모델에 필요한 정보 찾기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
디스크 모델 정보를 찾으려면 공급업체 및 모델 번호를 확인하고 인터넷 검색을 실행합니다.



== 이 작업에 대해

디스크 모델 정보는 인터넷 검색을 실행하는 것처럼 간단하게 찾을 수 있습니다. 검색하기 전에 공급업체 이름과 디스크 모델 번호를 기록해 두십시오.



== 단계

. 공급업체의 데이터 시트 및/또는 드라이브 설치 설명서를 찾으려면 공급업체, 모델 및 문서 유형 ""PDF"에 대한 고급 인터넷 검색을 사용하는 것이 좋습니다. 이러한 데이터 시트는 일반적으로 공급업체 디스크 정보의 가장 좋은 소스입니다.
. 공급업체 사양이 전체 모델 번호를 기반으로 필요한 모든 정보를 제공하는 것은 아닙니다. 공급업체 사이트에서 모델 번호 문자열의 여러 부분을 검색하여 모든 정보를 찾는 것이 유용합니다.
. 디스크 공급업체 이름, 전체 모델 번호, 디스크 크기 및 속도 및 인터페이스 유형을 찾습니다. OnCommand Insight에서 새 디스크 모델을 정의하려면 다음 표를 참조하십시오.
+
|===


| 이 필드의 경우: | 다음 중 무엇입니까? | 입력 내용: 


 a| 
모델 번호(aka Key)
 a| 
필수 요소입니다
 a| 



 a| 
공급업체
 a| 
필수 요소입니다
 a| 



 a| 
디스크 속도(RPM)
 a| 
필수 요소입니다
 a| 



 a| 
크기(GB)
 a| 
필수 요소입니다
 a| 



 a| 
인터페이스 유형(하나 선택)
 a| 
필수 요소입니다
 a| 
ATA, SATA, SATA2, SATA3, FC, SAS, FATA, SSD, 기타



 a| 
탐색 시간(ms)
 a| 
선택 사항
 a| 



 a| 
최대 전송 속도(MB/sec)입니다
 a| 
선택 사항
 a| 



 a| 
인터페이스 전송 속도(MB/sec)입니다
 a| 
선택 사항
 a| 



 a| 
공급업체/모델 정보 링크
 a| 
선택 사항이지만 권장됩니다
 a| 

|===
. 에 해당 정보를 입력합니다 `new_disk_models.txt` 파일. 을 참조하십시오 link:content-of-the-new-disk-models-txt-file.md#["new_disk_models.txt 파일의 내용입니다"] 형식, 순서 및 예제를 보려면

