---
permalink: config-admin/managing-insight.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight은 환경을 모니터링하여 위기 상황이 보고되기 전에 잠재적 문제를 조사할 수 있도록 합니다. 자산 대시보드는 요약 원형 차트, IOPS용 열 맵, 사용률이 가장 높은 10개의 스토리지 풀에 대한 대화형 차트를 제공합니다. 
---
= Insight 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight은 환경을 모니터링하여 위기 상황이 보고되기 전에 잠재적 문제를 조사할 수 있도록 합니다. 자산 대시보드는 요약 원형 차트, IOPS용 열 맵, 사용률이 가장 높은 10개의 스토리지 풀에 대한 대화형 차트를 제공합니다.



== 단계

. Insight** Assets Dashboard** 를 열고 커서를 원형 차트 위로 이동하여 다음 세 가지 차트의 자산 분포를 검토합니다.
+
** 공급업체별 용량 에는 각 공급업체의 총 스토리지 물리적 용량이 표시됩니다.
** 계층별 용량은 각 스토리지 계층에 대해 사용 가능한 총 용량을 보여 줍니다.
** 스위치 포트 원형 차트는 포트 제조업체를 표시하고 사용된 포트 비율을 표시합니다.


. 환경 관련 정보 * 를 보고 사용 중인 환경의 용량, 용량 효율성, 사용된 FC 리소스 및 가상 인프라 통계에 대한 정보를 확인하십시오.
. 스토리지 풀의 사용된 용량과 사용되지 않는 용량을 보려면 * 상위 10개 사용 풀 * 차트의 스토리지 풀 바 위에 커서를 놓습니다.
. 스토리지 IOP * 히트맵에서 큰 텍스트(자산에 문제가 있음을 나타냄)로 표시되는 자산 이름을 클릭하여 해당 자산의 현재 상태를 요약하는 페이지를 표시합니다.
. 자산 대시보드 * 의 오른쪽 아래 모서리에 있는 * 가상 머신 IOPS * 히트맵에서 큰 텍스트(자산에 문제가 있음을 나타냄)로 표시되는 자산 이름을 클릭하여 자산의 현재 상태를 요약하는 페이지를 표시합니다.
. Insight 도구 모음에서 * Admin * 을 클릭합니다.
. 빨간색 원으로 표시된 영역을 확인합니다.
+
OnCommand Insightfob UI에서는 잠재적인 문제가 빨간색 원으로 표시됩니다.

. 데이터 소스 * 를 클릭하여 모니터링된 모든 데이터 소스 목록을 검사합니다.
+
빨간색 원으로 고정된 메시지가 포함된 * Status * 열이 있는 데이터 소스를 검사하고, * Impact * 가 High 또는 Medium 으로 나열됩니다. 이러한 항목은 테이블 상단에 있습니다. 이러한 데이터 소스의 문제는 해결해야 하는 네트워크의 중요한 부분에 영향을 미칩니다.

. Insight를 실행하는 각 IP 주소의 상태를 확인하고 필요한 경우 획득 장치를 다시 시작하려면 * Acquisition Units * (획득 단위)를 클릭합니다
. Insight 서버의 상위 인스턴스 모니터링을 보려면 * 상태 * 를 클릭하십시오.

