---
permalink: config-admin/managing-security-on-an-rau.html 
sidebar: sidebar 
keywords: rekey 
summary: SecurityAdmin 도구를 사용하여 RA의 보안 옵션을 관리할 수 있습니다. 볼트 구성을 백업 또는 복원하거나 암호화 키를 변경하거나 획득 장치의 암호를 업데이트해야 할 수 있습니다. 
---
= RAU에 대한 보안 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
를 클릭합니다 `securityadmin` 도구를 사용하면 RA의 보안 옵션을 관리할 수 있습니다. 볼트 구성을 백업 또는 복원하거나 암호화 키를 변경하거나 획득 장치의 암호를 업데이트해야 할 수 있습니다.



== 이 작업에 대해

를 사용합니다 `securityadmin` 보안 관리 도구:

* 윈도우 - `C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat`
* Linux - `/bin/oci-securityadmin.sh`


Lau, RAU에 대한 보안 구성을 업데이트하는 한 가지 시나리오는 해당 사용자의 암호가 서버에서 변경된 경우 'acquisition' 사용자 암호를 업데이트하는 것입니다. 모든 RA와 Lau는 서버 '획득' 사용자의 암호와 동일한 암호를 사용하여 서버와 통신합니다.

[NOTE]
====

====
'acquisition' 사용자는 Insight 서버에만 있습니다. RAU 또는 Lau는 서버에 연결할 때 해당 사용자로 로그인합니다.

RAU에서 보안 옵션을 관리하려면 다음 단계를 따르십시오.



== 단계

. RAU를 실행 중인 서버에 원격 로그인을 수행한다
. 대화형 모드에서 보안 관리 도구를 시작합니다. `Windows - C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat -i``Linux - /bin/oci-securityadmin.sh -i`
+
시스템에서 로그인 자격 증명을 요청합니다.

. "Admin" 자격 증명이 있는 계정의 사용자 이름과 암호를 입력합니다.
+
RAU에 대한 메뉴가 표시됩니다.

+
** * 백업 *
+
모든 암호 및 키가 포함된 볼트의 백업 zip 파일을 작성하고 사용자가 지정한 위치 또는 다음 기본 위치에 파일을 배치합니다.

+
*** 윈도우 - `C:\Program Files\SANscreen\backup\vault`
*** Linux - `/var/log/netapp/oci/backup/vault`


** * 복원 *
+
작성된 볼트의 zip 백업을 복원합니다. 복원되면 모든 암호와 키는 백업 생성 시 기존 값으로 되돌려집니다.

+
[NOTE]
====
복원은 여러 서버의 암호와 키를 동기화하는 데 사용할 수 있습니다. 예를 들어 - 한 서버의 암호화 키 변경 - 볼트 백업 작성 - 두 번째 서버로 볼트 백업을 복원합니다

를 누릅니다

====
** * 암호화 키 변경 *
+
단말기 암호를 암호화 또는 해독하는 데 사용되는 RAU 암호화 키를 변경합니다.

+
[NOTE]
====
암호화 키를 변경할 때는 업그레이드 또는 설치 후 복원할 수 있도록 새 보안 구성을 백업해야 합니다.

====
** * 암호 업데이트 *
+
'촬영' 사용자 계정의 암호를 변경합니다.

+
[NOTE]
====
암호를 변경할 때 일부 계정을 동기화해야 합니다. 예를 들어, 서버에서 'acquisition' 사용자의 암호를 변경하는 경우 Lau, RAU 및 DWH에서 'acquisition' 사용자의 암호를 변경하여 일치시켜야 합니다. 또한 암호를 변경할 때는 업그레이드 또는 설치 후에 복원할 수 있도록 새 보안 구성을 백업해야 합니다.

====
** * 기본값으로 재설정 *
+
암호화 키 및 암호를 기본값으로 재설정합니다. 기본값은 설치 중에 제공되는 값입니다.

** * 종료 *
+
를 종료합니다 `securityadmin` 도구.




