---
permalink: config-admin/managing-security-on-the-insight-server.html 
sidebar: sidebar 
keywords:  
summary: SecurityAdmin 도구를 사용하면 Insight 서버의 보안 옵션을 관리할 수 있습니다. 보안 관리에는 암호 변경, 새 키 생성, 사용자가 만든 보안 구성 저장 및 복원, 기본 설정으로 구성 복원 등이 포함됩니다. 
---
= Insight 서버의 보안 관리
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
를 클릭합니다 `securityadmin` 도구를 사용하면 Insight 서버의 보안 옵션을 관리할 수 있습니다. 보안 관리에는 암호 변경, 새 키 생성, 사용자가 만든 보안 구성 저장 및 복원, 기본 설정으로 구성 복원 등이 포함됩니다.



== 이 작업에 대해

를 사용합니다 `securityadmin` 보안 관리 도구:

* 윈도우 - `C:\Program Files\SANscreen\securityadmin\bin\securityadmin.bat`
* Linux - `/bin/oci-securityadmin.sh`




== 단계

. Insight 서버에 원격 로그인을 수행합니다.
. 대화형 모드에서 보안 관리 도구를 시작합니다. `securityadmin -i`
+
시스템에서 로그인 자격 증명을 요청합니다.

. "Admin" 자격 증명이 있는 계정의 사용자 이름과 암호를 입력합니다.
. 서버 * 를 선택합니다.
+
다음 서버 구성 옵션을 사용할 수 있습니다.

+
** * 백업 *
+
모든 암호 및 키가 포함된 볼트의 백업 zip 파일을 작성하고 사용자가 지정한 위치 또는 다음 기본 위치에 파일을 배치합니다.

+
*** 윈도우 - `C:\Program Files\SANscreen\backup\vault`
*** Linux - `/var/log/netapp/oci/backup/vault`


** * 복원 *
+
작성된 볼트의 zip 백업을 복원합니다. 복원되면 모든 암호와 키는 백업 생성 시 기존 값으로 되돌려집니다.

+
[NOTE]
====
복원은 여러 서버의 암호와 키를 동기화하는 데 사용할 수 있습니다. 예를 들어 - 한 서버의 서버 암호화 키 변경 - 볼트 백업 작성 - 두 번째 서버로 볼트 백업을 복원합니다

를 누릅니다

====
** * 암호화 키 변경 *
+
프록시 사용자 암호, SMTP 사용자 암호, LDAP 사용자 암호 등을 암호화 또는 해독하는 데 사용되는 서버 암호화 키를 변경합니다.

+
[NOTE]
====
암호화 키를 변경할 때는 업그레이드 또는 설치 후 복원할 수 있도록 새 보안 구성을 백업해야 합니다.

====
** * 암호 업데이트 *
+
Insight에서 사용하는 내부 계정의 암호를 변경합니다. 다음 옵션이 표시됩니다.

+
*** _내부
*** 획득
*** Cognos_admin
*** DWh _ 내부
*** 호스트
*** 인벤토리
*** 루트




+
[NOTE]
====
암호를 변경할 때 일부 계정을 동기화해야 합니다. 예를 들어, 서버에서 'acquisition' 사용자의 암호를 변경하는 경우 Lau, RAU 및 DWH에서 'acquisition' 사용자의 암호를 변경하여 일치시켜야 합니다. 또한 암호를 변경할 때는 업그레이드 또는 설치 후에 복원할 수 있도록 새 보안 구성을 백업해야 합니다.

====
+
** * 기본값으로 재설정 *
+
키와 암호를 기본값으로 재설정합니다. 기본값은 설치 중에 제공되는 값입니다.

** * 종료 *
+
를 종료합니다 `securityadmin` 도구.



. 변경할 옵션을 선택하고 화면의 지시를 따릅니다.

