---
permalink: config-admin/metric-definitions.html 
sidebar: sidebar 
keywords:  
summary: 자산 페이지의 전문가 보기 섹션에는 자산에 대해 선택한 기간에 따라 몇 가지 메트릭이 표시됩니다. 각 메트릭은 자체 성능 차트에 표시됩니다. 보려는 데이터에 따라 차트에서 메트릭 및 관련 자산을 추가하거나 제거할 수 있습니다. 
---
= 전문가 뷰 메트릭 정의
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
자산 페이지의 전문가 보기 섹션에는 자산에 대해 선택한 기간에 따라 몇 가지 메트릭이 표시됩니다. 각 메트릭은 자체 성능 차트에 표시됩니다. 보려는 데이터에 따라 차트에서 메트릭 및 관련 자산을 추가하거나 제거할 수 있습니다.

|===


| 미터 | 설명 


 a| 
BB 크레딧 제로 Rx, Tx
 a| 
샘플링 기간 동안 수신/전송 버퍼 대 버퍼 크레딧 수가 0으로 전환된 횟수입니다. 이 메트릭은 제공할 크레딧이 없기 때문에 연결된 포트의 전송을 중지해야 하는 횟수를 나타냅니다.



 a| 
BB 크레딧 없음 기간 Tx
 a| 
샘플링 간격 동안 전송 BB 크레딧이 0인 시간(밀리초)입니다.



 a| 
캐시 적중률(총, 읽기, 쓰기) %
 a| 
캐시 적중으로 인한 요청의 비율입니다. 적중 횟수와 볼륨 액세스 횟수가 많을수록 성능이 향상됩니다. 캐시 적중 정보를 수집하지 않는 스토리지 시스템의 경우 이 열이 비어 있습니다.



 a| 
캐시 활용률(총) %
 a| 
캐시 적중으로 인한 캐시 요청의 총 비율입니다



 a| 
클래스 3이 삭제됩니다
 a| 
Fibre Channel Class 3 데이터 전송 폐기 횟수



 a| 
CPU 사용률(총) %
 a| 
사용 가능한 총 CPU(모든 가상 CPU)의 백분율로 사용 중인 CPU 리소스의 양입니다.



 a| 
CRC 오류입니다
 a| 
샘플링 기간 동안 포트에서 감지된 잘못된 CRC(Cyclic Redundancy Check)의 프레임 수입니다



 a| 
프레임 속도
 a| 
초당 프레임 수(FPS)로 프레임 속도 전송



 a| 
프레임 크기 평균(Rx, Tx)
 a| 
프레임 크기에 대한 트래픽 비율입니다. 이 메트릭을 통해 Fabric에 오버헤드 프레임이 있는지 여부를 확인할 수 있습니다.



 a| 
프레임 크기가 너무 깁니다
 a| 
너무 긴 Fibre Channel 데이터 전송 프레임 수입니다.



 a| 
프레임 크기가 너무 짧습니다
 a| 
너무 짧은 Fibre Channel 데이터 전송 프레임 수입니다.



 a| 
I/O 밀도(Total, Read, Write)
 a| 
볼륨, 내부 볼륨 또는 스토리지 요소에 대한 IOPS를 사용된 용량(데이터 소스의 최신 인벤토리 폴에서 얻은 값)으로 나눈 값입니다. TB당 초당 I/O 작업 수로 측정



 a| 
IOPS(총, 읽기, 쓰기)
 a| 
I/O 채널을 통해 전달되는 읽기/쓰기 I/O 서비스 요청 수 또는 시간 단위당 해당 채널의 일부(초당 I/O로 측정)



 a| 
IP 처리량(총, 읽기, 쓰기)
 a| 
총계: 초당 메가바이트 단위의 IP 데이터가 전송 및 수신된 총 속도입니다. 읽기: IP 처리량(수신): IP 데이터가 수신된 평균 속도(MB/초)입니다.

쓰기: IP 처리량(전송): IP 데이터가 전송된 평균 속도(MB/초)입니다.



 a| 
지연 시간(총, 읽기, 쓰기)
 a| 
지연 시간(R&W): 고정된 시간 내에 데이터를 가상 시스템에 읽거나 쓰는 비율. 이 값은 초당 메가바이트로 측정됩니다.

지연 시간: 데이터 저장소의 가상 머신에서 평균 응답 시간입니다.

최고 지연 시간: 데이터 저장소의 가상 머신에서 응답 시간이 가장 긴 경우



 a| 
링크 실패
 a| 
샘플링 기간 동안 포트에서 감지된 링크 장애 수입니다.



 a| 
Link Reset Rx, Tx(링크 재설정 Rx, Tx
 a| 
샘플링 기간 동안 수신 또는 전송 링크 재설정 횟수 이 메트릭은 이 포트에 연결된 포트에서 실행된 링크 재설정의 수를 나타냅니다.



 a| 
메모리 사용률(총) %
 a| 
호스트에서 사용하는 메모리의 임계값입니다.



 a| 
부분 R/W(총) %
 a| 
읽기/쓰기 작업이 RAID 5, RAID 1/0 또는 RAID 0 LUN의 디스크 모듈에서 스트라이프 경계를 교차하는 총 횟수입니다. 일반적으로 스트라이프 크로싱은 각 LUN에 추가 I/O가 필요하기 때문에 유용하지 않습니다 비율이 낮다면 효율적인 스트라이프 요소 크기를 나타내며 볼륨(또는 NetApp LUN)이 잘못 정렬되었음을 나타냅니다.

CLARiX의 경우 이 값은 총 IOPS 수로 나눈 스트라이프 크로싱 수입니다.



 a| 
포트 오류
 a| 
샘플링 기간/지정된 기간 동안의 포트 오류 보고.



 a| 
신호 손실 카운트
 a| 
신호 손실 오류 수입니다. 신호 손실 오류가 발생하면 전기 연결이 없고 물리적 문제가 있는 것입니다.



 a| 
스왑 속도(총 속도, 속도, 아웃 속도)
 a| 
샘플링 기간 동안 메모리를 디스크에서 활성 메모리로 스왑하거나, 스왑 아웃하거나, 둘 다 활성 메모리로 스왑하는 속도입니다. 이 카운터는 가상 머신에 적용됩니다.



 a| 
동기화 손실 카운트
 a| 
동기화 손실 오류 수입니다. 동기화 손실 오류가 발생하면 하드웨어가 트래픽을 감지하거나 해당 트래픽을 잠글 수 없습니다. 모든 장비가 동일한 데이터 속도를 사용하지 않거나, 광학 또는 물리적 연결의 품질이 저하될 수 있습니다. 이러한 각 오류 후에 포트가 재동기화되어야 하며, 이는 시스템 성능에 영향을 줍니다. KB/초 단위로 측정됩니다



 a| 
처리량(총, 읽기, 쓰기)
 a| 
입출력 서비스 요청에 대한 응답으로 데이터가 전송, 수신 또는 모두 고정된 시간(MB/sec 단위로 측정)으로 전송되는 속도입니다.



 a| 
시간 초과 폐기 프레임 - Tx
 a| 
시간 초과로 인해 폐기된 전송 프레임 수입니다.



 a| 
트래픽 속도(합계, 읽기, 쓰기)
 a| 
샘플링 기간 동안 전송, 수신 또는 두 가지 모두 수신된 트래픽(초당 메비바이트)입니다.



 a| 
트래픽 사용률(총, 읽기, 쓰기)
 a| 
샘플링 기간 동안 수신/전송/총 수신/전송/총 용량의 비율입니다.



 a| 
사용률(총, 읽기, 쓰기) %
 a| 
전송(Tx) 및 수신(Rx)에 사용되는 가용 대역폭의 비율입니다.



 a| 
쓰기 보류(총)
 a| 
보류 중인 쓰기 입출력 서비스 요청 수입니다.

|===