---
permalink: config-admin/microsoft-hyper-v-wmi-data-source.html 
sidebar: sidebar 
keywords:  
summary: '구성의 경우 Microsoft Hyper-V 데이터 원본에는 물리적 호스트(하이퍼바이저\)에 대한 IP 주소 또는 확인 가능한 DNS 이름이 필요합니다. 이 데이터 소스는 Powershell\(이전에 사용된 WMI\)을 사용합니다.' 
---
= Microsoft Hyper-V 데이터 소스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
구성의 경우 Microsoft Hyper-V 데이터 원본에는 물리적 호스트(하이퍼바이저)의 IP 주소 또는 확인 가능한 DNS 이름이 필요합니다. 이 데이터 소스는 Powershell(이전에 사용한 WMI)을 사용합니다.



== 용어

OnCommand Insight는 Hyper-V 데이터 소스에서 다음 인벤토리 정보를 가져옵니다. Insight에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 소스를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

|===


| 공급업체/모델 기간 | Insight 용어입니다 


 a| 
가상 하드 디스크
 a| 
가상 디스크



 a| 
호스트
 a| 
호스트



 a| 
가상 머신
 a| 
가상 머신



 a| 
CSV(Cluster Shared Volumes), 파티션 볼륨
 a| 
데이터 저장소



 a| 
인터넷 SCSI 장치, 다중 경로 SCSI LUN
 a| 
LUN을 클릭합니다



 a| 
Fibre Channel 포트
 a| 
포트

|===
[NOTE]
====
이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 소스의 모든 경우를 나타내는 것은 아닙니다.

====


== 요구 사항

* Hyper-V를 사용하려면 데이터 수집 및 원격 액세스/관리를 위해 포트 5985를 열어야 합니다.
* 클러스터링 그룹 노드의 IP 주소입니다
* 하이퍼바이저의 로컬 관리자 사용자 및 암호
* 관리 수준 사용자 계정
* 포트 요구 사항: Windows 2003 및 이전 버전의 경우 포트 135 및 동적 TCP 포트 1024-65535와 Windows 2008의 경우 49152-65535가 할당됩니다.
* 데이터 수집기가 IP 주소만 가리키는 경우에도 DNS 확인이 성공해야 합니다.
* 각 Hyper-V 하이퍼바이저에는 모든 호스트의 모든 VM에 대해 "리소스 계측"이 켜져 있어야 합니다. 따라서 각 하이퍼바이저마다 각 게스트에서 Cloud Insights에 사용할 수 있는 데이터가 더 많아집니다. 이 옵션을 설정하지 않으면 각 게스트에 대해 더 적은 성능 메트릭이 획득됩니다. 리소스 측정에 대한 자세한 내용은 Microsoft 설명서를 참조하십시오.
+
https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-R2-and-2012/hh831661(v=ws.11)["Hyper-V 리소스 측정 개요"]

+
https://docs.microsoft.com/en-us/powershell/module/hyper-v/enable-vmresourcemetering?view=win10-ps["활성화 - VMResourceMetering"]





== 구성

|===


| * 필드 * | * 설명 * 


 a| 
물리적 호스트 IP 주소입니다
 a| 
물리적 호스트(하이퍼바이저)의 IP 주소 또는 정규화된 도메인 이름



 a| 
사용자 이름
 a| 
관리자 사용자 이름은 하이퍼바이저를 수행합니다



 a| 
암호
 a| 
하이퍼바이저의 암호입니다



 a| 
NT 도메인
 a| 
클러스터의 노드에서 사용하는 DNS 이름입니다

|===


== 고급 구성

|===


| * 필드 * | * 설명 * 


 a| 
재고 폴링 간격(분)
 a| 
재고 조사 간격(기본값 20분)



 a| 
연결 시간 초과(ms)
 a| 
연결 시간 초과(기본값 60000ms)

|===