---
permalink: config-admin/microsoft-azure-compute-data-source.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insights는 Azure 컴퓨팅 데이터 수집기를 사용하여 Azure 컴퓨팅 인스턴스에서 인벤토리 및 성능 데이터를 가져옵니다. 
---
= Microsoft Azure 컴퓨팅 데이터 소스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insights는 Azure 컴퓨팅 데이터 수집기를 사용하여 Azure 컴퓨팅 인스턴스에서 인벤토리 및 성능 데이터를 가져옵니다.



== 요구 사항

이 데이터 수집기를 구성하려면 다음 정보가 필요합니다.

* 포트 요구 사항: 443 HTTPS
* Azure 관리 REST IP(management.azure.com)
* Azure 서비스 주 응용 프로그램(클라이언트) ID(사용자 계정)
* Azure Service Principal Authentication 키(사용자 암호)


Insight 검색을 위해 Azure 계정을 설정해야 합니다. 계정이 올바르게 구성되고 Azure에 애플리케이션을 등록하면 Insight에서 Azure 인스턴스를 검색하는 데 필요한 자격 증명이 제공됩니다. 다음 링크에서는 검색을 위해 계정을 설정하는 방법에 대해 설명합니다. https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-create-service-principal-portal



== 구성

아래 표에 따라 데이터 원본 필드에 데이터를 입력합니다.

|===


| 필드에 입력합니다 | 설명 


 a| 
Azure 서비스 주 응용 프로그램(클라이언트) ID(리더 역할 필요)
 a| 
Azure에 로그인 ID를 입력합니다. 리더 역할 액세스가 필요합니다.



 a| 
Azure 테넌트 ID입니다
 a| 
Microsoft 테넌트 ID입니다



 a| 
Azure 서비스 주 인증 키
 a| 
로그인 인증 키



 a| 
API 요청에 대한 Microsoft의 청구서를 알고 있습니다
 a| 
Insight 폴링을 통해 API 요청이 접수된다는 사실을 알고 있는지 확인하려면 이 확인란을 선택하십시오.

|===


== 고급 구성

아래 표에 따라 데이터 원본 필드에 데이터를 입력합니다.

|===


| 필드에 입력합니다 | 설명 


 a| 
재고 폴링 간격(분)
 a| 
기본값은 60입니다



 a| 
태그별로 VM 필터링에 적용하려면 '제외' 또는 '포함'을 선택합니다
 a| 
데이터를 수집할 때 태그별로 VM을 포함할지 제외할지 여부를 지정합니다. ''포함''을 선택하면 태그 키 필드를 비워둘 수 없습니다.



 a| 
태그 키 및 VM을 필터링할 값
 a| 
VM의 키 및 태그 값과 일치하는 키 및 값을 필터링하여 포함/제외할 VM(및 관련 디스크)을 선택하려면 * + 필터 태그 * 를 클릭합니다. 태그 키는 필수이며 태그 값은 선택 사항입니다. 태그 값이 비어 있으면 태그 키와 일치하는 한 VM이 필터링됩니다.



 a| 
성능 폴링 간격(초)|
 a| 
기본값은 300입니다

|===