---
permalink: config-admin/monitoring-oncommand-insight-system-health.html 
sidebar: sidebar 
keywords:  
summary: Insight 시스템 구성 요소의 현재 상태를 주기적으로 확인하여 각 구성 요소의 상태를 표시하고 문제가 있을 경우 알려줍니다. 
---
= OnCommand Insight 시스템 상태 모니터링
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Insight 시스템 구성 요소의 현재 상태를 주기적으로 확인하여 각 구성 요소의 상태를 표시하고 문제가 있을 경우 알려줍니다.



== 단계

. Insight트위브 UI에 로그인합니다.
. Admin * 을 클릭하고 * Health * 를 선택합니다.
+
상태 페이지가 표시됩니다.

. 빨간색 원 앞에 있는 * Details * 열의 주의 상태에 특히 주의를 기울인 구성 요소의 현재 상태에 대한 요약을 봅니다. 이 열은 즉각적인 주의가 필요한 문제를 나타냅니다.
+
상태 페이지에는 시스템 구성에 따라 다음과 같은 Insight 구성 요소 중 일부 또는 전체에 대한 정보가 표시됩니다.

+
|===


| 구성 요소 | 테스트 | 세부 정보 | 표시됩니다 


 a| 
획득
 a| 
재고 데이터 처리
 a| 
로컬 획득 장치의 상태입니다
 a| 
동시 폴링 데이터 소스의 수가 실행 풀 최대값의 75% 미만일 경우 ""OK"(기본값: 30). 사용이 75%를 초과하는 경우 "Acquisition is busy(획득 사용 중)", 폴링 간격을 늘리거나 원격 획득 장치를 더 추가하는 것이 좋습니다.



 a| 
이상 현상 감지 엔진
 a| 
엔진 용량
 a| 
이상 징후 감지를 위해 모니터링되는 애플리케이션의 수입니다
 a| 
가능한 48개 응용 프로그램 중 모니터링 중인 응용 프로그램의 수 및 백분율입니다.



 a| 
이상 현상 감지 엔진
 a| 
엔진 상태
 a| 
이상 탐지 엔진의 상태입니다
 a| 
오류가 발견되지 않으면 발견된 오류에 대한 정보가 표시됩니다. 를 참조하십시오 `prelert.log` 파일 을 참조하십시오.



 a| 
DWH
 a| 
백업
 a| 
데이터 웨어하우스 예약 백업의 상태입니다
 a| 
DWH 예약 백업이 활성화된 경우 "OK(확인)" 및 마지막으로 성공한 DWH 백업 시간 그렇지 않으면 발견된 오류에 대한 정보가 표시됩니다.



 a| 
DWH
 a| 
ETL
 a| 
데이터 웨어하우스 ETL의 상태입니다
 a| 
"OK"와 마지막 성공한 DWH 빌드 시간(오류 없음). 그렇지 않으면 발견된 오류에 대한 정보가 표시됩니다.



 a| 
서버
 a| 
ASUP
 a| 
ASUP 상태
 a| 
""ASUP 활성화"" 및 가능한 경우 마지막으로 성공한 전화집 시간. "ASUP Failed"(ASUP 실패) - phonehome이 활성화되어 있지만 문제가 발생한 경우

백업 디렉토리가 유효하지 않은 경우 + "잘못된 백업 위치"

+ 마지막으로 성공한 전화 시간과 마지막으로 실패한 시도(있는 경우)를 표시합니다.

폰홈이 비활성화된 경우 + "'ASUP 비활성화'.



 a| 
서버
 a| 
자동 해상도
 a| 
자동 장치 해상도 상태입니다
 a| 
오류가 없으면 OK를 누릅니다. 확인 오류로 인해 해결 과정이 진행되지 않으면 자동 해결이 차단됩니다.

일반 디바이스의 75% 미만이 식별될 수 있는 경우 + ""낮은 성공률""



 a| 
서버
 a| 
Elasticsearch(Elasticsearch)
 a| 
탄력적인 검색 데이터 저장소의 상태입니다
 a| 
오류가 없으면 OK를 누릅니다. "서비스를 사용할 수 없습니다."라는 메시지가 표시됩니다.

둘 이상의 노드가 감지되면 + "클러스터 모드 감지됨"

사용된 힙 공간이 85%를 초과하는 경우 + "높은 메모리 사용률"

"상태: 빨간색"은 탄성 검색에서 보고된 오류를 나타냅니다. 오류에 대한 정보를 표시하고 고객 지원 센터에 문의할 것을 권장합니다.



 a| 
서버
 a| 
CPU
 a| 
Insight CPU 사용량
 a| 
CPU 부하가 65% 미만이면 "OK" 시스템 CPU 부하가 높습니다. CPU 부하를 줄입니다." CPU 로드가 65%보다 큰 경우



 a| 
서버
 a| 
디스크 공간
 a| 
디스크 공간의 상태입니다
 a| 
디스크 여유 공간, Insight에서 사용 중인 디스크 공간 및 Insight용으로 예약된 권장 디스크 공간 디스크 사용률이 80%를 초과할 경우 ""디스크 공간 부족"".



 a| 
서버
 a| 
이벤트 버스
 a| 
EventBus의 상태입니다
 a| 
EventBus는 비어 있습니다. EventBus 대기열이 비어 있으면 EventBus 대기열 상태를 표시합니다.



 a| 
서버
 a| 
재고 데이터 처리
 a| 
Insight 서버의 인벤토리 데이터 처리 기능 상태입니다
 a| 
Insight 서버가 사용 중이 아니면 "OK"입니다. 서버가 마지막 시간의 75% 이상 사용 중이면 서버가 사용 중입니다. 에서는 데이터 소스를 더 추가하지 않을 것을 권장하며 환경을 여러 서버로 분할할 것을 권장합니다.



 a| 
서버
 a| 
MySQL
 a| 
MySQL 데이터베이스의 상태입니다
 a| 
문제가 발견되지 않으면 OK. "데이터베이스에 성능 문제가 있습니다. 일부 쿼리는 느린 쿼리 수가 5%를 초과할 경우 "(을) 실행하는 데 너무 오래 걸립니다.

데이터베이스 로그 파일은 지난 한 시간 동안 <size>보다 더 많이 성장했습니다. 오류 로그가 20KB를 초과할 경우 MySQL 로그 파일 ""을 확인하십시오.



 a| 
서버
 a| 
성능 아카이브
 a| 
성능 아카이브의 상태입니다
 a| 
"Performance archive is enabled" 또는 "Performance archive is not enabled".



 a| 
서버
 a| 
물리적 메모리
 a| 
물리적 메모리의 상태입니다
 a| 
메모리 사용량이 85% 미만일 경우 "OK". "메모리 사용량이 높습니다. 시스템 안정성을 위해 전체 메모리 공간을 줄일 수 있습니다."



 a| 
서버
 a| 
서비스 팩
 a| 
서비스 팩 가용성
 a| 
Insight에서 서비스 팩을 사용할 수 있는지 여부를 표시합니다. 서비스 팩을 사용할 수 있는 경우 에 지침이 표시됩니다.



 a| 
서버
 a| 
사용 정보
 a| 
사용 정보 전송 상태
 a| 
NetApp에 사용 정보 전송이 설정되었는지 여부를 표시합니다. 는 사용하지 않는 경우 활성화할 것을 권장합니다. 마지막으로 시도했거나 마지막으로 성공한 전송 시간을 표시합니다.

+ 발생한 문제에 대한 정보를 표시합니다.



 a| 
서버
 a| 
위반
 a| 
미결 위반 상태
 a| 
개방형 위반 건수가 위반 건수의 75% 미만이면 OK. "허용되는 최대 공개 위반 수는 <number>"입니다. 위반 허용 횟수가 위반 제한의 75%를 초과하는 경우. 에서는 성능 정책 구성을 검토할 것을 권장합니다.

위반 건수가 위반 한도인 경우 위반 관리자가 차단됩니다.

+위반 관리자는 새로운 위반 사항을 작성할 수 없으며 성능 정책 구성을 검토할 것을 권장합니다.



 a| 
서버
 a| 
주간 백업
 a| 
주별 백업의 상태입니다
 a| 
주 단위 백업이 활성화된 경우 "OK(확인)", 그렇지 않으면 "Weekly backup is not enabled(주간 백업이 활성화되지 않음)"가 표시됩니다.

|===
+
[NOTE]
====
이상 징후 탐지 엔진에 오류가 표시되는 경우 를 참조하십시오 `prelert.log` 자세한 내용은 다음 위치에 있는 파일: - Windows: `disk drive:\install directory\SANscreen\Wildfly\Standalone\Logs`Linux: `/var/log/netapp/oci/wildfly/`

를 누릅니다

====

