---
permalink: config-admin/netapp-solidfire-data-source.html 
sidebar: sidebar 
keywords:  
summary: NetApp SolidFire 데이터 소스는 인벤토리 및 성능 수집을 위해 iSCSI와 파이버 채널 SolidFire 구성을 모두 지원합니다. 
---
= NetApp SolidFire 데이터 소스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp SolidFire 데이터 소스는 인벤토리 및 성능 수집을 위해 iSCSI와 파이버 채널 SolidFire 구성을 모두 지원합니다.

SolidFire 데이터 소스는 SolidFire REST API를 사용합니다. 데이터 소스가 상주하는 획득 장치에서는 SolidFire 클러스터 관리 IP 주소의 TCP 포트 443에 대한 HTTPS 연결을 시작할 수 있어야 합니다. 데이터 원본에는 SolidFire 클러스터에서 REST API 쿼리를 수행할 수 있는 자격 증명이 필요합니다.



== 용어

OnCommand Insight는 NetApp SolidFire 데이터 소스에서 다음 인벤토리 정보를 가져옵니다. Insight에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 소스를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

|===


| 공급업체/모델 기간 | Insight 용어입니다 


 a| 
드라이브
 a| 
디스크



 a| 
클러스터
 a| 
스토리지



 a| 
노드
 a| 
스토리지 노드



 a| 
볼륨
 a| 
볼륨



 a| 
Fibre Channel 포트
 a| 
포트



 a| 
볼륨 액세스 그룹, LUN 할당
 a| 
볼륨 맵



 a| 
iSCSI 세션
 a| 
볼륨 마스크

|===
[NOTE]
====
이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 소스의 모든 경우를 나타내는 것은 아닙니다.

====


== 요구 사항

다음은 이 데이터 소스를 구성하기 위한 요구 사항입니다.

* 관리 가상 IP 주소
* 포트 443




== 구성

|===


| 필드에 입력합니다 | 설명 


 a| 
관리 가상 IP 주소(MVIP)
 a| 
SolidFire 클러스터의 관리 가상 IP 주소입니다



 a| 
사용자 이름
 a| 
SolidFire 클러스터에 로그인하는 데 사용되는 이름입니다



 a| 
암호
 a| 
SolidFire 클러스터에 로그인하는 데 사용되는 암호입니다

|===


== 고급 구성

|===


| 필드에 입력합니다 | 설명 


 a| 
재고 폴링 간격(분)
 a| 
재고 조사 간격(기본값: 60분)



 a| 
TCP 포트
 a| 
SolidFire 서버에 연결하는 데 사용되는 TCP 포트(기본값 443)



 a| 
연결 시간 초과(초)
 a| 
연결 시간 초과(기본값 60초)



 a| 
성능 폴링 간격(초)
 a| 
성능 폴링 간격(기본값 300초)

|===


== 문제 해결

SolidFire에서 오류를 보고하면 다음과 같이 OnCommand Insight에 표시됩니다.

`An error message was received from a SolidFire device while trying to retrieve data. The call was <method> (<parameterString> ). The error message from the device was (check the device manual): <message>`

여기서,

* 메소드>는 GET 또는 PUT와 같은 HTTP 메소드 입니다.
* parameterString>은 REST 호출에 포함된 쉼표로 구분된 매개 변수 목록입니다.
* message>는 오류 메시지로 반환된 장치와 상관없이 표시됩니다.

