---
permalink: config-admin/netapp-host-and-vm-filesystems-data-source.html 
sidebar: sidebar 
keywords:  
summary: 'NetApp 호스트 및 VM 파일 시스템 데이터 소스를 사용하여 모든 Microsoft Windows 호스트 및 VM\(가상 머신\) 파일 시스템과 지원되는 모든 Linux VM\(가상 매핑된 VM\)에 대한 파일 시스템 세부 정보 및 스토리지 리소스 매핑을 검색할 수 있습니다. 구성된 CRG\(Compute Resource Group)로 주석이 추가된 Insight 서버에 있는 기존' 
---
= NetApp 호스트 및 VM 파일 시스템 데이터 소스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NetApp 호스트 및 VM 파일 시스템 데이터 소스를 사용하여 모든 Microsoft Windows 호스트 및 VM(가상 머신) 파일 시스템과 지원되는 모든 Linux VM(가상 매핑된 것에만 해당)에 대한 파일 시스템 세부 정보 및 스토리지 리소스 매핑을 검색할 수 있습니다. 구성된 CRG(Compute Resource Group)로 주석이 추가된 Insight 서버의 기존



== 일반 요구 사항

* 이 기능은 별도로 구입해야 합니다.
+
도움이 필요하면 Insight 담당자에게 문의하십시오.

* Insight Support Matrix를 확인하여 호스트 또는 가상 머신 운영 체제가 지원되는지 확인해야 합니다.
+
파일 시스템에서 스토리지 리소스로의 링크가 생성되었는지 확인하려면 관련 스토리지 또는 가상화 공급업체 유형 및 버전이 필요한 볼륨 또는 가상 디스크 식별 데이터를 보고하는지 확인하십시오.





== Microsoft Windows 요구 사항

* 이 데이터 소스는 WMI(Window Management Instrumentation) 데이터 구조를 사용하여 데이터를 검색합니다.
+
이 서비스는 원격으로 작동하고 사용 가능해야 합니다. 특히, 포트 135에 액세스할 수 있어야 하며 방화벽 뒤에 있는 경우 열어야 합니다.

* Windows 도메인 사용자는 WMI 구조에 액세스할 수 있는 적절한 권한이 있어야 합니다.
* 관리자 권한이 필요합니다.
* Windows 2003 및 이전 버전에서 1024-65535로 할당된 동적 TCP 포트
* Windows 2008의 경우 포트 49152 - -65535


[NOTE]
====
일반적으로 Insight, AU 및 이 데이터 소스 간에 방화벽을 사용하려고 할 때 Microsoft 팀에 문의하여 필요한 포트를 확인해야 합니다.

====


== Linux 요구 사항

* 이 데이터 소스는 SSH(Secure Shell) 연결을 사용하여 Linux VM에서 명령을 실행합니다.
+
SSH 서비스가 운영되어야 하며 원격으로 이용할 수 있어야 합니다. 특히, 포트 22에 액세스할 수 있어야 하며 방화벽 뒤에 있는 경우 열어야 합니다.

* SSH 사용자는 sudo 권한이 있어야 Linux VM에서 읽기 전용 명령을 실행할 수 있습니다.
+
동일한 암호를 사용하여 SSH에 로그인하고 sudo 암호 챌린지에 응답해야 합니다.





== 사용 권장 사항

* 동일한 Compute Resource Group 주석을 사용하여 공통 운영 체제 자격 증명이 있는 호스트 및 가상 시스템 그룹에 주석을 추가해야 합니다.
+
각 그룹에는 이러한 호스트 및 가상 시스템에서 파일 시스템 세부 정보를 검색하는 이 데이터 소스의 인스턴스가 있습니다.

* 성공률이 낮은 이 데이터 소스의 인스턴스가 있는 경우(예: OnCommand Insight가 그룹에 있는 1000개의 호스트 및 가상 머신 중 50개에 대한 파일 시스템 세부 정보를 검색하는 경우), 검색이 성공한 호스트와 가상 머신을 별도의 컴퓨팅 리소스 그룹으로 이동해야 합니다.




== 구성

|===


| 필드에 입력합니다 | 설명 


 a| 
사용자 이름
 a| 
운영 체제 사용자 Windows 운영 체제 사용자의 파일 시스템 데이터를 검색할 수 있는 적절한 권한이 있어야 합니다. 여기에는 도메인 접두사가 포함되어야 합니다.



 a| 
암호
 a| 
운영 체제 사용자의 암호입니다



 a| 
컴퓨팅 리소스 그룹
 a| 
데이터 소스에 대한 호스트 및 가상 머신에 플래그를 지정하는 데 사용되는 주석 값은 파일 시스템을 검색합니다. 빈 값은 데이터 소스가 현재 Compute Resource Group(계산 리소스 그룹)으로 주석이 추가되지 않은 모든 호스트 및 가상 시스템에 대한 파일 시스템을 검색함을 나타냅니다.

|===


== 고급 구성

|===


| 필드에 입력합니다 | 설명 


 a| 
재고 폴링 간격(분)
 a| 
재고 조사 간격(기본값 360분)

|===