---
permalink: config-admin/netapp-clustered-data-ontap-data-source.html 
sidebar: sidebar 
keywords:  
summary: 이 데이터 소스는 clustered Data ONTAP을 사용하는 스토리지 시스템에 사용해야 하며 읽기 전용 API 호출에 사용되는 관리자 계정이 필요합니다. 
---
= NetApp clustered Data ONTAP 데이터 소스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이 데이터 소스는 clustered Data ONTAP을 사용하는 스토리지 시스템에 사용해야 하며 읽기 전용 API 호출에 사용되는 관리자 계정이 필요합니다.



== 용어

OnCommand Insight는 clustered Data ONTAP 데이터 소스에서 다음 인벤토리 정보를 가져옵니다. Insight에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 소스를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

|===


| 공급업체/모델 기간 | Insight 용어입니다 


 a| 
디스크
 a| 
디스크



 a| 
RAID 그룹
 a| 
디스크 그룹



 a| 
클러스터
 a| 
스토리지



 a| 
노드
 a| 
스토리지 노드



 a| 
집계
 a| 
스토리지 풀



 a| 
LUN을 클릭합니다
 a| 
볼륨



 a| 
볼륨
 a| 
내부 볼륨

|===
[NOTE]
====
이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 소스의 모든 경우를 나타내는 것은 아닙니다.

====


== 요구 사항

* 읽기 전용 API 호출에 사용되는 관리자 계정입니다
* 타겟 IP는 클러스터 관리 LIF입니다
* NetApp 클러스터에 로그인할 수 있는 사용자 이름(읽기 전용 역할 이름을 ontapi 애플리케이션에 기본 SVM으로 지정) 및 암호
* 포트 요구 사항: 80 또는 443
* 라이센스 요구사항: 검색에 필요한 FCP 라이센스 및 매핑/마스킹된 볼륨




== 구성

|===


| * 필드 * | * 설명 * 


 a| 
NetApp 관리 IP
 a| 
NetApp 클러스터의 IP 주소 또는 정규화된 도메인 이름입니다



 a| 
사용자 이름
 a| 
NetApp 클러스터의 사용자 이름입니다



 a| 
암호
 a| 
NetApp 클러스터의 암호입니다

|===


== 고급 구성

|===


| * 필드 * | * 설명 * 


 a| 
재고 폴링 간격(분)
 a| 
재고 조사 간격(기본값 20분)



 a| 
성능 폴링 간격(초)
 a| 
성능 폴링 간격(기본값 300초)

|===