---
permalink: config-admin/openstack-data-source.html 
sidebar: sidebar 
keywords:  
summary: 'OpenStack\(REST API/KVM\) 데이터 소스에서 OpenStack 하드웨어 인스턴스에 대한 정보를 수집합니다. 이 데이터 소스는 모든 OpenStack 인스턴스에 대한 인벤토리 데이터를 수집하고 선택적으로 VM 성능 데이터를 수집합니다.' 
---
= OpenStack 데이터 소스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OpenStack(REST API/KVM) 데이터 소스에서 OpenStack 하드웨어 인스턴스에 대한 정보를 수집합니다. 이 데이터 소스는 모든 OpenStack 인스턴스에 대한 인벤토리 데이터를 수집하고 선택적으로 VM 성능 데이터를 수집합니다.



== 요구 사항

다음은 OpenStack 데이터 소스를 구성하기 위한 요구사항입니다.

* OpenStack 컨트롤러의 IP 주소입니다
* OpenStack 관리자 역할 자격 증명 및 Linux KVM 하이퍼바이저에 대한 sudo 액세스를 권장합니다.
+
[NOTE]
====
admin 계정 또는 admin에 상응하는 권한을 사용하지 않는 경우에도 데이터 소스에서 데이터를 획득할 수 있습니다. admin 역할이 아닌 사용자가 API를 호출할 수 있도록 정책 구성 파일(예: etc/nova/policy.json)을 수정해야 합니다.

====
+
** "OS_컴퓨팅_API:OS-가용성-영역:세부 정보":"
** "OS_컴퓨팅_API:OS-하이퍼바이저":"
** OS_컴퓨팅_API:서버:세부 정보:get_all_tenant":""


* 성능 수집을 위해 OpenStack Ceilometer 모듈을 설치하고 구성해야 합니다. Ceilometer 구성은 를 편집하여 수행할 수 있습니다 `nova.conf` 각 하이퍼바이저에 대해 파일을 생성한 다음 각 하이퍼바이저에서 Nova 컴퓨팅 서비스를 다시 시작합니다. 옵션 이름이 OpenStack의 다양한 릴리즈에서 변경되었습니다.
+
** 아이스하우스
** 준오
** 킬로
** 리버티
** 미타카
** 뉴턴
** 옥타


* CPU 통계의 경우 컴퓨팅 노드의 /etc/nova/nova.conf에서 "compute_monitor=ComputeDriverCPUMonitor"를 켜야 합니다.
* 포트 요구 사항:
+
** http의 경우 5000, Keystone 서비스의 경우 13000
** 22 KVM SSH의 경우
** Nova 컴퓨팅 서비스: 8774
** 8776을 참조하십시오
** Ceilometer 성능 서비스용 8777
** Glance 이미지 서비스를 위한 9292
+
[NOTE]
====
포트는 특정 서비스에 바인딩되며, 대규모 환경의 컨트롤러 또는 다른 호스트에서 서비스가 실행될 수 있습니다.

====






== 구성

|===


| * 필드 * | * 설명 * 


 a| 
OpenStack 컨트롤러 IP 주소입니다
 a| 
OpenStack 컨트롤러의 IP 주소 또는 정규화된 도메인 이름입니다



 a| 
OpenStack 관리자
 a| 
OpenStack 관리자의 사용자 이름입니다



 a| 
OpenStack 암호
 a| 
OpenStack Admin에 사용되는 암호입니다



 a| 
OpenStack 관리자 테넌트
 a| 
OpenStack 관리자 테넌트



 a| 
KVM Sudo 사용자
 a| 
KVM Sudo 사용자 이름입니다



 a| 
자격 증명 유형을 지정하려면 '암호' 또는 'OpenSSH 키 파일'을 선택하십시오
 a| 
SSH를 통해 장치에 연결하는 데 사용되는 자격 증명 유형입니다



 a| 
재고 개인 키에 대한 전체 경로
 a| 
재고 개인 키에 대한 전체 경로



 a| 
KVM Sudo 암호
 a| 
KVM Sudo 암호

|===


== 고급 구성

|===


| * 필드 * | * 설명 * 


 a| 
SSH를 통해 하이퍼바이저 인벤토리 검색을 설정합니다
 a| 
SSH를 통해 하이퍼바이저 인벤토리 검색을 설정하려면 이 확인란을 선택합니다



 a| 
OpenStack 관리 URL 포트입니다
 a| 
OpenStack 관리 URL 포트입니다



 a| 
HTTPS를 사용합니다
 a| 
보안 HTTP를 사용하려면 선택합니다



 a| 
HTTP 연결 시간 초과(초)
 a| 
HTTP 연결 시간 초과(기본값 300초)



 a| 
SSH 포트
 a| 
SSH에 사용되는 포트입니다



 a| 
SSH 프로세스 대기 시간 초과(초)
 a| 
SSH 프로세스 시간 초과(기본값 30초)



 a| 
SSH 프로세스 재시도
 a| 
인벤토리 재시도 횟수입니다



 a| 
재고 폴링 간격(분)
 a| 
재고 조사 간격(기본값 20분)

|===