---
permalink: config-admin/oracle-zfs-data-source.html 
sidebar: sidebar 
keywords:  
summary: Oracle ZFS 데이터 소스는 인벤토리 및 성능 수집을 지원합니다. 
---
= Oracle ZFS 데이터 소스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Oracle ZFS 데이터 소스는 인벤토리 및 성능 수집을 지원합니다.



== 용어

OnCommand Insight는 이 데이터 소스에서 다음 인벤토리 정보를 가져옵니다. Insight에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 소스를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

|===


| 공급업체/모델 기간 | Insight 용어입니다 


 a| 
디스크(SDD)
 a| 
디스크



 a| 
클러스터
 a| 
스토리지



 a| 
컨트롤러
 a| 
스토리지 노드



 a| 
LUN을 클릭합니다
 a| 
볼륨



 a| 
LUN 매핑
 a| 
볼륨 맵



 a| 
초기자, 대상
 a| 
볼륨 마스크



 a| 
공유
 a| 
내부 볼륨

|===
[NOTE]
====
이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 소스의 모든 경우를 나타내는 것은 아닙니다.

====


== 요구 사항

다음은 이 데이터 소스를 구성하기 위한 요구 사항입니다.

* ZFS Controller-1 및 ZFS Controller-2의 호스트 이름
* 관리자 사용자 이름 및 자격 증명
* 포트 요구 사항: 215 HTTP/HTTPS




== 구성

|===


|  |  


 a| 
ZFS Controller-1 호스트 이름
 a| 
스토리지 컨트롤러 1의 호스트 이름입니다



 a| 
ZFS Controller-2 호스트 이름
 a| 
스토리지 컨트롤러의 호스트 이름 2



 a| 
사용자 이름입니다
 a| 
스토리지 시스템 관리자 사용자 계정의 사용자 이름입니다



 a| 
암호
 a| 
관리자 사용자 계정의 암호입니다

|===


== 고급 구성

|===


| 필드에 입력합니다 | 설명 


 a| 
TCP 포트
 a| 
ZFS에 연결하는 데 사용되는 TCP 포트(기본값 215)



 a| 
연결 유형
 a| 
HTTP 또는 HTTPS



 a| 
인벤토리 폴링 간격입니다
 a| 
인벤토리 폴링 간격(기본값: 60분)



 a| 
연결 시간 초과
 a| 
기본값은 60초입니다



 a| 
성능 폴링 간격(초)
 a| 
성능 폴링 간격(기본값 300초)

|===


== 문제 해결

이 데이터 수집기에서 문제가 발생할 경우 다음과 같은 방법을 시도해 보십시오.

|===


| 문제: | 다음을 시도해 보십시오. 


 a| 
"잘못된 로그인 자격 증명"
 a| 
ZFS 사용자 계정 및 암호를 확인합니다



 a| 
"구성 오류" 및 "reST 서비스가 비활성화되었습니다" 오류 메시지
 a| 
이 장치에서 REST 서비스가 활성화되어 있는지 확인합니다.



 a| 
"구성 오류" 및 "명령에 대한 권한이 없는 사용자" 오류 메시지
 a| 
특정 역할(예: 'advanced_analytics')이 구성된 사용자 <userName>에 포함되지 않을 수 있습니다. 가능한 해결 방법:

* 읽기 전용 역할을 사용하여 ${user} 사용자의 분석(통계) 범위를 수정하십시오. - 구성 → 사용자 화면에서 마우스를 역할 위에 놓고 두 번 클릭하여 편집할 수 있습니다
* 범위 드롭다운 메뉴에서 "분석"을 선택합니다. 가능한 속성 목록이 나타납니다.
* 맨 위 확인란을 클릭하면 세 가지 속성이 모두 선택됩니다. - 오른쪽에 있는 추가 단추를 클릭합니다.
* 팝업 창의 오른쪽 위에 있는 적용 단추를 클릭합니다. 팝업 창이 닫힙니다.


|===