---
permalink: config-admin/predefined-annotation-types.html 
sidebar: sidebar 
keywords:  
summary: OnCommandInsight는 몇 가지 기본 주석 유형을 제공합니다. 이러한 주석은 데이터를 필터링하거나 그룹화하고 데이터 보고를 필터링하는 데 사용할 수 있습니다. 
---
= 기본 주석 유형
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommandInsight는 몇 가지 기본 주석 유형을 제공합니다. 이러한 주석은 데이터를 필터링하거나 그룹화하고 데이터 보고를 필터링하는 데 사용할 수 있습니다.

다음과 같은 기본 주석 유형과 자산을 연결할 수 있습니다.

* 생일, 일몰 또는 수명 종료 등의 자산 수명 주기
* 데이터 센터, 건물 또는 바닥과 같은 장치에 대한 위치 정보
* 품질(계층), 연결된 장치(스위치 수준) 또는 서비스 수준별 자산 분류
* 핫(높은 활용도) 등의 상태


다음 표에는 기본 주석 유형이 나열되어 있습니다. 이러한 주석 이름을 필요에 맞게 편집할 수 있습니다.

|===


| 주석 유형 | 설명 | 유형 


 a| 
별칭
 a| 
리소스에 대한 사용자 친화적인 이름입니다.
 a| 
텍스트



 a| 
생일
 a| 
장치가 온라인 상태가 되거나 온라인으로 전환되는 날짜입니다.
 a| 
날짜



 a| 
건물
 a| 
호스트, 스토리지, 스위치 및 테이프 리소스의 물리적 위치
 a| 
목록



 a| 
도시
 a| 
호스트, 스토리지, 스위치 및 테이프 리소스의 지방자치당국 위치
 a| 
목록



 a| 
컴퓨팅 리소스 그룹
 a| 
Host 및 VM Filesystems 데이터 소스에서 사용하는 그룹 할당입니다.
 a| 
목록



 a| 
대륙
 a| 
호스트, 스토리지, 스위치 및 테이프 리소스의 지리적 위치
 a| 
목록



 a| 
국가
 a| 
호스트, 스토리지, 스위치 및 테이프 리소스의 국가별 위치
 a| 
목록



 a| 
데이터 센터
 a| 
리소스의 물리적 위치이며 호스트, 스토리지 시스템, 스위치 및 테이프에서 사용할 수 있습니다.
 a| 
목록



 a| 
직접 연결
 a| 
스토리지 리소스가 호스트에 직접 접속되어 있으면 (예 또는 아니요)를 나타냅니다.
 a| 
부울



 a| 
수명 종료
 a| 
예를 들어 임대가 만료되었거나 하드웨어가 폐기되는 경우 장치가 오프라인 상태가 되는 날짜입니다.
 a| 
날짜



 a| 
패브릭 별칭
 a| 
Fabric의 사용자 친화적인 이름입니다.
 a| 
텍스트



 a| 
바닥
 a| 
건물 바닥에 있는 장치의 위치. 호스트, 스토리지 시스템, 스위치 및 테이프에 대해 설정할 수 있습니다.
 a| 
목록



 a| 
핫
 a| 
이미 사용량이 많은 디바이스를 정기적으로 또는 용량 임계값으로 사용 중입니다.
 a| 
부울



 a| 
참고
 a| 
자원에 연결할 메모입니다.
 a| 
텍스트



 a| 
랙
 a| 
리소스가 상주하는 랙입니다.
 a| 
텍스트



 a| 
있습니다
 a| 
호스트, 스토리지, 스위치 및 테이프 리소스의 건물 또는 기타 위치 내의 공간입니다.
 a| 
목록



 a| 
산
 a| 
네트워크의 논리 파티션입니다. 호스트, 스토리지 시스템, 테이프, 스위치 및 애플리케이션에서 사용할 수 있습니다.
 a| 
목록



 a| 
서비스 수준
 a| 
리소스에 할당할 수 있는 지원되는 서비스 수준 집합입니다. 내부 볼륨, qtree, 볼륨에 대한 정렬 옵션 목록을 제공합니다. 서비스 수준을 편집하여 다양한 수준에 대한 성능 정책을 설정합니다.
 a| 
목록



 a| 
시/도
 a| 
리소스가 있는 시/군/구 또는 시/군/구
 a| 
목록



 a| 
일몰
 a| 
해당 디바이스에 새 할당을 수행할 수 없는 임계값을 설정합니다. 계획된 마이그레이션 및 기타 보류 중인 네트워크 변경에 유용합니다.
 a| 
날짜



 a| 
스위치 레벨
 a| 
에는 스위치에 대한 범주를 설정하기 위한 미리 정의된 옵션이 포함되어 있습니다. 일반적으로 이러한 지정은 필요한 경우 편집할 수 있지만 장치의 수명 기간 동안 유지됩니다. 스위치에만 사용할 수 있습니다.
 a| 
목록



 a| 
계층
 a| 
는 사용자 환경 내에서 서로 다른 서비스 수준을 정의하는 데 사용할 수 있습니다. 계층은 필요한 속도(예: 금 또는 은)와 같은 수준의 유형을 정의할 수 있습니다. 이 기능은 내부 볼륨, Qtree, 스토리지 어레이, 스토리지 풀 및 볼륨에서만 사용할 수 있습니다.
 a| 
목록



 a| 
위반 심각도입니다
 a| 
중요도가 가장 높은 계층부터 가장 낮은 계층까지 위반 등급(예: 중요)의 순위를 지정합니다(예: 호스트 포트 누락 또는 이중화 누락).
 a| 
목록

|===
[NOTE]
====
별칭, 데이터 센터, 핫, 서비스 레벨, 일몰, 스위치 수준, 서비스 수준, 계층 및 위반 심각성 은 시스템 수준 주석으로, 삭제하거나 이름을 바꿀 수 없습니다. 할당된 값만 변경할 수 있습니다.

====