---
permalink: config-admin/pure-storage-flasharray-http-data-source.html 
sidebar: sidebar 
keywords:  
summary: 'Pure Storage FlashArray\(HTTP\) 데이터 소스는 Pure Storage Flash Array로부터 정보를 수집하는 데 사용됩니다. Insight는 인벤토리 및 성능 수집을 모두 지원합니다.' 
---
= Pure Storage FlashArray 데이터 소스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Pure Storage FlashArray(HTTP) 데이터 소스는 Pure Storage Flash Array로부터 정보를 수집하는 데 사용됩니다. Insight는 인벤토리 및 성능 수집을 모두 지원합니다.



== 용어

OnCommand Insight는 Pure Storage FlashArray 데이터 소스에서 다음 인벤토리 정보를 가져옵니다. Insight에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 소스를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

|===


| 공급업체/모델 기간 | Insight 용어입니다 


 a| 
드라이브(SSD)
 a| 
디스크



 a| 
스토리지
 a| 
스토리지



 a| 
컨트롤러
 a| 
스토리지 노드



 a| 
볼륨
 a| 
볼륨



 a| 
포트
 a| 
포트



 a| 
LUN 맵(호스트, 호스트 그룹, 타겟 포트)
 a| 
볼륨 맵, 볼륨 마스크

|===
[NOTE]
====
이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 소스의 모든 경우를 나타내는 것은 아닙니다.

====


== 요구 사항

* 스토리지 시스템 IP 주소입니다
* Pure 스토리지 시스템의 관리자 계정에 대한 사용자 이름 및 암호입니다.
* 포트 요구 사항: HTTP/HTTPS 80/443




== 구성

|===


| * 필드 * | * 설명 * 


 a| 
FlashArray 호스트
 a| 
FlashArray Management Server의 IIP 주소 또는 정규화된 도메인 이름입니다



 a| 
사용자 이름
 a| 
FlashArray 관리 서버의 사용자 이름입니다



 a| 
암호
 a| 
FlashArray Management Server의 암호입니다

|===


== 고급 구성

|===


| * 필드 * | * 설명 * 


 a| 
연결 유형
 a| 
관리 서버



 a| 
TCP 포트
 a| 
FlashArray 서버에 연결하는 데 사용되는 TCP 포트(기본값 443)



 a| 
연결 시간 초과(초)
 a| 
연결 시간 초과(기본값 60초)



 a| 
재고 폴링 간격(분)
 a| 
재고 조사 간격(기본값: 60분)



 a| 
성능 폴링 간격(초)
 a| 
성능 폴링 간격(기본값 300초)

|===