---
permalink: config-admin/researching-a-failed-data-source.html 
sidebar: sidebar 
keywords:  
summary: '데이터 소스에 "인벤토리 실패!"가 있는 경우 또는 "성능 실패!" 메시지 및 높음 또는 보통 영향의 경우 연결된 정보가 있는 데이터 원본 요약 페이지를 사용하여 이 문제를 조사해야 합니다.' 
---
= 실패한 데이터 소스 조사
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 소스에 " * Inventory failed! * " 또는 " * Performance failed! * " 메시지가 있고 High 또는 Medium Impact가 있는 경우 연결된 정보가 있는 데이터 소스 요약 페이지를 사용하여 이 문제를 조사해야 합니다.



== 단계

. 데이터 원본의 연결된 * 이름 * 을 클릭하여 요약 페이지를 엽니다.
. 요약 페이지에서 * Comments * 영역을 확인하여 이 고장을 조사할 수 있는 다른 엔지니어가 남긴 메모를 읽습니다.
. 성능 메시지를 기록합니다.
. 이 데이터 원본에 적용되는 패치가 있는 경우 링크를 클릭하여 * 패치 페이지 * 를 확인하여 문제가 발생했는지 확인합니다.
. 마우스 포인터를 * 이벤트 타임라인 * 그래프 세그먼트 위로 이동하여 추가 정보를 표시합니다.
. 장치에 대한 오류 메시지를 선택하고 이벤트 타임라인 아래에 표시된 * 오류 세부 정보 * 아이콘을 클릭하면 메시지 오른쪽에 표시됩니다.
+
오류 세부 정보에는 오류 메시지 텍스트, 가능한 원인, 사용 중인 정보 및 문제 해결을 위해 시도할 수 있는 권장 사항이 포함됩니다.

. 이 데이터 소스 영역에서 보고한 장치 영역에서 목록을 필터링하여 관심 있는 장치만 표시할 수 있으며, 장치의 연결된 * 이름 * 을 클릭하여 해당 장치의 _asset 페이지_를 표시할 수 있습니다.
. 이전에 표시된 페이지로 돌아가려면 다음 방법 중 하나를 사용합니다.
+
** 브라우저의 뒤로 화살표를 클릭합니다.
** 뒤로 화살표를 마우스 오른쪽 단추로 클릭하여 페이지 목록을 표시하고 원하는 페이지를 선택합니다.


. 다른 자원에 대한 자세한 정보를 표시하려면 연결된 다른 이름을 클릭합니다.
. 데이터 원본 요약 페이지로 돌아가면 페이지 하단의 * 변경 * 영역을 확인하여 최근 변경으로 인해 문제가 발생했는지 확인합니다.

