---
permalink: config-admin/scrubbing-data-for-transfer-to-support-webui.html 
sidebar: sidebar 
keywords:  
summary: '보안 환경을 갖춘 고객은 NetApp 고객 서비스와 통신하여 데이터베이스 정보를 그대로 유지하면서 발생하는 문제를 해결해야 합니다. OnCommand Insight 스크럽 유틸리티를 사용하면 키워드 및 패턴의 포괄적인 사전을 설정하여 중요한 데이터를 "정리"하고 스크러빙된 파일을 고객 지원 센터로 보낼 수 있습니다.' 
---
= 전송을 지원하기 위해 데이터를 스크러빙합니다
:allow-uri-read: 
:experimental: 
:icons: font
:imagesdir: ../media/


[role="lead"]
보안 환경을 갖춘 고객은 NetApp 고객 서비스와 통신하여 데이터베이스 정보를 그대로 유지하면서 발생하는 문제를 해결해야 합니다. OnCommand Insight 스크럽 유틸리티를 사용하면 키워드 및 패턴의 포괄적인 사전을 설정하여 중요한 데이터를 "정리"하고 스크러빙된 파일을 고객 지원 센터로 보낼 수 있습니다.



== 단계

. 웹 UI에서 * Admin * 을 클릭하고 * Troubleshooting * 을 선택합니다.
. 다른 작업 영역의 페이지 하단에서 * 스크럽 유틸리티 * 링크를 클릭합니다.
+
사전, 스크럽 데이터 및 빌드 사전의 조회, 사용자 지정 키워드, 정규식 등 여러 가지 스크럽 섹션이 있습니다.

. 
+
.. 사전의** 조회** 섹션에서 대체 값을 표시할 코드를 입력하거나 값을 입력하여 해당 값을 대체하는 코드를 표시합니다. 참고: 조회를 수행하기 전에 지원 데이터에서 스크럽할 값을 식별하기 위해 사전을 * 구축 * 해야 합니다.


. 지원 데이터에서 스크럽할 키워드를 직접 추가하려면 * 사용자 정의 키워드 * 섹션에서 메뉴 [사용자 정의 키워드 추가]를 클릭합니다. 키워드를 입력하고 * 저장 * 을 클릭합니다. 키워드가 사전에 추가됩니다.
. 패턴(regexp) * 을 확장합니다. 새 패턴을 입력하기 위한 대화 상자를 표시하려면 * 추가 * 를 클릭합니다.
. 정규식을 사용하여 스크럽할 단어나 구를 식별하려면 * 정규식 * 섹션에 패턴이나 패턴을 입력합니다. 메뉴 클릭: 작업 [정규식 추가], 패턴의 이름 및 필드에 정규식을 입력하고 * 저장 * 을 클릭합니다. 사전에 정보가 추가되었습니다.
+
[NOTE]
====
패턴은 정규식 캡처 그룹을 식별하기 위해 둥근 괄호로 묶어야 합니다.

====
. 빌드 사전** 섹션에서 * 빌드 * 를 클릭하여 OnCommand Insight 데이터베이스에서 중요한 것으로 식별되는 모든 단어의 사전 컴파일을 시작합니다.
+
완료되면 개정된 사전을 사용할 수 있음을 알리는 메시지가 표시됩니다. 데이터베이스 설명에는 사전에 있는 키워드 수를 나타내는 줄이 포함됩니다. 사전에 있는 키워드의 정확성을 확인하십시오. 문제를 찾고 사전을 다시 빌드하려면 데이터베이스 블록에서 * 재설정 * 을 클릭하여 OnCommand Insight 데이터베이스에서 수집한 모든 키워드를 사전에서 제거합니다. 메시지가 표시되면 다른 키워드는 삭제되지 않습니다. 스크럽 유틸리티로 돌아가서 사용자 지정 키워드를 다시 입력합니다.

. 스크럽 사전을 만든 후 이를 사용하여 로그, XML 또는 기타 텍스트 파일을 스크럽하여 데이터를 익명으로 만들 수 있습니다.
. 로그, XML 또는 기타 텍스트 파일을 스크럽하려면 * 스크럽 데이터 * 섹션에서 찾아보기를 클릭하여 파일을 찾은 다음 * 스크럽 파일 * 을 클릭합니다.

