---
permalink: config-admin/violin-memory-data-source.html 
sidebar: sidebar 
keywords:  
summary: 'Violin 6000 시리즈 Flash Memory Array\(HTTP\) 데이터 소스는 Violin 6000 시리즈 플래시 메모리 어레이에서 분석 및 검증을 위해 네트워크 정보를 수집합니다.' 
---
= Violin Flash Memory Array 데이터 소스
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Violin 6000 시리즈 Flash Memory Array(HTTP) 데이터 소스는 Violin 6000 시리즈 플래시 메모리 어레이에서 분석 및 검증을 위해 네트워크 정보를 수집합니다.



== 용어

[NOTE]
====
이 데이터 수집기는 OnCommand Insight 7.3.11부터 더 이상 사용할 수 없습니다.

====
OnCommand Insight는 Violin 6000 시리즈 플래시 메모리 어레이 데이터 소스에서 다음 인벤토리 정보를 수집합니다. Insight에서 획득한 각 자산 유형에 대해 이 자산에 가장 일반적으로 사용되는 용어가 표시됩니다. 이 데이터 소스를 보거나 문제를 해결할 때 다음 용어를 염두에 두십시오.

|===


| 공급업체/모델 기간 | Insight 용어입니다 


 a| 
Violin 지능형 메모리 모듈(VIMM)
 a| 
디스크



 a| 
컨테이너
 a| 
스토리지



 a| 
메모리 게이트웨이
 a| 
스토리지 노드



 a| 
LUN을 클릭합니다
 a| 
볼륨



 a| 
이니시에이터, 이니시에이터 그룹, 타겟
 a| 
볼륨 맵, 볼륨 마스크

|===
[NOTE]
====
이러한 용어 매핑은 일반적인 용어 매핑일 뿐이며 이 데이터 소스의 모든 경우를 나타내는 것은 아닙니다.

====


== 요구 사항

* 스토리지에 대한 읽기 전용 사용자 이름과 암호가 필요합니다.
* 스토리지 IP 주소를 사용하여 웹 브라우저에서 액세스를 검증합니다.




== 구성

|===


| 필드에 입력합니다 | 설명 


 a| 
Violin Memory Array 주 게이트웨이의 IP 주소 또는 FQDN
 a| 
Violin Memory Array Main Gateway의 IP 주소 또는 정규화된 도메인 이름입니다



 a| 
사용자 이름
 a| 
Violin Memory Array 주 게이트웨이의 사용자 이름입니다



 a| 
암호
 a| 
Violin Memory Array 주 게이트웨이의 암호입니다

|===


== 고급 구성

|===


| 필드에 입력합니다 | 설명 


 a| 
통신 포트
 a| 
Violin Array와의 통신에 사용되는 포트입니다



 a| 
HTTPS가 활성화되었습니다
 a| 
HTTPS를 사용하려면 선택합니다



 a| 
재고 폴링 간격(분)
 a| 
재고 조사 간격(기본값 20분)



 a| 
연결 시간 초과(초)
 a| 
연결 시간 초과(기본값 60초)



 a| 
성능 폴링 간격(초)
 a| 
성능 폴링 간격(기본값 300초)

|===