---
permalink: faq/faq-additional-information.html 
sidebar: sidebar 
keywords: redhat,Linux 
summary: 추가 정보는 어디에서 찾을 수 있습니까? 
---
= 추가 정보
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight에 대한 추가 정보는 어디에서 확인할 수 있습니까?



== 데이터 소스 지원

Insight 지원 데이터 원본에 대한 정보는 OnCommand Insight 데이터 원본 지원 매트릭스에서 확인할 수 있습니다. NetApp Support 사이트 자격 증명을 사용하여 로그인하라는 메시지가 표시됩니다.

link:https://mysupport.netapp.com/api/content-service/staticcontents/content/products/oncommandinsight/DatasourceSupportMatrix_7.3.x.pdf["OnCommand Insight 데이터 소스 지원 매트릭스"]현재 지원되는 OnCommand Insight 버전에 대한 지원 매트릭스입니다.



== 지원

link:https://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴(IMT)"]에서는 OnCommand Insight에서 지원하는 장치 및 플랫폼에 대해 설명합니다.

link:https://mysupport.netapp.com/site/products/all/details/oncommand-insight/guideme-tab["NetApp 안내된 문제 해결 방법"]안내식 문제 해결 기능은 선별된 기술 콘텐츠, 사용 방법 리소스, 제품, 기능 및 작업으로 구성된 문제 해결 단계를 제공합니다. 채팅 기능을 사용하면 케이스를 열거나 기술 지원 부서에 문의하지 않고도 신속하게 문제를 해결할 수 있습니다.

NetApp Knowledgebase를 사용하여 제품 관리 및 관리에 대한 기술 문서에 액세스할 수 있습니다. 공개된 기술 자료의 일부 하위 집합을 사용할 수 있습니다. 등록된 사용자는 광범위한 기술 자료 문서에 액세스할 수 있습니다.

NetApp 글로벌 서비스 연락처 해당 지역의 지원 센터에 문의하십시오.



== 커뮤니티

NetApp Storefront는 NetApp의 주요 보고서 템플릿, 솔루션 팩, 데이터 수집기 및 OnCommand Insight에 대한 스크립트 예제를 폭넓게 제공합니다.

OnCommand Insight 비디오 OnCommand Insight 제품 비디오 재생 목록의 다양한 항목에 대한 비디오를 시청하십시오.

Insight 커뮤니티 토론 OnCommand Insight의 토론에 참여할 수 있습니다.



== 기타

IBM Cognos용 IBM Cognos 문서 웹 사이트에서.
