---
permalink: reporting/data-model-overview.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight는 보고서 개발에 사용할 수 있는 여러 가지 데이터 모델을 제공합니다. 각 데이터 모델은 데이터를 요약하는 집계로서, 쿼리하고 검색할 수 있습니다. 예를 들어 용량 계획에 대한 보고서에서는 용량 데이터 모델을 사용합니다. 
---
= 데이터 모델 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight는 보고서 개발에 사용할 수 있는 여러 가지 데이터 모델을 제공합니다. 각 데이터 모델은 데이터를 요약하는 집계로서, 쿼리하고 검색할 수 있습니다. 예를 들어 용량 계획에 대한 보고서에서는 용량 데이터 모델을 사용합니다.

OnCommand Insight 엔터프라이즈 보고 데이터 모델은 데이터 요소 간의 데이터 요소와 상호 관계를 제공하여 데이터를 비즈니스 뷰로 볼 수 있도록 합니다. 데이터 요소와 관계를 사용하면 NetApp에서 권장하는 IBM Cognos Analytics 보고서 생성 도구를 사용하여 보고서를 만들 수 있습니다.

또한 OnCommand Insight는 자체 SQL 쿼리를 개발하는 데 사용할 수 있는 데이터 마트를 제공합니다. 이러한 SQL 쿼리 데이터 마트와 보고에 사용되는 데이터 모델 간에는 차이가 있습니다. 개별 OnCommand Insight 보고 데이터 모델은 데이터 마트에 제공된 기본 OnCommand Insight 데이터베이스 스키마를 사용합니다. 그러나 데이터 모델은 테이블의 추가 테이블과 때로는 새 요소를 사용합니다. 예를 들어 데이터 모델에는 데이터베이스 스키마 및 데이터 마트의 용량 팩트 테이블을 기반으로 하는 스토리지 용량 데이터 모델에 월별 용량 팩트 테이블이 포함됩니다. 데이터 모델은 데이터베이스 스키마 테이블의 값을 필터링하여 월 정보만 표시합니다.

데이터 마트에 사용되는 데이터베이스 스키마와 데이터 모델 간의 차이에 대한 또 다른 예는 위반 테이블과 위반 유형 열에 있습니다. 데이터 모델은 OnCommand Insight 웹 UI에 표시되는 텍스트와 일치하도록 데이터베이스의 프로그래밍 방식의 명명된 값을 변환합니다.
