---
permalink: reporting/reporting-made-easy.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight 보고 포털에서 미리 정의된 보고서를 생성하고, 다른 사용자에게 이메일로 보내고, 수정할 수도 있습니다. 여러 보고서를 통해 장치, 사업체 또는 계층별로 필터링할 수 있습니다. 보고 도구는 IBM Cognos를 기반으로 하며 다양한 데이터 표시 옵션을 제공합니다. 
---
= 간편한 보고
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight 보고 포털에서 미리 정의된 보고서를 생성하고, 다른 사용자에게 이메일로 보내고, 수정할 수도 있습니다. 여러 보고서를 통해 장치, 사업체 또는 계층별로 필터링할 수 있습니다. 보고 도구는 IBM Cognos를 기반으로 하며 다양한 데이터 표시 옵션을 제공합니다.

* OnCommand Insight의 사전 정의 보고서에는 인벤토리, 스토리지 용량, 비용 청구, 성능, 스토리지 효율성, 클라우드 비용 데이터입니다. 이러한 사전 정의된 보고서를 수정하고 수정 사항을 저장할 수 있습니다.


사용 가능한 보고서 데이터는 다음을 비롯한 여러 가지 사항에 의해 제어됩니다.

* 역할에 따라 정의된 OnCommand Insight 보고 포털에 로그인합니다.
* 보고서에 대한 데이터를 저장하는 OnCommand InsightData Warehouse의 설정입니다.


HTML, PDF, CSV, XML 등 다양한 형식의 보고서를 생성할 수 있습니다. Excel을 클릭합니다.

OnCommand Insight는 사용자를 사업부와 연결할 수 있도록 하여 보고에서 다중 임차를 수용합니다. 이 기능을 사용하면 관리자는 사용자 또는 소속 관계 특성에 따라 데이터나 보고서를 분리할 수 있습니다.

[NOTE]
====
Cognos 버전 11.1.2 이상에서는 보고 URL이 "안정성"으로 간주되지 않으며 변경될 수 있습니다. 보고 URL을 북마크한 경우 이러한 북마크가 나중에 실패할 수 있습니다. 자세한 내용은 다음 웹 사이트를 참조하십시오. http://queryvision.com/ibm-analytics-11-x-urls-they-are-a-changing/[]

====
[NOTE]
====
OnCommand Insight는 새로운 데이터 모듈 기능을 사용하지 않는 한 IBM Cognos의 패키지를 사용하여 만든 대시보드를 지원하지 않습니다.

====