---
permalink: install-windows/backing-up-the-data-warehouse-database.html 
sidebar: sidebar 
keywords:  
summary: Cognos 백업도 포함된 데이터 웨어하우스 데이터베이스를 파일에 백업하고 나중에 데이터 웨어하우스 포털을 사용하여 복원할 수 있습니다. 이러한 백업을 사용하면 다른 데이터 웨어하우스 서버로 마이그레이션하거나 새 데이터 웨어하우스 버전으로 업그레이드할 수 있습니다. 
---
= 데이터 웨어하우스 데이터베이스 백업
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Cognos 백업도 포함된 데이터 웨어하우스 데이터베이스를 파일에 백업하고 나중에 데이터 웨어하우스 포털을 사용하여 복원할 수 있습니다. 이러한 백업을 사용하면 다른 데이터 웨어하우스 서버로 마이그레이션하거나 새 데이터 웨어하우스 버전으로 업그레이드할 수 있습니다.



== 단계

. 에서 데이터 웨어하우스 포털에 로그인합니다 `+https://fqdn/dwh+`.
. 왼쪽의 탐색 창에서 * 백업/복원 * 을 선택합니다.
. 백업 * 을 클릭하고 백업 구성을 선택합니다.
+
.. 성능 데이터 마트를 제외한 모든 데이터 마트
.. 모든 데이터 마트


+
이 작업은 30분 이상 소요될 수 있습니다.

+
+ 데이터 웨어하우스는 백업 파일을 만들고 그 이름을 표시합니다.

. 백업 파일을 마우스 오른쪽 단추로 클릭하고 원하는 위치에 저장합니다.
+
파일 이름을 변경하지 않으려는 경우에는 데이터 웨어하우스 설치 경로 외부에 파일을 저장해야 합니다.

+
데이터 웨어하우스 백업 파일에는 DWH 인스턴스의 MySQL, 사용자 정의 스키마(MySQL DB) 및 테이블, LDAP 구성, Cognos를 MySQL 데이터베이스에 연결하는 데이터 소스(Insight 서버를 데이터를 얻기 위해 장치에 연결하는 데이터 소스 아님)가 포함됩니다. 보고서를 가져오거나 내보낸 작업, 보안 역할, 그룹 및 네임스페이스 보고, 사용자 계정 수정된 보고 포털 보고서 및 내 폴더 디렉토리에서도 저장된 위치에 관계없이 모든 사용자 정의 보고서 SMTP 서버 설정 및 Cognos 사용자 지정 메모리 설정과 같은 Cognos 시스템 구성 매개 변수는 백업되지 않습니다.

+
사용자 지정 테이블이 백업되는 기본 스키마는 다음과 같습니다.

+
|===


 a| 
dWh _ 용량



 a| 
dWh_capacity_staging



 a| 
dWh _ 치수



 a| 
dWh_fs_util



 a| 
dWh_재고



 a| 
dWh_inventory_staging



 a| 
dWh_inventory_transient



 a| 
dWh _ 관리



 a| 
더 뛰어난 성능



 a| 
dWh_performance_staging



 a| 
dWh_ports



 a| 
dWh 보고서



 a| 
dWh_sa_staging



 a| 



 a| 



 a| 

|===
+
사용자 지정 테이블이 백업에서 제외되는 스키마는 다음과 같습니다.

+
|===


 a| 
information_schema를 참조하십시오



 a| 
획득



 a| 
CLOUD_MODEL



 a| 
host_data를 선택합니다



 a| 
InnoDB



 a| 
인벤토리



 a| 
Inventory_private을 선택합니다



 a| 
Inventory_Time(재고 시간)



 a| 
로그



 a| 
관리



 a| 
MySQL



 a| 
NAS



 a| 
성능



 a| 
performance_schema를 나타냅니다



 a| 
Performance_views(성능 보기)



 a| 
SANscreen



 a| 
스크럽



 a| 
서비스 보장



 a| 
테스트



 a| 
tmp(tmp)



 a| 
워크벤치



 a| 



 a| 



 a| 

|===
+
수동으로 시작된 모든 백업에서 는 입니다 `.zip` 다음 파일이 포함된 파일이 생성됩니다.

+
** 일일 백업입니다 `.zip` Cognos 보고서 정의가 포함된 파일
** 가 백업을 보고합니다 `.zip` 내 폴더 디렉토리의 보고서를 포함하여 Cognos의 모든 보고서가 들어 있는 파일입니다
** 데이터 웨어하우스 데이터베이스 백업 파일 Cognos는 언제든지 수행할 수 있는 수동 백업 외에도 매일 실행되는 백업(라는 파일에 매일 자동으로 생성됨)을 생성합니다 `DailyBackup.zip`)에 보고서 정의가 포함되어 있습니다. 일일 백업에는 제품과 함께 제공되는 최상위 폴더와 패키지가 포함됩니다. 내 폴더 디렉토리 및 제품의 최상위 폴더 외부에서 생성한 디렉토리는 Cognos 백업에 포함되지 않습니다.


+
[NOTE]
====
Insight에서 파일 이름을 로 지정하는 방식 때문입니다 `.zip` 파일, 일부 압축 해제 프로그램은 파일을 열 때 파일이 비어 있음을 표시합니다. 를 누릅니다 `.zip` 파일의 크기가 0보다 크고 로 끝나지는 않습니다 `.bad` 내선 번호 `.zip` 파일이 유효합니다. 7-Zip 또는 WinZip ® 과 같은 다른 압축 해제 프로그램으로 파일을 열 수 있습니다.

====

