---
permalink: install-windows/data-warehouse-and-reporting-server-requirements.html 
sidebar: sidebar 
keywords:  
summary: 이미 설정된 하드웨어 및 소프트웨어 요구 사항과 호환되는 컴퓨터에서 데이터 웨어하우스 및 보고 서버를 실행해야 Apache 웹 서버 또는 보고 소프트웨어가 이 컴퓨터에 설치되어 있지 않습니다. 
---
= 데이터 웨어하우스 및 보고 서버 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이미 설정된 하드웨어 및 소프트웨어 요구 사항과 호환되는 컴퓨터에서 데이터 웨어하우스 및 보고 서버를 실행해야 Apache 웹 서버 또는 보고 소프트웨어가 이 컴퓨터에 설치되어 있지 않습니다.

[NOTE]
====
OnCommand Insight를 위한 사이징에는 운영 환경의 자산 수, 유지되는 기간별 데이터 양 등과 같은 다양한 종속 관계가 있습니다. 다음 데이터 웨어하우스 사이징 예는 지침일 뿐이며 Insight가 테스트된 일부 환경을 나타냅니다. 환경의 이러한 요인 또는 기타 요소를 변경하면 Insight의 사이징 요구 사항이 변경될 수 있습니다.

====
Insight를 설치 또는 업그레이드하기 전에 세일즈 엔지니어에게 자세한 사이징 지침을 문의하는 것이 좋습니다.

* 예: *

|===


| 환경 요인: | 테스트한 디스크 공간, CPU 및 메모리: 


 a| 
스토리지 18개가상 머신 3,400개

4,500개의 스위치 포트
 a| 
200GB 하드 디스크8 코어

32GB RAM



 a| 
110개의 스토리지 어레이11,500개의 VM을 제공합니다

14,500개의 스위치 포트
 a| 
300GB 하드 디스크8 코어

48GB RAM

|===
* 요구 사항: *

|===


| 구성 요소 | 필수 요소입니다 


 a| 
운영 체제
 a| 
최신 서비스 팩이 설치된 64비트 Microsoft Windows Server 2016, 2019 또는 2022를 실행하는 컴퓨터. OnCommand Insight를 설치하기 전에 Windows .NET Framework 버전 3.5를 설치해야 합니다.



 a| 
가상 머신(VM)
 a| 
이 구성 요소는 인스턴스에 대한 CPU 및 메모리 리소스가 예약되어 있는 경우 가상 환경에서 실행될 수 있습니다.



 a| 
CPU
 a| 
8-40개의 CPU 코어



 a| 
메모리
 a| 
32GB - 2TB RAM 모범 사례: 페이징 파일 크기를 ""Windows 관리"로 설정하는 것이 좋습니다. 크기가 작은 페이징 파일은 Insight 성능 데이터의 성공적인 저장을 방해할 수 있습니다.



 a| 
사용 가능한 디스크 공간입니다
 a| 
200GB - 2TB 디스크 공간 설치 시 C: 드라이브에 최소 20GB의 여유 공간이 필요합니다.


NOTE: Windows에서 Insight Data Warehouse with Reporting을 사용하려면 설치 드라이브에 8dot3 이름 생성 지원을 활성화해야 합니다. 일반적으로 C: 드라이브에는 이 기능이 기본적으로 활성화되어 있습니다. 다음 명령을 실행하여 타겟 설치 드라이브에서 8dot3 이름 생성이 활성화되었는지 확인할 수 있습니다(D: 타겟 설치 드라이브로 대체).

Fsutil 8dot3name 쿼리 D:

8dot3 이름 생성을 활성화하려면 다음 명령을 실행합니다(D: 대상 설치 드라이브로 대체).

fsutil 8dot3name 집합 D:0



 a| 
네트워크
 a| 
* 100Mbps 또는 1Gbps 이더넷 연결
* 고정 IP 주소입니다
* Windows에 Reporting이 있는 데이터 웨어하우스를 설치하기 전에 포트 50000을 사용할 수 있어야 합니다
* OnCommand Insight DWH 서버 프로세스의 경우 포트 80, 443, 1098, 1099, 3873, 8083, 4444 ~ 4446
* 보고 엔진용 포트 1527, 9362, 9300 및 9399
* MySQL의 경우 포트 3306입니다
* 을 수행하여 DNS가 제대로 작동하는지 확인합니다 `nslookup` 호스트 반대입니다




 a| 
바이러스 검사
 a| 
이 OnCommand Insight 구성 요소를 설치하는 동안 모든 바이러스 스캐너를 완전히 비활성화해야 합니다. 설치 후에는 Insight 구성 요소(설치, 백업 및 Archiver 경로)와 모든 DWH 구성 요소 설치 경로(SANscreen, DB2 및 백업 경로)에 사용되는 경로를 바이러스 검사에서 제외해야 합니다.



 a| 
Visual Studio를 참조하십시오
 a| 
Visual Studio 2019 https://docs.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist["재배포판"] Windows에 Reporting을 사용하여 데이터 웨어하우스를 설치하기 전에 설치해야 합니다.

|===