---
permalink: install-windows/downloading-the-installation-packages.html 
sidebar: sidebar 
keywords:  
summary: '업그레이드하기 전에 Insight, Data Warehouse 및 Remote Acquisition Unit\(해당되는 경우\)에 대한 설치 패키지를 다운로드해야 합니다. 패키지 다운로드 시간(.msi 파일\)은 사용 가능한 대역폭에 따라 다릅니다.' 
---
= OnCommand Insight 설치 패키지를 다운로드합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
업그레이드하기 전에 Insight, Data Warehouse 및 Remote Acquisition Unit(해당되는 경우)에 대한 설치 패키지를 다운로드해야 합니다. 패키지 다운로드 시간 (`.msi` 파일)은 사용 가능한 대역폭에 따라 다릅니다.



== 이 작업에 대해

Insight WebUI를 사용하거나 에서 해당 OnCommand Insight 링크로 이동하여 설치 패키지를 다운로드할 수 있습니다 http://support.netapp.com/NOW/cgi-bin/software[].

Insight 서버 내에서 설치 패키지를 다운로드하려면 다음을 수행합니다.



== 단계

. 웹 브라우저를 열고 다음 중 하나를 입력하여 Insight 웹 UI를 엽니다.
+
** Insight 서버: `+https://localhost+`
** 모든 위치: `+https://IP Address:port or fqdn:port+`
+
포트 번호는 443 또는 Insight 서버를 설치할 때 구성된 포트입니다. URL에 포트 번호를 지정하지 않으면 포트 번호는 443으로 기본 설정됩니다.



. Insight에 로그인합니다.
. 도움말 아이콘을 클릭하고 * 업데이트 확인 * 을 선택합니다.
. 최신 버전이 감지되면 메시지 상자의 지침을 따르십시오.
+
최신 버전의 InsightDescription 페이지로 이동합니다.

. 설명 * 페이지에서 * 계속 * 을 클릭합니다.
. 최종 사용자 사용권 계약(EULA)이 표시되면 * 동의 * 를 클릭합니다.
. 각 구성 요소(Insight 서버, 데이터 웨어하우스, 원격 획득 장치) 등에 대한 설치 패키지 링크를 클릭하고 * 다른 이름으로 저장 * 을 클릭하여 설치 패키지를 저장합니다.
+
업그레이드하기 전에 데이터 웨어하우스 및 원격 획득 장치 설치 패키지를 해당 서버에 로컬인 디스크에 복사해야 합니다.

. checksum * 을 클릭하고 각 설치 패키지와 관련된 숫자 값을 기록합니다.
. 설치 패키지를 다운로드한 후 오류 없이 설치가 완료되었는지 확인합니다.
+
파일 전송이 완료되지 않으면 업그레이드 프로세스에 문제가 발생할 수 있습니다.

+
설치 패키지에 대한 MD5 해시 값을 생성하려면 Microsoft와 같은 타사 유틸리티를 사용하십시오link:HTTP://SUPPORT.MICROSOFT.COM/KB/841290["파일 ChecksumIntegrity Verifier"] 유틸리티.


