---
permalink: install-windows/insight-server-requirements.html 
sidebar: sidebar 
keywords: redhat 
summary: OnCommand Insight 서버 구성 요소 설치 요구 사항 
---
= Insight Server 요구사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
전용 서버가 권장됩니다. 다른 애플리케이션이 설치된 서버에 Insight를 설치하지 마십시오. 제품 요구 사항이 충족되는 경우 물리적 서버와 가상 서버가 모두 지원됩니다.

OnCommand Insight 서버 소프트웨어를 설치하려면 로컬 관리자 권한이 있어야 합니다.

[NOTE]
====
OnCommand Insight 크기 조정에는 데이터 소스 유형 및 크기, 환경의 자산 수, 폴링 간격 등 다양한 종속 항목이 있습니다. 다음 사이징 예는 지침일 뿐이며 Insight가 테스트된 환경의 일부를 나타냅니다. 환경의 이러한 요인 또는 기타 요소를 변경하면 Insight의 사이징 요구 사항이 변경될 수 있습니다. 이러한 지침에는 최대 90일간의 성능 아카이브 데이터를 위한 디스크 공간이 포함되어 있습니다.

====
Insight를 설치 또는 업그레이드하기 전에 세일즈 엔지니어에게 자세한 사이징 지침을 문의하는 것이 좋습니다.

* 예: *

|===


| 환경 요인: | 테스트한 디스크 공간, CPU 및 메모리: 


 a| 
80개 스토리지 4,000개 볼륨

4,000개의 VM

4,000개의 스위치 포트
 a| 
250GB 디스크 공간 8코어

32GB RAM



 a| 
160 스토리지 어레이40,000개의 볼륨

8,000개의 VM

8,000개의 스위치 포트
 a| 
1TB 디스크 공간 12개 코어

48GB RAM

|===
* 요구 사항: *

|===


| 구성 요소 | 필수 요소입니다 


 a| 
운영 체제
 a| 
최신 서비스 팩이 설치된 64비트 Microsoft Windows Server 2016, 2019 또는 2022를 실행하는 컴퓨터.

Windows Server 2012에 도입된 복구 파일 시스템(ReFS)은 OnCommand Insight와 호환되지 않습니다. OnCommand Insight의 Windows 설치는 NTFS 파일 시스템에서만 지원됩니다.

전용 서버가 권장됩니다.



 a| 
가상 머신(VM)
 a| 
이 구성 요소는 인스턴스에 대한 CPU 및 메모리 리소스가 예약되어 있는 경우 가상 환경에서 실행될 수 있습니다.



 a| 
메모리 및 CPU
 a| 
24-256GB RAM

8~32코어

페이징 파일 크기를 "Windows 관리"로 설정하는 것이 좋습니다. 크기가 작은 페이징 파일은 Insight 성능 데이터의 성공적인 저장을 방해할 수 있습니다.



 a| 
사용 가능한 디스크 공간입니다
 a| 
100GB - 3TB 설치 디스크 공간

50GB - 1TB 성능 아카이브 디스크 공간

Insight 설치 공간에는 SSD 디스크를 사용하는 것이 좋습니다.



 a| 
네트워크
 a| 
이더넷 연결 및 포트:

* FC 장치 및 원격 획득 장치를 포함하여 SAN의 모든 구성 요소에 대한 전용(정적) IP 주소 및 IP 연결을 통한 100Mbps 또는 1Gbps 이더넷 연결
* OnCommand Insight 서버 프로세스의 포트 요구 사항은 80, 443, 1090 ~ 1100, 3873, 8083입니다. 4444 ~ 4446, 5445, 5455, 4712 ~ 4714, 5500, 및 5501을 참조하십시오.
* 획득 프로세스의 포트 요구 사항은 12123 및 5679입니다.
* MySQL의 포트 요구 사항은 3306입니다.
* Elasticsearch의 포트 요구 사항은 9200 및 9310입니다
* Win2008/2012의 동적 포트 요구 사항은 49152 ~ 65535입니다


포트 443 및 3306은 존재하는 방화벽을 통해 외부 액세스를 필요로 합니다.



 a| 
권한
 a| 
OnCommand Insight 서버에 로컬 관리자 권한이 필요합니다.

다음 폴더 중 하나가 심볼 링크인 경우 대상 디렉토리에 '755' 권한이 있는지 확인하십시오.

* /opt/NetApp을 참조하십시오
* /var/lib/netapp
* /var/log/netapp




 a| 
원격 연결
 a| 
WebEx 액세스를 위한 인터넷 연결 또는 설치 및 설치 후 지원을 위한 원격 데스크톱 연결



 a| 
접근성
 a| 
HTTPS 액세스가 필요합니다.



 a| 
바이러스 검사
 a| 
이 OnCommand Insight 구성 요소를 설치하는 동안 모든 바이러스 스캐너를 완전히 비활성화해야 합니다. 설치 후에는 Insight 구성 요소(설치, 백업 및 Archiver 경로)에서 사용하는 경로를 바이러스 검사에서 제외해야 합니다.

또한 설치 후 바이러스 백신 검사에서 IBM/DB2 폴더(예: _C:\Program Files\IBM\DB2_)를 제외해야 합니다.



 a| 
HTTP 또는 HTTPS 서버
 a| 
Microsoft IIS(인터넷 정보 서비스) 또는 다른 HTTPS 서버는 OnCommand Insight 서버와 동일한 포트(443)에 대해 경쟁해서는 안 되며 자동으로 시작해서는 안 됩니다. 포트 443을 수신해야 하는 경우 다른 포트를 사용하도록 OnCommand Insight 서버를 구성해야 합니다.

|===