---
permalink: install-windows/insight-upgrade-checklist.html 
sidebar: sidebar 
keywords: 6.4 
summary: 제공된 체크리스트를 사용하여 업그레이드를 준비하는 동안 진행 상황을 기록할 수 있습니다. 이러한 작업은 업그레이드 실패 위험을 완화하고 복구 및 복원 작업을 신속하게 수행하는 데 도움이 됩니다. 
---
= OnCommand Insight 업그레이드 체크리스트
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
제공된 체크리스트를 사용하여 업그레이드를 준비하는 동안 진행 상황을 기록할 수 있습니다. 이러한 작업은 업그레이드 실패 위험을 완화하고 복구 및 복원 작업을 신속하게 수행하는 데 도움이 됩니다.



== 업그레이드 준비 체크리스트(필수)

|===


| 조건 | 완료? 


 a| 
모든 Insight 서버에서 업그레이드 프로세스를 수행하는 데 필요한 Windows 로컬 관리자 권한이 있는지 확인합니다.
 a| 



 a| 
Insight, Data Warehouse 또는 Remote Acquisition Unit 서버가 32비트 플랫폼에 상주하는 경우 서버를 64비트 플랫폼으로 업그레이드해야 합니다. Insight 7.x는 64비트 플랫폼에서만 업그레이드할 수 있습니다.
 a| 



 a| 
사용자 환경의 모든 서버에서 바이러스 백신 소프트웨어를 수정하거나 비활성화하는 데 필요한 권한이 있는지 확인합니다. 활성 바이러스 검사 소프트웨어로 인한 업그레이드 실패를 방지하려면 Insight 설치 디렉터리를 제외해야 합니다 (`disk drive:\install directory\sanscreen` 업그레이드 중 바이러스 백신 검사에 액세스할 수 있습니다. 모든 구성 요소를 업그레이드한 후 바이러스 백신 소프트웨어를 안전하게 다시 활성화할 수 있습니다. 그러나 Insight 설치 디렉터리의 모든 내용을 제외하도록 검사를 구성해야 합니다.

또한 설치 후 바이러스 백신 검사에서 IBM/DB2 폴더(예: _C:\Program Files\IBM\DB2_)를 제외해야 합니다.
 a| 

|===


== 업그레이드 준비 체크리스트(모범 사례)

|===


| 조건 | 완료? 


 a| 
업그레이드 시기를 계획하십시오. 대부분의 업그레이드는 최소 4~8시간이 소요되고, 대기업은 더 오래 걸립니다. 업그레이드 시간은 사용 가능한 리소스(아키텍처, CPU 및 메모리), 데이터베이스 크기 및 환경에서 모니터링되는 개체의 수에 따라 달라질 수 있습니다.
 a| 



 a| 
업그레이드 계획에 대해 계정 담당자에게 문의하고 설치한 Insight 버전과 업그레이드하려는 버전을 제공하십시오.
 a| 



 a| 
Insight, 데이터 웨어하우스 및 원격 획득 장치에 할당된 현재 리소스가 권장 사양을 충족하는지 확인합니다. 모든 서버에 대한 권장 사이징 지침을 참조하거나 계정 담당자에게 문의하여 사이징 지침을 논의할 수 있습니다.
 a| 



 a| 
데이터베이스 백업 및 복원 프로세스에 충분한 디스크 공간이 있는지 확인합니다. 백업 및 복원 프로세스에는 Insight 및 데이터 웨어하우스 서버의 백업 파일에 사용되는 디스크 공간의 약 5배가 필요합니다. 예를 들어 50GB 백업에는 250GB에서 300GB의 사용 가능한 디스크 공간이 필요합니다.
 a| 



 a| 
Insight 및 Data Warehouse 데이터베이스를 백업할 때 Firefox ® 또는 Chrome ™ 브라우저에 액세스할 수 있는지 확인합니다. 4GB보다 큰 파일을 업로드 및 다운로드할 때 문제가 발생하기 때문에 Internet Explorer는 권장되지 않습니다.
 a| 



 a| 
를 삭제합니다 `.tmp` 다음 위치에서 찾을 수 있는 Insight 서버의 파일: `<install directory>\SANscreen\wildfly\standalone\tmp`.
 a| 



 a| 
Insight 클라이언트에서 중복 데이터 소스 및 사용 중지된 데이터 소스를 제거합니다. 사용 중단되거나 중복된 데이터 원본을 제거하면 업그레이드를 수행하는 데 필요한 시간이 줄어들고 데이터 손상 가능성이 줄어듭니다.
 a| 



 a| 
Insight와 함께 제공된 기본 보고서를 수정한 경우 보고서를 다른 이름으로 저장한 다음 고객 보고서 폴더에 저장하여 시스템을 업그레이드 또는 복원할 때 수정된 보고서를 잃지 않도록 해야 합니다.
 a| 



 a| 
사용자나 전문 서비스에서 만든 사용자 지정 또는 수정된 데이터 웨어하우스 보고서가 있는 경우 이를 XML로 내보낸 다음 고객 보고서 폴더로 이동하여 백업을 만듭니다. 백업이 데이터 웨어하우스 서버에 있지 않은지 확인합니다. 보고서를 권장 폴더로 이동하지 않으면 업그레이드 프로세스에서 이러한 보고서가 백업되지 않을 수 있습니다. 이전 버전의 Insight에서 해당 폴더에서 보고서를 찾지 못하면 사용자 지정 보고서와 수정된 보고서가 손실될 수 있습니다.
 a| 



 a| 
IBM Cognos 구성 유틸리티의 모든 설정을 기록합니다. 이러한 설정은 데이터 웨어하우스 백업에 포함되지 않으므로 업그레이드 후에 다시 구성해야 합니다. 이 유틸리티는 에 있습니다 `disk drive:\install directory\SANscreen\cognos\c10_64\bin64` 데이터 웨어하우스 서버의 디렉터리이며 을 사용하여 실행합니다 `cogconfigw` 명령. 또는 Cognos의 전체 백업을 수행한 다음 모든 설정을 가져올 수 있습니다. 자세한 내용은 IBM Cognos 설명서를 참조하십시오.
 a| 

|===


== 업그레이드 준비 체크리스트(해당하는 경우)

|===


| 조건 | 완료? 


 a| 
브라우저 보안 경고로 인해 Insight 설치가 생성한 자체 서명된 인증서를 내부 인증 기관이 서명한 인증서로 대체한 경우 다음 위치에 있는 키 저장소 파일을 백업합니다. `disk drive:\install directory\SANscreen\wildfly\standalone\configuration` 업그레이드 후 복원합니다. 이렇게 하면 Insight에서 만든 자체 서명된 인증서가 서명된 인증서와 교체됩니다.
 a| 



 a| 
사용자 환경에서 수정된 데이터 소스가 있고 업그레이드하는 Insight 버전에서 이러한 수정 사항이 사용 가능한지 확실하지 않은 경우 다음 디렉토리의 복사본을 만듭니다. 이 디렉토리는 복구 문제가 있을 경우 문제를 해결하는 데 도움이 됩니다. `disk drive:\install directory\SANscreen\wildfly\standalone\deployments\datasources.war`.
 a| 



 a| 
를 사용하여 모든 사용자 지정 데이터베이스 테이블 및 뷰를 백업합니다 `mysqldump` 명령줄 도구. 사용자 지정 데이터베이스 테이블을 복원하려면 권한이 있는 데이터베이스 액세스가 필요합니다. 이러한 테이블 복원에 대한 자세한 내용은 기술 지원 부서에 문의하십시오.
 a| 



 a| 
Insight 데이터 소스, 백업 또는 기타 필수 데이터에 필요한 사용자 지정 통합 스크립트, 타사 구성 요소가 에 저장되지 않도록 합니다 `disk drive:\install directory\sanscreen` 업그레이드 프로세스에서 이 디렉토리의 내용이 삭제되므로 디렉토리입니다. 이러한 항목을 에서 이동시키십시오 `\sanscreen` 다른 위치에 디렉토리를 지정합니다. 예를 들어 환경에 사용자 지정 통합 스크립트가 포함되어 있는 경우 다음 파일을 이 아닌 다른 디렉터리에 복사해야 합니다 `\sanscreen` 디렉터리:

`\install_dir\SANscreen\wildfly\standalone\deployments\datasources.war\new_disk_models.txt`.
 a| 

|===