---
permalink: install-windows/installing-a-remote-acquisition-unit-rau.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight 환경에 하나 이상의 RA를 설치합니다. 
---
= 원격 획득 장치(RAU) 설치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight 환경에 하나 이상의 RA를 설치합니다.



== 시작하기 전에

설치 필수 구성 요소를 모두 완료해야 합니다.

변경 정보를 서버로 전달하려면 RAU 서버와 OnCommand Insight 서버 간에 하나 이상의 포트를 열고 사용할 수 있어야 합니다. 확실하지 않은 경우 RAU 컴퓨터에서 웹 브라우저를 열고 OnCommand Insight 서버로 전달하여 유효성을 검사합니다.

[listing]
----
 https://< OnCommand Insight Server hostname >:< acquisition_port >
----
획득 포트는 기본적으로 443으로 설정되지만 서버 설치 중에 변경되었을 수 있습니다. 연결에 성공하면 RAU와 OnCommand Insight 서버 간에 사용 가능한 포트가 열려 있음을 나타내는 OnCommand Insight 응답 페이지가 나타납니다.



== 단계

. 관리자 권한이 있는 계정을 사용하여 RAU 서버에 로그인합니다.
. Windows 탐색기를 열고 RAU 설치 파일이 있는 디렉터리로 이동합니다.
. 두 번 클릭합니다 `.MSI` 파일을 클릭하여 설치를 시작합니다.
. 라이센스 계약을 표시하는 창으로 계속 진행하려면 * 다음 * 을 클릭합니다. 이 내용을 읽고 사용권 계약 내용에 동의한 후 * 다음 * 을 클릭합니다.
. 로컬 하드 드라이브에 RAU를 설치하거나 로컬 하드 드라이브에 전체 기능을 설치하려면 선택합니다. 디스크 사용 링크를 확인하여 공간이 충분한지 확인할 수 있습니다. 116MB가 필요합니다. 다음 * 을 클릭합니다.
. 구성 창에서 사이트에 특정한 다음 매개 변수를 설정합니다.
+
** * OnCommand Insight * * * 서버 이름 또는 주소 * - OnCommand Insight 서버를 식별하기 위한 호스트 이름 또는 IP 주소입니다. RAU는 이 이름/IP를 사용하여 서버와의 통신 링크를 엽니다. 호스트 이름을 지정하는 경우 DNS를 통해 호스트 이름을 확인할 수 있는지 확인합니다.
** * 획득 장치 이름 * - RAU를 식별하는 고유한 이름입니다.
** * OnCommand Insight 보안 원격 획득 포트(HTTPS) * - 환경 변경 정보를 OnCommand Insight 서버로 전송하기 위해 원격 획득 장치에서 사용하는 포트입니다. 이 설정은 OnCommand Insight 서버를 설치할 때 입력한 값과 일치해야 하며 모든 RA에서 동일해야 합니다.


. 선택 사항을 검토합니다. 뒤로 돌아가 변경하려면 * 뒤로 * 를 클릭합니다. 다음 * 을 클릭합니다.
. 설치를 시작하려면 * 설치 * 를 클릭합니다.
+
설치가 완료될 때까지 기다립니다. 이 작업은 약 5-10분 정도 걸립니다.





== 작업을 마친 후

설치가 완료되면 최종 창이 나타납니다. 원격 촬영 서비스 시작 * 상자를 클릭하여 RAU를 시작하고 * 마침 * 을 클릭하여 이 작업을 종료합니다.
