---
permalink: install-windows/installing-the-anomaly-detection-software.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight에는 머신 러닝 이상 탐지 기능을 Insight 데이터에 적용하는 소프트웨어가 포함되어 있습니다. 이 소프트웨어는 다른 OnCommand Insight 구성 요소와 별도로 설치할 수 있습니다. 
---
= 이상 현상 감지 소프트웨어 설치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight에는 머신 러닝 이상 탐지 기능을 Insight 데이터에 적용하는 소프트웨어가 포함되어 있습니다. 이 소프트웨어는 다른 OnCommand Insight 구성 요소와 별도로 설치할 수 있습니다.



== 시작하기 전에

설치 필수 구성 요소를 모두 완료해야 합니다.



== 단계

. sudo 권한이 있는 계정을 사용하여 이상 탐지 서버에 로그인합니다.
. 를 복사합니다 `.zip` Linux 서버에 대한 이상 탐지 소프트웨어가 포함된 파일입니다.
. 에 파일의 압축을 풉니다 `oci-prelert-<version>-linux-x86_64` 디렉토리.
. 설치 프로그램이 있는 디렉토리로 이동합니다. `cd oci-prelert-<version>-linux-x86_64`
. 이상 현상 감지 소프트웨어를 설치합니다. `sudo ./oci-prelert-install.sh`
+
설치 중에 OnCommand Insight 서버의 서버 이름 또는 IP 주소와 관리자 권한이 있는 계정의 사용자 이름 및 암호를 입력하라는 메시지가 표시됩니다.

+
다음 명령을 사용하여 이상 탐지 소프트웨어를 제거할 수 있습니다. `sudo /usr/bin/oci-prelert-uninstall.sh`





== 결과

소프트웨어는 설치 시 지정된 OnCommand Insight 인스턴스에 자동으로 등록됩니다. 소프트웨어는 등록된 OnCommand Insight 인스턴스와만 통신할 수 있으며, 소프트웨어 인스턴스는 OnCommand Insight 서버에 하나만 등록할 수 있습니다.

이상 현상 감지 소프트웨어 또는 Insight 서버를 실행 중인 서버를 다시 시작하면 이상 현상 감지 프로세스가 자동으로 다시 시작됩니다.

[NOTE]
====
매개 변수에 대한 설치 프롬프트를 표시하는 대신 매개 변수를 제공하여 명령줄을 통해 이상 징후 탐지 소프트웨어를 설치하는 경우 다음 매개 변수를 제공하지 않으면 Insight 서버에 등록하지 못합니다. `--path rest/v1`

====