---
permalink: install-windows/installing-the-oncommand-insight-data-warehouse-and-reporting.html 
sidebar: sidebar 
keywords:  
summary: '설치는 자동으로 포함되어 있으며 DWH(OnCommand Insight Data Warehouse)\ 및 보고 유틸리티를 실행하고 운영하는 데 필요한 요소를 포함합니다.' 
---
= OnCommand Insight 데이터 웨어하우스 및 보고 설치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
설치는 자체 완비되었으며 DWH(OnCommand Insight Data Warehouse) 및 보고 유틸리티를 실행하고 운영하는 데 필요한 요소를 포함합니다.



== 시작하기 전에

설치 또는 업그레이드하기 전에 다음 사항을 확인하십시오.

* 업그레이드 중인 경우 DWH를 백업합니다.
* 보고 기능이 있는 OnCommand Insight 데이터 웨어하우스를 설치하려면 로컬 __administrator_ 권한이 있어야 합니다.
* Windows 모듈 설치 관리자 서비스가 활성화되어 있는지 확인합니다(자동 또는 수동으로).
* C: 드라이브가 아닌 드라이브에 설치하는 경우 짧은 파일 이름을 활성화해야 합니다. 활성화되지 않은 경우 설치 프로그램이 이를 활성화합니다.
* DB2 구성 요소의 경우 DB2 사용자는 _domain_user 또는 _local_user 일 수 있습니다.
+
** DB2 사용자가 _DOMAIN_USER인 경우 다음이 있어야 합니다.
+
*** DB2 사용자가 이미 생성되어 있어야 하며 사용자 이름과 암호를 알고 있어야 합니다
*** 보고 기능이 있는 DWH를 설치하는 사용자는 DB2 사용자를 쿼리할 수 있어야 합니다. 다음 명령을 사용하여 이 기능을 검증할 수 있습니다.
+
**** `net user <db2 user name> /domain`




** DB2 사용자가 _LOCAL_USER인 경우 다음이 있어야 합니다.
+
*** DB2 사용자로 실행하는 데 사용할 사용자의 사용자 이름 및 암호입니다. 이 사용자가 없으면 설치 프로그램이 해당 사용자를 생성합니다.


** [참고]




[]
====
DB2 사용자 이름 및 Windows 로그인 이름에는 다음과 같은 제한이 있습니다. * 유효한 문자는 'A' ~ 'Z', 'A' ~ 'z', '0' ~ '9', '#';'@'; '_';'!';'(';')';'{'; '}';'-'; 및 '.'. * 특수 문자 '!';'(';')';'{';'}'를 사용하는 경우 '-'; 및 '.' 사용자 이름에 대문자를 모두 사용해야 합니다. * 문자열의 첫 번째 문자는 영문자 @, # 또는 $ 여야 합니다. 숫자 또는 문자 시퀀스 _SYS_, _dBm_ 또는 _IBM_* 중 하나여야 합니다. 길이는 128바이트를 초과할 수 없습니다. * 사용자, 관리자, 게스트, 공용, 로컬 또는 SQL 예약 단어는 사용할 수 없습니다.

====
* DB2 사용자는 설치를 수행하는 사용자와 같을 수 없습니다.




== 단계

. 관리자 권한이 있는 계정을 사용하여 데이터 웨어하우스 서버에 로그인합니다.
. Reporting.zip 파일이 있는 데이터 웨어하우스를 다운로드하고 설치 폴더에 압축을 풉니다.
. <download location>\OCI_dWh_installer\_ 폴더로 이동하여 _INSTALL_OCI_dWh.bat_script를 실행합니다.
+
[NOTE]
====
OnCommand Insight 7.3.10 이상에서는 적절한 DWH/Reporting 설치를 위해 스크립트를 실행해야 합니다. MSI 설치 실행 파일을 실행하지 마십시오.

====
. DB2 도메인을 입력하거나 로컬 도메인에 대해 Enter 키를 누릅니다.
. DB2 사용자 이름을 입력합니다. 사용자 이름 제한에 대해서는 위 항목을 참조하십시오.
. DB2 사용자의 암호를 입력합니다. 메시지가 나타나면 암호를 다시 입력합니다.
. DB2 구성 요소의 설치 경로를 입력하거나 기본값으로 Enter 키를 누릅니다.
. 입력한 정보가 표시됩니다. 모든 설정을 주의 깊게 확인하십시오. Enter 키를 눌러 설치를 시작합니다.
. 메시지가 표시되면 Windows에서 DB2 설치를 계속 진행하도록 허용합니다.
. DB2 설치 후 DWH 설치 마법사가 실행됩니다. 지침에 따라 DWH with Reporting을 설치합니다.
+
보고 설치를 완료하는 데 최대 1시간이 소요될 수 있습니다.


