---
permalink: install-windows/installing-the-oncommand-insight-server.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight 설치 마법사를 사용하여 OnCommand Insight 서버를 쉽게 설치할 수 있습니다. 
---
= OnCommand Insight 서버 설치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight 설치 마법사를 사용하여 OnCommand Insight 서버를 쉽게 설치할 수 있습니다.



== 시작하기 전에

설치 필수 구성 요소를 모두 완료해야 합니다.


NOTE: OnCommand Insight를 업그레이드하는 경우, 현재 버전을 제거하거나 업그레이드하기 전에 * 볼트를 백업해야 합니다 *.



== 단계

. 관리자 권한이 있는 계정을 사용하여 Insight 서버에 로그인합니다.
. Windows 탐색기를 열고 설치 파일이 있는 디렉터리로 이동합니다.
. 를 두 번 클릭합니다 `.MSI` 파일을 다운로드했습니다.
. 계속하려면 * 다음 * 을 클릭합니다.
. 사용권 계약을 읽고 사용권 계약 * 확인란의 조건에 동의합니다 * 를 선택한 후 * 다음 * 을 클릭합니다.
. 고객 정보 * 창에 고객 이름과 사이트 이름을 입력하고 * 다음 * 을 클릭합니다.
+
* 모범 사례: * 고객 이름을 사이트 접두사로 사용합니다(예: NetApp).

. 관리자 암호를 입력합니다. 암호를 확인합니다.
. 고객 정보: NetApp ASUP * 구성 창에서 다음을 수행합니다.
+
.. 다음 옵션 중 하나를 선택하여 ASUP에 업로드할 데이터가 포함된 데이터베이스를 선택합니다.
+
*** * 데이터베이스 백업 없음 *: 백업이 ASUP로 전송되지 않습니다.
*** * 성능 데이터 없이 백업 *: 백업이 수행되어 ASUP로 전송되지만 성능 데이터는 포함되지 않습니다.
*** * 성능 데이터를 사용한 백업 *: 성능 데이터가 포함된 백업이 만들어지지만 이로 인해 엄청난 문제가 발생할 수 있습니다 `*.gz` 파일.




+
[NOTE]
====
ASUP는 HTTPS 프로토콜을 사용하여 제공됩니다.

====
+
.. 로그 * 에서 데이터 소스 기록을 포함하는 로그, 기본 로그 또는 확장 로그를 사용하지 않도록 선택합니다.
.. 다음 * 을 클릭합니다.


. Insight 소비 라이센스 모델을 사용하는 경우 * Send usage information * 섹션에서 * Enable susage information to NetApp * 확인란을 선택해야 합니다.
. 다음 * 을 클릭합니다
. 서버 구성* 창에서 OnCommand Insight 서버를 구성하기 위한 적절한 구성 매개 변수를 선택하거나 설정합니다.
+
|===


| 옵션을 선택합니다 | 설명 


 a| 
포털 포트(HTTP)
 a| 
관리 작업을 수행하기 위한 포털을 포함하여 사용자 웹 서비스를 지원하기 위해 OnCommand Insight 서버에서 사용하는 포트입니다. 기본값(80)을 사용합니다. 그러나 기본 포트가 사용 중이면 다른 포트로 변경합니다.



 a| 
포털 포트(HTTPS)
 a| 
보안 채널을 통해 SAN 변경 정보를 OnCommand Insight 서버로 전송하기 위해 원격 획득 장치에서 사용하는 포트입니다. 기본값(443)을 사용합니다. 그러나 기본 포트가 사용 중이면 다른 포트로 변경합니다. RA를 구성할 때 동일한 포트 번호를 지정합니다.



 a| 
내부 데이터베이스 포트(SQL)
 a| 
OnCommand Insight 서버가 실행 중인 PC에서 데이터베이스에 대한 액세스 지점 역할을 하기 위해 내부적으로 사용하는 포트입니다. 기본값(3306)을 사용합니다. 그러나 기본 포트가 사용 중이면 다른 포트로 변경하십시오.

|===
. 다음 * 을 클릭합니다.
. 계속하려면 * 설치 * 를 클릭하십시오.
+
설치된 응용 프로그램에 따라 약 20분 정도 소요됩니다.

. 마침 * 을 클릭합니다.
. 원격 획득 장치(RAU)를 설치할 경우 SecurityAdmin 도구를 실행하여 _acquisition_user에 대한 암호를 만들어야 합니다. RAU를 설치할 때 이 암호가 필요합니다.
+
참고: 이 암호를 만든 경우 아래에 설명된 대로 서버와 RAU를 동기화하지 않아도 됩니다.





== DWH 및 RAU와 서버 동기화


IMPORTANT: 원격 수집 장치 및/또는 데이터 웨어하우스를 설치한 후에는 RAU/DWH를 OnCommand Insight 서버와 동기화해야 합니다. 아래 설명된 단계를 따르십시오.

link:../install-windows/installing-a-remote-acquisition-unit-rau.html#synchronize-server-and-rau["서버 및 RAU 동기화(Windows)"]

link:../install-windows/installing-the-oncommand-insight-data-warehouse-and-reporting.html#synchronize-server-and-dwh["서버 및 DWH 동기화(Windows)"]

link:../install-linux/installing-a-remote-acquisition-unit-rau-linux.html#synchronize-server-and-rau["서버와 RAU 동기화(Linux)"]

link:../install-linux/installing-oncommand-insight-data-warehouse-linux.html#synchronize-server-and-dwh["서버와 DWH 동기화(Linux)"]
