---
permalink: install-windows/overview-of-insight-upgrade-process.html 
sidebar: sidebar 
keywords:  
summary: Insight 업그레이드를 시작하기 전에 업그레이드 프로세스를 이해하는 것이 중요합니다. 대부분의 Insight 버전에서 업그레이드 프로세스는 동일합니다. 
---
= OnCommand Insight 업그레이드 프로세스 개요
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Insight 업그레이드를 시작하기 전에 업그레이드 프로세스를 이해하는 것이 중요합니다. 대부분의 Insight 버전에서 업그레이드 프로세스는 동일합니다.

Insight의 업그레이드 프로세스에는 다음과 같은 상위 작업이 포함됩니다.

* 설치 패키지를 다운로드합니다
* 데이터 웨어하우스 데이터베이스 백업
+
데이터 보고 오류가 발생하지 않도록 하려면 Insight 데이터베이스를 백업하기 전에 데이터 웨어하우스 데이터베이스를 백업해야 합니다.

* Insight 데이터베이스 백업
+
데이터 이동 없이 업그레이드를 수행하면 Insight 데이터베이스가 자동으로 백업됩니다. 업그레이드하기 전에 데이터베이스를 백업하고 Insight 서버 이외의 위치에 백업을 배치하는 것이 좋습니다. Insight는 업그레이드 프로세스 중에 새 데이터를 수집하지 않습니다. 수집되지 않은 데이터의 양을 최소화하려면 계획된 업그레이드 시간 중 1시간 또는 2시간 이내에 데이터베이스 백업을 시작해야 합니다.

* 기본 구성에서 구성이 변경된 경우 데이터 웨어하우스 및 원격 획득 장치 보안 구성을 백업합니다.
+
업그레이드가 완료된 후 데이터 웨어하우스 데이터베이스를 시스템으로 복원하기 전에 기본값이 아닌 보안 구성을 데이터 웨어하우스 및 RAU 서버로 복원해야 합니다.

* 사용자 지정 데이터 웨어하우스 보고서 백업
+
데이터 웨어하우스 데이터베이스를 백업하는 경우 사용자 정의 보고서가 포함됩니다. 백업 파일은 데이터 웨어하우스 서버에 생성됩니다. 사용자 정의 보고서를 데이터 웨어하우스 서버가 아닌 다른 위치에 백업하는 것이 좋습니다.

* 데이터 웨어하우스 및 원격 획득 장치 소프트웨어 제거(해당하는 경우
+
Insight 서버에는 현재 위치 업그레이드가 있으므로 소프트웨어를 제거할 필요가 없습니다. 현재 위치 업그레이드는 데이터베이스를 백업하고 소프트웨어를 제거한 다음 새 버전을 설치한 다음 데이터베이스를 복원합니다.

* Insight 서버, 데이터 웨어하우스 및 원격 획득 장치에서 소프트웨어 업그레이드
+
이전에 적용한 모든 사용권은 레지스트리에 남아 있으므로 이 사용권을 다시 적용할 필요가 없습니다.

* 업그레이드 후 작업 완료

