---
permalink: install-windows/restoring-the-data-warehouse-database.html 
sidebar: sidebar 
keywords:  
summary: 데이터 웨어하우스 데이터베이스를 백업할 때 데이터 웨어하우스는 나중에 동일한 데이터베이스를 복원하는 데 사용할 수 있는 .zip 파일을 만듭니다. 
---
= 데이터 웨어하우스 데이터베이스 복원
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 웨어하우스 데이터베이스를 백업할 때 데이터 웨어하우스는 을 작성합니다 `.zip` 나중에 동일한 데이터베이스를 복원하는 데 사용할 수 있는 파일입니다.



== 이 작업에 대해

데이터 웨어하우스 데이터베이스를 복원할 때 백업에서 사용자 계정 정보도 복원할 수 있습니다. 사용자 관리 테이블은 데이터 웨어하우스 보고서 엔진이 데이터 웨어하우스 전용 설치에서 사용됩니다.



== 단계

. 에서 데이터 웨어하우스 포털에 로그인합니다 `+https://fqdn/dwh+`.
. 왼쪽의 탐색 창에서 * 백업/복원 * 을 클릭합니다.
. Restore Database and Reports * 섹션에서 * Browse * 를 클릭하고 를 찾습니다 `.zip` 데이터 웨어하우스 백업을 보관하는 파일입니다.
. 다음 옵션을 모두 선택한 상태로 두는 것이 좋습니다.
+
** * 데이터베이스 복원 *
+
데이터 웨어하우스 설정, 데이터 마트, 연결 및 사용자 계정 정보가 포함됩니다.

** * 보고서 복원 *
+
사용자 지정 보고서, 미리 디자인된 보고서, 사용자가 만든 미리 디자인된 보고서의 변경 내용 및 보고 연결에서 수행한 보고 설정이 포함됩니다.



. 복원 * 을 클릭합니다.
+
복원 상태를 벗어나지 마십시오. 이렇게 하면 복구 상태가 더 이상 표시되지 않으며 복원 작업이 완료되면 아무런 표시가 나타나지 않습니다.

. 업그레이드 프로세스를 확인하려면 를 참조하십시오 `dwh_upgrade.log` 다음 위치에 있는 파일: `<install directory>\SANscreen\wildfly\standalone\log`.
+
복원 프로세스가 완료되면 * Restore * 버튼 바로 아래에 메시지가 나타납니다. 복원 프로세스가 성공적으로 완료되면 성공 메시지가 표시됩니다. 복원 프로세스가 실패하면 이 메시지는 실패의 원인이 된 특정 예외를 나타냅니다. 이 경우 기술 지원 부서에 연락하여 지원을 요청하십시오 `dwh_upgrade.log` 파일. 예외가 발생하고 복원 작업이 실패하면 원래 데이터베이스가 자동으로 재설정됩니다.

+
[NOTE]
====
""COGnos 컨텐츠 저장소 업그레이드 실패" 메시지와 함께 복구 작업이 실패하면 데이터 웨어하우스 데이터베이스를 보고서 없이 복원하고(데이터베이스만 해당) XML 보고서 백업을 사용하여 보고서를 가져옵니다.

====

