---
permalink: install-windows/troubleshooting-an-upgrade.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight 업그레이드 후 문제가 발생할 경우 몇 가지 가능한 문제와 관련된 문제 해결 정보를 검토하는 것이 좋습니다. 
---
= 업그레이드 문제 해결
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight 업그레이드 후 문제가 발생할 경우 몇 가지 가능한 문제와 관련된 문제 해결 정보를 검토하는 것이 좋습니다.



== Windows 시작 메뉴에서 Cognos를 시작할 수 없습니다

앞에 공백이 있습니다 `\SANscreen\cognos` 경로 이름에 문제가 있습니다. 자세한 내용은 NetApp 고객 성공 커뮤니티에서 다음 내용을 참조하십시오. https://forums.netapp.com/thread/62721[].



== ""유효하지 않은 Win32 응용 프로그램"" 오류 메시지

이것은 Microsoft Windows의 문제입니다. 이 문제를 해결하려면 레지스트리의 이미지 경로 주위에 따옴표를 입력해야 합니다. 자세한 내용은 다음 설명서를 참조하십시오. https://support.microsoft.com/en-us/kb/812486/en-us[].



== 주석이 없습니다

데이터 웨어하우스 ETL 작업이 Insight 인스턴스의 주석을 쿼리하면 경우에 따라 빈 응답(0 결과)이 오류로 수신되기도 합니다. 이 오류는 데이터 웨어하우스의 ""현재" 및 ""존재하지 않음"" 상태 사이에서 특정 개체가 앞뒤로 이동하는 주석을 만듭니다. 자세한 내용은 다음을 참조하십시오. https://forums.netapp.com/docs/DOC-44167[]



== 보고서에 표시되는 값의 차이

7.0 이전에는 보고서가 정수 기반이었습니다. 이 값은 이제 10진수이므로 업그레이드한 후 값이 표시되는 방식이 증가하거나 감소하는 것을 확인할 수 있습니다.



== 데이터가 보고서에 표시되지 않습니다

7.0.1에서는 여러 모델 이름이 변경되었습니다(예: Symmetrix가 Symmetrix VMAX로 변경됨). 따라서 보고서에 'Symmetrix metrix' 필터가 포함되어 있으면 보고서를 실행할 때 데이터가 표시되지 않습니다. 보고서를 변경하려면 Report Studio에서 쿼리 탐색기 로 보고서를 열고 모델 이름을 검색하고 새 모델 이름으로 바꾸고 보고서를 저장해야 합니다.
