---
permalink: install-windows/upgrading-data-warehouse.html 
sidebar: sidebar 
keywords:  
summary: 모든 필수 작업을 완료한 후 데이터 웨어하우스 서버에 로그인하여 설치 패키지를 실행하여 업그레이드를 완료할 수 있습니다. 
---
= 데이터 웨어하우스 업그레이드 중
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
모든 필수 작업을 완료한 후 데이터 웨어하우스 서버에 로그인하여 설치 패키지를 실행하여 업그레이드를 완료할 수 있습니다.



== 이 작업에 대해

DWH(데이터 웨어하우스)에서는 인라인 업그레이드를 지원하지 않습니다. DWH 소프트웨어의 새 버전으로 업그레이드하려면 다음 단계를 수행하십시오.

[NOTE]
====
DWH를 업그레이드하면 _SecurityAdmin_tool 볼트 백업이 포함된 폴더가 삭제됩니다. DWH를 업그레이드하기 전에 볼트를 백업하는 것이 좋습니다. 참조의 경우 기본 볼트 폴더는 다음과 같습니다.

* 볼트 폴더 (사용 중인 볼트):``%SANSCREEN_HOME%\wildfly\standalone\configuration\vault``
* 볼트 백업: `%SANSCREEN_HOME%\backup\vault`


을 참조하십시오 http://ie-docs.rtp.openeng.netapp.com/oci-73_ram/topic/com.netapp.doc.oci-acg/GUID-E3351676-2088-4767-AAB5-CB1D8476291C.html?resultof=%22%76%61%75%6c%74%22%20["데이터 웨어하우스의 보안 관리"] 를 참조하십시오.

====


== 단계

. Windows 로컬 관리자 권한이 있는 계정을 사용하여 DWH 서버에 로그인합니다.
. DWH 포털 인터페이스를 사용하여 DWH DB 및 보고서를 백업합니다.
. 서버가 기본값이 아닌 보안 구성을 사용하는 경우 보안 구성을 백업합니다.
. 서버에서 DWH 소프트웨어를 제거합니다.
. 메모리를 구성 요소 제거하기 위해 서버를 재부팅합니다.
. 새 버전의 DWH를 서버에 설치합니다.
+
설치 시간은 약 2시간입니다. 모든 기본값을 그대로 두는 것이 가장 좋습니다.

. 기본이 아닌 보안 구성을 DWH 서버로 복원합니다.
. DWH 데이터베이스를 서버로 복원합니다.




== 작업을 마친 후

업그레이드 후 데이터 웨어하우스 데이터베이스를 복원해야 합니다. 이 데이터베이스는 업그레이드보다 오래 또는 오래 걸릴 수 있습니다.

[NOTE]
====
OnCommand Insight 업그레이드 중에 고객이 다른 Insight 서버로 전환하는 경우가 드물지 않게 있습니다. Insight 서버를 변경한 경우 데이터 웨어하우스 데이터베이스를 복원하면 기존 커넥터가 이전 서버 IP 주소 또는 호스트 이름을 가리킵니다. 오류가 발생하지 않도록 커넥터를 삭제하고 새 커넥터를 작성하는 것이 가장 좋습니다.

====