---
permalink: install-windows/upgrading-remote-acquisition-servers.html 
sidebar: sidebar 
keywords:  
summary: 모든 필수 작업을 완료한 후 원격 획득 장치 서버에 로그인하여 설치 패키지를 실행하여 업그레이드를 완료할 수 있습니다. 사용자 환경의 모든 원격 획득 서버에서 이 작업을 수행해야 합니다. 
---
= 원격 획득 장치 서버 업그레이드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
모든 필수 작업을 완료한 후 원격 획득 장치 서버에 로그인하여 설치 패키지를 실행하여 업그레이드를 완료할 수 있습니다. 사용자 환경의 모든 원격 획득 서버에서 이 작업을 수행해야 합니다.



== 시작하기 전에

* OnCommand Insight를 업그레이드해야 합니다.
* OnCommand Insight 설치 패키지는 서버에 있어야 합니다.


[NOTE]
====
업그레이드하기 전에 볼트를 백업해야 합니다.

link:../config-admin\/security-management.html["SecurityAdmin 도구"]볼트에 대한 자세한 내용은 지침을 참조하십시오.

====


== 단계

. Windows 로컬 관리자 권한이 있는 계정을 사용하여 원격 획득 장치 서버에 로그인합니다.
. 볼트를 백업합니다.
. Insight 설치 패키지를 찾습니다 (`RAU-x64-version_number-build_number.msi`) Windows 탐색기를 사용하여 두 번 클릭합니다.
+
OnCommand Insight 설치 마법사가 표시됩니다.

. 생성된 모든 오류가 보기에서 숨겨지지 않도록 설치 마법사 진행률 창을 화면 중앙에서 멀리 이동하고 설치 마법사 창에서 멀리 이동합니다.
. 설치 마법사의 지시를 따릅니다.
+
모든 기본값을 그대로 두는 것이 가장 좋습니다.





== 작업을 마친 후

* 업그레이드가 성공했는지 또는 오류가 생성되었는지 확인하려면 다음 위치에서 업그레이드 로그를 확인하십시오. `<install directory>\SANscreen\bin\log`.
* 를 사용합니다 `securityadmin` 저장된 보안을 복원하는 도구입니다
+
구성. 자세한 내용은 OnCommand Insight에서 SecurityAdmin을 검색하십시오

+
문서 센터: http://docs.netapp.com/oci-73/index.jsp[]

* 브라우저의 캐시 및 기록을 지워 서버에서 최신 데이터를 수신하고 있는지 확인합니다.

