---
permalink: install-linux/anomaly-detection-requirements.html 
sidebar: sidebar 
keywords: redhat 
summary: 이상 현상 감지 소프트웨어에는 특정 운영 체제, 메모리 양, CPU 코어 및 디스크 공간이 필요합니다. 이상 현상 감지 소프트웨어를 성공적으로 설치하려면 특정 요구 사항을 준수해야 합니다. 
---
= 이상 징후 탐지 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
이상 현상 감지 소프트웨어에는 특정 운영 체제, 메모리 양, CPU 코어 및 디스크 공간이 필요합니다. 이상 현상 감지 소프트웨어를 성공적으로 설치하려면 특정 요구 사항을 준수해야 합니다.

|===


| 구성 요소 | 필수 요소입니다 


 a| 
운영 체제
 a| 
다음 중 하나의 라이센스 버전을 실행하는 컴퓨터, 다른 응용 프로그램 수준 소프트웨어를 실행하지 않는 컴퓨터:

* Red Hat Enterprise Linux 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9, 8.1, 8.2, 8.3, 8.4, 8.5
* CentOS 7.5, 7.6, 7.7, 7.8, 7.9, CentOS 8 스트림
* Oracle Enterprise Linux 7.5, 7.6, 7.7, 7.8, 7.9, 8.1, 8.2, 8.3, 8.4, 8.5
* SUSE Enterprise Linux 15.1, 15.2, 15.3
* openSUSE 15.1, 15.2, 15.3


라이센스가 있는 버전을 사용하면 설치에 필요한 종속성이 운영 체제에 의해 자동으로 확인됩니다.

전용 서버가 권장됩니다.



 a| 
가상 머신(VM)
 a| 
이상 현상 감지는 인스턴스의 CPU 및 메모리 리소스가 예약된 경우 가상 환경에서 실행될 수 있습니다.



 a| 
CPU 및 메모리
 a| 
8코어. 64GB 메모리 서버.



 a| 
사용 가능한 디스크 공간입니다
 a| 
서버는 다음과 같이 200GB의 사용 가능한 디스크 공간을 분할해야 합니다.

* 150GB 인치 `/var/lib`
* 25GB 인치 `/var/log`
* 25GB 인치 `/opt`


소프트웨어를 설치하려면 다음 디스크 공간이 필요합니다.

* 5GB 인치 `/var/lib`
* 25GB 인치 `/var/log`
* 25GB 인치 `/opt`


장착하는 것이 가장 좋습니다 ``/opt``및 루트 파일 시스템과 별도의 디스크에 있습니다 (`/`)를 클릭합니다.



 a| 
권한
 a| 
이상 탐지 소프트웨어를 설치하려면 sudo 권한이 필요합니다.



 a| 
네트워크
 a| 
이상 현상 감지 소프트웨어를 설치하려는 Insight 서버는 이상 현상 감지 엔진을 실행 중인 서버와 동일한 네트워크 또는 동일한 사이트 또는 데이터 센터에 있어야 합니다. 이상 현상 감지 소프트웨어는 WAN(Wide-Area Network)의 구성을 지원하지 않습니다.

TCP 포트 8080 및 9200이 VM에서 열려 있어야 합니다.



 a| 
필수 구성 요소
 a| 
유효한 Perform 라이센스가 있어야 합니다. 이상 현상 감지 소프트웨어를 설치할 Insight 서버의 IP 주소가 있어야 합니다.

기본 포트를 허용하지 않는 경우 Insight 서버에 대체 포트 번호가 있어야 합니다.

TCP 포트 8080 및 9200이 VM에서 열려 있어야 합니다.

VM에서 관리자 권한이 있는 계정의 사용자 이름과 암호가 있어야 합니다.

단일 백슬래시(company\user)가 포함된 사용자 이름에 대해 두 개의 백슬래시(company\\user)를 입력해야 합니다.

사용자 이름은 백슬래시(company\\Tom) 뒤에 ""t""를 포함할 수 없습니다.

|===
[NOTE]
====
모든 사이징 권장사항을 NetApp 담당자와 논의하고 검증해야 합니다.

====