---
permalink: install-linux/data-warehouse-server-requirements-linux.html 
sidebar: sidebar 
keywords:  
summary: 데이터 웨어하우스 서버는 정해진 하드웨어 및 소프트웨어 요구 사항과 호환되는 컴퓨터에서 실행해야 합니다. Apache 웹 서버 또는 보고 소프트웨어가 이 시스템에 설치되어 있지 않은지 확인해야 합니다. 
---
= 데이터 웨어하우스 서버 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 웨어하우스 서버는 정해진 하드웨어 및 소프트웨어 요구 사항과 호환되는 컴퓨터에서 실행해야 합니다. Apache 웹 서버 또는 보고 소프트웨어가 이 시스템에 설치되어 있지 않은지 확인해야 합니다.

[NOTE]
====
OnCommand Insight를 위한 사이징에는 운영 환경의 자산 수, 유지되는 기간별 데이터 양 등과 같은 다양한 종속 관계가 있습니다. 다음 데이터 웨어하우스 사이징 예는 지침일 뿐이며 Insight가 테스트된 일부 환경을 나타냅니다. 환경의 이러한 요인 또는 기타 요소를 변경하면 Insight의 사이징 요구 사항이 변경될 수 있습니다.

====
Insight를 설치 또는 업그레이드하기 전에 세일즈 엔지니어에게 자세한 사이징 지침을 문의하는 것이 좋습니다.

* 예: *

|===


| 환경 요인: | 테스트한 디스크 공간, CPU 및 메모리: 


 a| 
스토리지 18개가상 머신 3,400개

4,500개의 스위치 포트
 a| 
200GB 하드 디스크8 코어

32GB RAM



 a| 
110개의 스토리지 어레이11,500개의 VM을 제공합니다

14,500개의 스위치 포트
 a| 
300GB 하드 디스크8 코어

48GB RAM

|===
* 요구 사항: *

|===


| 구성 요소 | 필수 요소입니다 


 a| 
운영 체제
 a| 
다음 중 하나의 라이센스 버전을 실행하는 컴퓨터, 다른 응용 프로그램 수준 소프트웨어를 실행하지 않는 컴퓨터:

* Red Hat Enterprise Linux 7.9, 8.10, 9.4
* CentOS 8 스트림, CentOS 9 스트림
* Oracle Enterprise Linux 7.9, 8.10, 9.4




 a| 
가상 머신(VM)
 a| 
이 구성 요소는 인스턴스에 대한 CPU 및 메모리 리소스가 예약되어 있는 경우 가상 환경에서 실행될 수 있습니다.



 a| 
CPU
 a| 
8-40개의 CPU 코어



 a| 
메모리
 a| 
32GB - 2TB RAM



 a| 
사용 가능한 디스크 공간
 a| 
200GB - 512GB 디스크 공간 에는 50GB 이상의 사용 가능한 디스크 공간이 있어야 합니다 `/var/lib` 파티션 및 에서 25GB의 사용 가능한 디스크 공간 `/opt` 및 `/var/log` 파티션.



 a| 
네트워크
 a| 
* 100Mbps 또는 1Gbps 이더넷 연결
* 고정 IP 주소입니다
* OnCommand Insight DWH 서버 프로세스의 경우 포트 80, 443, 1098, 1099, 3873, 8083, 4444 ~ 4446
* MySQL의 경우 포트 3306입니다


|===