---
permalink: install-linux/insight-server-requirements.html 
sidebar: sidebar 
keywords: redhat 
summary: 전용 서버가 권장됩니다. 다른 애플리케이션이 설치된 서버에 Insight를 설치하지 마십시오. 제품 요구 사항이 충족되는 경우 물리적 서버와 가상 서버가 모두 지원됩니다. 
---
= Insight Server 요구사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
전용 서버가 권장됩니다. 다른 애플리케이션이 설치된 서버에 Insight를 설치하지 마십시오. 제품 요구 사항이 충족되는 경우 물리적 서버와 가상 서버가 모두 지원됩니다.

OnCommand Insight 서버 소프트웨어를 설치하려면 sudo 권한이 있어야 합니다.

일부 Insight 구성 요소는 설치 중에 종속 패키지가 필요할 수 있습니다. Insight를 설치하기 전에 YUM 저장소에 액세스할 수 있는지 확인합니다.

[NOTE]
====
OnCommand Insight 크기 조정에는 데이터 소스 유형 및 크기, 환경의 자산 수, 폴링 간격 등 다양한 종속 항목이 있습니다. 다음 사이징 예는 지침일 뿐이며 Insight가 테스트된 환경의 일부를 나타냅니다. 환경의 이러한 요인 또는 기타 요소를 변경하면 Insight의 사이징 요구 사항이 변경될 수 있습니다. 이러한 지침에는 최대 90일간의 성능 아카이브 데이터를 위한 디스크 공간이 포함되어 있습니다.

====
Insight를 설치 또는 업그레이드하기 전에 세일즈 엔지니어에게 자세한 사이징 지침을 문의하는 것이 좋습니다.

* 예: *

|===


| 환경 요인: | 테스트한 디스크 공간, CPU 및 메모리: 


 a| 
80개 스토리지 4,000개 볼륨

4,000개의 VM

4,000개의 스위치 포트
 a| 
250GB 디스크 공간 8코어

32GB RAM



 a| 
160 스토리지 어레이40,000개의 볼륨

8,000개의 VM

8,000개의 스위치 포트
 a| 
1TB 디스크 공간 12개 코어

48GB RAM

|===
* 요구 사항: *

|===


| 구성 요소 | 필수 요소입니다 


 a| 
운영 체제
 a| 
다음 중 하나의 라이센스 버전을 실행하는 컴퓨터, 다른 응용 프로그램 수준 소프트웨어를 실행하지 않는 컴퓨터:

* Red Hat Enterprise Linux 7.9, 8.10, 9.4
* CentOS 8 스트림, CentOS 9 스트림
* Oracle Enterprise Linux 7.9, 8.10, 9.4


라이센스가 있는 버전은 설치에 필요한 종속 항목이 운영 체제에 의해 자동으로 해결되도록 합니다.

Insight를 설치하기 전에 MariaDB를 제거해야 합니다.

[NOTE]
====
MariaDB를 제거하면 Postfix Mail Transport Agent도 제거됩니다.

====
전용 서버가 권장됩니다.



 a| 
가상 머신(VM)
 a| 
이 구성 요소는 인스턴스에 대한 CPU 및 메모리 리소스가 예약되어 있는 경우 가상 환경에서 실행될 수 있습니다.



 a| 
메모리 및 CPU
 a| 
24-256GB RAM

8~32코어



 a| 
사용 가능한 디스크 공간입니다
 a| 
100GB - 3TB 설치 디스크 공간

50GB - 1TB 성능 아카이브 디스크 공간

예를 들어 500GB 환경에서는 다음과 같은 파티션 분할이 권장됩니다.

* /opt 디렉토리 -- 50GB
* /var/log 디렉토리 -- 100GB
* /var/lib 디렉토리 -- 350GB


장착하는 것이 가장 좋습니다 `/opt` 및 `/var` 루트 파일 시스템과 별도의 디스크에 있습니다 (`/`)를 클릭합니다.

Insight 설치 공간에는 SSD 디스크를 사용하는 것이 좋습니다.



 a| 
네트워크
 a| 
이더넷 연결 및 포트:

* FC 장치 및 원격 획득 장치를 포함하여 SAN의 모든 구성 요소에 대한 전용(정적) IP 주소 및 IP 연결을 통한 100Mbps 또는 1Gbps 이더넷 연결
* OnCommand Insight 서버 프로세스의 포트 요구 사항은 80, 443, 1090 ~ 1100, 3873, 8083입니다. 4444 ~ 4446, 5445, 5455, 4712 ~ 4714, 5500, 및 5501을 참조하십시오.
* 획득 프로세스의 포트 요구 사항은 12123 및 5679입니다.
* MySQL의 포트 요구 사항은 3306입니다.
* Elasticsearch의 포트 요구 사항은 9200 및 9310입니다


포트 443 및 3306은 존재하는 방화벽을 통해 외부 액세스를 필요로 합니다.



 a| 
권한
 a| 
OnCommand Insight 서버에 sudo 권한이 필요합니다.

다음 폴더 중 하나가 심볼 링크인 경우 대상 디렉토리에 '755' 권한이 있는지 확인하십시오.

* /opt/NetApp을 참조하십시오
* /var/lib/netapp
* /var/log/netapp




 a| 
원격 연결
 a| 
WebEx 액세스를 위한 인터넷 연결 또는 설치 및 설치 후 지원을 위한 원격 데스크톱 연결



 a| 
접근성
 a| 
HTTPS 액세스가 필요합니다.



 a| 
HTTP 또는 HTTPS 서버
 a| 
Apache HTTP 서버 또는 다른 HTTPS 서버는 OnCommand Insight 서버와 동일한 포트(443)에 대해 경쟁해서는 안 되며 자동으로 시작해서는 안 됩니다. 포트 443을 수신해야 하는 경우 다른 포트를 사용하도록 OnCommand Insight 서버를 구성해야 합니다.

|===