---
permalink: install-linux/installing-an-ethernet-monitoring-unit-linux.html 
sidebar: sidebar 
keywords:  
summary: '“이더넷 모니터링 장치\(emus\)는 사용자 환경에서 네트워크 패킷을 검사하여 호스트에서 스토리지 리소스로의 네트워크 트래픽 측면에서 성능 문제를 해결할 수 있도록 합니다.' 
---
= 이더넷 모니터링 장치 설치
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
""이더넷 모니터링 장치(emus)는 사용자 환경에서 네트워크 패킷을 검사하여 호스트에서 스토리지 리소스로의 네트워크 트래픽 측면에서 성능 문제를 해결할 수 있도록 합니다.



== 시작하기 전에

[NOTE]
====
이더넷 모니터링 장치(EMU)는 OnCommand Insight 버전 7.3.12 이상에서 지원되지 않습니다.

====
설치 필수 구성 요소를 모두 완료해야 합니다.



== 단계

. sudo 권한이 있는 계정을 사용하여 EMU 서버에 로그인합니다.
. 설치 파일이 있는 서버의 디렉터리로 이동하여 다음 명령을 입력합니다.
+
`unzip oci-ethernet-<version>-linux-x86_64.zip`

+
위치 `<version>` 다운로드한 파일 이름에 지정된 버전 번호입니다.

. 에 대한 구문, 명령 인수 및 매개 변수 사용을 볼 수 있습니다 `oci-install.sh`:
+
`sudo ./oci-ethernet-<version>-linux-x86_64/oci-install.sh --help`

. 설치 스크립트를 실행합니다.
+
`sudo ./oci-ethernet-<version>-linux-x86_64/oci-install.sh`

. 사용권 계약을 읽고 동의합니다.
. 각 프롬프트에 응답합니다.
+
** * OnCommand Insight * * * 서버 이름 또는 IP 주소 * - OnCommand Insight 서버를 식별하기 위한 호스트 이름 또는 IP 주소입니다. EMU는 이 이름/IP를 사용하여 서버와의 통신 링크를 엽니다. 호스트 이름을 지정하는 경우 DNS를 통해 호스트 이름을 확인할 수 있는지 확인합니다.
** * 획득 장치 이름 * - EMU를 식별하는 고유 이름입니다.
** * OnCommand Insight 보안 원격 획득 포트(HTTPS) * - EMU가 환경 변경 정보를 OnCommand Insight 서버로 전송하는 데 사용하는 포트입니다. 이 설정은 OnCommand Insight 서버를 설치할 때 입력한 값과 일치해야 하며 모든 EMUS에서 동일해야 합니다.
** * 이더넷 PAS 출력 디렉토리 * - PAS 출력 폴더를 입력합니다.
** * 모니터링할 이더넷 PAS 인터페이스 * - 모니터링할 트래픽을 가진 인터페이스를 입력합니다.
** * 점보 패킷 사용 * - 고객 환경에서 점보 패킷을 사용하는 경우 EMU는 이러한 패킷을 읽기 위해 큰 패킷 버퍼를 생성합니다. 그렇지 않으면 EMU는 표준 이더넷 패킷에 사용 가능한 메모리 풀을 사용합니다. 모든 메시지에 응답하면 설치가 시작되고 설치된 응용 프로그램에 따라 약 10분 정도 소요됩니다.



