---
permalink: install-linux/network-traffic-generated-by-oncommand-insight.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight가 생성하는 네트워크 트래픽, 네트워크를 통과하는 처리된 데이터의 양 및 OnCommand Insight가 디바이스에 배치하는 로드는 여러 요인에 따라 달라집니다. 
---
= OnCommand Insight에서 생성된 네트워크 트래픽입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight가 생성하는 네트워크 트래픽, 네트워크를 통과하는 처리된 데이터의 양 및 OnCommand Insight가 디바이스에 배치하는 로드는 여러 요인에 따라 달라집니다.

트래픽, 데이터 및 로드는 다음 요소에 따라 환경에 따라 다릅니다.

* 원시 데이터
* 장치 구성
* OnCommand Insight의 구축 토폴로지
* 느린 디바이스를 발견하거나 대역폭을 처리할 수 있도록 여러 인벤토리 및 성능 데이터 소스 폴링 간격을 줄일 수 있습니다


OnCommand Insight에서 수집하는 원시 구성 데이터는 크게 다를 수 있습니다.

다음 예에서는 구성 데이터가 어떻게 변하는지, 그리고 여러 구성 요소의 트래픽, 데이터 및 로드가 어떤 영향을 받는지 보여 줍니다. 예를 들어 각각 1,000개의 디스크가 있는 두 개의 어레이가 있을 수 있습니다.

* 어레이 1: 크기가 모두 1TB인 SATA 디스크 1,000개가 있습니다. 1,000개의 디스크가 모두 하나의 스토리지 풀에 있고 1,000개의 LUN이 있으며, 모두 ESX 클러스터의 동일한 32개 노드에 표시(매핑 및 마스킹됨)됩니다.
* 어레이 2: 2TB 데이터 디스크 400개, 600GB FC 디스크 560개 및 SSD 40개가 있습니다. 스토리지 풀은 3개가 있지만 FC 디스크 320개가 기존 RAID 그룹에 사용됩니다. RAID 그룹에 포함된 LUN은 기존 마스킹 유형(symmaskdb)을 사용하는 반면, 씬 프로비저닝된 풀 기반 LUN은 최신 마스킹 유형(symaccess)을 사용합니다. 150개의 호스트에 600개의 LUN이 제공됩니다. 200개의 BCV(600개의 LUN 중 200개의 전체 블록 복제본 볼륨)가 있습니다. 다른 사이트의 스토리지에 있는 볼륨의 원격 복제본 볼륨인 R2 볼륨도 200개가 있습니다.


이러한 어레이에는 각각 1,000개의 디스크와 1,000개의 논리적 볼륨이 있습니다. 이러한 공간은 데이터 센터에서 소비하는 랙 공간의 크기와 물리적으로 동일하며 동일한 펌웨어를 실행하기도 하지만 두 번째 어레이는 첫 번째 어레이보다 구성에서 훨씬 복잡합니다.
