---
permalink: dwh/adding-a-reporting-user.html 
sidebar: sidebar 
keywords:  
summary: 보고 포털에 액세스해야 하는 각 사용자에 대해 새 사용자 계정을 추가해야 합니다. 각 사용자에 대해 다른 사용자 계정을 만들면 액세스 권한, 개인 기본 설정 및 책임을 제어할 수 있습니다. 
---
= 보고 사용자 추가
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
보고 포털에 액세스해야 하는 각 사용자에 대해 새 사용자 계정을 추가해야 합니다. 각 사용자에 대해 다른 사용자 계정을 만들면 액세스 권한, 개인 기본 설정 및 책임을 제어할 수 있습니다.



== 시작하기 전에

보고 사용자를 추가하기 전에 고유한 사용자 이름을 할당하고, 사용할 암호를 결정하고, 올바른 사용자 역할 또는 역할을 확인해야 합니다. 이러한 역할은 보고 포털에 전문화되어 있습니다.



== 단계

. Data Warehouse Portal( )에 관리자로 로그인합니다 `+https://hostname/dwh+`, 위치 `hostname` OnCommand Insight 데이터 웨어하우스가 설치된 시스템의 이름입니다.
. 왼쪽의 탐색 창에서 * 사용자 관리 * 를 클릭합니다.
. 사용자 관리 * 창에서 * 새 사용자 추가 * 를 클릭합니다.
. 새 보고 사용자에 대해 다음 정보를 입력합니다.
+
** * 사용자 이름 *
+
계정에 대한 사용자 이름(영숫자, a-z, A-Z 및 0-9 포함)

** * 이메일 주소 *
+
사용자 계정과 연결된 이메일 주소이며 사용자가 보고서를 구독하는 경우 필요합니다

** * 암호 *
+
사용자가 일반적으로 선택하고 인터페이스에서 확인할 수 있는 이 사용자 계정으로 OnCommand Insight에 로그인하기 위한 암호입니다

** * Insight 역할 *
+
적절한 권한이 있는 사용자가 사용할 수 있는 역할

+
[NOTE]
====
OnCommand Insight 역할의 옵션은 OnCommand Insight가 보고 기능과 동일한 시스템에 설치되어 있는 경우에만 표시되며, 이는 일반적인 옵션은 아닙니다.

====
** * 보고 역할 *
+
이 사용자 계정에 대한 보고 역할(예: Pro Author)

+
[NOTE]
====
관리자 역할은 고유합니다. 이 역할은 모든 사용자에게 추가할 수 있습니다.

====


. 추가 * 를 클릭합니다.

