---
permalink: dwh/annotations.html 
sidebar: sidebar 
keywords:  
summary: 주석은 사용자 환경의 개체와 관련된 정보를 정의한 다음 주석을 기반으로 개체를 추적할 수 있는 방법을 제공합니다. 예를 들어 사용자 환경의 디바이스에 건물 또는 층 번호 주석을 추가한 다음 데이터 센터의 1층에 있는 모든 디바이스를 반환하는 쿼리를 만들 수 있습니다. 
---
= 주석을 사용하여 수행할 수 있는 작업
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
주석은 사용자 환경의 개체와 관련된 정보를 정의한 다음 주석을 기반으로 개체를 추적할 수 있는 방법을 제공합니다. 예를 들어 사용자 환경의 디바이스에 건물 또는 층 번호 주석을 추가한 다음 데이터 센터의 1층에 있는 모든 디바이스를 반환하는 쿼리를 만들 수 있습니다.

또한 특정 데이터 센터 또는 사업체 에 있는 모든 장치를 살펴보고 최상위 계층 1 스토리지를 사용 중인 업무 엔티티를 결정할 수 있습니다. 이렇게 하려면 OnCommand Insight 웹 UI를 사용하여 데이터 센터, 사업체 또는 계층 주석을 장치에 할당합니다. 그런 다음 OnCommand Insight에서 선택한 사용자 정의 주석을 데이터 웨어하우스로 가져올 수 있습니다. 개체에 할당된 주석 값이 사용자 정의 보고서에 표시되도록 하려면 이 작업을 수행합니다.

데이터 웨어하우스에 적용할 사용자 정의 주석을 지정할 수 있습니다. 주석은 인벤토리의 객체 테이블과 데이터 마트의 관련 차원 테이블에 추가 열로 추가됩니다. OnCommand Insight 사용자 인터페이스를 사용하여 리소스의 주석을 업데이트하고 다음 데이터 웨어하우스 빌드를 시작하거나 기다릴 때 다음 표에 결과가 표시됩니다.

* dWh_inventory.annotation_value 를 입력합니다
* dWh_inventory.object_to_annotation


OnCommand Insight에 입력된 주석이 데이터 웨어하우스에 포함되는지 확인하려면 다음과 같은 주요 프로세스가 필요합니다.

* 주석을 데이터 웨어하우스로 가져오기 전에 OnCommand Insight에서 준비되었는지 확인해야 합니다.
+
이렇게 하려면 * Troubleshooting * > * Force Update of Annotations for Data Warehouse * 옵션을 수동으로 실행하거나 예약된 다음 임시 데이터 실행 프로세스가 실행될 때까지 기다립니다. 주석을 강제로 업데이트할 때 OnCommand Insight 서버가 임시 데이터(예: 주석 값)를 계산하고 데이터베이스 테이블에 배치하도록 하여 데이터 웨어하우스 ETL 프로세스에서 데이터를 읽을 수 있도록 합니다. 주석 데이터는 15분마다 자동으로 업데이트되지만, 더 자주 강제로 업데이트할 수 있습니다.

* 그런 다음 데이터 웨어하우스** 주석** 옵션을 사용하여 주석을 데이터 웨어하우스로 가져옵니다.
* OnCommand Insight 보고 포털 보고서 작성 도구를 사용하여 작성한 보고서에 주석을 포함하려면 OnCommand Insight 보고 메타데이터 모델을 업데이트해야 합니다.


데이터 웨어하우스를 업그레이드하면 데이터베이스 복원 프로세스 중에 주석 작업이 자동으로 실행됩니다. WildFly가 시작되면 주석 작업도 자동으로 실행됩니다.

[NOTE]
====
WildFly는 OnCommand Insight Java 코드가 실행되고 OnCommand Insight 서버 및 데이터 웨어하우스 모두에 필요한 응용 프로그램 서버입니다.

====