---
permalink: dwh/configuring-reporting-ldap.html 
sidebar: sidebar 
keywords:  
summary: 관리자는 데이터 웨어하우스 포털에서 데이터 웨어하우스 및 보고에 대한 LDAP 사용을 구성할 수 있습니다. 
---
= 보고를 위해 LDAP 구성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
관리자는 데이터 웨어하우스 포털에서 데이터 웨어하우스 및 보고에 대한 LDAP 사용을 구성할 수 있습니다.



== 시작하기 전에

이 작업을 수행하려면 Insight에 관리자로 로그인해야 합니다.

모든 보안 Active Directory(예: LDAPS) 사용자의 경우 인증서에 정의된 대로 AD 서버 이름을 정확히 사용해야 합니다. 보안 AD 로그인에 IP 주소를 사용할 수 없습니다.



== 단계

. 에서 데이터 웨어하우스 포털에 로그인합니다 `+https://hostname/dwh+`, 위치 `hostname` OnCommand Insight 데이터 웨어하우스가 설치된 시스템의 이름입니다.
. 왼쪽의 탐색 창에서 * 사용자 관리 * 를 클릭합니다.
. LDAP 구성 * 을 클릭합니다.
. LDAP 사용자 인증 및 인증 프로세스를 시작하려면 * LDAP 활성화 * 를 선택합니다.
. LDAP를 구성하는 데 필요한 모든 변경 작업을 수행합니다.
+
대부분의 필드에는 기본값이 포함되어 있습니다. 기본 설정은 Active Directory에 유효합니다.

+
** * 사용자 기본 이름 속성 *
+
LDAP 서버의 각 사용자를 식별하는 속성입니다. 기본값은 입니다 `userPrincipalName`이는 세계적으로 고유한 기능입니다. OnCommand Insight는 이 특성의 내용과 위에서 제공한 사용자 이름을 일치시킵니다.

** * 역할 속성 *
+
지정된 그룹 내에서 사용자의 맞춤을 식별하는 LDAP 속성입니다. 기본값은 입니다 `memberOf`.

** * 메일 속성 *
+
사용자의 이메일 주소를 식별하는 LDAP 속성입니다. 기본값은 입니다 `mail`. 이 기능은 OnCommand Insight에서 제공하는 보고서를 구독하려는 경우에 유용합니다. Insight는 각 사용자가 처음 로그인할 때 사용자의 이메일 주소를 선택하며, 그 후에는 이를 찾아보지 않습니다.

+
[NOTE]
====
LDAP 서버에서 사용자의 이메일 주소가 변경되면 Insight에서 업데이트해야 합니다.

====
** * 고유 이름 특성 *
+
사용자의 고유 이름을 식별하는 LDAP 속성입니다. 기본값은 입니다 `distinguishedName`.

** * 참조 *
+
엔터프라이즈에 여러 도메인이 있는 경우 다른 도메인에 대한 경로를 따르는지 여부를 나타냅니다. 항상 기본값을 사용해야 합니다 `follow` 설정.

** * 시간 초과 *
+
시간 초과 전에 LDAP 서버의 응답을 기다리는 시간(밀리초)입니다. 기본값은 2,000이며, 모든 경우에 적절하며 수정할 수 없습니다.

** LDAP 서버 *
+
LDAP 서버를 식별하기 위한 IP 주소 또는 DNS 이름입니다. 특정 포트를 식별하기 위해 `ldap-server-address` LDAP 서버의 이름이며 다음 형식을 사용할 수 있습니다.

+
[listing]
----
ldap://ldap-server-address:port
----
+
기본 포트를 사용하려면 다음 형식을 사용할 수 있습니다.

+
[listing]
----
ldap://ldap-server-address
----
+
[NOTE]
====
 When entering multiple LDAP servers in this field, separate entries with a comma, and ensure that the correct port number is used in each entry.
+ LDAP 인증서를 가져오려면 * 인증서 가져오기 * 를 클릭하고 인증서 파일을 자동으로 가져오거나 수동으로 찾습니다.

====
** * 도메인 *
+
OnCommand Insight가 LDAP 사용자를 찾기 시작해야 하는 LDAP 노드입니다. 일반적으로 조직의 최상위 도메인입니다. 예를 들면 다음과 같습니다.

+
[listing]
----
DC=<enterprise>,DC=com
----
** * Insight 서버 관리자 그룹 *
+
Insight Server 관리자 권한이 있는 사용자를 위한 LDAP 그룹입니다. 기본값은 입니다 `insight.server.admins`.

** * Insight 관리자 그룹 *
+
Insight Administrator 권한이 있는 사용자를 위한 LDAP 그룹입니다. 기본값은 입니다 `insight.admins`.

** * Insight 사용자 그룹 *
+
Insight 사용자 권한이 있는 사용자를 위한 LDAP 그룹입니다. 기본값은 입니다 `insight.users`.

** * Insight 게스트 그룹 *
+
Insight 게스트 권한이 있는 사용자를 위한 LDAP 그룹입니다. 기본값은 입니다 `insight.guests`.

** * 보고 관리자 그룹 *
+
Insight Reporting 관리자 권한이 있는 사용자를 위한 LDAP 그룹입니다. 기본값은 입니다 `insight.report.admins`.

** * 보고 전문가 그룹 *
+
Insight Reporting Pro 작성자 권한이 있는 사용자를 위한 LDAP 그룹입니다. 기본값은 입니다 `insight.report.proauthors`.

** * 보고 비즈니스 저자 그룹 *
+
Insight Reporting 비즈니스 작성자 권한이 있는 사용자를 위한 LDAP 그룹입니다. 기본값은 입니다 `insight.report.business.authors`.

** * 비즈니스 소비자 그룹 보고 *
+
Insight Reporting 비즈니스 소비자 권한이 있는 사용자를 위한 LDAP 그룹입니다. 기본값은 입니다 `insight.report.business.consumers`.

** * 보고 수신자 그룹 *
+
Insight Reporting 받는 사람 권한이 있는 사용자를 위한 LDAP 그룹입니다. 기본값은 입니다 `insight.report.recipients`.



. 변경한 경우 * 디렉터리 조회 사용자 * 및 * 디렉터리 조회 사용자 암호 * 필드에 값을 입력합니다.
+
이러한 필드에 수정된 값을 입력하지 않으면 변경 내용이 저장되지 않습니다.

. 디렉터리 조회 사용자 암호 확인 * 필드에 디렉터리 조회 사용자 암호를 다시 입력하고 * 암호 확인 * 을 클릭하여 서버에서 암호를 확인합니다.
. Update * 를 클릭하여 변경 사항을 저장합니다. 변경 사항을 제거하려면 * 취소 * 를 클릭합니다.

