---
permalink: dwh/connecting-data-warehouse-to-oncommand-insight-servers.html 
sidebar: sidebar 
keywords:  
summary: 커넥터는 OnCommand Insight 데이터 웨어하우스에서 OnCommand Insight 서버로의 연결을 설정합니다. 데이터 웨어하우스를 하나 이상의 OnCommand Insight 서버에 연결할 수 있습니다. OnCommand Insight 데이터베이스에 대한 연결을 추가하거나 데이터베이스에서 연결을 제거할 수 있습니다. 
---
= OnCommand Insight 서버에 데이터 웨어하우스 연결
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
커넥터는 OnCommand Insight 데이터 웨어하우스에서 OnCommand Insight 서버로의 연결을 설정합니다. 데이터 웨어하우스를 하나 이상의 OnCommand Insight 서버에 연결할 수 있습니다. OnCommand Insight 데이터베이스에 대한 연결을 추가하거나 데이터베이스에서 연결을 제거할 수 있습니다.



== 이 작업에 대해

데이터 웨어하우스는 커넥터 이름과 함께 사용되는 커넥터에 글로벌 고유 ID를 할당합니다. 커넥터를 추가한 후 데이터 웨어하우스는 OnCommand Insight 데이터베이스에서 OnCommand Insight 사이트 이름 및 버전을 쿼리합니다.

SSL을 사용하거나 사용하지 않고 데이터 원본에 연결하도록 선택할 수 있습니다. 보안 데이터 소스를 선택하면 OnCommand Insight 원격 데이터베이스와 통신할 때 연결이 SSL을 사용하게 됩니다.

데이터 웨어하우스는 여러 OnCommand Insight 설치에서 통합된 데이터 뷰를 제공할 수 있습니다. 이 통합 데이터베이스는 다음 정보를 제공합니다.

* 전역적으로 고유한 식별자
+
각 개체에는 충돌하는 ID를 방지하고 중복 검색을 사용하기 위해 개별 사이트에서 사용하는 ID와 독립적인 전역 고유 ID가 할당됩니다. 이러한 ID는 모든 데이터 마트 간에 공유됩니다. 이 ID는 Inventory Data Mart 테이블의 Comment 열에 있는 GUID(Globally Unique ID)입니다.

* 중복이 없습니다
+
여러 OnCommand Insight 데이터베이스에 있는 엔터티는 통합 데이터베이스에 한 번만 등록됩니다.

* 현재 레코드
+
통합된 데이터베이스(Inventory Data Mart)의 데이터는 항상 가장 최신 상태로 유지됩니다.



연결을 추가하거나 편집할 때 연결을 테스트할 수도 있습니다. 테스트는 다음을 수행합니다.

* 호스트 IP 주소, 사용자 이름 및 암호를 확인하고 연결을 설정할 수 있는지 확인합니다.
+
잘못된 연결이 빨간색으로 표시됩니다.

* OnCommand Insight 버전을 데이터 웨어하우스 버전과 비교합니다.
+
버전이 호환되지 않으면 오류 메시지가 나타납니다.

* OnCommand Insight 데이터베이스가 마지막 데이터 웨어하우스 처리에 표시된 다른 데이터베이스로 변경 또는 복원되지 않았는지 확인합니다. 변경 사항이 있으면 오류 메시지가 나타납니다.




== 단계

. 에서 데이터 웨어하우스 포털에 로그인합니다 `+https://hostname/dwh+`, 위치 `hostname` OnCommand Insight 데이터 웨어하우스가 설치된 시스템의 이름입니다.
. 왼쪽의 탐색 창에서 * 커넥터 * 를 클릭합니다.
+
커넥터 테이블은 처음에 공백으로 나타나고 커넥터를 추가한 후 커넥터 정보를 표시합니다.

. 새 커넥터를 추가하려면 * 새로 만들기 * 를 클릭합니다.
. 다음을 입력합니다.
+
** * 암호화 *
+
SSL 암호화를 사용하여 데이터 웨어하우스 요청을 하려면 를 선택합니다 `Enabled`.

** * 이름 *
+
커넥터 뷰에서 커넥터를 식별하는 커넥터 이름입니다.

** * 호스트 *
+
호스트 IP 주소입니다

** * 사용자 이름 *
+
"'재고'"

+
[NOTE]
====
이 사용자 이름 및 암호를 사용하여 원격 OnCommand Insight 데이터베이스에 로그인하고 데이터에 대한 쿼리를 수행할 수 있습니다.

====
** * 암호 *
+
"SANscreen"



. 호스트에 대한 TCP 연결에 사용할 포트를 지정하려면 * 고급 * 을 클릭하고 TCP 포트 번호를 입력합니다.
. 호스트에 대한 HTTPS 연결에 사용할 포트(기본 포트 제외)를 지정하려면 * 고급 * 을 클릭하고 포트 번호를 입력합니다.
. Test * 를 클릭합니다.
+
데이터 웨어하우스가 연결을 테스트합니다.

. 저장 * 을 클릭합니다.
+
여러 설치에 대해 여러 연결을 입력하면 데이터 웨어하우스는 데이터를 추출할 각 데이터베이스마다 하나씩 독립 빌드 프로세스를 호출합니다. 이러한 각 빌드 프로세스는 OnCommand Insight 데이터베이스에서 데이터를 추출하여 통합된 데이터베이스에 로드합니다.


