---
permalink: dwh/data-retention-and-time-periods.html 
sidebar: sidebar 
keywords:  
summary: 'OnCommand Insight 데이터 웨어하우스는 데이터의 다양한 데이터 마트와 시간 세분화를 기반으로 ETL(Extract, Transform, Load) 프로세스에서 얻은 데이터를 다른 기간 동안 보존합니다.' 
---
= 데이터 보존, ETL 및 기간
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight 데이터 웨어하우스는 ETL(Extract, Transform, Load) 프로세스에서 얻은 데이터를 데이터의 다양한 데이터 마트와 시간 세분화에 따라 다른 기간 동안 보존합니다.



== 볼륨 및 내부 볼륨에 대한 성능 및 시간 단위 세분화

OnCommand Insight 데이터 웨어하우스는 14일 동안 하루 중 각 시간(24개 데이터 포인트)에 대한 시간별 평균, 시간별 최대값 및 액세스 비트를 기록합니다. 액세스 비트는 매시간 간격 동안 볼륨에 액세스하지 않을 경우 true 이고, 볼륨이 액세스되지 않으면 false 입니다. 이전 날짜의 모든 24개 데이터 포인트는 해당 날짜의 첫 번째 ETL 프로세스 중에 얻어집니다.

시간별 데이터 지점을 수집하기 위해 시간당 하나의 ETL 프로세스를 실행할 필요가 없습니다. 하루 동안 추가 ETL 프로세스를 실행해도 OnCommand Insight 서버에서 성능 정보를 얻을 수 없습니다.



== 볼륨 및 내부 볼륨에 대한 성능 마트와 일일 세분화를 설명합니다

ETL을 처리할 때마다 데이터 웨어하우스 내에서 전날의 일별 평균이 계산되고 채워집니다. 일일 평균은 전날의 24개 데이터 요소에 대한 요약입니다. 성능 데이터 마트는 13개월 동안 볼륨 및 내부 볼륨에 대한 일일 요약을 보존합니다.



== 용량 마트 및 매일 단위

용량 마트는 13개월 동안 매일 다양한 용량 팩트에 대한 일일 측정을 제공합니다. 데이터 웨어하우스의 용량 팩트는 ETL 이전에 장치에 대한 마지막 데이터 소스 취득의 최신 상태입니다.



== 용량 마트 및 월별 세분성

데이터 웨어하우스는 13개월 동안 일일 용량 데이터를 보존합니다. 13개월 임계값에 도달하면 용량 데이터가 월별 기준으로 요약됩니다. 월별 데이터는 월별 대표 날짜인 날짜에 반영된 값을 기준으로 합니다.

다음 표는 월별 요약에 포함되는 월별 데이터를 보여줍니다.

|===


| 날짜 | 은(는) 월 대표 값입니다 | 할당된 용량입니다 


 a| 
1월 1일
 a| 
1(참)
 a| 
50TB



 a| 
1월 2일
 a| 
0(거짓)
 a| 
52TB



 a| 
...
 a| 
...
 a| 
...



 a| 
1월 31일
 a| 
0(거짓)
 a| 
65TB



 a| 
2월 1일
 a| 
1(참)
 a| 
65TB

|===
이 표에 따르면 월별 보고서에는 1월에 할당된 50TB와 2월에 할당된 65TB가 표시됩니다. 1월의 다른 모든 용량 값은 월별 요약에 포함되지 않습니다.



== 재고 마트

재고 데이터 마트는 기록이 아닙니다. ETL 프로세스가 실행될 때마다 Inventory Mart가 삭제되고 재구축됩니다. 따라서 재고 마트에서 생성된 모든 보고서는 과거 재고 구성을 반영하지 않습니다.
