---
permalink: dwh/data-warehouse-database-build-from-history-overview.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight 서버의 기록 데이터를 사용하여 데이터 웨어하우스 데이터베이스를 구축할 수 있습니다. 데이터 웨어하우스는 OnCommand Insight 서버에서 데이터를 추출하고 기록 일정에 따라 데이터 웨어하우스 데이터 마트를 작성합니다. 
---
= 데이터 웨어하우스 데이터베이스는 기록 개요에서 빌드됩니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight 서버의 기록 데이터를 사용하여 데이터 웨어하우스 데이터베이스를 구축할 수 있습니다. 데이터 웨어하우스는 OnCommand Insight 서버에서 데이터를 추출하고 기록 일정에 따라 데이터 웨어하우스 데이터 마트를 작성합니다.

이 옵션에는 특수 라이센스가 필요하지 않으며, 재고 데이터가 빌드에 포함됩니다. 그러나 용량 정보를 작성하려면 OnCommand Insight Plan 및 OnCommand Insight Perform 라이센스가 필요합니다.

기록 또는 현재 빌드가 이미 수행된 경우 마지막 작업 이전 날짜에 빌드를 수행할 수 없습니다. 즉, 현재 빌드를 수행하는 경우 기록에서 빌드할 수 없습니다. 보다 구체적으로, 2012년 1월 1일에 종료된 기록에서 빌드를 수행한 경우 2011년부터는 빌드를 수행할 수 없습니다.

기록 빌드에 실패한 ETL 프로세스가 하루 또는 2개 포함되어 있지 않으면 며칠 동안 기록을 작성하려고 하지 마십시오. 기록 데이터는 더 긴 기간이며 하루 또는 이틀 동안 추세를 크게 변경하지 않습니다. 기록에서 재생성하려면 전체 기록을 재생성합니다.

기록에서 작성 보기에는 모든 커넥터의 모든 빌드 작업이 표시됩니다. 예를 들어, 보기에는 모든 커넥터의 인벤토리 작업, 모든 빌드 실행에 대한 포트 용량 작업 및 주석 작업이 표시될 수 있습니다.

기록에서 빌드를 구성하기 전에 다음 작업이 수행되어야 합니다.

* 커넥터를 구성해야 합니다.
* 주석은 OnCommand Insight에 입력해야 하며 이전 OnCommand Insight 포털에서 * DWH용 주석 강제 업데이트 옵션 * 을 사용하여 수동으로 업데이트할 수 있습니다. 그렇지 않으면 15분 후에 자동으로 업데이트됩니다.

