---
permalink: dwh/etl-frequency.html 
sidebar: sidebar 
keywords:  
summary: '압축 풀기, 변환 및 로드\(ETL\) 프로세스를 하루에 한 번 이상 실행해야 합니다. 그러나 필요한 경우 ETL을 여러 번 실행하도록 선택합니다.' 
---
= ETL 빈도 및 날짜 데이터
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
압축 풀기, 변환 및 로드(ETL) 프로세스를 하루에 한 번 이상 실행해야 합니다. 그러나 필요한 경우 ETL을 여러 번 실행하도록 선택할 수 있습니다.

기본적으로 Cognos 보고 엔진은 모든 용량 및 성능 팩트를 추가 기능으로 처리합니다. 따라서 적절한 시간 필터 없이 하루에 ETL 프로세스를 여러 번 실행하면 용량 데이터가 두 배로 계산될 위험이 있습니다.

날짜 차원에 있는 두 날짜 데이터 요소는 일별 ETL 프로세스와 관련됩니다. 여러 데이터 모델에서 사용되는 Date 차원은 ETL의 영향을 받는 다음과 같은 데이터 요소를 포함합니다.

* * 일 대표 * 입니다
+
"IS Day Representative" 데이터 요소는 지정된 날짜 동안 첫 번째 ETL 프로세스가 실행되는 동안 1(TRUE)의 값으로 설정됩니다. 첫 번째 ETL 프로세스가 오전 1시에 실행되면 오전 1시에 로드된 모든 데이터에 대해 Day Representative가 1로 설정됩니다 ETL 프로세스. 두 번째 ETL이 나중에 예약된 경우(예: 오후 1:00), IS Day Representative는 해당 ETL 프로세스 중에 로드된 데이터에 대해 0(false)으로 설정됩니다.

* * 는 최신 * 입니다
+
"is latest" 멤버는 각 ETL 프로세스가 완료된 후 1(TRUE)의 값으로 설정됩니다. 첫 번째 ETL 프로세스가 오전 1:00에 실행되면 오전 1:00에 로드된 모든 데이터에 대해 가 최신인 가 1로 설정됩니다 ETL 프로세스. 나중에 다른 ETL 프로세스가 예약되면(예: 오후 1:00), 는 오후 1:00 동안 로드된 데이터에 대해 1로 설정됩니다 ETL 프로세스. ETL 프로세스는 오전 1시도 설정합니다 ETL 로드가 0에 가장 최근 항목입니다(FALSE).


