---
permalink: dwh/reporting-user-roles.html 
sidebar: sidebar 
keywords:  
summary: 각 사용자 계정에는 권한 집합이 있는 역할이 할당됩니다. 사용자 수는 각 역할에 연결된 보고 라이센스 수에 따라 제한됩니다. 
---
= 사용자 역할을 보고합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
각 사용자 계정에는 권한 집합이 있는 역할이 할당됩니다. 사용자 수는 각 역할에 연결된 보고 라이센스 수에 따라 제한됩니다.

각 역할은 다음 작업을 수행할 수 있습니다.

* * 수신자 *
+
OnCommand Insight 보고 포털 보고서를 보고 언어 및 표준 시간대와 같은 개인 기본 설정을 설정합니다.

+
[NOTE]
====
받는 사람은 보고서를 만들거나, 보고서를 실행하거나, 보고서를 예약하거나, 보고서를 내보내거나, 관리 작업을 수행할 수 없습니다.

====
* * 기업 소비자 *
+
보고서를 실행하고 모든 사용자 옵션을 수행합니다.

* * 비즈니스 저자 *
+
예약된 보고서를 보고, 대화형으로 보고서를 실행하고, 스토리를 만들고, 모든 비즈니스 소비자 옵션을 수행합니다.

* * 프로 작가 *
+
모든 Business Author 옵션을 수행할 뿐 아니라 보고서를 만들고 패키지 및 데이터 모듈을 만듭니다.

* * 관리자 *
+
보고서 정의 가져오기 및 내보내기, 보고서 구성, 데이터 소스 구성, 보고 작업 종료 및 재시작 등의 보고 관리 작업을 수행합니다.



다음 표에는 각 역할에 허용되는 권한 및 최대 사용자 수가 나와 있습니다.

|===


| 피처 | 받는 사람 | 비즈니스 소비자 | 비즈니스 저자 | 프로 작가 | 관리자 


 a| 
팀 콘텐츠 탭에서 보고서를 봅니다
 a| 
예
 a| 
예
 a| 
예
 a| 
예
 a| 
예



 a| 
보고서를 실행합니다
 a| 
아니요
 a| 
예
 a| 
예
 a| 
예
 a| 
예



 a| 
보고서 예약
 a| 
아니요
 a| 
예
 a| 
예
 a| 
예
 a| 
예



 a| 
외부 파일을 업로드합니다
 a| 
아니요
 a| 
아니요
 a| 
예
 a| 
예
 a| 
아니요



 a| 
스토리 만들기
 a| 
아니요
 a| 
아니요
 a| 
예
 a| 
예
 a| 
아니요



 a| 
보고서 작성
 a| 
아니요
 a| 
아니요
 a| 
예
 a| 
예
 a| 
아니요



 a| 
패키지 및 데이터 모듈을 생성합니다
 a| 
아니요
 a| 
아니요
 a| 
아니요
 a| 
예
 a| 
아니요



 a| 
관리 작업을 수행합니다
 a| 
아니요
 a| 
아니요
 a| 
아니요
 a| 
아니요
 a| 
예



 a| 
사용자 수
 a| 
OnCommand Insight 사용자 수입니다
 a| 
20
 a| 
2
 a| 
1
 a| 
1

|===
새 데이터 웨어하우스 및 보고 사용자를 추가할 때 역할의 제한을 초과하면 해당 사용자는 "비활성화"로 추가되며, 새 사용자 멤버십을 부여하려면 해당 역할을 가진 다른 사용자를 비활성화 또는 제거해야 합니다.

[NOTE]
====
보고서 작성 기능을 사용하려면 Insight Plan 라이센스가 필요합니다. ARAP(Additional Report Authoring Package)를 구매하여 비즈니스 작성자 및 Pro Author 사용자를 추가할 수 있습니다. 도움이 필요하면 OnCommand Insight 담당자에게 문의하십시오.

====
이러한 보고 사용자 역할은 직접 데이터베이스 액세스에 영향을 주지 않습니다. 이러한 보고 사용자 역할은 데이터 마트를 사용하여 SQL 쿼리를 만드는 기능에 영향을 주지 않습니다.
