---
permalink: dwh/restoring-the-data-warehouse-database.html 
sidebar: sidebar 
keywords:  
summary: 데이터 웨어하우스 데이터베이스를 백업할 때 만든 .zip 파일을 사용하여 데이터 웨어하우스 데이터베이스를 복원할 수 있습니다. 
---
= 데이터 웨어하우스 데이터베이스 복원
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
을 사용하여 데이터 웨어하우스 데이터베이스를 복원할 수 있습니다 `.zip` 데이터 웨어하우스 데이터베이스를 백업할 때 생성된 파일입니다.



== 이 작업에 대해

데이터 웨어하우스 데이터베이스를 복원할 때 백업에서 사용자 계정 정보를 복원할 수도 있습니다. 사용자 관리 테이블은 데이터 웨어하우스 보고서 엔진이 데이터 웨어하우스 전용 설치에서 사용됩니다.



== 단계

. 에서 데이터 웨어하우스 포털에 로그인합니다 `+https://hostname/dwh+`, 위치 `hostname` OnCommand Insight 데이터 웨어하우스가 설치된 시스템의 이름입니다.
. 왼쪽의 탐색 창에서 * 백업/복원 * 을 클릭합니다.
. 데이터베이스 및 보고서 복원 * 섹션에서 * 찾아보기 * 를 클릭하고 을 찾습니다 `.zip` 데이터 웨어하우스 백업을 포함하는 파일입니다.
. 보고서 또는 사용자 계정 데이터를 복원하려면 다음 확인란 중 하나 또는 둘 다를 선택합니다.
+
** * 데이터베이스 복원 *
+
데이터 웨어하우스 설정, 데이터 마트, 연결 및 사용자 계정 정보가 포함됩니다.

** * 보고서 복원 *
+
사용자 지정 보고서, 미리 디자인된 보고서, 미리 디자인된 보고서의 변경 내용, 보고 포털에서 만든 보고 설정 등이 포함됩니다.

+
[NOTE]
====
데이터베이스 백업에 이름에 슬래시(/) 또는 여는 대괄호([)가 있는 사용자 지정 보고서(예: US IT Center Switch Port Boston/July)가 포함되어 있는 경우 복원 작업에서는 보고서의 이름을 바꾸고 슬래시 또는 여는 대괄호를 밑줄로 바꿉니다(예: 미국 IT 센터 스위치 포트 Boston_July).

====


. 복원 * 을 클릭합니다.
+
복원 프로세스가 완료되면 복원 단추 아래에 메시지가 표시됩니다. 복원 프로세스가 성공적으로 완료되면 성공 메시지가 표시됩니다. 복원 프로세스가 실패하면 이 메시지는 오류를 발생시킨 특정 예외를 보고합니다. 예외가 발생하고 복원 프로세스가 실패하면 원래 데이터베이스가 자동으로 재설정됩니다.


