---
permalink: dwh/restoring-and-upgrading-reports-for-versions-prior-to-6-3.html 
sidebar: sidebar 
keywords:  
summary: 6.3 이전 Insight 버전을 업그레이드하는 경우 보고 아티팩트를 수동으로 복원해야 합니다. 
---
= 6.3 이전 버전의 보고서 복원 및 업그레이드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
6.3 이전 Insight 버전을 업그레이드하는 경우 보고 아티팩트를 수동으로 복원해야 합니다.



== 시작하기 전에

"DWH(데이터 웨어하우스 업그레이드)" 및 "사용자 정의 보고서 및 보고 아티팩트 백업" 항목의 지침을 따릅니다.



== 단계

. 버전 6.3 이전 버전에서 보고 아티팩트를 복원하려면 에서 만들고 저장한 backup.zip 파일 내보내기 를 복사합니다 `<install>\cognos\c10_64\deployment` 디렉토리.
. 브라우저를 열고 로 이동합니다 `http://<server>:<port>/reporting` 설치 중에 사용한 서버 및 포트의 경우.
. 사용자 이름과 암호를 입력하고 * 로그인 * 을 클릭합니다.
. 시작 * 메뉴에서 * Insight Reporting Administration * 을 선택합니다.
. Configuration * 탭을 클릭합니다.
+
데이터 모델의 변경으로 인해 이전 패키지의 보고서가 실행되지 않을 수 있으므로 업그레이드해야 합니다.

. 콘텐츠 관리 * 를 클릭합니다.
. 새 가져오기 * 버튼을 클릭합니다.
. 배포 디렉터리에 복사한 아카이브를 확인합니다(예: `backup6.0.zip`)를 선택하고 * 다음 * 을 클릭합니다.
. 보관 파일을 보호하기 위해 비밀번호를 입력한 경우 비밀번호를 입력하고 * OK * (확인 *)를 클릭합니다.
. 이름을 변경합니다 `+Export...+` 를 선택합니다 `Import Backup` 를 클릭하고 * 다음 * 을 클릭합니다.
. 각 패키지 이름 옆에 있는 연필 아이콘을 클릭하고 필요한 경우 새 대상 이름을 입력합니다. 예를 들어, 을 추가합니다 `_original` 기존 이름에 접미사 사용. 그런 다음 * 확인 * 을 클릭합니다.
. 모든 패키지의 대상 패키지 이름을 변경한 후 모든 파란색 폴더를 선택하고 * 다음 * 을 클릭하여 계속합니다.
. 모든 기본값을 적용합니다.
. 마침 * 을 클릭한 다음 * 실행 * 을 선택합니다.
. 이 가져오기의 세부 정보를 확인하고 * OK * 를 클릭합니다.
. 가져오기 상태를 보려면 * Refresh * (새로 고침 *)를 클릭합니다.
. 가져오기가 완료되면 * 닫기 * 를 클릭합니다.




== 결과

두 개의 패키지 세트가 공용 폴더 탭에 나타납니다. 예를 들어, 가 있는 가 있습니다 `7.0` 접미사(새 버전의 경우) 및 가 포함된 접미사 `_original` (또는 백업/복원 절차 중에 입력한 내용) 접미사에 이전 보고서가 포함되어 있습니다. 데이터 모델의 변경으로 인해 이전 패키지의 보고서가 실행되지 않을 수 있으므로 업그레이드해야 합니다. 이제 포털 탭이 포털 페이지의 현재 버전을 가리킵니다.
