---
permalink: dwh/setting-up-multiple-tenancy-in-reporting.html 
sidebar: sidebar 
keywords:  
summary: 'OnCommand Insight 데이터 웨어하우스는 사용자를 하나 이상의 비즈니스 엔터티에 연결할 수 있도록 하여 보고에서 다중 임차\(종종 "다중 임차" 또는 "멀티 테넌시"\ 로 단축)를 수용합니다. 이 기능을 사용하면 관리자는 사용자 속성 또는 사용자 가입에 따라 데이터나 보고서를 분리할 수 있습니다.' 
---
= 보고에서 다중 임차 설정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight 데이터 웨어하우스는 사용자를 하나 이상의 비즈니스 엔티티에 연결할 수 있도록 하여 보고에서 다중 임차(종종 "몰티 테넌시" 또는 "몰티테넌시"로 단축)를 수용합니다. 이 기능을 사용하면 관리자는 사용자 속성 또는 사용자 가입에 따라 데이터나 보고서를 분리할 수 있습니다.

업무 엔티티는 다음 값을 사용하여 용량 차지백 목적으로 계층을 사용합니다.

* 테넌트: 기본적으로 서비스 공급자가 리소스를 고객과 연결하는 데 사용합니다. 예를 들어 NetApp이 있습니다.
* 사업 부문(LOB): 회사 내 사업 부문(예: "하드웨어" 또는 "소프트웨어").
* 사업부: "영업" 또는 "마케팅"과 같은 기존 사업부입니다.
* Project(프로젝트): 용량 비용 청구를 할당할 수 있는 프로젝트입니다.


다중 임차를 구성하는 프로세스에는 다음과 같은 주요 단계가 포함됩니다.

* 데이터 웨어하우스 사용자 계정을 구성합니다.
* 보고 포털에서 그룹을 만듭니다.
* 비즈니스 엔티티를 나타내는 하나 이상의 그룹에 사용자를 할당합니다.
* 사용자를 하나 이상의 업무 엔티티에 할당합니다. 예를 들어, "NetApp"과 관련된 사용자는 테넌트로 ""NetApp""을 보유한 모든 비즈니스 엔터티에 액세스할 수 있습니다.
* 사용자가 볼 수 있는 보고서만 볼 수 있는지 테스트합니다.


다음은 사용자가 보고 데이터에 액세스하는 방법을 요약한 내용입니다.

* 그룹에 할당되지 않은 사용자는 모든 데이터에 액세스할 수 있습니다.
* 그룹에 할당된 사용자는 업무 엔티티가 없는 레코드에 액세스할 수 없습니다.


예를 들어 다음 부서가 있을 수 있으며 이러한 부서 내의 사용자에 대한 보고서를 분리해야 할 수 있습니다.

|===


| 사용자 | 엔지니어링 | 지원 | 재무 | 법적 고지 


 a| 
사용자1
 a| 
X
 a| 
X
 a| 
 a| 



 a| 
사용자2
 a| 
 a| 
 a| 
X
 a| 
X



 a| 
사용자3
 a| 
 a| 
X
 a| 
 a| 

|===