---
permalink: dwh/viewing-switches-consolidation-issues.html 
sidebar: sidebar 
keywords:  
summary: 스위치에 대해 보고된 데이터는 Inventory Data Mart에서 파생됩니다. 모든 스위치에 대해 각 커넥터를 보고하는 행과 각 스위치를 사용하는 기본 커넥터가 있습니다. 
---
= 스위치 통합 문제 보기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스위치에 대해 보고된 데이터는 Inventory Data Mart에서 파생됩니다. 모든 스위치에 대해 각 커넥터를 보고하는 행과 각 스위치를 사용하는 기본 커넥터가 있습니다.



== 단계

. 에서 데이터 웨어하우스 포털에 로그인합니다 `+https://hostname/dwh+`, 위치 `hostname` OnCommand Insight 데이터 웨어하우스가 설치된 시스템의 이름입니다.
. 왼쪽의 탐색 창에서 ** 문제 해결** 을 클릭합니다.
. 섀시 통합 * 섹션에서 * SAN 스위치 * 를 클릭합니다.
. 필요한 경우 텍스트 부분을 입력하고 * Filter * 를 클릭하여 이 보기의 데이터를 필터링합니다. 필터를 지우려면 필터 상자의 선택을 취소하고 * 필터 * 를 클릭합니다. 스위치 이름, 스위치 IP, 공급업체 모델 또는 OnCommand Insight 객체 ID를 기준으로 필터링할 수 있습니다.
+
필터는 대소문자를 구분합니다.

. 다음 데이터를 검토합니다.
+
** GUID *
+
이 유형의 통합 디바이스(스토리지 어레이)에 대한 글로벌 고유 식별자

** * 이름 *
+
데이터 웨어하우스에 표시되는 통합 스토리지 배열의 이름입니다

** * IP *
+
통합 스토리지 시스템의 IP 주소입니다

** * 공급업체 및 모델 *
+
통합 스토리지 어레이를 판매하는 공급업체 이름 및 제조업체의 모델 번호입니다

** WWN *
+
통합 스위치의 WWN입니다

** * 주 커넥터 *
+
데이터의 실제 소스인 OnCommand Insight 커넥터의 이름입니다

** * 사용 가능한 커넥터 *
+
통합 스토리지 배열이 있는 모든 OnCommand Insight 커넥터

** * Insight ID *
+
주 커넥터가 상주하는 OnCommand Insight 섀시의 통합 스토리지 배열의 ID입니다

** * Insight 변경 시간 *
+
스토리지 배열에 대한 OnCommand Insight에서 업데이트가 발생한 경우 및 다른 OnCommand Insight 서버에서 동일한 스토리지 배열이 업데이트된 경우




