---
permalink: howto/collecting-integration-data.html 
sidebar: sidebar 
keywords:  
summary: 통합 데이터를 OnCommand Insight 시스템으로 가져올 수 있습니다. 성능 데이터를 수집하는 데몬으로 실행되는 오픈 소스 소프트웨어인 Collectd를 사용하거나 일반 SNMP 데이터를 수집할 수 있는 통합 SNMP 데이터 소스를 사용하여 데이터를 가져올 수 있습니다. 
---
= 통합 데이터 수집 중
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
통합 데이터를 OnCommand Insight 시스템으로 가져올 수 있습니다. 성능 데이터를 수집하는 데몬으로 실행되는 오픈 소스 소프트웨어인 Collectd를 사용하거나 일반 SNMP 데이터를 수집할 수 있는 통합 SNMP 데이터 소스를 사용하여 데이터를 가져올 수 있습니다.



== 통합 데이터를 위한 데이터 흐름

다음은 OnCommand Insight 서버에 제공할 수 있는 총 통합 데이터 양에 적용됩니다.

* 100개의 통화가 대기됩니다.
+
클라이언트가 대기열에서 1분 이상 대기하면 시간 초과 오류가 발생합니다.

* 통합 데이터에 권장되는 수집 속도는 클라이언트당 분당 1회입니다.
* 허용되는 통합 객체 유형은 300개로 제한됩니다.




== Collectd 소프트웨어 및 설명서 액세스

NetApp의 GitHub 사이트에서 collectd에 대한 출력 작성기 플러그인 소프트웨어 및 문서에 액세스할 수 있습니다. https://github.com/NetApp/OCI_collectd[]



== 통합 데이터의 백업 및 복원

통합 데이터의 백업 및 복구는 OnCommand Insight 성능 데이터 백업 및 복원 정책을 기반으로 모델링됩니다. 성능 데이터를 위해 백업을 구성하면 통합 데이터도 백업에 포함됩니다. 성능 백업과 마찬가지로 최근 7일간의 통합 데이터가 백업에 포함됩니다. 백업에 있는 모든 통합 데이터는 복원 작업에서 복원됩니다.



== 추가 수익 실적을

통합 데이터를 보고하려면 Perform 라이센스가 필요합니다. Perform 라이센스가 없는 경우 "Perform license required to report integration data(통합 데이터를 보고하는 데 필요한 라이센스 수행)" 메시지와 함께 오류가 발생합니다.
