---
permalink: howto/compare-objects-with-the-top-10-latency-total-to-the-average-latency-for-all-like-objects.html 
sidebar: sidebar 
keywords:  
summary: VM을 총 10개의 지연 시간 중 가장 짧은 지연 시간과 총 평균 지연 시간을 비교하여 평균 범위를 벗어나는 지연 시간을 확인할 수 있습니다. 이 정보는 VM에서 워크로드의 균형을 조정하는 결정에 도움이 될 수 있습니다. 
---
= 오브젝트 및 비슷한 모든 오브젝트의 평균 지연 시간과 상위 10개 지연 시간을 비교합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VM을 총 10개의 지연 시간 중 가장 짧은 지연 시간과 총 평균 지연 시간을 비교하여 평균 범위를 벗어나는 지연 시간을 확인할 수 있습니다. 이 정보는 VM에서 워크로드의 균형을 조정하는 결정에 도움이 될 수 있습니다.



== 단계

. 누적 영역형 차트가 있는 위젯을 새 대시보드에 추가합니다. * Widget * > * Stacked Area Chart *
+
.. 기본 디바이스를 가상 머신으로 변경합니다. * Storage * > * Virtual Machine * > * Latency Total * 을 클릭합니다
+
위젯은 모든 VM에 대한 총 지연 시간을 24시간 동안 누적 영역형 차트로 표시합니다.

.. 이 위젯에서 모든 VM에 대한 지연 시간 합계: * Widget * > * Line Chart * 를 표시하는 두 번째 디스플레이를 만듭니다
.. 기본 디바이스를 가상 머신으로 변경합니다. * Virtual Machine * > * Latency-total * 을 클릭합니다
+
위젯은 선형 차트를 사용하여 기본 24시간 기간의 지연 시간 합계를 표시합니다.

.. Roll Up * 표시줄에서 * X * 를 클릭하고 * Show * > * Top * > * 10 * 을 선택합니다


+
총 지연 시간을 기준으로 상위 10개의 VM이 표시됩니다.

. 모든 VM의 총 평균 지연 시간을 상위 10 IOPS와 비교하려면 다음 단계를 사용하십시오.
+
.. 추가 * 를 클릭합니다
.. 기본 디바이스를 가상 머신으로 변경합니다. * 스토리지 * > * 가상 머신 * > * IOPS 합계 * 를 클릭합니다
.. Roll Up * 표시줄에서 * X * 를 클릭하고 * Show * > * Top * > * 10 * 을 선택합니다


+
시스템은 지연 시간이 긴 10개의 오브젝트를 표시하며 선형 차트에 평균 지연 시간을 표시합니다.

+
이미지:::./media/analytics-top10-avg.gif[]

+
+평균 지연 시간은 1.6ms이고 상위 10개 VM의 지연 시간은 200ms입니다.


