---
permalink: howto/configuring-applications-for-your-company.html 
sidebar: sidebar 
keywords:  
summary: 회사 환경에서 사용되는 애플리케이션을 이해하면 자산 사용을 추적하고 비용을 보고하는 데 도움이 됩니다. 여기서는 회사의 애플리케이션을 구성하고 적절한 자산과 연결합니다. 
---
= 회사의 애플리케이션을 구성하는 중입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
회사 환경에서 사용되는 애플리케이션을 이해하면 자산 사용량을 추적하고 비용을 보고하는 데 도움이 됩니다. 여기서는 회사의 애플리케이션을 구성하고 적절한 자산과 연결합니다.



== 이 작업에 대해

회사의 업무 엔티티 구성 섹션에서 일부 업무 엔티티를 만들고 각 업무 엔티티에 연결된 모든 애플리케이션을 나열하도록 권장합니다. OnCommand Insight를 사용하면 사용 또는 비용 보고와 같은 관련 애플리케이션과 관련된 데이터를 추적할 수 있습니다.

사용자 환경에서 실행 중인 애플리케이션과 관련된 데이터를 추적하려면 먼저 해당 애플리케이션을 정의하고 적절한 자산과 연결해야 합니다. 호스트, 가상 머신, 볼륨, 내부 볼륨, qtree, 공유 및 하이퍼바이저.

이 연습에서는 마케팅 팀이 Exchange 전자 메일에 사용하는 가상 시스템의 사용을 추적하려고 합니다. 비즈니스 엔티티를 정의하는 동안 작성한 다음 테이블을 기억하실 것입니다. 이 워크시트에 각 업무 엔티티가 사용하는 애플리케이션을 나열하는 열을 추가해 보겠습니다. (이 표는 워크시트 예일 뿐입니다. Insight의 비즈니스 엔터티 테이블에는 "애플리케이션" 열이 표시되지 않습니다.)

|===


| 테넌트 | 사업 부문 | 사업부 | 프로젝트 | 응용 프로그램 


 a| 
넷엡
 a| 
데이터 스토리지
 a| 
법적 고지
 a| 
특허
 a| 
Oracle Identity Manager, Oracle On Demand, Patentg마법사



 a| 
넷엡
 a| 
데이터 스토리지
 a| 
마케팅
 a| 
영업 이벤트
 a| 
Exchange, Oracle Shared database, Blastoff Event Planner



 a| 
해당 없음
 a| 
해당 없음
 a| 
안전 및 보안
 a| 
해당 없음
 a| 
해당 없음



 a| 
...
 a| 
 a| 
 a| 
 a| 

|===
* Insight에서 애플리케이션 생성: *



== 단계

. 관리 권한이 있는 사용자로 Insight에 로그인합니다.
. Manage * > * Applications * 를 선택합니다
. 추가 * 버튼을 클릭합니다
. 애플리케이션의 이름을 입력합니다(예: ""Exchange"" 입력).
. 응용 프로그램의 우선 순위를 선택합니다
. 응용 프로그램을 업무 엔티티에 연결하려면 * 업무 엔티티 * 드롭다운에서 하나를 선택합니다. 그렇지 않으면 이를 "없음"으로 남겨둘 수 있습니다.
. 각 호스트가 클러스터의 동일한 볼륨에 액세스할 수 있도록 하려면 * 볼륨 공유 확인 * 상자가 선택되어 있는지 확인합니다. 예를 들어, high-availability 클러스터의 호스트는 장애 조치를 위해 동일한 볼륨에 마스킹되어야 하는 경우가 많지만, 관련 없는 애플리케이션의 호스트는 일반적으로 동일한 물리적 볼륨에 액세스할 필요가 없습니다. 또한 규정 정책에 따라 보안상의 이유로 관련 없는 응용 프로그램이 동일한 물리적 볼륨에 액세스하는 것을 명시적으로 허용하지 않을 수 있습니다. 볼륨 공유를 사용하지 않는 경우 * 볼륨 공유 확인 * 상자의 선택을 취소합니다. 이 작업을 수행하려면 보증 라이센스가 필요합니다.
. 저장 을 클릭합니다.
. 사용자 환경의 다른 모든 애플리케이션에 대해 이 과정을 반복합니다.




== 작업을 마친 후

마케팅 팀에서 Exchange 애플리케이션을 사용하고 있음을 알 수 있습니다. Exchange의 가상 시스템 활용률을 보고 스토리지 추가 시기를 예측하고자 합니다. Exchange 애플리케이션을 모든 마케팅 VM과 연결하겠습니다. 이 작업을 수행하는 가장 쉬운 방법은 쿼리를 사용하는 것입니다.

다음 단계에 따라 각 응용 프로그램을 해당 자산과 연결할 수 있습니다.

* 응용 프로그램을 자산에 연결: *

이제 애플리케이션을 만들고 원하는 비즈니스 엔티티에 연결했으므로 이제 해당 애플리케이션을 사용자 환경의 자산과 연결할 수 있습니다. 이 예에서는 Exchange 애플리케이션을 회사의 여러 가상 머신에 연결합니다. 가장 쉬운 방법은 쿼리입니다.

. 쿼리 * > * + 새 쿼리 * 를 선택합니다.
. 리소스 유형 선택 * 드롭다운에서 _Virtual Machine_을 선택합니다
. 마케팅 팀에서 자산 이름을 ""_mktg_" 문자열로 지정합니다. 이름 필터 상자에 ""_mktg_"(따옴표 제외)를 입력하고 적용(확인 표시) 단추를 클릭합니다.
. ""_mktg_" 문자열이 있는 모든 VM의 목록이 표시됩니다.
. 필요한 경우 * More * (자세히 *) 드롭다운을 클릭하고 추가 필터를 추가합니다.
. 원하는 각 VM 이름 옆의 확인란을 클릭하여 Exchange에 사용되는 VM을 선택하거나 열 상단의 확인란을 클릭하여 모든 VM을 선택합니다.
. 원하는 VM을 선택한 후 * Actions * 버튼을 클릭하고 * Add Application * 을 선택합니다.
. 응용 프로그램 할당 대화 상자에서 * 응용 프로그램 * 드롭다운을 클릭하고 ""교환""을 선택합니다.
. 저장 * 을 클릭합니다.
. 필요에 따라 Exchange 애플리케이션을 다른 자산(호스트, 볼륨 등)과 연결하려면 이 과정을 반복합니다.

