---
permalink: howto/creating-performance-policies-for-datastores.html 
sidebar: sidebar 
keywords: performance policy,Datastore 
summary: 모니터링 중인 스토리지 풀과 관련된 데이터 저장소와 연결된 메트릭에 대한 임계값을 사용하여 성능 정책을 생성할 수 있습니다. 기본적으로 성능 정책은 지정된 유형의 모든 디바이스를 생성할 때 적용됩니다. 성능 정책에 특정 장치 또는 장치 집합만 포함하도록 주석을 만들 수 있습니다. 
---
= 데이터 저장소에 대한 성능 정책 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
모니터링 중인 스토리지 풀과 관련된 데이터 저장소와 연결된 메트릭에 대한 임계값을 사용하여 성능 정책을 생성할 수 있습니다. 기본적으로 성능 정책은 지정된 유형의 모든 디바이스를 생성할 때 적용됩니다. 성능 정책에 특정 장치 또는 장치 집합만 포함하도록 주석을 만들 수 있습니다.



== 시작하기 전에

성능 정책에서 주석을 사용하는 경우 정책을 생성하기 전에 주석이 존재해야 합니다.



== 이 작업에 대해

모니터링 중인 하나 이상의 데이터 저장소가 사용자가 설정한 임계값을 초과할 때 알림을 제공하는 성능 정책을 생성합니다. 사용자의 요구에 맞는 글로벌 정책이 시스템에 이미 포함되어 있거나, 데이터 저장소에 주석을 달 경우 주석을 사용하는 정책도 작동할 수 있습니다.



== 단계

. Insight(인사이트) 도구 모음에서 * Manage(관리) * > * Performance Policies(성능 정책) * 를 선택합니다
+
성능 정책 페이지가 표시됩니다. 기존 성능 정책을 검토하여 모니터링할 임계값에 대한 메트릭을 처리하는 기존 정책을 식별합니다.

. 새 정책을 추가하려면 * + 추가 * 를 클릭합니다
. "정책 이름" 추가
+
개체의 다른 모든 정책 이름과 다른 이름을 사용해야 합니다. 예를 들어, 내부 볼륨에 대해 "지연 시간"이라는 두 개의 정책을 사용할 수는 없지만, 내부 볼륨에 대한 "지연 시간" 정책과 데이터 저장소에 대한 또 다른 "지연 시간" 정책을 가질 수는 있습니다. 가장 좋은 방법은 개체 유형에 관계없이 모든 정책에 대해 항상 고유한 이름을 사용하는 것입니다.

. Object Type으로 "Datastore"를 선택합니다
. "첫 번째 항목"을 클릭합니다.
+
첫 번째 발생 옵션은 첫 번째 데이터 샘플에서 임계값이 초과되면 알림을 트리거합니다. 다른 모든 옵션은 임계값을 한 번 넘어섰을 때 경고를 발생시키고 지정된 시간 이상 연속적으로 교차하는 경우에 발생합니다.

. "경고"를 클릭합니다.
. "'알림 생성''으로 * Capacity ratio-over commit * 을 선택하고 값을 * > 150 * 로 설정합니다
+
용량 합계** 및 * 사용된 용량 * 과 같은 용량 관련 경고를 추가로 생성할 수 있습니다.


