---
permalink: howto/creating-a-performance-policy-for-alerting.html 
sidebar: sidebar 
keywords:  
summary: 성능 정책을 사용하면 특정 조건이 충족되면 경고를 모니터링하고 보낼 수 있습니다. 
---
= 알림을 위한 성능 정책 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
성능 정책을 사용하면 특정 조건이 충족되면 경고를 모니터링하고 보낼 수 있습니다.



== 이 작업에 대해

이제 자산에 대한 주석을 작성했으므로 Sunnyvale(DC1_SVL) 데이터 센터의 모든 스토리지 어레이에서 지연 시간이 2ms보다 높을 때 경고하는 데 사용할 수 있는 성능 정책을 만들어 보겠습니다. 이러한 상황이 발생하면 선택한 수신자에게 이메일을 보냅니다.



== 단계

. 관리 * > * 성능 정책 * 을 선택합니다.
+
성능 정책 페이지가 열립니다. 여러 가지 기본 정책이 이미 설정되어 있으므로 필요에 따라 수정할 수 있습니다. 그러나 새 정책을 만들 것입니다.

. 추가 * 버튼을 클릭합니다.
+
Add Policy * (정책 추가 *) 대화 상자가 열립니다.

. Policy name * 필드에 "'VL Data Center Latency policy'를 입력합니다.
+
개체의 다른 모든 정책 이름과 다른 이름을 사용해야 합니다. 예를 들어, 내부 볼륨에 대해 "지연 시간"이라는 두 개의 정책을 사용할 수는 없지만, 내부 볼륨에 대한 "지연 시간" 정책과 다른 볼륨에 대한 "지연 시간" 정책을 사용할 수는 있습니다. 가장 좋은 방법은 개체 유형에 관계없이 모든 정책에 대해 항상 고유한 이름을 사용하는 것입니다.

. 유형 * 의 개체에 적용 에서 * 스토리지 * 를 선택합니다.
. with annotation * 필드에서 * Data Center * 가 "dC1_SVL"인 경우(또는 여기서 원하는 데이터 센터의 이름을 선택하십시오).
. 첫 번째 발생 항목 * 의 창 뒤에 적용합니다.
+
첫 번째 발생 옵션은 첫 번째 데이터 샘플에서 임계값이 초과되면 알림을 트리거합니다. 다른 모든 옵션은 임계값을 한 번 넘어섰을 때 경고를 발생시키고 지정된 시간 이상 연속적으로 교차하는 경우에 발생합니다.

. with severity * 목록에서 * Warning * 을 선택합니다.
. Email recipient * 에서 글로벌 수신자 목록을 무시하려면 클릭합니다. 처음 원하는 알림 수신인의 이메일 주소를 추가하려면 ** + ** 을 클릭하고 * 확인 * 을 클릭합니다. 원하는 추가 이메일 수신자에 대해 반복합니다.
. 다음 중 * 가 참인 경우 기본 선택 항목을 Create alert 로 둡니다. 설정된 임계값 중 하나가 충족되면 경고가 전송됩니다. 또한 설정된 모든 * 임계값이 충족되는 경우에만 알림을 보내도록 선택할 수 있습니다.
. 첫 번째 임계값을 설정하려면 드롭다운에서 * Latency - Total * 을 선택하고 2ms를 초과하도록 설정합니다.
. 필요한 경우 * Add threshold * (임계값 추가) 버튼을 클릭하여 알림에 추가 임계값을 추가합니다. 정책이 원하는 방식으로 사용자 지정되면 * 저장 * 을 클릭합니다.
. 알림이 생성된 경우 * 추가 정책 처리 중지 * 를 선택할 수도 있습니다. 이 정책 조건이 충족되면 추가 정책 경고가 중지됩니다.
. 비즈니스 요구에 따라 다른 조건에 따라 다른 받는 사람에 대한 알림을 설정하여 원하는 만큼 새 정책을 추가할 수 있습니다. 특정 수신자 없이 구성된 모든 정책은 * Admin * > * Notifications * 페이지에 설정된 글로벌 수신자 목록으로 경고를 보냅니다




== 작업을 마친 후

새 정책이 저장되면 각 정책이 자동으로 활성화되고 정책 조건이 충족되면 수신자는 알림을 받기 시작합니다(A_Violation_). 대시보드 * > * 위반 대시보드 * 에서 이러한 위반 사항을 모니터링할 수도 있습니다.
