---
permalink: howto/creating-policies-and-thresholds-for-storage-pools.html 
sidebar: sidebar 
keywords:  
summary: 스토리지 풀 자산에 대한 임계값이 초과되었을 때 알림을 트리거하는 성능 정책을 생성할 수 있습니다. 
---
= 스토리지 풀에 대한 성능 정책 생성
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
스토리지 풀 자산에 대한 임계값이 초과되었을 때 알림을 트리거하는 성능 정책을 생성할 수 있습니다.



== 시작하기 전에

이 절차에서는 스토리지 풀을 씬 프로비저닝했다고 가정합니다.



== 이 작업에 대해

운영 중단을 일으킬 수 있는 스토리지 풀의 변경 사항을 모니터링하고 보고하는 정책을 생성하려고 합니다. 씬 프로비저닝된 물리적 스토리지 풀의 경우 물리적 용량을 모니터링하고 Overcommit Ratio를 모니터링하려고 합니다.



== 단계

. 브라우저에서 OnCommand Insight를 엽니다.
. Manage * > * Performance Policies * 를 선택합니다
+
성능 정책 페이지가 표시됩니다. 정책은 객체별로 구성되며 목록에 나타나는 순서대로 평가됩니다. 알림이 활성화된 경우(* Admin*>* Notifications*) 성능 정책이 위반될 때 Insight에서 이메일을 보내도록 구성할 수 있습니다.

. 새 정책을 만들려면 **+Add**를 클릭합니다.
. 정책 이름 * 에 스토리지 풀의 정책 이름을 입력합니다.
. Apply to objects of type * 에서 Storage Pool 을 선택합니다.
. 다음 시간 뒤에 적용 * 에서 첫 번째 발생 항목을 입력합니다.
. 심각도 * 로 * 에 Critical 을 입력합니다
. 임계값이 위반될 때 알림을 받을 e-메일 수신자를 구성합니다.
+
기본적으로 정책 위반에 대한 전자 메일 알림은 전역 전자 메일 목록의 받는 사람에게 전송됩니다. 특정 정책에 대한 알림이 특정 수신자에게 전송되도록 이러한 설정을 재정의할 수 있습니다.

+
링크를 클릭하여 받는 사람 목록을 연 다음 + 단추를 클릭하여 받는 사람을 추가합니다. 이 정책에 대한 위반 알림은 목록의 모든 수신자에게 전송됩니다.

. 다음 중 하나라도 해당되는 경우 * Create alert에서 * Capacity ratio-used > 85%를 입력합니다




== 결과

이 구성은 스토리지 풀의 물리적 용량의 85% 이상이 사용될 때 시스템에서 심각한 경고 메시지를 보냅니다. 물리적 메모리의 100%를 사용하면 응용 프로그램 오류가 발생합니다.



== 추가 스토리지 풀 정책을 생성합니다



=== 이 작업에 대해

사용된 스토리지 풀 용량이 75%를 초과할 경우 경고 메시지를 표시하는 추가 "'사용된 용량 비율'" 정책을 생성합니다. 알림이 활성화된 경우(* Admin*>* Notifications*) 성능 정책이 위반될 때 Insight에서 이메일을 보내도록 구성할 수 있습니다.
