---
permalink: howto/custom-dashboard-concepts.html 
sidebar: sidebar 
keywords:  
summary: 사용자 지정 대시보드 및 위젯을 통해 데이터가 표시되는 방식을 유연하게 지정할 수 있습니다. 다음은 사용자 지정 대시보드를 최대한 활용하는 데 도움이 되는 몇 가지 개념입니다. 각 개념은 다음 섹션에서 자세히 설명합니다. 
---
= 사용자 지정 대시보드 개념
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
사용자 지정 대시보드 및 위젯을 통해 데이터가 표시되는 방식을 유연하게 지정할 수 있습니다. 다음은 사용자 지정 대시보드를 최대한 활용하는 데 도움이 되는 몇 가지 개념입니다. 각 개념은 다음 섹션에서 자세히 설명합니다.

* 변수 *

변수를 사용하면 대시보드의 일부 또는 모든 위젯에 표시된 데이터를 한 번에 변경할 수 있습니다. 각 위젯이 공통 변수를 사용하도록 설정하면 한 곳에서 변경한 경우 각 위젯에 표시된 데이터가 자동으로 업데이트됩니다.

* 여러 쿼리 및/또는 식 *

각 시계열 위젯(꺾은선형, 스플라인, 영역형 또는 누적 영역형 차트)에는 최대 5개의 쿼리 및/또는 식을 사용하여 표시할 데이터를 결정할 수 있으므로 단일 차트에서 서로 다른 데이터 집합을 비교할 수 있습니다. 예를 들어, 스토리지 및 VM의 IOPS를 보여 주는 선형 차트 또는 모든 스토리지 풀의 처리량과 지연 시간을 비교한 단일 차트를 사용할 수 있습니다.

* 롤업 및 그룹화 *

각 위젯에 표시된 데이터는 수집된 데이터 포인트에서 취합됩니다. 다음 방법 중 하나로 이 데이터를 롤업하도록 선택할 수 있습니다.

* Avg: 데이터를 기본 데이터의 평균으로 롤업합니다
* Max(최대): 데이터를 기본 데이터의 최대값으로 롤업합니다
* MIN(최소): 데이터를 최소 내부 데이터로 롤업합니다
* Sum(합계): 데이터를 원본 데이터의 합계로 롤업합니다


기본적으로 모든 원본 데이터는 차트 또는 테이블의 단일 항목(모두)으로 롤업됩니다. 데이터 센터 또는 계층과 같은 특정 속성에 대한 데이터를 롤업하여 기본 데이터를 원하는 그룹으로 분산하도록 선택할 수 있습니다. 위젯에는 선택한 속성에 대한 데이터만 표시됩니다.

선택한 특성에 따라 테이블 위젯에서 데이터를 그룹화할 수 있습니다. 예를 들어 데이터 센터별로 테이블을 그룹화하도록 선택할 수 있습니다. 그룹은 가능한 한 확장 또는 축소할 수 있습니다. 위젯에서 설정한 롤업 방법(평균, 최대, 최소 또는 합계)에 따라 테이블의 성능 데이터가 그룹 헤더에서 롤업됩니다.

표 위젯은 모든 열을 기준으로 정렬할 수 있으며 필요에 따라 열을 이동하거나 크기를 조정할 수 있습니다.

* 위/아래 *

이 옵션을 사용하여 차트 위젯에서 결과 집합을 제한하거나 위젯에 상위 N개의 결과를 표시할지 또는 하위 N개의 결과를 표시할지 여부를 선택할 수 있습니다. 데이터가 롤업되지 않거나 특정 특성에 의해 롤업되는 경우 이 옵션을 선택할 수 있습니다.

* 대시보드 시간 재정의 *

기본적으로 대시보드에 추가하는 대부분의 위젯은 대시보드의 시간 범위 설정(3시간, 24시간, 3D, 7d, 30d 또는 사용자 지정 범위)에 따라 데이터를 표시합니다. 그러나 개별 위젯에서 이 시간 설정을 재정의하여 대시보드의 시간 설정에 관계없이 특정 시간 컨텍스트에 데이터를 표시하도록 할 수 있습니다.

이러한 개념은 다음 섹션에서 자세히 설명합니다.
