---
permalink: howto/custom-dashboard-roll-up.html 
sidebar: sidebar 
keywords:  
summary: 대시보드 위젯에 표시되는 데이터는 수집된 데이터 지점에서 취합되므로 대시보드에서 유연성과 오목성이 확보됩니다. 
---
= 롤업 및 집선
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
대시보드 위젯에 표시되는 데이터는 수집된 데이터 지점에서 취합되므로 대시보드에서 유연성과 오목성이 확보됩니다.

각 위젯에 표시되는 데이터는 획득 중에 수집된 기본 데이터 지점에서 롤업됩니다. 예를 들어, 시간에 따른 스토리지 IOPS를 보여 주는 선형 차트 위젯이 있는 경우 각 데이터 센터에 대해 별도의 줄을 표시하여 빠르게 비교할 수 있습니다. 다음 방법 중 하나로 이 데이터를 롤업하도록 선택할 수 있습니다.

* * Avg *: 각 행을 기본 데이터의 _average_로 표시합니다.
* * Max *: 각 행을 내부 데이터의 _maximum_으로 표시합니다.
* * Min *: 각 행을 내부 데이터의 _minimum_으로 표시합니다.
* * Sum *: 각 행을 원본 데이터의 _sum_으로 표시합니다.


이렇게 하려면 먼저 위젯의 쿼리에서 자산 유형(예: _Storage_) 및 메트릭(예: __IOPS-Tota__l)을 선택합니다. Roll Up * 의 경우 롤업 방법(예: _Avg_)을 선택하고 데이터를 롤업할 특성 또는 주석을 선택합니다(예: _Data Center_). 위젯이 자동으로 업데이트되고 각 데이터 센터에 대한 줄이 표시됩니다.

기본 데이터의 _ALL_을 차트 또는 테이블로 롤업하도록 선택할 수도 있습니다. 이 경우 위젯의 각 쿼리에 대해 하나의 줄이 표시됩니다. 이 라인은 모든 기본 자산에 대해 선택한 메트릭의 평균, 최소, 최대 또는 합계를 표시합니다.

쿼리에 대한 필터를 설정한 경우 롤업되는 데이터는 필터링된 데이터를 기반으로 합니다.

모든 필드(예: _Model_)별로 위젯을 롤업하도록 선택한 경우에도 해당 필드에 대한 데이터를 차트나 테이블에 올바르게 표시하려면 해당 필드를 * Filter by * 로 지정해야 합니다.

* 데이터 집계: * 데이터 포인트를 분, 시간 또는 일 단위로 집계하여 해당 데이터가 속성(선택한 경우)에 의해 롤업되기 전에 시계열 차트(선, 영역 등)를 추가로 정렬할 수 있습니다. 평균, 최대, 최소 또는 합계에 따라 또는 선택한 간격 동안 수집된 마지막 데이터 요소에 따라 데이터 요소를 집계하도록 선택할 수 있습니다. 집계 방법을 선택하려면 위젯의 쿼리 섹션에서 * 추가 옵션 * 을 클릭합니다.

최소 허용 간격은 10분입니다. 긴 시간 범위와 결합하여 작은 간격을 사용하면 "집계 간격 때문에 데이터 요소가 너무 많습니다."가 발생할 수 있습니다. 경고. 간격이 작고 대시보드 기간을 7일로 늘릴 경우 이 내용이 표시될 수 있습니다. 이 경우 더 작은 기간을 선택할 때까지 Insight는 집계 간격을 1시간으로 일시적으로 늘립니다.

막대 차트 위젯과 단일 값 위젯에서 데이터를 집계할 수도 있습니다.

대부분의 자산 카운터는 기본적으로 _Avg_로 집계됩니다. 일부 카운터는 기본적으로 _Max_, _Min_ 또는 _Sum_으로 집계됩니다. 예를 들어 포트 오류는 기본적으로 _Sum_으로 집계되며, 여기서 스토리지 IOPS는 _Avg_로 집계됩니다.
