---
permalink: howto/custom-dashboards.html 
sidebar: sidebar 
keywords:  
summary: OnCommand Insight 7.3에는 향상된 맞춤형 대시보드 기능이 포함되어 있어 사용자에게 중요한 데이터를 한눈에 파악할 수 있으며, 데이터를 한눈에 파악할 수 있습니다. 
---
= 사용자 지정 대시보드 만들기
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Insight 7.3에는 향상된 맞춤형 대시보드 기능이 포함되어 있어 사용자에게 중요한 데이터를 한눈에 파악할 수 있으며, 데이터를 한눈에 파악할 수 있습니다.

OnCommand Insight를 사용하면 다양한 위젯이 포함된 사용자 지정 대시보드를 생성할 수 있으므로 IT 플랫폼 전반에 걸쳐 운영 뷰 인프라 데이터를 유연하게 생성할 수 있습니다. 각 대시보드는 데이터를 표시하고 차트에 작성할 때 매우 유연하게 사용할 수 있습니다. 이 사용 방법에서는 VM 성능을 강조하는 예제 대시보드를 만듭니다.

이 사용 방법은 예제로만 사용해야 하며 가능한 모든 시나리오를 포괄하지는 않습니다. 이 문서의 개념 및 단계를 사용하여 고유한 사용자 지정 대시보드를 만들어 특정 요구 사항에 맞는 데이터를 강조할 수 있습니다.

* 개요 *

다음 방법 중 하나를 사용하여 사용자 지정 대시보드를 만들 수 있습니다.

* * 대시보드 * > * + 새 대시보드 *
* 대시보드 * > * 모든 대시보드 표시 * 를 선택하고 * + 추가 * 를 클릭합니다


New Dashboard 화면에는 다음과 같은 몇 가지 컨트롤이 있습니다.

* * 시간 선택기 *: 사용자 지정 날짜 범위 선택기를 사용하여 3시간에서 90일까지 일정 범위의 대시보드 데이터를 볼 수 있습니다. 개별 위젯에서 이 전역 시간 범위를 재정의할 수 있습니다.
* [편집] * 버튼: ""켜기""를 선택하면 [편집] 모드가 활성화되므로 대시보드를 변경할 수 있습니다. 새 대시보드는 기본적으로 편집 모드로 열립니다.
* * 저장 * 버튼: 대시보드를 저장, 이름 변경 또는 삭제할 수 있습니다.
* * 변수 * 버튼: 대시보드에 변수를 추가할 수 있습니다. 변수를 변경하면 모든 위젯이 한 번에 업데이트됩니다. 변수에 대한 자세한 내용은 를 참조하십시오 link:custom-dashboard-concepts.md#["사용자 지정 대시보드 개념"]
* * Widget * 버튼: 대시보드에 표, 차트 또는 기타 위젯을 원하는 수만큼 추가할 수 있습니다.


위젯의 크기를 조정하고 대시보드 내의 다른 위치로 재배치하여 현재 필요에 따라 데이터를 가장 잘 볼 수 있습니다.

* 위젯 유형 *

다음 위젯 유형 중에서 선택할 수 있습니다.

* 표 * 위젯: 선택한 필터 및 열에 따라 데이터를 표시하는 테이블 테이블 데이터를 축소 및 확장할 수 있는 그룹으로 결합할 수 있습니다.

* 선, 자유곡선, 영역, 누적 영역 * 차트: 시간 경과에 따라 성능 및 기타 데이터를 표시할 수 있는 시계열 차트 위젯입니다.

* 단일 값 * 위젯: 카운터로부터 직접 유도하거나 쿼리 또는 표현식을 사용하여 계산할 수 있는 단일 값을 표시할 수 있는 위젯. 예를 들어, 환경의 모든 스토리지에 대한 총 IOPS의 합계를 대시보드 상단에 단일 값으로 표시할 수 있습니다.

* 막대 * 차트: 상위 또는 하위 5, 10, 20 또는 50 값을 표시하는 차트.

* 상자 플롯 * 차트: 단일 차트에서 데이터의 최소, 최대, 중간값 및 하위 사분점과 상위 사분위 사이의 범위에 대한 플롯.

* 산란 플롯 * 차트: IOPS 및 지연 시간과 같은 점으로 관련 데이터를 플롯합니다. 이 예에서는 짧은 지연 시간과 낮은 IOPS의 자산을 빠르게 봅니다.

또한 선택할 수 있는 여러 개의 레거시 위젯이 있습니다. 이러한 위젯을 보려면 * 위젯 * 드롭다운에서 ** 더 보기...**를 선택합니다.
