---
permalink: howto/expressions-example-read-iops-percentage.html 
sidebar: sidebar 
keywords:  
summary: 식을 사용하면 합계 비율과 같은 대체 방법으로 메트릭을 볼 수 있습니다. 
---
= 표현식 예: 읽기 IOPS 백분율
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
식을 사용하면 합계 비율과 같은 대체 방법으로 메트릭을 볼 수 있습니다.



== 이 작업에 대해

이 예에서는 총 IOPS의 백분율로 읽기 IOPS를 표시하려고 합니다. 이 수식을 다음과 같은 수식으로 생각할 수 있습니다.

* 읽기 백분율 = (읽기 IOPS / 총 IOPS) x 100


이 데이터는 대시보드의 선 그래프에 표시할 수 있습니다. 이렇게 하려면 다음 단계를 수행하십시오.



== 단계

. 새 대시보드를 만들거나 * 편집 모드 * 로 기존 대시보드를 엽니다.
. 대시보드에 위젯을 추가합니다. 영역표 * 를 선택합니다.
+
위젯이 편집 모드로 열립니다. 기본적으로 * 스토리지 * 자산에 대한 * IOPS - 합계 * 가 표시된 쿼리가 표시됩니다. 원하는 경우 다른 자산 유형을 선택합니다.

. Expression * 으로 변환 단추를 클릭합니다.
+
현재 쿼리가 식 모드로 변환됩니다. 표현식 모드에서는 자산 유형을 변경할 수 없습니다. 표현식 모드에 있는 동안 버튼이 * Query * 로 바뀝니다. 언제든지 쿼리 모드로 다시 전환하려면 이 옵션을 클릭합니다. 모드 간을 전환하면 필드가 기본값으로 재설정됩니다.

+
지금은 * Expression * 모드를 사용할 수 있습니다.

. IOPS-Total * 메트릭은 이제 알파벳 변수 필드 ""A""에 있습니다. ""b"" 변수 필드에서 * 선택 * 을 클릭하고 * IOPS - 읽기 * 를 선택합니다.
+
변수 필드 뒤에 있는**+** 버튼을 클릭하여 식에 대해 최대 5개의 알파벳 변수를 추가할 수 있습니다. 읽기 백분율 예에서는 총 IOPS(""a") 및 읽기 IOPS(""b")만 필요합니다.

. 식 * 필드에서 각 변수에 해당하는 문자를 사용하여 식을 작성합니다. 우리는 _ 읽기 백분율 = (읽기 IOPS / 총 IOPS) x 100 _ 을(를) 알고 있으므로 이 식을 다음과 같이 씁니다. `(b / a) * 100`
. Label * 필드는 표현식을 식별합니다. 레이블을 ""읽기 백분율" 또는 사용자에게 똑같이 의미 있는 것으로 변경합니다.
. 단위 * 필드를 ""%" 또는 ""%"로 변경합니다.
+
선택한 스토리지 디바이스에 대한 IOPS 읽기 백분율이 차트에 표시됩니다. 원하는 경우 필터를 설정하거나 다른 롤업 방법을 선택할 수 있습니다. Rollup 방법으로 * Sum * 을 선택하면 모든 백분율 값이 함께 추가되므로 100%보다 높아질 수 있습니다.

. 차트를 대시보드에 저장하려면 * 저장 * 을 클릭합니다.
+
또한 * 선형 차트 *, * 스플라인 차트 * 또는 * 누적 영역형 차트 * 위젯에서 식을 사용할 수도 있습니다.


