---
permalink: howto/expressions-example-system-i-o.html 
sidebar: sidebar 
keywords:  
summary: 식은 다른 메트릭에서 계산할 수 있는 차트 데이터를 자유롭게 제공합니다. 
---
= 식 예: "System" I/O
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
식은 다른 메트릭에서 계산할 수 있는 차트 데이터를 자유롭게 제공합니다.



== 이 작업에 대해

예 2: OnCommand Insight는 데이터 소스에서 여러 메트릭을 획득합니다. 그 중에는 읽기, 쓰기 및 총 IOPS가 있습니다. 그러나 취득에서 보고된 총 IOPS 수에 "시스템" IOPS가 포함되는 경우가 있습니다. 이는 데이터 읽기 또는 쓰기의 직접적인 부분이 아닌 IO 작업입니다. 또한 이 시스템 I/O는 적절한 시스템 작동에 필요하지만 데이터 작업과 직접 관련이 없는 "오버헤드" I/O로 생각할 수 있습니다.

이러한 시스템 I/O를 표시하기 위해 획득에서 보고된 총 IOPS에서 읽기 및 쓰기 IOPS를 뺄 수 있습니다. 수식은 다음과 같습니다.

* 시스템 IOPS = 총 IOPS - (읽기 IOPS + 쓰기 IOPS)


그런 다음 이 데이터를 대시보드의 선 그래프로 표시할 수 있습니다. 이렇게 하려면 다음 단계를 수행하십시오.



== 단계

. 새 대시보드를 만들거나 * 편집 모드 * 로 기존 대시보드를 엽니다.
. 대시보드에 위젯을 추가합니다. 꺾은선형 차트 * 를 선택합니다.
+
위젯이 편집 모드로 열립니다. 기본적으로 * 스토리지 * 자산에 대한 * IOPS - 합계 * 가 표시된 쿼리가 표시됩니다. 원하는 경우 다른 자산 유형을 선택합니다.

. 쿼리 복사본을 만들려면 단추를 클릭합니다.
+
쿼리의 복제본이 원본 아래에 추가됩니다.

. 두 번째 쿼리에서 * 표현식으로 변환 * 단추를 클릭합니다.
+
현재 쿼리가 식 모드로 변환됩니다. 언제든지 쿼리 모드로 다시 전환하려면 * 쿼리에서 되돌리기 * 를 클릭합니다. 모드 간을 전환하면 필드가 기본값으로 재설정됩니다.

+
지금은 * Expression * 모드를 사용할 수 있습니다.

. IOPS-Total * 메트릭은 이제 알파벳 변수 필드 ""A""에 있습니다. IOPS - 합계 * 를 클릭하고 * IOPS - 읽기 * 로 변경합니다. .
. ""b"" 변수 필드에서 * 선택 * 을 클릭하고 * IOPS-쓰기 * 를 선택합니다.
. 식 * 필드에서 각 변수에 해당하는 문자를 사용하여 식을 작성합니다. 간단히 다음과 같이 표현해 보겠습니다. `a + b`. Display* 섹션에서 이 표현식에 대한 ** Area chart**를 선택합니다.
. Label * 필드는 표현식을 식별합니다. 레이블을 "시스템 IOPS"로 변경하거나 사용자에게 똑같이 의미 있는 레이블을 변경합니다.
+
이 차트에는 총 IOPS가 선형 차트로 표시되며, 아래에 읽기 및 쓰기 IOPS의 조합이 나와 있는 영역 차트가 표시됩니다. 이 두 가지 간의 공백은 데이터 읽기 또는 쓰기 작업과 직접 관련이 없는 IOPS를 나타냅니다.

. 차트를 대시보드에 저장하려면 * 저장 * 을 클릭합니다.

