---
permalink: howto/host-and-vm-filesystem-utilization.html 
sidebar: sidebar 
keywords: filesystem 
summary: 호스트 및 VM 파일 시스템 데이터 소스와 호스트 활용도 라이센스를 함께 사용하면 알려진 호스트 및 VM의 파일 시스템 레벨에서 보고 및 차지백을 수행할 수 있습니다. 
---
= 호스트 및 VM 파일 시스템 사용률 데이터 수집
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
호스트 및 VM 파일 시스템 데이터 소스와 호스트 활용도 라이센스를 함께 사용하면 알려진 호스트 및 VM의 파일 시스템 레벨에서 보고 및 차지백을 수행할 수 있습니다.

OnCommand Insight는 스토리지 디바이스에서 데이터를 취합하며, 이 중 대부분은 볼륨을 블록 디바이스로 보고합니다. Insight는 이를 통해 파일 시스템 레벨이 아닌 스토리지 레벨의 활용도에 대해 보고할 수 있습니다. 스토리지 어레이는 일반적으로 어떤 블록이 기록되었지만 어떤 블록이 해제되었는지 알지 못합니다.

클라이언트 호스트 및 VM에서 파일 시스템 구현(NTFS, ext *...) 블록 장치 위에 있습니다. 대부분의 파일 시스템은 디렉토리 및 파일 메타데이터를 포함하는 목차를 보관합니다. 파일이 삭제되면 해당 항목이 목차에서 제거됩니다. 이러한 파일이 사용하는 블록은 이제 파일 시스템에서 재사용할 수 있지만 스토리지 시스템은 이를 알지 못합니다. Insight에서 파일 시스템 사용량을 보고하려면 정확한 차지백을 위해 클라이언트 호스트 또는 VM 관점에서 데이터를 수집해야 합니다.

Insight를 사용하면 * 호스트 활용률 * 라이센스와 함께 * NetApp 호스트 및 VM 파일 시스템 * 데이터 소스를 통해 이러한 수준의 파일 시스템 활용률 데이터 수집을 수행할 수 있습니다. VM에는 적절한 * Compute Resource Group * 이름을 주석으로 추가해야 하며, 관련 스토리지 어레이에는 정확한 비용 보고를 위해 적절한 비용으로 적절한 * Tier * 주석을 추가해야 합니다.

[NOTE]
====
Host Utilization 라이센스는 다른 Insight 라이센스와 달리 용량 기반과는 달리 리소스 기반입니다.

====