---
permalink: howto/how-to-troubleshoot-fibre-channel-bb-credit-0-errors.html 
sidebar: sidebar 
keywords:  
summary: '파이버 채널은 버퍼 대 버퍼 크레딧 \(BB 크레딧\)을 사용하여 전송 흐름을 제어합니다. 포트에서 프레임이 전송되면 크레딧 값이 감소하고 포트에서 응답을 받으면 크레딧 값이 보충됩니다. 포트의 BB 크레딧을 보충하지 않으면 전송 흐름에 영향을 줄 수 있습니다. 포트가 순서대로 조립되어 전달될 때까지 프레임을 임시로 저장하려면 메모리 또는 버퍼가 필요합니다. 버퍼 수는 포트가 저장할 수 있는 프레임 수이며 버퍼 크레디트 라고 합니다.' 
---
= Fibre Channel BB 크레딧 0 오류 문제 해결
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
파이버 채널은 BB 크레딧(Buffer-to-Buffer 크레딧)을 사용하여 전송 흐름을 제어합니다. 포트에서 프레임이 전송되면 크레딧 값이 감소하고 포트에서 응답을 받으면 크레딧 값이 보충됩니다. 포트의 BB 크레딧을 보충하지 않으면 전송 흐름에 영향을 줄 수 있습니다. 포트가 순서대로 조립되어 전달될 때까지 프레임을 임시로 저장하려면 메모리 또는 버퍼가 필요합니다. 버퍼 수는 포트가 저장할 수 있는 프레임 수이며 버퍼 크레디트 라고 합니다.

지정된 포트 접근 0에 대해 사용 가능한 크레딧으로, 0에 도달하면 포트에서 전송 수신을 중지하고 BB 크레딧을 보충할 때까지 다시 시작하지 않는다는 경고가 표시됩니다.

Insight 성능 정책을 사용하면 다음 포트 메트릭에 대한 임계값을 설정할 수 있습니다.

|===


 a| 
BB 크레딧 제로 Rx



 a| 
샘플링 기간 동안 수신 버퍼 대 버퍼 크레딧 수가 0으로 전환된 횟수입니다



 a| 
BB 크레딧 0 - Tx



 a| 
샘플링 기간 동안 전송 버퍼 대 버퍼 크레딧 수가 0으로 전환된 횟수입니다



 a| 
BB 크레딧 없음 - 합계



 a| 
연결된 포트가 제공할 수 있는 크레딧이 없기 때문에 이 포트가 전송을 중지해야 하는 횟수입니다



 a| 
BB 크레딧 없음 기간 - Tx



 a| 
샘플링 간격 동안 Tx BB 크레딧이 0인 시간(밀리초)입니다

|===
BB 크레딧 오류는 다음과 같은 경우에 발생할 수 있습니다.

* 지정된 구축 환경에서 FC 프레임의 비율이 최대 크기보다 훨씬 작을 경우 더 많은 BB 크레딧이 필요할 수 있습니다.
* 스토리지 노드와 같이 포트에 연결된 장치 또는 포트에 영향을 줄 수 있는 환경의 워크로드 변경


패브릭, 스위치 및 포트 자산 페이지를 사용하여 파이버 채널 환경을 모니터링할 수 있습니다. 포트 자산 페이지는 리소스, 해당 토폴로지(장치 및 연결), 성능 차트 및 관련 리소스 표에 대한 요약 정보를 제공합니다. Fibre Channel 문제를 해결할 때 각 포트 자산에 대한 성능 차트는 선택한 최상위 기여 포트의 트래픽을 보여 주기 때문에 유용합니다. 또한 포트 자산 페이지에는 버퍼 대 버퍼 크레딧 메트릭과 포트 오류가 이 차트에 표시되며 Insight는 각 메트릭에 대한 별도의 성능 차트를 표시합니다.
