---
permalink: howto/more-on-dashboard-variables.html 
sidebar: sidebar 
keywords:  
summary: 대시보드 변수는 여러 가지 형식으로 제공되며 서로 다른 필드에서 사용할 수 있으며 명명 규칙을 따라야 합니다. 이러한 개념은 여기에 설명되어 있습니다. 
---
= 대시보드 변수에 대한 자세한 정보
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
대시보드 변수는 여러 가지 형식으로 제공되며 서로 다른 필드에서 사용할 수 있으며 명명 규칙을 따라야 합니다. 이러한 개념은 여기에 설명되어 있습니다.



== 변수 유형

변수는 다음 형식 중 하나일 수 있습니다.

* 텍스트 *: 영숫자 문자열입니다. 기본 변수 유형입니다.

* 숫자 *: 숫자 또는 숫자 범위.

* 부울 *: True/False, Yes/No, 0/1 등의 값을 가진 필드에 사용합니다 부울 변수의 선택 항목은 _Yes_, _No_, _None_, _Any_입니다.

* 날짜 *: 날짜 또는 날짜 범위입니다.



== "일반" 변수

변수 * 버튼을 클릭하고 위에 나열된 유형 중 하나를 선택하여 일반 또는 범용 변수를 설정할 수 있습니다. 이러한 유형은 항상 드롭다운 목록의 맨 위에 표시됩니다. 변수에 ""$var1" 등의 기본 이름이 지정되고 특정 주석이나 속성에 연결되지 않습니다.

제네릭 변수를 구성하면 위젯에서 해당 변수를 사용하여 해당 형식의 _any_필드를 필터링할 수 있습니다. 예를 들어, _Name_, _Alias_ 및 _Vendor_(모든 텍스트 유형 속성)를 표시하는 테이블 위젯이 있고 ""$var1""가 텍스트 유형 변수인 경우 위젯에서 각 필드에 대해 필터를 설정하여 $var1 변수를 사용할 수 있습니다. 다른 위젯에서 해당 필드나 텍스트 필드에 $var1을 사용하도록 설정할 수 있습니다.

대시보드 페이지에서 $var1을 값(예: ""NetApp"")으로 설정하면 해당 변수를 사용하도록 설정된 _ALL_Widget의 해당 필드 중 _ALL_이 필터링됩니다. 이렇게 하면 여러 위젯을 한 번에 업데이트하여 원하는 대시보드 데이터를 강조 표시할 수 있습니다.

제네릭 변수는 해당 형식의 모든 필드에 사용될 수 있으므로 해당 기능을 변경하지 않고 제네릭 변수의 이름을 변경할 수 있습니다.

[NOTE]
====
모든 변수는 특정 특성에 대해 생성한 변수까지도 "일반" 변수로 취급됩니다. 해당 형식의 특성이나 주석에 대해 필터를 설정할 때 형식의 구성된 모든 변수가 표시되기 때문입니다. 그러나 위의 _Name/Alias/Vendor_Example 과 같이 여러 필드에 걸쳐 값을 필터링하는 데 사용할 일반 변수를 만드는 것이 가장 좋습니다.

====


== 변수 이름 지정

변수 이름:

* 항상 ""$" 접두사로 붙여야 합니다. 변수를 설정하면 자동으로 추가됩니다.
* 특수 문자는 포함할 수 없습니다. 문자 A-z 및 숫자 0-9 만 허용됩니다.
* ""$" 기호를 포함하여 20자를 초과할 수 없습니다.
* 대소문자를 구분하지 않습니다. $CityName 및 $cityname은 동일한 변수입니다.
* 기존 변수 이름과 같을 수 없습니다.
* ""$" 기호만이 될 수 없습니다.




== 변수를 사용하는 위젯

변수는 다음 위젯과 함께 사용할 수 있습니다.

* 영역 차트
* 가로 막대형 차트
* 상자 플롯 차트
* 꺾은선형 차트
* 산포도 차트
* 단일 값 위젯
* 스플라인 차트
* 누적 영역형 차트
* 테이블 위젯

