---
permalink: howto/servicenow-integration-set-up-user.html 
sidebar: sidebar 
keywords:  
summary: Insight에 연결하고 데이터를 동기화하려면 ServiceNow 사용자를 설정해야 합니다. 
---
= ServiceNow 통합 - 사용자 설정
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Insight에 연결하고 데이터를 동기화하려면 ServiceNow 사용자를 설정해야 합니다.



== 이 작업에 대해



== 단계

. ServiceNow에서 서비스 계정을 생성합니다. ServiceNow에 로그인하고 * 시스템 보안 * > * 사용자 및 그룹 * > * 사용자 * 로 이동합니다. New * 를 클릭합니다.
. 사용자 이름을 입력합니다. 이 예제에서는 통합 사용자로 ""OCI2SNOW"를 사용합니다. 이 사용자의 암호를 입력합니다.
+
[NOTE]
====
이 사용 방법에서는 설명서에 ""OCI2SNOW""라는 이름의 서비스 계정 사용자를 사용합니다. 다른 서비스 계정을 사용할 수도 있지만 환경 전체에서 일관되는지 확인하십시오.

====
. 메뉴 모음을 마우스 오른쪽 단추로 클릭하고 * 저장 * 을 클릭합니다. 이렇게 하면 역할을 추가하기 위해 이 사용자를 계속 사용할 수 있습니다.
. 편집 * 을 클릭하고 이 사용자에게 다음 역할을 추가합니다.
+
** 자산
** import_transformer 를 선택합니다
** REST_SERVICE


. 저장 * 을 클릭합니다.
. 이 동일한 사용자를 OnCommand Insight에 추가해야 합니다. 관리자 권한이 있는 사용자로 Insight에 로그인합니다.
. Admin * > * Setup * 으로 이동하여 * Users * 탭을 클릭합니다.
. Actions * 버튼을 클릭하고 * Add user * 를 선택합니다.
. 이름으로 ""OCI2SNOW""를 입력합니다. 위에서 다른 사용자 이름을 사용한 경우 여기에 해당 이름을 입력하십시오. 위의 ServiceNow 사용자에 대해 사용한 것과 동일한 암호를 입력합니다. 이메일 필드는 비워 둘 수 있습니다.
. 이 사용자에게 * 사용자 * 역할을 할당합니다. 저장 * 을 클릭합니다.

