---
permalink: howto/using-performance-policies-to-reduce-risk-in-thin-provisioning.html 
sidebar: sidebar 
keywords:  
summary: 가상 인프라스트럭처의 임계값이 위반될 경우 알림을 발생시키기 위해 성능 정책을 만들어야 합니다. 알림을 통해 운영 중단 또는 중단을 일으킬 수 있는 환경 변화에 미리 대응할 수 있습니다. 
---
= 성능 정책을 사용하여 씬 프로비저닝의 위험 감소
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
가상 인프라스트럭처의 임계값이 위반될 경우 알림을 발생시키기 위해 성능 정책을 만들어야 합니다. 알림을 통해 운영 중단 또는 중단을 일으킬 수 있는 환경 변화에 미리 대응할 수 있습니다.

가상 인프라스트럭처를 모니터링하는 데 도움이 되는 정책은 다음과 같습니다.

* * 데이터 저장소 *
+
데이터 저장소에서 다음 정책을 사용할 수 있습니다.

+
** 용량 비율 - Overcommit
** 용량 비율 - 사용됨
** 용량 - 사용됨
** 용량 - 합계


* * 스토리지 풀 *
+
다음 정책은 씬 프로비저닝 환경에서 스토리지 관련 용량 중단으로부터 보호할 수 있습니다.

+
** 용량이 프로비저닝되었습니다
** 사용된 용량
** 용량 비율 - Overcommit
** 용량 비율 - 사용됨




이러한 정책을 확장하여 다음과 같은 가상 인프라스트럭처의 용량을 모니터링할 수 있습니다.

* 내부 볼륨
* LUN을 클릭합니다
* 디스크
* VMDK입니다
* VM


주석을 사용하여 정책을 구성할 수 있습니다. 응용 프로그램을 지원하는 특정 자산에 동일한 주석을 할당합니다. 예를 들어, 씬 프로비저닝된 애플리케이션의 데이터 저장소 및 스토리지 풀에 주석을 할당할 수 있습니다. 운영 환경에 대한 Production , 개발 환경에 대한 Development 등의 주석이 있을 수 있습니다. 자산이 지원하는 애플리케이션의 유형에 따라 경고의 임계값과 중요도를 변경할 수 있습니다. 예를 들어 운영 애플리케이션의 데이터 저장소에 대한 임계값을 위반할 경우 _critical warning_이 발생할 수 있지만 개발 환경에 대한 동일한 위반은 _warning_만 발생시킬 수 있습니다. 정의된 정책 내에 주석을 통합하면 중요하지 않은 자산에 대한 원치 않는 경고 소음을 더욱 줄일 수 있습니다.
