---
sidebar: sidebar 
permalink: task_config_telegraf_dcos.html 
keywords: telegraf, installation, install, dcos 
summary: DCO 구성 
---
= DC/OS Data Collector
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cloud Insights는 이 데이터 수집기를 사용하여 DC/OS에서 메트릭을 수집합니다.



== 설치

. 관측성 > 수집기 * 에서 * + Data Collector * 를 클릭합니다. DC/OS * 를 선택합니다.
+
컬렉션에 대한 Agent를 구성하지 않은 경우 메시지가 표시됩니다 link:task_config_telegraf_agent.html["에이전트를 설치합니다"] 있습니다.

+
에이전트가 이미 구성되어 있는 경우 해당 운영 체제 또는 플랫폼을 선택하고 * 계속 * 을 클릭합니다.

. DC/OS Configuration(DC/OS 구성) 화면의 지침에 따라 데이터 수집기를 구성합니다. 지침은 데이터 수집에 사용하는 운영 체제 또는 플랫폼의 유형에 따라 다릅니다.




== 설정

설정 정보는 에서 찾을 수 있습니다 https://docs.mesosphere.com["DC/OS 설명서"].



== 개체 및 카운터

다음 개체와 해당 카운터가 수집됩니다.

[cols="<.<,<.<,<.<,<.<"]
|===
| 오브젝트 | 식별자 | 속성 | 데이터 요소 


| DCO_NODE | DCOs_container 를 선택합니다
DCOs_app을 선택합니다 | 클러스터
호스트 이름
경로(파일 시스템 필드만 해당)
인터페이스(네트워크 필드만 해당)
container_id입니다
작업_이름 | 시스템 가동 시간(부동)
cpu_cores(부동)
CPU_TOTAL(부동)
CPU_user(부동)
CPU_SYSTEM(부동)
CPU_IDLE(부동)
CPU_WAIT(부동)
LOAD_1min(부동)
LOAD_5분(플로트)
LOAD_15분(플로트)
filesystem_capacity_total_bytes(int)
filesystem_capacity_used_bytes(int)
filesystem_capacity_free_bytes(int)
filesystem_inode_total(float)
filesystem_inode_used (float)
filesystem_inode_free (float)
memory_total_bytes(int)
memory_free_bytes(int)
Memory_buffers_bytes(int)
memory_cached_bytes(int)
swap_total_bytes(int)
swap_free_bytes(int)
swap_used_bytes(int)
network_in_bytes(int)
network_out_bytes(int)
network_in_packets(부동)
network_out_packets(부동)
network_in_dropped(부동)
network_out_dropped(부동)
network_in_errors(부동)
network_out_error(부동)
Process_count(부동) 
|===


== 문제 해결

추가 정보는 에서 찾을 수 있습니다 link:concept_requesting_support.html["지원"] 페이지.
